### ISSUE TITLE
Investigate and add support for 255 devices/pvsci controller

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#10]
Looks like PVSCI supports 255 devices (not 15)
https://opengrok.eng.vmware.com/source/xref/vmkernel-main.perforce.1666/bora/public/vm_device_version.h#198 
and
https://opengrok.eng.vmware.com/source/xref/vmkernel-main.perforce.1666/bora/devices/pvscsi/pvscsi_monitorVMK.c#201

Need to validate, change code and add a related test.

**Comment by pdhamdhere** [comment]
This feature is not enabled by default. Need following changes- 
1. Add "scsi%u.maxTargets=255" in vmx file
2. In esx_service/vmdk_ops.py
```
-        availSlots = set(range(0, 6) + range(8, 16)) - taken
+        availSlots = set(range(0, 6) + range(8, 255)) - taken
```

We should use this feature iff we run out of slots (15 vDisks x 4 Controllers = 60 vDisks). So, making this issue P1 and #38 as P0.

**Comment by msterin** [comment]
if there is no programmatic way to enable 255 targets, I think  we should consider adding it as a admin CLI option. Something like `vmdkops_admin.py set --max_targets=255 --vm=<vm>` (or a better syntax, but via the CLI)

**Comment by govint** [comment]
There is no way to add the maxTargets for a scsi adapter in the VM config, except to append the setting into the VMX. Suggest closing this issue and fixing the max allowed devices as 15 x pvscsi controllers in issue #38

**Comment by govint** [comment]
Closing

**Comment by msterin** [comment]
Just because we cannot automate it does not mean we should do nothing.
IMO we should document how to set it in VMX (or refer to relevant KB) and add support in our code to go over 15 when the option is set.

**Comment by govint** [comment]
The documentation is available here - https://www.vmware.com/pdf/vsphere6/r60/vsphere-60-configuration-maximums.pdf. The documented max is 15 devices per controller. There is no way to set to any value more than that.

**Comment by govint** [comment]
This feature isn't available at this time. Closing.
