### ISSUE TITLE
Misleading error message while renaming a tenant to a name which already exists

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1001]
Steps to reproduce:
1. create two tenants T1 and T2
2. invoke ```vmdkops_admin tenant ls``` to verify tenants correctly or not
3. rename one of the tenant with the existing tenant name i.e. invoke ```vmdkops_admin.py tenant update --name T1 --new-name T2``` where as ```T2``` is already present in the system

on ESX
```
[root@sc-rdops-vm10-dhcp-36-198:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name      Description               Default_datastore  VM_list         
------------------------------------  --------  ------------------------  -----------------  --------------  
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default tenant  vsanDatastore                      
c308b6a2-1b00-450a-bb95-275b958ffde7  T1                                  vsanDatastore                      
42b1a76c-65df-4cf6-b18d-9dd17b684a9b  T2                                  vsanDatastore      vmFolderPhoton  

[root@sc-rdops-vm10-dhcp-36-198:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name      Description               Default_datastore  VM_list         
------------------------------------  --------  ------------------------  -----------------  --------------  
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default tenant  vsanDatastore                      
c308b6a2-1b00-450a-bb95-275b958ffde7  T1                                  vsanDatastore                      
42b1a76c-65df-4cf6-b18d-9dd17b684a9b  T2                                  vsanDatastore      vmFolderPhoton  

[root@sc-rdops-vm10-dhcp-36-198:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant update --name T1 --new-name T2
Tenant T1 already exists
[root@sc-rdops-vm10-dhcp-36-198:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py status
Version: 0.12.3f64805-0.0.1
Status: Running
Pid: 1321926
```

**Comment by govint** [comment]
Current code seems to work ok.

 /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name           Description                Default_datastore  VM_list
------------------------------------  -------------  -------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT       This is a default vmgroup  _VM_DS
05c0d4b2-9066-4945-bdd4-50d91fe3a554  user_tenant_2                             _VM_DS
e180f3bf-9609-405a-ab93-735fed311a2c  user_tenant_1                             _VM_DS

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup update --name user_tenant_1 --new-name user_tenant_2
Vmgroup user_tenant_2 already exists
