### ISSUE TITLE
refactor existing go tests which requires Docker config to accept TCP connection

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1011]
Currently [sanity_test] ( https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/sanity_test.go ) requires docker config to be set in order to accept TCP connection. 

The test can be refactored further as we have automated some tests which uses ssh channel to invoke docker CLI.

// @msterin

**Comment by govint** [comment]
@shuklanirdesh82 can you evaluate this issue and close or specify what more changes needs to be done.

**Comment by shuklanirdesh82** [comment]
This issue was meant for enhancing the existing test to use ssh way of making call (to keep in sync with other tests) instead of TCP connection for communicating to docker daemon. 

More over, person has to configure test VM to open port `2357` to let vms talk among over tcp. 

I think we may close this issue having it said we have test bed deployment automation script and no more issue while using automated testbed.
