### ISSUE TITLE
[test automation] VM snapshot tests

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1012]
Test -1: Test to take snapshot of vm with persistent volume attached

```
- Create a persistent volume vol1
- Run a container with volume (vol1) mounted
- Take snapshot of the vm - operation should succeed

```
https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/docker-volume-cli.md#attach_as-vsphere-only

Test -2: Test to take snapshot of vm with independent_persistent volume attached

```
- Create a independent_persistent volume vol1
- Run a container with volume (vol1) mounted
- Take snapshot of the vm operation should fail as vm has independent disk attached
- Stop the container
- Again try taking the snapshot of vm - operation will succeed 

```

**Comment by govint** [comment]
Default is to have a independent-persistent disk and its never part of the snap. The test should be to have both a persistent and independent-persistent disk and snapshot the VM.
