### ISSUE TITLE
Install on Ubuntu Docker host with  docker version 17.03.0-ce failed

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1023]
root@swarm01:~# sudo dpkg -i /tmp/docker-volume-vsphere_0.12.172687e_amd64.deb 
sudo: unable to resolve host swarm01
(Reading database ... 124397 files and directories currently installed.)
Preparing to unpack .../docker-volume-vsphere_0.12.172687e_amd64.deb ...
Unpacking docker-volume-vsphere (0.12.172687e) over (0.12.172687e) ...
  File: '/proc/1/exe' -> '/lib/systemd/systemd'
dpkg: dependency problems prevent configuration of docker-volume-vsphere:
 docker-volume-vsphere depends on docker-engine (>> 1.9); however:
  Package docker-engine is not installed.

dpkg: error processing package docker-volume-vsphere (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 docker-volume-vsphere
root@swarm01:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3 MiB
Name: swarm01
ID: FEFU:HCK3:ERQA:ILLR:KCVJ:XSNY:JGOU:EBKS:S4CX:7E4O:EKFI:QZQ3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by pdhamdhere** [comment]
With Docker moving to YY/MM versioning scheme, we need to update checks in package builder.

[Makefile](https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/Makefile#L47)

```
MIN_DOCKER_VERSION :=1.9
```

```
deb: pkg-prep deb-pkg-prep
	@$(CHECK) pkg
	$(FPM) --deb-no-default-config-files $(FPM_COMMON) -d '$(DOCKER_PACKAGE) > $(MIN_DOCKER_VERSION)' -t deb .
```

**Comment by msterin** [comment]
One would expect that 17.0 > 1.9 :-)

I suggest just dropping the check. I doubt anyone is using 1.8  and earlier  anyways

**Comment by lipingxue** [comment]
OK. I will try the fix you suggested.
