### ISSUE TITLE
[Tenancy] 'vmdkops_admin ls' enhancement

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1043]
**[ ] How to handle volumes owned by an orphan tenant**

For admin `ls` command; add a new column in the output to indicate volume  folder location. This will improve the transparency to admin and also will be helpful to deal with orphan volumes.
 
Later, we can add additional `move` command on admin cli to move a volume from one tenant to another.

**[ ] How to handle 'ls' output being too wide**

Have a “default list of columns” hardcoded (or in config file) and show only them by default. Keep `–c` flag as is , and add new flag `-a` to print ALL columns

**[ ] How to handle vmdkops_admin commands consistency**

 Rename 'vmdkops_admin ls" to ‘vmdkops_admin volume ls’ and rename ‘vmdkops_admin set’ to ‘ vmdkops_admin volume set’

**Comment by govint** [comment]
These are nice to have but I'm not sure we want to get this in the next sprint. At best, these aren't bugs and I'd suggest fixing if user complains.

For ls output, the user has the option of limiting the columns which they can script or use at the command line anytime.

**Comment by govint** [comment]
Suggest moving this to Future.

**Comment by govint** [comment]
Moving to Rafiki per eartlier updates, this isn't a bug and existing admin CLI _ls_ command allows user to specify a limited set of columns for print. Choosing a default is really an enhancement that a user can already script with the options available.

**Comment by govint** [comment]
Closing this issue, the user has the ability to use a smaller set of columns with the admin CLI command and whether its scripted or run manually its hardly an issue to specify the columns needed - which is why that option is there.
