### ISSUE TITLE
Complete the move to managed plugins - drop support for unmanaged ones

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#1051]
In #1006 we added managed plugins support
To complete this, we already have #1033 (photoOS support) and #1020 (CI / full build) issues. 

We also need to 

- [ ] drop build and use of .rpm/.deb. We can still have the targets in Makefile in case we need it for troubleshooting or comparison, but they should not be a part of regular build. 
- [ ] change all tests to use the managed plugins (since in #1020 we focus only ADDING management plugin test) 
- [x] update documentation to refer to Docker managed plugin in, and give an example of vDVS install, plus debug option (fixed #1115)

Few more action items (notes from @shuklanirdesh82)

- [x] upgrade all test VMs to use docker 1.13/17.03 (keep last two docker releases)
- [x] install ```make``` utility to all VMs

//CC @shuklanirdesh82 @tusharnt

**Comment by tusharnt** [comment]
The following action item will be aimed at 0.13.

- [ ] update documentation to refer to Docker managed plugin in, and give an example of vDVS install, plus debug option

**Comment by shuklanirdesh82** [comment]
@msterin 

> drop build and use of .rpm/.deb. We can still have the targets in Makefile in case we need it for troubleshooting or comparison, but they should not be a part of regular build.

with PR #1163,DEB/RPM usage support is dropped but build support is still exist (as decided to keep for next 2-3 releases), I am opening a new issue to track required work on dropping build/publish support for DEB/RPM
