### ISSUE TITLE
multiple instances of vsphere plugin should not be allowed

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1056]
with non-mananged plugin (rpm/deb), we are making sure of having only one instance of vmdk/vsphere driver whereas it is possible to have multiple instance of vsphere driver through managed plugin.

```
root@sc-rdops-vm18-dhcp-57-89:~# docker plugin ls
ID                  NAME                                   DESCRIPTION                           ENABLED
1ab6415ef01f        cnastorage/docker-volume-vsphere:1.0   VMWare vSphere Docker Volume plugin   true
9fe14eeaf7eb        vsphere_ashahi:latest                  VMWare vSphere Docker Volume plugin   true
```

could be resulted to duplicates as shown below
```
root@sc-rdops-vm18-dhcp-57-89:~# docker volume ls
DRIVER                                 VOLUME NAME
cnastorage/docker-volume-vsphere:1.0   someVolume@TestDatastore
cnastorage/docker-volume-vsphere:1.0   someVolume@TestDatastore
vsphere_ashahi:latest                  someVolume@TestDatastore
vsphere_ashahi:latest                  someVolume@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume1@TestDatastore
vsphere_ashahi:latest                  testVolume1@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume1@TestDatastore
vsphere_ashahi:latest                  testVolume1@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume3@TestDatastore
vsphere_ashahi:latest                  testVolume3@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume3@TestDatastore
vsphere_ashahi:latest                  testVolume3@TestDatastore
vsphere_ashahi:latest                  testVolume@TestDatastore
vsphere_ashahi:latest                  testVolume@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume@TestDatastore
cnastorage/docker-volume-vsphere:1.0   testVolume@TestDatastore
```

/cc @msterin @pdhamdhere

**Comment by msterin** [comment]
i am wondering how does it behave with other plugins ?

**Comment by pdhamdhere** [comment]
Plugin Sockets are per container and Docker doesn't offer any way to stop starting multiple instances. So, we depend on user to make sure only one version/instance of plugin is running at any point in time.

**Comment by govint** [comment]
We can still have the plugin create a lock file - say vsphere.lock on a common location say /var (exposed to the container) and prevent multiple instances of the plugin. Are there any resources claimed by the plugin container on the guest OS that will mandate having a single instance?

**Comment by msterin** [comment]
>  Are there any resources claimed by the plugin container on the guest OS that will mandate having a single instance?

Nothing we know of.

The issue is closed. Unless there is a customer problem to solve, lets' leave it at that.

**Comment by pdhamdhere** [comment]
@govint Lock file in /etc is sound idea. However, installing multiple instances of plugin is really user error. We can revisit in future if needed.
