### ISSUE TITLE
tiny bug in documentation

### ISSUE THREAD

**Issue by lachnerd** [vmware/docker-volume-vsphere#1067]
Hi there,

i have found a little bug in your docs:
![image](https://cloud.githubusercontent.com/assets/25339466/24247348/a26767fc-0fcb-11e7-8381-efb92c54c56b.png)

I think "attach_as" is wrong should be "attach-as".

**Comment by pdhamdhere** [comment]
Good catch! It's already fixed by #1041 on master and documentation will be updated in next release. Thanks for reporting!
