### ISSUE TITLE
can't get it working

### ISSUE THREAD

**Issue by lachnerd** [vmware/docker-volume-vsphere#1068]
Hi,

i don't know if this has something todo with #1023 or #1039 but i built my deb-file for vsphere-volume -driver from trunk and installed it but i can't get it working.
Everytime i want to use vspehre Volume nothing happens.
For Example:
`docker volume create --driver=vsphere --name=MyVolume@san-datastore6 -o size=1gb -o attach-as=persistent -o access=read-write`
If i then want to start a container using this volume with:
`docker run -ti --name MyVolume -v MyVolume:/var/log/nginx -p 80 nginx`

Nothing happens - i waited several Minutes and then aborted it.

I also noticed that `docker volume ls` takes about 15-20s till something is printed on screen.

Docker: 17.03.0-ce
OS: Ubuntu 16.04.2 LTS

Any Tipps ?

**Comment by pdhamdhere** [comment]
@lachnerd Can you please share following logs;

From VM: /var/log/docker-volume-vsphere.log
From ESX: /var/log/vmware/vmdk_ops.log 

Is your VM running on "san-datastore6"? 
Can you please drop "@san-datastore6" in volume create command and try again? OR change your run command to use fully volume name;
`docker run -ti --name MyVolume@san-datastore6 -v MyVolume:/var/log/nginx -p 80 nginx`

**Comment by lachnerd** [comment]
Hi pdhamdhere thx for answering,

i added the logs 
[vmdk_ops.zip](https://github.com/vmware/docker-volume-vsphere/files/867918/vmdk_ops.zip)
[docker-volume-vsphere.zip](https://github.com/vmware/docker-volume-vsphere/files/867919/docker-volume-vsphere.zip)

And i also tried creating volumes without "@san-datastore6" - i even tried to name the datastore at volume mount (i think you meant something like this not naming the container @datastore6) `docker run -ti --name MyVolumeContainer -v MyVolume@san-datastore6:/var/log/nginx -p 80 nginx` 

And yes VM is also running on "san-datastore6".

But everytime i ended up with the same result - nothing happens - no Container is starting up.

**Comment by pdhamdhere** [comment]
Sorry @lachnerd that you are having trouble with relatively simple test. I looked in logs and dont see any errors. Looks like Docker is starting and immediately exiting container.  Will need to look into docker logs (`journalctl -u docker.service >docker-logs.txt`).

Can I ask you to run following quick test;

```
root@u-1:~# docker volume create -d vsphere testvol
testvol
root@u-1:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      testvol@datastore1
root@u-1:~# docker run --rm -v testvol:/data busybox sh -c 'echo "Hello" >/data/hello.txt; cat /data/hello.txt'
Hello
root@u-1:~# docker run --rm -v testvol:/data busybox sh -c 'cat /data/hello.txt'
Hello
root@u-1:~#
```

I tried same command as yours except with "-ti" (interactive) replaced with "-d" (daemon mode) on master and seems to work fine;

```
root@u-1:~# docker run -d --name MyVolumeContainer -v MyVolume@datastore1:/var/log/nginx -p 80 nginx
d62e15d4c9fcbc5b35c4b5b513c13d7d57f4c00a241e65510f94f7e66d4b9e3d
root@u-1:~# docker inspect MyVolumeContainer |grep HostPort
                        "HostPort": ""
                        "HostPort": "32775"
root@u-1:~# curl localhost:32775
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@u-1:~#
```

**Comment by lachnerd** [comment]
ok, i tested this and you're right - problems seems to be with '-ti'.
If i start containers in daemon mode all works like expected.

**Comment by pdhamdhere** [comment]
Thanks @lachnerd for confirming.

> But i think interactive mode should work as well?

Yes, it should work. I tried following sequence on my setup. Can you give this a try?

```
root@u-1:~# docker volume create -d vsphere v2
v2
root@u-1:~# docker run --rm -it -v v2:/data busybox
/ # echo "Hello World from inside container" >/data/hello.txt
/ # cat /data/hello.txt 
Hello World from inside container
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
none                      6.8G      1.9G      4.5G  30% /
tmpfs                   487.4M         0    487.4M   0% /dev
tmpfs                   487.4M         0    487.4M   0% /sys/fs/cgroup
/dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:2:0
                         92.8M      1.5M     84.3M   2% /data
/dev/sdb1                 6.8G      1.9G      4.5G  30% /etc/resolv.conf
/dev/sdb1                 6.8G      1.9G      4.5G  30% /etc/hostname
/dev/sdb1                 6.8G      1.9G      4.5G  30% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   487.4M         0    487.4M   0% /proc/kcore
tmpfs                   487.4M         0    487.4M   0% /proc/timer_list
tmpfs                   487.4M         0    487.4M   0% /proc/timer_stats
tmpfs                   487.4M         0    487.4M   0% /proc/sched_debug
tmpfs                   487.4M         0    487.4M   0% /sys/firmware
/ # exit
root@u-1:~#
```

**Comment by lachnerd** [comment]
thx pdhamdhere i tried this and it worked but i have no idea what was causing my problems
