### ISSUE TITLE
'vmdk-opsd stop' needs to drain operations in flight 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#1073]
Currently `vmdk-opsd stop` just stops (exits) the vmdk_ops.py service. If there were operations in fligth it could kill them in the middle of execution. That can potentially create inconsistencies in VM attachement, KV files or auth-db.

To prevent this, we need to drain the ops in flight before stopping. 
Something along this line
[ ]  On 'stop' requests, add a barrier so executeRequest does fails all new incoming requests with "The server is stopping, operation declined". 
[ ] Add count of ops in flight, and when barrier is installed makes sure the count drops to zero before proceeding
[ ] Add a way to force-kill the service in case something is stuck (e.g. a 10TB format is running). This will  behave as today's "stop" but issue additional message about potential danger. I suggest `vmdk-opsd kill`. 
[ ] Add a message for "status" that the "service is being stopped, waiting for completion of X operations in flight "

//CC @pdhamdhere

**Comment by shaominchen** [comment]
> [ ] Add a message for "status" that the "service is being stopped, waiting for completion of X operations in flight "

As per offline discussion with @msterin, we think it makes more sense to print the message for "stop" itself instead of doing that for "status".
