### ISSUE TITLE
Increase default timeout parameter while running E2E tests

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1078]
e2e-dkrVolDriver-test is taking more time and exceeds go test framework due to CI VMs slowness .. our objective is not to fail test due to test framework limitation.

#1057 is raised to root caused the test run slowness and this issue is to increase time out value.

It is highly possible the failure is ignored and hard to catch when the regression is introduced.

https://ci.vmware.run/vmware/docker-volume-vsphere/1788
https://ci.vmware.run/vmware/docker-volume-vsphere/1741

Sample failure
```
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/vmware/docker-volume-vsphere/vmdk_plugin/E2E_Tests	600.004s
make[1]: *** [e2e-dkrVolDriver-test] Error 1
make: *** [e2e-dkrVolDriver-test] Error 2
```

/cc @govint @msterin @pdhamdhere

**Comment by pdhamdhere** [comment]
I am against increasing timeout. Current 10m timeout for TestVolumeProperties is already large enough. We should fix testbed issues.

**Comment by shuklanirdesh82** [comment]
> @pdhamdhere's comment https://github.com/vmware/docker-volume-vsphere/issues/1078#issuecomment-289074093

> We should fix testbed issues

Testbed cleanup and improvement is done. Closing this issue as wontfix.
