### ISSUE TITLE
Optimize TestVolumeProperties

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#1096]
[TestVolumeProperties](https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/E2E_Tests/e2e_verifyVolmProperties_test.go#L68) test takes more than a minute. 

We run following sequence thrice (for each disk type "thin", "zeroedthick", "eagerzeroedthick");
1.  Create volume (`docker volume create --driver=vsphere ...`
2. Verify size, disk-format type and attached-status with Admin CLI
3. Compare same properties with Docker CLI
4. Start busybox with volume attached
5. Repeat verification from Step 2 
6. Repeat verification from Step 3

Step 4-6 can be independent test with "thin" volume type. No need to repeat these steps for each disk-type.

**Comment by shuklanirdesh82** [comment]
@ashahi1 

As we have gocheck testing framework, let's have a plan to use gocheck instead of go testing so it will be easier to manage testcases.

Please prioritize this task to finish as part of 0.15 milestone.

Thanks.

/CC @tusharnt

**Comment by shuklanirdesh82** [comment]
close via #1310
