### ISSUE TITLE
"restart" option in CI does nothing

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#1107]
"restart" used to work before and restart the CI run. Please fix since many times CI failures are unrelated to PR and pushing a dummy commit is unnecessary overhead.

CC/ @tusharnt

**Comment by shuklanirdesh82** [comment]
@pdhamdhere 

> "restart" used to work before and restart the CI run. 

sorry there should be some confusion here. If agree please change it to ```feature``` from ```bug```

https://github.com/vmware/docker-volume-vsphere/blob/ee957a9790978e2242c58b685e24bbe2424079ff/misc/drone-scripts/validate-and-serialize.sh#L28

**Comment by govint** [comment]
It works but need to go back to the main list of the running builds (start from https://ci.vmware.run/login, login) and then select the one to restart and then restart. Had the same issue and followed above approach and worked.

**Comment by shuklanirdesh82** [comment]
@govint  I doubt it, please have a look at my comment (https://github.com/vmware/docker-volume-vsphere/issues/1107#issuecomment-289986543) .. our script is not supporting to restart build incase of failure.
