### ISSUE TITLE
Race condition while using docker engine api to calculate refCounts for volumes after plugin restart.

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1112]
This happens when plugin is used as a service and not when plugin is used as a managed plugin.

1. The refCount_test creates 5 containers, attaches a volume to them and makes them sleep.
2. It then creates another container, lists the contents of the volume attached in step 1.
3. Kills the plugin. Plugin restarts and calls the docker api to populate the refCounts for the volumes

In above steps, docker doesn't respond to api calls in step 3 because it itself tries to talk to plugin for an unmount command. But the source of unmount command is to be traced because the unmount for 6th container (to list contents of volume) was already received before kill as per logs.

If step 2 is not done, everything works fine and docker responds perfectly to the api calls.

This could be a possible bug in docker and also might establish the need to do reference counting of volumes post-init.

**Comment by govint** [comment]
Step 2 can happen in a real life scenario.  A set of containers have attached the volume and the plugin restarts for some reason. And one of the containers exits in the meantime causing the unmount. Same refcount test with a smalller sleep time in each container can trigger the issue.

**Comment by pshahzeb** [comment]
Enabled this in #1444.
