### ISSUE TITLE
Add goreport tag to the project

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#1136]
https://goreportcard.com/report/github.com/vmware/docker-volume-vsphere

See https://github.com/kubernetes/kops for example - they add goreport side by side with "build" tag. 

I am sure it's trivial and looks nice too :-)

**Comment by shuklanirdesh82** [comment]
> I am sure it's trivial and looks nice too :-)

Yeah indeed. Thanks @msterin for bringing this up and sharing details.
