### ISSUE TITLE
handling default_datastore for vmgroup

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1143]
When a VM addresses the volume using short notation (volume_name, without @datastore),  we will create this volume on the default_datastore of the vmgroup which the VM belongs to.  Currently, user can set "default_datastore" field for a vmgroup through "vmgroup access add" command:
1) The datastore used in the first privilege which is added to a vmgroup is set as "default_datastore" for that vmgroup automatically
2) User can specify "default_datastore" for a vmgroup when adding a privilege for a vmgroup with option "--default_datastore" specified explicitly.

With the above logic, correctly handling "default_datastore" may need many special checks and we may not sure whether the logic  in our code can cover all the corner cases( see an example in #1044).

After discuss with Mark and Sam,  we found that there are the use cases need to support:

Case1:  volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "vm_datastor"e where the VM lives, and can only access the vm_datastore

Case2:  volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "vm_datastore" where the VM lives, and can access some datastores other than "vm_datastore"

Case3: volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "vm_datastore" where the VM lives, and can access all datastores 

Case4:  volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "default_datastore" of this vmgroup, and can only access  the "default_datastore"

Case5:  volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "default_datastore" of this vmgroup, and can access some datastores other than the "default_datastore"

Case6: volume create from a VM which belongs to a named vmgroup, and by default, user wants to create the volume on the "default_datastore", and can access all datastores  (THIS IS NOT A COMMON USE CASE)

Case7:  volume create from a VM which belongs to "__DEFAULT"  vmgroup, and by default, user wants to create the volume on the "vm_datastore" where the VM lives, and can only access the "vm_datastore"

Case8:  volume create from a VM which belongs to "__DEFAULT"  vmgroup, and by default, user wants to create the volume on the "vm_datastore" where the VM lives, and can access all datastores 

Case9:  volume create from a VM which belongs to "__DEFAULT"  vmgroup, and by default, user wants to create the volume on the "default_datastore" of this vmgroup, and can only access to the "default_datastore"

Case10:  volume create from a VM which belongs to "__DEFAULT"  vmgroup, and by default, user wants to create the volume on the "default_datastore", and can access all datastores 

In order to support the above four use cases in a consistent way, we decide to make the following changes in the "default_datastore" handling:

1)  user is forced to set "default_datastore" when create a vmgroup.  The "default_datastore" can be either a real datastore which existed on ESX host or a hardcoded one "__VM_DS". If user set the "default_datastore" for a vmgroup as "__VM_DS", it means by default, user wants to create the volume on the datastore where the VM lives.

2) During creating the vmgroup, , our code will create that privilege with full access to" default_datastore"  specified by user in "vmgroup create" command automatically.
Need to print the message to tell user that the privilege is created with full access.
- If the "default_datastore" is set to a real datastore, this added access privilege make sure VM in this vmgroup has the privilege to the "default_datastore".
- If the "default_datastore" is set to the "__VM_DS", , this added access privilege make sure VM in this vmgroup has the privilege to create on the "vm_datastore" where the VM lives.

3) Add an option "--default_datastore"  in command "vmgroup update" to modify the "default_datastore" for a vmgroup.  Need to print warning message to warn user that he/she may lose control to the existing volumes after changing the "default_datastore" since the access privilege to old "default_datastore" will be replaced with access privilege to new "default_datastore". 

4) In order to make backward compatible (VM in “_DEFAULT” vmgroup will be able to reference the volume in vm_datastore when given short name, and should have access to all datastores), we will introduce two hardcoded datastore name and corresponding datastore_url. 
"__VM_DS": "__VM_DS://"
"__ALL_DS": "__ALL_DS://"

For any vmgroup:
- if it has an access privilege to "__VM_DS", which means VM in this vmgroup has access privilege to the "vm_datastore" where VM lives
- if it has an access privilege to "__ALL_DS", which means VM in this vmgroup has access privilege to all datastores
 
After install, system will automatically create the following
1) A "_DEFAULT" vmgroup, and set the "default_datastore" to "VM_DS"
2) A full access privilege with (_DEFAULT, __VM_DS)
3) A full access privilege with (_DEFAULT, __ALL_DS)

5) Update document to reflect the proposed changes.

6) Handle DB upgrade related change

**Comment by pdhamdhere** [comment]
@lipingxue Should we close this?

**Comment by lipingxue** [comment]
@pdhamdhere Not yet, the upgrade part #1179 has not been merged yet. I have two approval for that upgrade PR. Mark has some comments for that PR and I have addressed. Hope it can merge it today.

**Comment by lipingxue** [comment]
#1179 is merged, close this issue.
