### ISSUE TITLE
Able to create volume from VM which belongs to newly created tenant

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1145]
Steps:
1. Create a new tenant and add a vm to it. 
2. Create a volume from the tenant's vm. 
    I have not set any privileges on the tenant and still I am able to create volume.

Is this expected? Has there been recent change of behavior with respect to user created tenant? 

User-guide says that ```By default no "allow_create" right is given. "allow_create" right is given when you run the command with "--allow-create" flag```
https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/admin-cli.md

Please update the user-guide if there has been recent change of behavior for user created tenant.

------------------

Steps and their output are as follows:

- 1. Create a tenant - vmgroup1 and add a vm to it - photon-VM1.2
```
[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group create --name=vmgroup1 --vm-list=photon-VM1.2
vm-group create succeeded
[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name              Description                 Default_datastore  VM_list
------------------------------------  ----------------  --------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT          This is a default vm-group
bfc62d4f-ab41-4367-b683-3b62e1b51642  vmgroup1                                                         photon-VM1.2

[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group access ls --name=vmgroup1
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------

```

- 2. Created a volume from photon-VM1.2.

```
root@photon-xVmYMbyTn [ ~ ]# docker volume create --driver=vsphere --name=testVol_NT -o size=500mb
testVol_NT
root@photon-xVmYMbyTn [ ~ ]#
``` 
- 3. Admin cli volume ls 

```
[root@sc-rdops-vm06-dhcp-187-200:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume        Datastore     VM-Group          Capacity  Used  Filesystem  Policy  Disk Format  Attached-to   Access      Attach-as               Created By    Created Date
------------  ------------  ----------------  --------  ----  ----------  ------  -----------  ------------  ----------  ----------------------  ------------  ------------------------
testVol_NT    sharedVmfs-0  vmgroup1          500MB     23MB  ext4        N/A     thin         detached      read-write  independent_persistent  photon-VM1.2  Tue Apr  4 08:00:42 2017

[root@sc-rdops-vm06-dhcp-187-200:~]
```

**Comment by lipingxue** [comment]
It is the expected behavior based on the current code. The reason that it allows to create volume is because the default privilege is matched.
We have an ongoing discussion about whether we should allow volume create if user does not add privilege explicitly for named vmgroup.

**Comment by tusharnt** [comment]
This issue is no longer relevant after PR #1155
