### ISSUE TITLE
Restrict validate/retrieval of datastore names to only datastores provisioned to a vmgroup

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1149]
Today the ESX service functions that select/validate datastore names on a create req. do so against a list of all datastores (in mem. cache) kept in the ESX service. This must change to check against only the datastores assigned to the vmgroup that the requesting VM belongs to.

On create failure for unknown datastores, all known datastores are returned including those not assigned to the vmgroup. Change this to return only those that are present in the vmgroup.

**Comment by tusharnt** [comment]
@govint We need data to identify how much performance improvement we get by failing faster.

**Comment by govint** [comment]
This isn't for performance improvement, its only to avoid misleading the user on what datastores they have access to.  On error _all_ datastores are listed like the user has access to those. But in reality they don't have access to anything outside of the vmgroup. But its not a critical bug to go fix. Closing.
