### ISSUE TITLE
not able to use VMWare Volumes

### ISSUE THREAD

**Issue by lachnerd** [vmware/docker-volume-vsphere#1152]
Hi,
i want to use some of our development apps as docker version on vmware vsphere volumes.

For example i wanted to use Artifactory Pro from JFrog, so i tried the following;

1. created a vsphere volume
`docker volume create -d vsphere artifactory-data@san-datastore6 -o size=800gb` 
2. used Rancher to start artifactory
`artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.1.4
    stdin_open: true
    volumes:
    - artifactory-data:/var/opt/jfrog/artifactory
    tty: true
    mem_reservation: 2147483648
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.container.pull_image: always`

Application wants to start but after performing very slow i see the following output in the logs:

`Apr 06, 2017 11:33:43 AM org.apache.catalina.core.StandardContext startInternal
6.4.2017 13:33:43SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.core.StandardContext startInternal
6.4.2017 13:33:43SEVERE: Context [/artifactory] startup failed due to previous errors
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
6.4.2017 13:33:43WARNING: The web application [artifactory] registered the JDBC driver [org.apache.derby.jdbc.AutoloadedDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
6.4.2017 13:33:43WARNING: The web application [artifactory] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
6.4.2017 13:33:43 sun.nio.fs.LinuxWatchService.poll(Native Method)
6.4.2017 13:33:43 sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
6.4.2017 13:33:43 sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
6.4.2017 13:33:43 java.lang.Thread.run(Thread.java:745)
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.startup.HostConfig deployDescriptor
6.4.2017 13:33:43INFO: Deployment of configuration descriptor /opt/jfrog/artifactory/tomcat/conf/Catalina/localhost/artifactory.xml has finished in 2,427 ms
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.startup.HostConfig deployDirectory
6.4.2017 13:33:43INFO: Deploying web application directory /opt/jfrog/artifactory/tomcat/webapps/ROOT
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.catalina.startup.HostConfig deployDirectory
6.4.2017 13:33:43INFO: Deployment of web application directory /opt/jfrog/artifactory/tomcat/webapps/ROOT has finished in 100 ms
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.coyote.AbstractProtocol start
6.4.2017 13:33:43INFO: Starting ProtocolHandler ["http-nio-8081"]
6.4.2017 13:33:43Apr 06, 2017 11:33:43 AM org.apache.coyote.AbstractProtocol start
6.4.2017 13:33:43INFO: Starting ProtocolHandler ["ajp-nio-8019"]`

And Artifactory does not start successfully.

I tried the same with a simple Host Volume and Artifactory is fully up in about 15s.

What could be wrong here with vsphere Volume ?

**Comment by pdhamdhere** [comment]
@lachnerd Volume mount errors show up on console. I do not see volume errors on console. I think volume is attached and mounted successfully. We can confirm from /var/log/docker-volume-vsphere.log (VM) and /var/log/vmware/vmdk_ops.log (ESX). 

I don't have Rancher but I tried it with docker CLI and artifactory came up fine;

```
root@u-3:~# docker volume create -d vsphere artifactory-data@datastore1
artifactory-data@datastore1

root@u-3:~# docker run --rm -it -v artifactory-data:/var/opt/jfrog/artifactory docker.bintray.io/jfrog/artifactory-pro:5.1.4
...
...
###########################################################
### Artifactory successfully started (118.582 seconds)  ###
###########################################################

```

Then I started using local volume that worked too.

```
root@u-3:~# docker run --rm -it -v /tmp/artifactory-data:/var/opt/jfrog/artifactory docker.bintray.io/jfrog/artifactory-pro:5.1.4

Preparing to run Artifactory in Docker
=====================================
...

###########################################################
### Artifactory successfully started (119.849 seconds)  ###
###########################################################
```

Can we jump on a quick WebEx for troubleshooting? Drop us a note @ containers@vmware.com with day & time that works best for you.

**Comment by lachnerd** [comment]
@pdhamdhere  
i made one mistake i didn't test my Artifactory Setup without Rancher on console.
It seems like Rancher is the Problem here - if i start the containers with vsphere volumes like you in console everything seems fine.

If i take the same docker-compose.yml file and try to start it in rancher then i'm getting the same weird problems is stated above.

So it seems everything is fine with vsphere volume driver. 
Thanx for support.

**Comment by pdhamdhere** [comment]
Thanks for confirming @lachnerd Would you mind sharing docker-compose.yml you are having issues with Rancher? You can share it here or email @ containers@vmware.com

**Comment by lachnerd** [comment]
Hi heres my compose file.
