### ISSUE TITLE
Volume stays attached after abrupt docker plugin kill and container exit

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1159]
This is seen when the vDVS managed plugin is killed forcefully while the volume is still being used by a container. Reproduced as follows:

1. Create a volume and attach it to a container.
```
root@photon-xVmYMbyTn [ ~ ]# docker volume create -d vsphere:latest --name=testVol1_MP
testVol1_MP
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      testVol1_MP@sharedVmfs-0

root@photon-xVmYMbyTn [ ~ ]# docker run -it --volume-driver=vsphere:latest -v testVol1_MP@sharedVmfs-0:/vol1 --name ub ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d54efb8db41d: Pull complete
f8b845f45a87: Pull complete
e8db7bf7c39f: Pull complete
9654c40e9079: Pull complete
6d9ef359eaaa: Pull complete
Digest: sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
Status: Downloaded newer image for ubuntu:latest
root@53fa5061e340:/# df -h
Filesystem                                       Size  Used Avail Use% Mounted on
overlay                                          7.8G  721M  6.7G  10% /
tmpfs                                            2.0G     0  2.0G   0% /dev
tmpfs                                            2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0   93M  1.6M   85M   2% /vol1
/dev/root                                        7.8G  721M  6.7G  10% /etc/hosts
shm                                               64M     0   64M   0% /dev/shm
tmpfs                                            2.0G     0  2.0G   0% /sys/firmware
root@53fa5061e340:/#
root@53fa5061e340:/#
```
2. volume is indicated as attached to the VM
```
[root@sc-rdops-vm16-dhcp-237-252:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume       Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By  Created Date
-----------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ----------  ------------------------
testVol1_MP  sharedVmfs-0  _DEFAULT  100MB     15MB  ext4        N/A     thin         photon       read-write  independent_persistent  photon      Mon Apr 10 19:21:23 2017
```
3. Disable the plugin and kill the container from another terminal
```
root@photon-xVmYMbyTn [ ~ ]# docker plugin disable vsphere:latest -f
vsphere:latest

root@photon-xVmYMbyTn [ ~ ]# docker rm -f 53fa5061e340
53fa5061e340
root@photon-xVmYMbyTn [ ~ ]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
4. Volume still stays attached.
```
[root@sc-rdops-vm16-dhcp-237-252:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume       Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By  Created Date
-----------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ----------  ------------------------
testVol1_MP  sharedVmfs-0  _DEFAULT  100MB     15MB  ext4        N/A     thin         photon       read-write  independent_persistent  photon      Mon Apr 10 19:21:23 2017
```

While this reproduction is too harsh and destructive, such related and haywire behavior could happen on the docker side leading to not getting an unmount request on esx side.
Note: VM was powered on the time. So just monitoring VM events for cleaning up unattached volumes don't help much as pointed out in #369

**Comment by govint** [comment]
Won't this be an issue on Docker to disallow disabling a plugin when volumes (managed by the plugin) are in use? Much like an FS can;'t be unmounted when there are users for it.

**Comment by pshahzeb** [comment]
It does disallow. But it can still be disabled through the forced flag. This could also happen in context of plugin crash.

**Comment by govint** [comment]
The refcount logic should handle volumes left mounted with no containers
using those?

**Comment by msterin** [comment]
@pshahzeb - if after these steps you enable the plugin, does it issue the Linux unmount ?
Basically, we need 3 steps after the ones you've done
1. run 'grep vmdk /proc/mounts' to see if the volume is still mounted to Linux
2. enable the plugin 
3. check plugin logs for err messages and re-run (1)

**Comment by pshahzeb** [comment]
@govint @msterin 
After doing the above steps, the behavior is graceful. 
After restart, the plugin detects the one volume and issues unmount.
The volume status updates to 'detached'

With killing docker itself, here is the behavior:
I created a volume and attached a container.
Killed the docker with -9
docker restarts and our plugin restarts with it. We timeout in refcounting because docker itself is restarting. As we return, syncMountsWithRefCounters doesn't get called (it gets called from discoverAndSync). So the volume stays mounted.

**Comment by msterin** [comment]
In case we time out we should simply accept the inevitable and schedule a scan in a few minutes IMO. 
Comments ?

**Comment by pshahzeb** [comment]
Scan again to ask docker about used volumes? Good option.

**Comment by govint** [comment]
Yes, basically, redo the scan or simply do the scan once the plugin init
completes.
