### ISSUE TITLE
Support shared volumes on NFS datastores provisioned to the managed plugin.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1183]

**Comment by pdhamdhere** [comment]
@govint Can you write-up a quick proposal on user experience to use shared NFS volume and high level design?

**Comment by BaluDontu** [comment]
Would like to read the the design proposal for this when its out. So tagging myself @BaluDontu.

**Comment by govint** [comment]
Sorry, missed posting the spec to this issue, will update the spec and post it here with comments addressed. Missed that I'd not published here after the review over mail.

**Comment by govint** [comment]
Closing per discussion. There isn't a need to support NFS (or rather, non-vSphere storage) in the plugin or even as a separate plugin. There's little value add to have this capability when multiple options exist already to use NFS and more network based storage with Docker.
