### ISSUE TITLE
Publish VUM compatible zip file for vmdkops

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#1198]
Github releases used to publish VUM compatible VIB binary packaged as ZIP file. When we migrated 0.13 to bintray, we didn't publish ZIP file.

1. Fix release process to publish ZIP file. I am not sure how signing process works for ZIP file.
2. Test with VUM

**Comment by shuklanirdesh82** [comment]
> @pdhamdhere's comment https://github.com/vmware/docker-volume-vsphere/issues/1198#issue-224646460
> Fix release process to publish ZIP file. I am not sure how signing process works for ZIP file.

oops, it's a complete miss; thanks @pdhamdhere for catching this.

0.13 release is updated with following entry under download section.
```
ESX VIB Offline Bundle: https://bintray.com/vmware/vDVS/download_file?file_path=vmware-esx-vmdkops-0.13.15d313a.zip
```

Testing Done: on both ESX 6.0U2 and 6.5
```
[root@sc2-rdops-vm05-dhcp-191-69:~] esxcli software vib install -d /tmp/vmware-esx-vmdkops-0.13.15d313a.zip
Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: VMWare_bootbank_esx-vmdkops-service_0.13.15d313a-0.0.1
   VIBs Removed: 
   VIBs Skipped: 
[root@sc2-rdops-vm05-dhcp-191-69:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py status
Version: 0.13.15d313a-0.0.1
Status: Running
Pid: 1543767
Port: 1019
LogConfigFile: /etc/vmware/vmdkops/log_config.json
LogFile: /var/log/vmware/vmdk_ops.log
LogLevel: INFO
```

**Comment by pdhamdhere** [comment]
>oops, it's a complete miss; thanks @pdhamdhere for catching this.

I didn't. Customer did 😌

Can we also make sure VIB can be installed with VUM

**Comment by shuklanirdesh82** [comment]
> @pdhamdhere's comment https://github.com/vmware/docker-volume-vsphere/issues/1198#issuecomment-297606837
> Can we also make sure VIB can be installed with VUM

Thanks to @govint for sharing steps for vum on vsphere 6.5!

**for older VUM**: https://www.ivobeerens.nl/2012/07/17/add-hp-drivers-vib-to-vmware-update-manager-vum/ ... It's a good read for the future reference.

closing this now.

**Comment by shuklanirdesh82** [comment]
there is already an issue for adding documentation for vib installation using VUM see #555 and documentation part will be finished soon.
