### ISSUE TITLE
Review the use of handle_stale_attach

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1201]
After #1168,
The status of volume is updated at the poweroff event for VMs. This change makes handle_stale_attach in vmdk_ops useless. Get rid of the this check.
This should indirectly fix #1191. Because metadata reset happens in handle_stale_attach when VM to which a volume is attached isn't found (in shared db mode, the vm might reside on another host and hence won't be able to find)

**Comment by govint** [comment]
Prioritizing #1262 for now to get those test cases implemented. Have made the changes based on last round of reviews, needs testing and then will push the changes again.

**Comment by govint** [comment]
Closing
