### ISSUE TITLE
Refactor common code between photon_driver.go and vmdk_driver.go

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1212]
A big amount of code is common in these two files. Need to refactor them and place the common part in a common placeholder.

**Comment by govint** [comment]
The Create() and Mount() are possibly the only functions that are mostly similar in actions between Photon and the VMDK driver. Rest are specific to use the Photon Controller API and not really separable into common code between the two.

**Comment by shuklanirdesh82** [comment]
based on https://github.com/vmware/docker-volume-vsphere/issues/1212#issuecomment-300236648 ... adding `invalid` keyword
