### ISSUE TITLE
Missing steps to install on Photon .. or is it broken on Photon OS?

### ISSUE THREAD

**Issue by runecalico** [vmware/docker-volume-vsphere#1215]
First time using Photon, First time trying to use docker-volume-vpshere as well.  So far not very inspiring. Installing the plugin will crash docker, crash systemd (or something) requiring me to "hard power cycle" the VM and afterwards docker refuses to start.

Steps to reproduce:

Download Photon 1.0 Rev 2 OVA
Deploy OVA to VM
Update VM to latest packages (tdnf distro-sync -y), Reboot
After reboot, enable SSH
Login via SSH, enable docker service, docker plugin install.. and watch ..

Here is most of the output from the above steps.
root@photon-machine [ ~ ]# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@photon-machine [ ~ ]# systemctl enable docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/doc                                                           ker.service.
root@photon-machine [ ~ ]# systemctl start docker
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
root@photon-machine [ ~ ]# docker --version
Docker version 1.13.1, build 092cba3
root@photon-machine [ ~ ]# docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest
latest: Pulling from vmware/docker-volume-vsphere
bc8c14d82abc: Download complete
Digest: sha256:6b81577c0502f537bc8a5ccf3f1599d9f9b7276242d7043d00d04496f312b976
Status: Downloaded newer image for vmware/docker-volume-vsphere:latest
Error response from daemon: rpc error: code = 2 desc = containerd: container not started
root@photon-machine [ ~ ]# docker plugin disable vsphere
Error response from daemon: plugin "vsphere" not found
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
root@photon-machine [ ~ ]# systemctl status docker
Failed to connect to bus: No such file or directory
root@photon-machine [ ~ ]# reboot
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.

and then after a "hard reset"

root@photon-machine [ ~ ]# systemctl status docker
● docker.service - Docker Daemon
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-05-03 01:29:29 UTC; 16s ago
     Docs: http://docs.docker.com
  Process: 298 ExecStart=/usr/bin/docker daemon $DOCKER_OPTS --containerd /run/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 298 (code=exited, status=1/FAILURE)

May 03 01:29:28 photon-machine systemd[1]: Starting Docker Daemon...
May 03 01:29:28 photon-machine docker[298]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
May 03 01:29:29 photon-machine docker[298]: Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/fd...
May 03 01:29:29 photon-machine systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 03 01:29:29 photon-machine systemd[1]: Failed to start Docker Daemon.
May 03 01:29:29 photon-machine systemd[1]: docker.service: Unit entered failed state.
May 03 01:29:29 photon-machine systemd[1]: docker.service: Failed with result 'exit-code'.

Variations on this that also don't work.
1) Download the ISO, and do a full install (vs the OVA)
2) enable/start docker-containerd service prior to docker plugin install
3) Run the VM on ESX 6.0 vSan cluster
4) Run the VM on ESX 6.5 vSan cluster

Should this be moved/submitted to the Photon OS issue list?

**Comment by shuklanirdesh82** [comment]
Hi @runecalico,

Sorry to hear that you run into too many issues.

> Error response from daemon: rpc error: code = 2 desc = containerd: container not started

It is likely to be a docker issue https://github.com/moby/moby/issues/22226#issuecomment-292617804

Can you please share `docker` and `docker-volume-vsphere.log` logs for further look? 

just FYI: there are photon VMs with docker 1.13.1 on our CI system and plugin installation works fine. It would be great if you can share logs that helps to find root cause. By looking at the above steps it seems docker issue to me.

Thanks for sharing steps!

/CC @govint @msterin

**Comment by pdhamdhere** [comment]
@runecalico Sorry you had hard time getting started. We are able to reproduce the issue with latest Photon release. We will root cause and follow-up with Photon OS team (CC/ @sharathjg ). Manually upgrading to latest Docker release seems to resolve the issue;

```
  tdnf install wget
  wget https://test.docker.com/builds/Linux/x86_64/docker-17.05.0-ce-rc3.tgz
  systemctl stop docker
  tar --strip-components=1 -xvzf docker-17.05.0-ce-rc3.tgz -C /usr/bin
  tdnf install tar
  tar --strip-components=1 -xvzf docker-17.05.0-ce-rc3.tgz -C /usr/bin
  systemctl start docker
  docker info
  docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest
  docker volume create -d vsphere v2
  docker volume ls
  docker run --rm -it -v v2:/data busybox
```

Another option is to use non-plugin version i.e. RPM version of vSphere Docker Volume Service.

```
wget https://bintray.com/vmware/vDVS/download_file?file_path=docker-volume-vsphere-0.13.15d313a-1.x86_64.rpm
rpm -ivh docker-volume-vsphere-0.13.15d313a-1.x86_64.rpm
systemctl status docker-volume-vsphere
docker volume ls
docker volume create -d vsphere v3
docker run -it -v v3:/data busybox
```

**Comment by pdhamdhere** [comment]
@runecalico Photon OS team has root caused the issue and working on updated OVA. Issue is tracked in [PhotonOS #640](https://github.com/vmware/photon/issues/640)

In the meantime, you can try one of alternative proposed above (manually upgrade to latest Docker release or use RPM)

Feel free to reach out to us @ containers@vmware.com if you need assistance and we can schedule time to go over features and discuss your use case.

**Comment by runecalico** [comment]
Awesome! I'll look into the suggestions and update. Re: RPM .. Since the doc mentioned that the RPM was no longer the supported/recommended install method (and it's not in the Photon repo) I didn't even look! (doh).   Re: latest docker - I expected it was something like that as I was able to get the driver working on a RedHat 7 box with the latest docker ..  Thanks a bunch, I was hoping to test Photon vs RHEL as container hosts in our Vmware environment ..

**Comment by runecalico** [comment]
@pdhamdhere 

For an install that has already gone south, the only option seems to be to completely uninstall docker and cleanup any docker locations (like /var/lib/docker and /etc/docker) and then re-install.  At that point.. Both recommendations worked for me. Thanks for the help on getting this working, much appreciated.

**Comment by pdhamdhere** [comment]
Thanks @runecalico Keep us posted with results from your experiments and let us know if you run into any issues.
