### ISSUE TITLE
Wrong network type in config.json

### ISSUE THREAD

**Issue by oliverbestmann** [vmware/docker-volume-vsphere#1225]
When starting the docker-engine with this plugin, docker creates a bind mount for `/etc/hosts` and `/etc/resolv.conf`. To me, it looks like this is happening because of this line in the config file: https://github.com/vmware/docker-volume-vsphere/blob/master/plugin/config.json#L39

I think the correct value should be the empty string. Compare with this: https://github.com/moby/moby/blob/bbce24997c7a31454edd1d3d979823582bcdd95d/plugin/v2/plugin_linux.go#L42

**Comment by msterin** [comment]
Yep, thanks for the catch. //CC @shuklanirdesh82

**Comment by shuklanirdesh82** [comment]
Thanks @oliverbestmann for sharing details!

> https://github.com/vmware/docker-volume-vsphere/issues/1225#issue-227027764
> I think the correct value should be the empty string. Compare with this: https://github.com/moby/moby/blob/bbce24997c7a31454edd1d3d979823582bcdd95d/plugin/v2/plugin_linux.go#L42

I will test out locally and supply a quick fix, confirmed this change with @msterin offline (Thanks to  Mark!) 

/CC @msterin
