### ISSUE TITLE
VSAN volume status isn't updated to "detached" on VM poweroff event

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1233]
Steps to reproduce
1. create a volume on vsanDatastore
2. attach this volume to a container
3. kill the VM
4. use /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls to verify the status. It will be attached to the VM.

Reason:
We decide if a volume is vDVS volume if its backing file name starts with "dockvols"
But on vsan dockvols is a symlink to the directory uuid. So the volume backing file name starts with directory uuid.

The fix is to resolve the symlinks for dockvols folder for a datastore and use the resolved dockvols directory to identify if it is a vDVS volume

//CC @pdhamdhere

**Comment by shaominchen** [comment]
>> The fix is to resolve the symlinks for dockvols folder for a datastore and use the resolved dockvols directory to identify if it is a vDVS volume
I agree. Let's create a PR for this.

**Comment by msterin** [comment]
findDeviceByPath() already uses os.path.realpath. Where exactly is the bug ?
