### ISSUE TITLE
Wrong indention in the docker-stack yaml file

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1237]
There's a wrong indention in the docker-stack yaml file on this page: http://vmware.github.io/docker-volume-vsphere/documentation/docker-stacks.html

Instead of this:

volumes:
++db-data:
++++driver: vsphere
++++++driver_opts:
++++++++size: 1Gb

Should be like this:

volumes:
++db-data:
++++driver: vsphere
++++driver_opts:
++++++size: 1Gb

**Comment by tusharnt** [comment]
cc @girishshilamkar
