### ISSUE TITLE
Add support to automation script for running swarm testcases (on nimbus infra)

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1250]
As of now our deployment scripts deploys testbed with 4 ESX vms and 6 docker host vm (preconfigured with docker version passed as input). 

We need to enhance the deployment script to get the testbed with docker swarm cluster configured.

/CC @shaominchen

**Comment by ashahi1** [comment]
Have modified the testbed deployment script to take care of configuring swarm in the deployed VMs for the testbed deployed on Nimbus. Closing this issue for now.
