### ISSUE TITLE
[3 tests] Automate refcount P0 testcases

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1252]
- [ ] Testcase 1: Test stale mounts 
Steps:
```
    a. Start container without restart flag
    b. kill docker and wait for docker to start
    c. Check if disk is detached
```

- [ ] Testcase 2: Kill Plugin
```
Kill Plugin
   a. Start container with restart flag
   b. kill plugin
   c. stop container
   d. start container (should succeed)
   e. stop container (should succeed & volume should be detached.
```

- [ ] Testcase 3: kill docker host vm
```
kill docker host vm

1. create volume
2. mount more than one container with restart policy `--restart=always` (let's mount 5 containers)
3. perform verification through docker volume inspect and vmdkops_admin volume ls to check for the attached status
4. kill docker host vm
5. start docker host vm
6. stop all containers
7. verifies the volume is in detached state and containers are not in running mode
8. remove volume and make sure volume rm works fine

```

Note: New change for 0.14
 
reference count rescan
With --restart=always flag containers are restarted even after  docker host restart.
Verify tests 1 to 4 with and without this flag. If this flag is used, containers are restarted and disk will be attached again. If using this flag, explicitly stop the containers and then verify if disk has been detached.
If this flag is not used, then containers don’t automatically restart and volume remains detached. This is docker behaviour

**Comment by pshahzeb** [comment]
Test 3 doesn't hit refcount logic. It is because of step 4, which will trigger VM listener event and disk would be detached after step 4 itself. This gets tested through #1256 .

**Comment by pshahzeb** [comment]
Automated through #1265 and #1287
