### ISSUE TITLE
[3 tests] Automate P0 plugin Test Cases

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1254]
- [ ] 1. Verify volume creation with different options for volume names
Detailed steps are found at https://github.com/vmware/docker-volume-vsphere/issues/856#issue-200197407 & https://github.com/vmware/docker-volume-vsphere/issues/856#issuecomment-277108897

- [ ] 2. Verify volume creation with different volume create options
Steps are found at https://github.com/vmware/docker-volume-vsphere/issues/855#issue-200196599 & https://github.com/vmware/docker-volume-vsphere/issues/855#issuecomment-286897008

- [ ] 3. Verify if able to update access attribute for volume from admin cli
Steps are found at: https://github.com/vmware/docker-volume-vsphere/issues/820#issue-195411672

**Comment by pshahzeb** [comment]
Additional test cases as per updated steps for #820
