### ISSUE TITLE
Admin CLI config rm doesn't remove the DB when --no-backup option is used

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1258]
/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config rm --no-backup --local --confirm

ls -l /etc/vmware/vmdkops/
total 20
-rw-r--r--    1 root     root         15360 May 16 11:17 auth-db
-rw-r--r--    1 root     root          1257 May 16 11:08 log_config.json

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config status
DB_Mode: SingleNode (local DB exists)
DB_LocalPath: /etc/vmware/vmdkops/auth-db
DB_SharedLocation: N/A

**Comment by msterin** [comment]
It removes perfectly fine on test bed, synced to the latest master. It may have been fixed since May. Please re-verify
@govint

**Comment by govint** [comment]
Yes, it moves the current DB to a backup file, but this issue happens when the --no-backup option is  given.

**Comment by shaominchen** [comment]
Correctness issue - must fix for Kubecon release.

**Comment by govint** [comment]
Closing, cross-ESX multi-tenancy isn't supported and with Kubernetes + CSI + VC backed volume plugin multi-tenancy is as definable via the container orchestrator. Multi-tenancy inside the platform and not at the container orchestrator level is not worth pursuing any more.
