### ISSUE TITLE
[5 tests] Automate P0 Tenancy testcases

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1261]
- [ ] ~1. Moving a VM across tenants and validates volume accessibility~
~steps: Please refer Issue #897~

- [x] 2. Add VMs to the _DEFAULT tenant
steps: Please refer Issue #1125

- [ ] ~3. Verify 'Attached to vm' field~
~steps: Please refer Issue #1053~

- [x] 4. Orphaned volume should not be viewable from any docker host
steps: Please refer Issue #1031

- [x] 5. Tenant ls command does not works if vm that was added to tenant is deleted.
steps: Please refer Issue #929

**Comment by shaominchen** [comment]
@ashahi1 Can you split this to separate issues so that it's easier to track?

**Comment by ashahi1** [comment]
For 3rd test, created separate issue as CI needs to have two ESXs #1453

**Comment by ashahi1** [comment]
case 4 and 5 will be addressed by #1381

**Comment by ashahi1** [comment]
For 1st test, created separate issue - #1491

**Comment by ashahi1** [comment]
Tests 2, 4 and 5 have been checked-in. Closing this issue.
