### ISSUE TITLE
[9 tests] Automate P0 Tenancy testcases

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1262]
- [ ] 1. Verify _DEFAULT tenant exist with default privileges and verify volume creation
steps: Please refer Issue #895

- [ ] 2. Verify volume creation by updating access privileges for _DEFAULT tenant
steps: Please refer Issue #895

- [ ] 3. Verify volume creation after deleting _DEFAULT tenant
steps: Please refer Issue #899

- [ ] 4. Verify volume creation from new tenant
steps: Please refer Issue #899

- [ ] 5. Verify volume creation after deleting user created tenant
steps: Please refer Issue #899

- [ ] 6. Update datastore access for volume creation (--allow-create) for the Tenant T1 and create volume from VM1
steps: Please refer Issue #899

- [ ] 7. Update datastore access for --volume-totalsize from 1 GB to 2GB by keeping allow_create to true and Max_volume_size to satisfiable
steps: Please refer Issue #899

- [ ] 8. Update datastore access for --volume-maxsize from 500MB to 600MB by keeping all other rights satisfiable
steps: Please refer Issue #899

- [ ] 9. Update access rights gradually from non-satisfiable to satisfiable for {volume-maxsize, allow-create, volume-totalsize}
steps: Please refer Issue #899

**Comment by govint** [comment]
Tests 4 overlaps with 1 and 5 isn't allowed anymore. Vmgroup can't be deleted with a VM in it. Test 6 in #899 led to fixes that prevent deleting the vmgroup with a VM in it. Test 3 is also disallowed now.

**Comment by govint** [comment]
Closed #1286
