### ISSUE TITLE
Automate Basic tests

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1263]
Detail steps are mentioned at https://github.com/vmware/docker-volume-vsphere/issues/957#issue-209840924 & https://github.com/vmware/docker-volume-vsphere/issues/957#issuecomment-282431323

**Comment by shaominchen** [comment]
As discussed offline with @shuklanirdesh82, we agree that the test cases described in #957 are quite distinct, so we should move some test scenarios to other test groups. I will file separate issues to track those scenarios. Currently the basic_test group will only include 3 tests: TestVolumeLifecycle, TestBasicVolumeIsolation, and TestVmGroupVolumeIsolation.

**Comment by shuklanirdesh82** [comment]
Thanks @shaominchen for breaking this down and creating separate issues. for the 0.16 there is only one testcase being tracked for this issue. 

Can you please refresh the estimate for `TestVmGroupVolumeIsolation `?
