### ISSUE TITLE
Upgrade drone node to use drone 0.5 release

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1268]
CI is running with drone 0.4 release and needs to be upgraded.

Some probable tasks

- [ ] configure test launcher node to have 0.5 release

- [ ] .drone.yml or .drone.dev.yml files needs to be updated to accommodate new version

- [ ] re-sign the security file

**Comment by shuklanirdesh82** [comment]
The strong need for upgrading to drone 0.5 was enabling parallel execution on CI system. I have figured out a way to use matrix approach and being tracked at #1325 so moving this out to next milestone i.e. 0.17.

**Comment by shaominchen** [comment]
CI improvement - must fix for Kubecon release.

**Comment by shuklanirdesh82** [comment]
The idea behind this issue was to make parallel run using drone matrix. Drone 0.4 does support matrix to invoke test but it is not applicable to our strategy. We are using snapshot functionality to reset testbed. 

There is already an improvement issue https://github.com/vmware/docker-volume-vsphere/issues/1323 so closing this as invalid.
