### ISSUE TITLE
Extend test verification using govmomi functionality

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1277]
Please refer https://github.com/vmware/docker-volume-vsphere/blob/master/tests/utils/verification/volumeproperties.go#L107 for more information.

govmomi support is required to traverse through VC/ESX inventory.

**Comment by pshahzeb** [comment]
As of now, the check to compare vm name attached to a volume against expected vm name (obtained using govc) in VerifyAttachedStatus in tests/utils/verification/volumeproperties.go is commented. Need to uncomment it.

**Comment by shuklanirdesh82** [comment]
What is the reason for reopening this issue? This issue has nothing to do with the problem we are dealing with photon vm's guest IP.

Closing this PR and need to open a separate issue to take care about uncommenting part.

/CC @shaominchen

**Comment by shaominchen** [comment]
Opened a new issue: #1284
