### ISSUE TITLE
Prepare CI testbed to run all P0 tests

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1279]
Currently CI is having 1 ESX and 2 VMS for vSphere 6.5 and the same for 6.0. For running P0 tests, there is a need of having 2 ESX + 6 vms (1 vm each on local/shared/vsan).

2 ESX 6.5 as nested VMs: 

- having access to 3 datastore (shared/local/vsan)
- 1 vm each on above datastores ( 3vms)

The same setup for ESX 6.0 U2 as well.

**Comment by shaominchen** [comment]
Some test scenarios are being commented out due to testbed limitation. We need to collect all the detailed requirements here and decide what's exactly needs to be done.

**Comment by shaominchen** [comment]
@shuklanirdesh82 Can you please clarify how many P0 tests are being blocked by this? If there are a lot, we need to mark this as mustfix as it impacts code coverage.

**Comment by tusharnt** [comment]
All P0 tests are supported on CI.
