### ISSUE TITLE
[test automation common util] Add an approach to query specific test vm/esx details for automation tests

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1280]
Enhance https://github.com/vmware/docker-volume-vsphere/blob/master/tests/utils/inputparams/testparams.go to gain more hooks on the underlying testbed. It helps for test automation scripts and increases readability.

**Comment by shaominchen** [comment]
Some test scenarios are being commented out due to testbed limitation. We need to collect all the detailed requirements here and decide what's exactly needs to be done.

**Comment by shaominchen** [comment]
This is useful, but doesn't seem to be mustfix for Kubecon release.

**Comment by shuklanirdesh82** [comment]
with the closure of #1279 this issue is no longer valid. closing as `invalid`.
