### ISSUE TITLE
vmdk_opsd does not properly restart on signal 10 (and instead throws an exception) 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1291]
Seeing ```Function not implemented error``` in the vmdkops log after I run the command to Initialize the Config DB to SingleNode.

Command: /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config init --local

/var/log/vmware/vmdk_ops.log snippet:
```
05/24/17 18:50:42 1386157 [MainThread] [ERROR  ] [Errno 38] Function not implemented: '/usr/lib/vmware/vmdkops/bin/vmdk_ops.py'
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1706, in main
    handleVmciRequests(port)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1637, in handleVmciRequests
    c = lib.vmci_get_one_op(g_vmci_listening_socket, byref(cartel), txt, c_int(bsize))
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1530, in signal_handler_restart
    os.execve(__file__, sys.argv, os.environ)

```

Logs: 
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1026768/vmdk_ops.txt)

**Comment by govint** [comment]
Happens in the signal handler when the service is restarted. Saw this a few times last week but then its not consistent. Are we trying to restart the script when the signal is received?

**Comment by msterin** [comment]
To clarify what is going on: 

* for some reason ` os.execve` in `signal_handler_restart` throws the "function not implemented" exception (see above). **This causes the whole service to exit, and it is restarted by init.d watchdog , up to 10 times (per config in vmdk-opsd). After the 10th time the service stays down** 

* this exposes a few obvious glitches, but unfortunately it is not clear what is going on:
  * os.execve() works fine on ESX (we double-checked it), but fails when called in the context of C waiting for VMCI connection. Not sure if it's an issue or a coincidence
  * we close vmci socket in `vmci_release_listening_socket` but do not clear up global `g_vmci_listening_socket`
  * os.execve params seem to be inaccurate (see suggestion below)

---

Note: Fixing the above items **does not** fix the issue, but we need to fix it still to remove dirt. 

Here is how execve params should look like, probably: 
```python
   executable = os.path.realpath(sys.executable)
    os.execve(executable, [executable,  __file__] + sys.argv, os.environ)
```

**Comment by msterin** [comment]
Setting to P0 because this bug will ALWAYS lead to service down after 10 attempts to do "vmdkops_admin.py config init" or "config rm"

**Comment by msterin** [comment]
ANother point: we can replace the whole signal sending with running os.system("/etc/init.d/vmdk-opsd restart") from admin tool (instead of . THis is heavy but can be a tmp patch.

**Comment by shaominchen** [comment]
This has caused CI failure as we have introduced some vmgroup related e2e tests which will run "config init" and "config rm" multiple times. Right now we are trying some workaround to restart vmdkops. But this seems not really a corner case, especially during testing or experiment scenarios.

**Comment by ashahi1** [comment]
I tested this scenario with Marks's commit ```b324923``` that was checked-in and I had not hit this issue.
https://github.com/vmware/docker-volume-vsphere/pull/1065

This is likely a regression.
@msterin

**Comment by shuklanirdesh82** [comment]
Thanks @msterin for going over this issue and walking through the vmdkops_admin.py code!

As per offline discussion, I have tried out the fix locally that @msterin suggested. I will send out the PR soon.

/CC @msterin
