### ISSUE TITLE
E2E - restart test errors

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1311]
Ran the e2e tests with no env. vars set, its supposed to fail which is ok, but at least take care of Panic issues.

2017/05/31 07:06:17 Creating volume [restart_test_volume_1496214377] on VM []

----------------------------------------------------------------------
FAIL: restart_test.go:38: PluginSuite.SetUpTest

restart_test.go:46:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4200abfc0), Stderr:[]uint8(nil)} ("exit status 255")
...

2017/05/31 07:06:17 Removing container [restart_test_container_1496214377] on VM []

----------------------------------------------------------------------
FAIL: restart_test.go:49: PluginSuite.TearDownTest

restart_test.go:51:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4200b8040), Stderr:[]uint8(nil)} ("exit status 255")
...

----------------------------------------------------------------------
PANIC: restart_test.go:89: PluginSuite.TestPluginKill

... Panic: Fixture has panicked (see related PANIC)
2017/05/31 07:06:17 Finding VM name from IP Address []
2017/05/31 07:06:17 START: Test vmdkops service restart + kill vm process
2017/05/31 07:06:17 Creating volume [vmlistener_test_volume_1496214377] on VM []
2017/05/31 07:06:17 Checking container [vmlistener_test_container_1496214377] presence on VM []
2017/05/31 07:06:17 Destroying volume [vmlistener_test_volume_1496214377]

**Comment by shuklanirdesh82** [comment]
@pshahzeb I am assigning to you as you worked on the plugin test.

**Comment by pshahzeb** [comment]
@govint I see the env handling in your PR #1428 to skip the test when the env vars are not set.
