### ISSUE TITLE
.vmdk Being formatted / recreated on Node failure.

### ISSUE THREAD

**Issue by Eireocean** [vmware/docker-volume-vsphere#1312]
Good Day,

We are testing vSphere Docker Volume Service (vDVS) in a testing environment : 

- VMWare ESXi 6.5.0 build 5310538
- Datastore VMFS 5

- CentOS 7.3.1611
- Kernel 3.10.0-514.16.1

- Docker EE 17.03.1.ee.3-1

We have 3 x Nodes all Managers in a Swarm.

The issue we are having is that we deploy Wordpress with MariaDB (Stack) on a Persistent Disk and test High-Availability. The Node that MariaDB is started on, is shutdown. Not gracefully.

As expected, it starts on another Node, however, all published content is gone and Wordpress presents with the installation page again.

Deployment : 

_# vim docker-compose.yml_

```
version: '3'

services:
   db:
     image: mariadb
     deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
     environment:
       MYSQL_ROOT_PASSWORD: rootpasswd
       MYSQL_USER: wp
       MYSQL_PASSWORD: wppasswd
       MYSQL_DATABASE: wp
     volumes:
       - mariadb:/var/lib/sql

   web:
     image: wordpress:latest
     deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
     depends_on:
       - db
     ports:
       - "8080:80"
     environment:
       WORDPRESS_DB_USER: wp
       WORDPRESS_DB_PASSWORD: wppasswd
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wp

volumes:
   mariadb:
      driver: vsphere
      driver_opts:
        size: 1Gb
        diskformat: zeroedthick
```

_# docker stack deploy -c docker-compose.yml wordpress_

Stack Creation Log 'docker-volume-vsphere.log' (Node 3) : 

_2017-05-31 11:34:18.065989758 +0000 UTC [INFO] Attaching volume and creating filesystem fstype=ext4 name="wordpress_mariadb"
2017-05-31 11:34:18.446760569 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0": 0x100 == IN_CREATE
2017-05-31 11:34:18.872102583 +0000 UTC [INFO] Volume and filesystem created name="wordpress_mariadb" fstype=ext4
2017-05-31 11:34:19.804128621 +0000 UTC [INFO] Mounting volume name="wordpress_mariadb"
2017-05-31 11:34:20.262664455 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0": 0x100 == IN_CREATE_

Disk Creation Log '/var/log/vmware/vmdk_ops.log' (Host3) : 

_05/31/17 11:43:10 67742 [MainThread] [INFO   ] Connecting to the local Service Instance as 'dcui'
05/31/17 11:43:10 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (8, 88980, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 11:43:11 67742 [Thread-2] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:11 67742 [Thread-2] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:11 67742 [Thread-2] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'Error': 'Volume wordpress_mariadb not found (file: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk)'}
05/31/17 11:43:11 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (10, 88980, b'{"cmd":"create","details":{"Name":"wordpress_mariadb","Opts":{"diskformat":"zeroedthick","fstype":"ext4","size":"1Gb"}},"version":"2"}')
05/31/17 11:43:11 67742 [Thread-3] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:11 67742 [Thread-3] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:11 67742 [Thread-3] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] *** createVMDK: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk opts = {'fstype': 'ext4', 'size': '1Gb', 'diskformat': 'zeroedthick'} vm_name=vdsv03 tenant_uuid=11111111-1111-1111-1111-111111111111 datastore_url=/vmfs/volumes/55350802-fa643ee2-e8f6-5cf3fc4e5690
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] No access control, skipping volumes tracing in auth DB
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'create' completed with ret=None
05/31/17 11:43:11 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (8, 88980, b'{"cmd":"attach","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 11:43:11 67742 [Thread-4] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:11 67742 [Thread-4] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:11 67742 [Thread-4] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] *** attachVMDK: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk to vdsv03 VM uuid = 42198604-607e-426a-7550-fea511e788ce
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Attaching /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk as independent_persistent
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Disk /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk successfully attached. controller pci_slot_number=160, disk_slot=2
05/31/17 11:43:11 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'attach' completed with ret={'Unit': '2', 'ControllerPciSlotNumber': '160'}
05/31/17 11:43:12 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (10, 88980, b'{"cmd":"detach","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 11:43:12 67742 [Thread-5] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:12 67742 [Thread-5] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:12 67742 [Thread-5] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:12 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] *** detachVMDK: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk from vdsv03 VM uuid = 42198604-607e-426a-7550-fea511e788ce
05/31/17 11:43:12 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Disk detached /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk
05/31/17 11:43:12 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'detach' completed with ret=None
05/31/17 11:43:12 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (8, 88980, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 11:43:12 67742 [Thread-6] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:12 67742 [Thread-6] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:12 67742 [Thread-6] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:12 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'fstype': 'ext4', 'attach-as': 'independent_persistent', 'status': 'detached', 'created by VM': 'vdsv03', 'diskformat': 'zeroedthick', 'datastore': 'FC-DS35-BLUE-DAT01', 'access': 'read-write', 'clone-from': 'None', 'capacity': {'size': '1GB', 'allocated': '1GB'}, 'created': 'Wed May 31 11:43:11 2017'}
05/31/17 11:43:13 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (10, 88980, b'{"cmd":"get","details":{"Name":"d88c3fbbeb201224df89dec1b59dfa74d0893323d23e552b3b13e0853d7c157a"},"version":"2"}')
05/31/17 11:43:13 67742 [Thread-7] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:13 67742 [Thread-7] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:13 67742 [Thread-7] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.d88c3fbbeb201224df89dec1b59dfa74d0893323d23e552b3b13e0853d7c157a] [INFO   ] executeRequest 'get' completed with ret={'Error': 'Volume d88c3fbbeb201224df89dec1b59dfa74d0893323d23e552b3b13e0853d7c157a not found (file: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/d88c3fbbeb201224df89dec1b59dfa74d0893323d23e552b3b13e0853d7c157a.vmdk)'}
05/31/17 11:43:13 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (8, 88980, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 11:43:13 67742 [Thread-8] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:13 67742 [Thread-8] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:13 67742 [Thread-8] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'fstype': 'ext4', 'attach-as': 'independent_persistent', 'status': 'detached', 'created by VM': 'vdsv03', 'diskformat': 'zeroedthick', 'datastore': 'FC-DS35-BLUE-DAT01', 'access': 'read-write', 'clone-from': 'None', 'capacity': {'size': '1GB', 'allocated': '1GB'}, 'created': 'Wed May 31 11:43:11 2017'}
05/31/17 11:43:13 67742 [MainThread] [INFO   ] Started new thread : 305296525056 with target <function execRequestThread at 0x47134afea0> and args (10, 88980, b'{"cmd":"attach","details":{"Name":"wordpress_mariadb@FC-DS35-BLUE-DAT01"},"version":"2"}')
05/31/17 11:43:13 67742 [Thread-9] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 11:43:13 67742 [Thread-9] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 11:43:13 67742 [Thread-9] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] *** attachVMDK: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk to vdsv03 VM uuid = 42198604-607e-426a-7550-fea511e788ce
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Attaching /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk as independent_persistent
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Disk /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk successfully attached. controller pci_slot_number=160, disk_slot=2
05/31/17 11:43:13 67742 [vdsv03-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'attach' completed with ret={'Unit': '2', 'ControllerPciSlotNumber': '160'}_

Wordpress Is setup and content is then published. There after the Node is 'killed'.

Recovery Log 'docker-volume-vsphere.log' (Node 2) : 

_2017-05-31 11:48:23.343988247 +0000 UTC [INFO] Mounting volume name="wordpress_mariadb"
2017-05-31 11:48:23.823372618 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0": 0x100 == IN_CREATE_

Recovery Log '/var/log/vmware/vmdk_ops.log' (Host2) : 

_05/31/17 13:47:53 67748 [MainThread] [INFO   ] Started new thread : 458876675840 with target <function execRequestThread at 0x6ad5621ea0> and args (10, 91477, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 13:47:53 67748 [Thread-3] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 13:47:53 67748 [Thread-3] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 13:47:53 67748 [Thread-3] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 13:47:53 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'datastore': 'FC-DS35-BLUE-DAT01', 'access': 'read-write', 'diskformat': 'zeroedthick', 'status': 'detached', 'created by VM': 'vdsv03', 'created': 'Wed May 31 11:43:11 2017', 'capacity': {'allocated': '1GB', 'size': '1GB'}, 'attach-as': 'independent_persistent', 'clone-from': 'None', 'fstype': 'ext4'}
05/31/17 13:47:53 67748 [MainThread] [INFO   ] Started new thread : 458876675840 with target <function execRequestThread at 0x6ad5621ea0> and args (9, 91477, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 13:47:53 67748 [Thread-4] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 13:47:53 67748 [Thread-4] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 13:47:53 67748 [Thread-4] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 13:47:53 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'datastore': 'FC-DS35-BLUE-DAT01', 'access': 'read-write', 'diskformat': 'zeroedthick', 'status': 'detached', 'created by VM': 'vdsv03', 'created': 'Wed May 31 11:43:11 2017', 'capacity': {'allocated': '1GB', 'size': '1GB'}, 'attach-as': 'independent_persistent', 'clone-from': 'None', 'fstype': 'ext4'}
05/31/17 13:47:54 67748 [MainThread] [INFO   ] Started new thread : 458876675840 with target <function execRequestThread at 0x6ad5621ea0> and args (10, 91477, b'{"cmd":"get","details":{"Name":"86839502fe764474343b6e2eb1cf0817bcf91d5198bdbc7c8fb91a4114ed1b0a"},"version":"2"}')
05/31/17 13:47:54 67748 [Thread-5] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 13:47:54 67748 [Thread-5] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 13:47:54 67748 [Thread-5] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 13:47:54 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.86839502fe764474343b6e2eb1cf0817bcf91d5198bdbc7c8fb91a4114ed1b0a] [INFO   ] executeRequest 'get' completed with ret={'Error': 'Volume 86839502fe764474343b6e2eb1cf0817bcf91d5198bdbc7c8fb91a4114ed1b0a not found (file: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/86839502fe764474343b6e2eb1cf0817bcf91d5198bdbc7c8fb91a4114ed1b0a.vmdk)'}
05/31/17 13:47:58 67748 [MainThread] [INFO   ] Started new thread : 458876675840 with target <function execRequestThread at 0x6ad5621ea0> and args (9, 91477, b'{"cmd":"get","details":{"Name":"wordpress_mariadb"},"version":"2"}')
05/31/17 13:47:58 67748 [Thread-6] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 13:47:58 67748 [Thread-6] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 13:47:58 67748 [Thread-6] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 13:47:58 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'get' completed with ret={'datastore': 'FC-DS35-BLUE-DAT01', 'access': 'read-write', 'diskformat': 'zeroedthick', 'status': 'detached', 'created by VM': 'vdsv03', 'created': 'Wed May 31 11:43:11 2017', 'capacity': {'allocated': '1GB', 'size': '1GB'}, 'attach-as': 'independent_persistent', 'clone-from': 'None', 'fstype': 'ext4'}
05/31/17 13:47:58 67748 [MainThread] [INFO   ] Started new thread : 458876675840 with target <function execRequestThread at 0x6ad5621ea0> and args (10, 91477, b'{"cmd":"attach","details":{"Name":"wordpress_mariadb@FC-DS35-BLUE-DAT01"},"version":"2"}')
05/31/17 13:47:58 67748 [Thread-7] [INFO   ] Checking DB mode for /etc/vmware/vmdkops/auth-db...
05/31/17 13:47:58 67748 [Thread-7] [INFO   ] Config DB does not exist. mode NotConfigured
05/31/17 13:47:58 67748 [Thread-7] [INFO   ] Auth DB /etc/vmware/vmdkops/auth-db is missing, allowing all access
05/31/17 13:47:58 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] *** attachVMDK: /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk to vdsv02 VM uuid = 42190c7b-4561-2e85-d562-0a26d487178e
05/31/17 13:47:58 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Attaching /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk as independent_persistent
05/31/17 13:47:58 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] Disk /vmfs/volumes/FC-DS35-BLUE-DAT01/dockvols/11111111-1111-1111-1111-111111111111/wordpress_mariadb.vmdk successfully attached. controller pci_slot_number=160, disk_slot=2
05/31/17 13:47:58 67748 [vdsv02-FC-DS35-BLUE-DAT01._DEFAULT.wordpress_mariadb] [INFO   ] executeRequest 'attach' completed with ret={'ControllerPciSlotNumber': '160', 'Unit': '2'}_

Any help much appreciated.

Regards

Shaun

**Comment by pdhamdhere** [comment]
@Eireocean We are looking into this. From log snippets, it does seem like failover of maria_db is **successful** and it's re-using `wordpress_mariadb` volume created earlier on Node 3. 

We will reproduce this internally update here.

**Comment by Eireocean** [comment]
Thanks ... yes does appear so but this is what I get : 

Before : 

```
MariaDB [wp]> show tables;
+-----------------------+
| Tables_in_wp          |
+-----------------------+
| wp_commentmeta        |
| wp_comments           |
| wp_links              |
| wp_options            |
| wp_postmeta           |
| wp_posts              |
| wp_term_relationships |
| wp_term_taxonomy      |
| wp_termmeta           |
| wp_terms              |
| wp_usermeta           |
| wp_users              |
+-----------------------+
12 rows in set (0.00 sec)

MariaDB [wp]>
```

After : 

```
MariaDB [wp]> show tables;
Empty set (0.00 sec)

MariaDB [wp]>
```

**Comment by lipingxue** [comment]
@Eireocean We are able to reproduce this issue using the yaml file you provided. After analysis the log and your yaml file, we found the root cause:
This line in your yaml file is incorrect:
volumes:
       - mariadb:/var/lib/sql

It should be changed to:
volumes:
       - mariadb:/var/lib/mysql

With your original yaml file, a local volume will be created and mapped to "/var/lib/mysql". 
After node fail-over,  the db service will be restarted and another local volume will be created on another node. That is why the content in DB is not persistent.

We have verified that all published content remains same after node fail-over after making the change we mentioned above in your yaml file.

Please verify it and let us know if it works. Thanks!

**Comment by Eireocean** [comment]
... well the word dumb comes to mind now. Thanks very much for the help.
