### ISSUE TITLE
[E2E] Refactoring e2e constants to avoid package name conflicts

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1314]
Currently in e2e test suite we have defined a lot of utility functions and constants in different folders. The problem is: these utils and constants are defined in the same package, which will cause naming conflicts in the imports. Even though we can use alias in the imports, it's still annoying and it's causing confusion when referencing the same name constant and functions. For example:

	"github.com/vmware/docker-volume-vsphere/tests/constants/dockercli"
	util "github.com/vmware/docker-volume-vsphere/tests/utils/dockercli"

We need to re-organize the folders & packages to streamline the usage of constants and util functions.

**Comment by shuklanirdesh82** [comment]
> "github.com/vmware/docker-volume-vsphere/tests/constants/dockercli"
how about renaming the package as `admincliconst`?

**Comment by shaominchen** [comment]
Moving refactoring tasks to P2.

**Comment by shaominchen** [comment]
Code improvement - not a mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment]
closing this as wontfix .. this is just an improvement. Please reopen if there is a strong need for doing this.
