### ISSUE TITLE
[E2E] Automate VM listener P1 tests [Part 1/2]

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1318]
- [ ] VM suspend, resume:
```
attach a volume
suspend the VM and resume it again.
This shouldn't change status and volume remains attached
```

- [ ] hostd restart
```
attach a volume
restart hostd
verify vmdkops_admin volume ls > verify volume stays as attached
kill the vm
status of the volume should be detached.
```

- [ ] Kill hostd service
```
attach a volume
kill hostd
verify vmdkops_admin volume ls > verify volume stays as attached
start hostd > verify vmdkops_admin result
kill the vm
status of the volume should be detached.

```

**Comment by govint** [comment]
Kill hostd test seems like something that we want to leave out of the test matrix. Its not a workflow that ever happens at all. If anything hostd is started/stopped/restarted.

**Comment by shuklanirdesh82** [comment]
It is an important scenario to validate this interop w.r.t. hostd service due to vmlistener thread implementation. We should not move out of test matrix as hostd crash/autorecovery happens in prod enviroment and we should be confident about no impact on our vmdkopsd service. I agree it is not P0 hence kept it as P1. We may avoid running such test per check in but can't move out of test matrix.

**Comment by govint** [comment]
PR #1513
