### ISSUE TITLE
[E2E] Automate P1 plugin tests

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1321]
- [ ] Recover and extra mount
   a. Start 2 containers using same volume with restart=always
   b. restart docker and wait for containers to start and reference counts to be initialized.
   c. Start 1 container using same volume
   d. Stop all 3 containers and confirm disk is detached

- [ ] 	 Short & long names
   a. Start container with restart flag and use short name for volume (vol1)
   b. restart docker
   c. start another instance of container with short name for volume (vol1)
   d. start another instance of container with long name for volume (vol1@datastore1)
   e. stop all 3 containers and confirm disk is detached.

- [ ] 	Duplicate volume name
   a. start container with restart flag and short name "vol1" (assuming vol1@ds1)
   b. start container with restart flag with same volume name on another ds: vol1@ds2
   c. restart docker
   d. start container with long name: vol1@ds1
   e. Stop all 3 containers and make sure both vol1@ds1 ad vol1@ds2 are detached.

**Comment by govint** [comment]
@shuklanirdesh82 is this issue for 0.17?  I'm done with the code and will post the PR tomorrow with the unit-tests done.

**Comment by shuklanirdesh82** [comment]
Yeah it is for 0.16, as you have code ready please send out soon and we can try to wrap up our code review as soon as possible.

**Comment by govint** [comment]
PR #1500
