### ISSUE TITLE
Unable to create docker volume for VFAT file system type

### ISSUE THREAD

**Issue by shivanshu21** [vmware/docker-volume-vsphere#1327]
Environment Details: (
#VMs = 2
ESX = 6.0u2
Datastore = vsan
Application = None

Steps to Reproduce:
1. Try creating a volume with file system type VFAT

Expected result: Should succeed

Actual Result:
==========

We see that VFAT is listed as supported.

user@ubuntu14A ~: docker volume create --driver=vsphere --name=MyVolume -o size=10gb -o fstype=ntfs
Error response from daemon: create MyVolume: VolumeDriver.Create: Not found mkfs for ntfs
Supported filesystems found: ext2, ext3, ext4, ext4dev, vfat, xfs

But volume creation fails. The params required are different.
-------------------------------------------------------------

user@ubuntu14A ~: docker volume create --driver=vsphere --name=MyVolume -o size=10mb -o fstype=vfat
Error response from daemon: create MyVolume: VolumeDriver.Create: Failed to create filesystem on /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0: exit status 1. Output = /sbin/mkfs.vfat: unrecognized option: L
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: mkfs.vfat [-v] [-n LABEL] BLOCKDEV [KBYTES]

Make a FAT32 filesystem

        -v      Verbose
        -n LBL  Volume label

All retries failed too:
---------------------

user@ubuntu14A ~: docker volume create --driver=vsphere --name=MyVolume -o size=10mb -o fstype=vfat
Error response from daemon: create MyVolume: VolumeDriver.Create: Failed to create filesystem on /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0: exit status 1. Output = /sbin/mkfs.vfat: unrecognized option: L
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: mkfs.vfat [-v] [-n LABEL] BLOCKDEV [KBYTES]

Make a FAT32 filesystem

        -v      Verbose
        -n LBL  Volume label
user@ubuntu14A ~: 
user@ubuntu14A ~: 
user@ubuntu14A ~: docker volume create --driver=vsphere --name=MyVolume -o size=10mb -o fstype=vfat
Error response from daemon: create MyVolume: VolumeDriver.Create: Failed to create filesystem on /dev/disk/by-path/pci-0000:0b:00.0-scsi-0:0:0:0: exit status 1. Output = /sbin/mkfs.vfat: unrecognized option: L
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: mkfs.vfat [-v] [-n LABEL] BLOCKDEV [KBYTES]

Make a FAT32 filesystem

        -v      Verbose
        -n LBL  Volume label
user@ubuntu14A ~:

**Comment by shivanshu21** [comment]
Not sure if this is relevant too but creating volumes of same name is also not failing with error message so long as you change the FS type.


user@ubuntu14A ~: docker volume create --driver=vsphere --name=vol1 -o size=10mb -o fstype=ext2
vol1
user@ubuntu14A ~: docker volume create --driver=vsphere --name=vol1 -o size=10mb -o fstype=ext3
vol1
user@ubuntu14A ~: docker volume create --driver=vsphere --name=vol1 -o size=10mb -o fstype=ext4
vol1
user@ubuntu14A ~: docker volume inspect vol1
[
    {
        "Driver": "vsphere:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/vol1",
        "Name": "vol1",
        "Options": {
            "fstype": "ext2",
            "size": "10mb"
        },
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "3MB",
                "size": "10MB"
            },
            "clone-from": "None",
            "created": "Thu Jun  1 10:46:21 2017",
            "created by VM": "Ubuntu14_A",
            "datastore": "datastore1",
            "diskformat": "thin",
            "fstype": "ext2",
            "status": "detached"
        }
    }
]
user@ubuntu14A ~: docker volume ls
DRIVER              VOLUME NAME
local               something
vsphere:latest      vol1@datastore1
user@ubuntu14A ~:

**Comment by tusharnt** [comment]
@ashahi1 to just document this issue as one of the known issues.

**Comment by ashahi1** [comment]
Closing through #1616
