### ISSUE TITLE
[E2E] Verify 'docker volume ls' works after migration of vm

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1329]
Detail in #1013

**Comment by govint** [comment]
Setting this to rafiki, needs a config with two ESX hosts with a single vSan DS and we can test the migration with govc.

**Comment by ashahi1** [comment]
All the migration related tests have already been performed and also updated under Interop.md
https://github.com/vmware/docker-volume-vsphere/blob/master/docs/external/Interop.md

**Comment by ashahi1** [comment]
Closing this PR

**Comment by shuklanirdesh82** [comment]
Adding `invalid` keyword. This issue was meant for test automation, as per https://github.com/vmware/docker-volume-vsphere/issues/1329#issuecomment-329917139 vDVS is not supporting such workflow. We shall create a new issue when vDVS start supporting vm migration workflow.

/CC @ashahi1
