### ISSUE TITLE
Automate swarm test - start service with restart_policy

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1334]
[To be discussed]

Start service with restart_policy:
1. In swarm cluster, start service with restart_policy: always using vsphere volume
2. Kill VM 
3. Swarm should restart container in another VM and disk should be detached from original vm
4. verifies the volume is attached to new VM

**Comment by shaominchen** [comment]
The test scenario is not finalized yet and needs further discussion to clarify. Not a mustfix for now.

**Comment by shuklanirdesh82** [comment]
as per offline discussion this is not valid scenario marking this `invalid` and closing now.
