### ISSUE TITLE
Automate Tenancy Test case - Update access privileges for user created tenant

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1342]
- [ ] Update datastore access for volume creation (--allow-create) for the Tenant T1 and create volume from VM1 - P0

- [ ] Update datastore access for --volume-totalsize from 1 GB to 2GB by keeping allow_create to true and Max_volume_size to satisfiable - P0

- [ ] Update datastore access for --volume-maxsize from 500MB to 600MB by keeping all other rights satisfiable - P0

- [ ] Update access rights gradually from non-satisfiable to satisfiable for {volume-maxsize, allow-create, volume-totalsize} - P0

- [ ] Remove access privilege for newly created tenant

Please refer to issue #896 and #899

**Comment by govint** [comment]
Almost all of these are already in tests/e2e/vmgroup_test.go - Please review and most likely the existing tests are sufficient.

**Comment by shuklanirdesh82** [comment]
it is already being taken care of.
