### ISSUE TITLE
[E2E] Automate P1 Tenancy Test case - Change VM's vmgroup

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1343]
- [ ] Tenant is changed while volume is still attached to a vm - vm belongs to default vmgroup
- [ ] Test to verify tenant creation by passing non-existing vm

Please refer to issue #899

**Comment by govint** [comment]
Please see vmgroups_test.go:TestVmGroupVolumeMobility() Its already testing the first condition - vm can't move out of vmgroup with volume attached

**Comment by govint** [comment]
@shuklanirdesh82 can you confirm if this test needs to be written given vmgroup_test.go already implements these tests.

**Comment by ashahi1** [comment]
@govint Are you talking of this test which covers the first scenario ?
https://github.com/vmware/docker-volume-vsphere/blob/master/tests/e2e/vmgroups_test.go#L373

**Comment by govint** [comment]
Yes thats correct. Second one is also doable by enhancing the existing test code.

**Comment by shuklanirdesh82** [comment]
Scenario 1 is covered for user created tenant T1 to user create tenant T2We need to cover for _DEFAULT to userCreated VmGroup T1.

**Comment by ashahi1** [comment]
Merged as part of PR #1564
