### ISSUE TITLE
Some e2e util functions are not generating unique numbers properly

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1344]
The following util functions are buggy:

1. GetVolumeNameWithTimeStamp
2. GetContainerNameWithTimeStamp
3. GetServiceNameWithTimeStamp

The intention of these functions is to generate a unique name, but we are using time.Now().Unix() which generates a number based on the same timestamp in seconds. The generated number will not be unique if we call this function multiple times in a short period or from different goroutines. It won't work even if we change it to time.Now().UnixNano().

We should fix these functions to use random number generator.

**Comment by shuklanirdesh82** [comment]
yeah @govint pointed out today https://github.com/vmware/docker-volume-vsphere/pull/1310#discussion_r119852856

**Comment by ashahi1** [comment]
I know, its a trivial issue and I will take care of it.

**Comment by ashahi1** [comment]
Fixing it in current change #1381
