### ISSUE TITLE
Improve error message when refcounting isn't complete

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1350]
As of now, for docker volume rm, the error message given is "VolumeDriver.Remove: Remove failure - volume is still mounted.  volume=vmlistener_test_volume_1496558624, refcount=1
" when tried before the refcount thread stabilizes.
It is ambiguous and doesn't make it clear if refcount is actually one or we are disallowing delete due to unsuccessful refcount init. We need to give error like "Plugin Initialization in progress" till refcounting is initialized.

//CC @shaominchen @shuklanirdesh82

**Comment by pshahzeb** [comment]
Duplicate of #1348

**Comment by shuklanirdesh82** [comment]
Thanks @pshahzeb for closing. We do have `duplicate` label, please make sure to add in future.
