### ISSUE TITLE
[Test util] Add a common util function to return a map of all volume properties

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1365]
Add a common util function to return a map of all volume properties in which the key is the property name and the value is the property value.

**Comment by ashahi1** [comment]
Have a Map(volumeName,VolPropStruct) where volume name is the key and Struct object is for various properties.struct VolPropStruct {
     capacity
     attached-to-vm
     disk-format
}

**Comment by shaominchen** [comment]
Test code improvement - not a mustfix for Kubecon.

**Comment by shuklanirdesh82** [comment]
closing this as wontfix; we may use different approach while improving test.
