### ISSUE TITLE
Swarm test error in CI

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1372]
Got thsi error during CI run - https://ci.vmware.run/vmware/docker-volume-vsphere/397

2017/06/07 12:44:13 Failed to invoke command [docker volume inspect  --format '{{index .Status.status}}' swarm_test_volume_1496839264]: exit status 1
2017/06/07 12:44:13 Sleep for 2 seconds
2017/06/07 12:44:16 Failed to invoke command [docker volume inspect  --format '{{index .Status.status}}' swarm_test_volume_1496839264]: exit status 1
2017/06/07 12:44:16 Sleep for 2 seconds
2017/06/07 12:44:18 Failed to invoke command [docker volume inspect  --format '{{index .Status.status}}' swarm_test_volume_1496839264]: exit status 1
2017/06/07 12:44:18 Sleep for 2 seconds
2017/06/07 12:44:21 Failed to invoke command [docker volume inspect  --format '{{index .Status.status}}' swarm_test_volume_1496839264]: exit status 1
2017/06/07 12:44:21 Sleep for 2 seconds
2017/06/07 12:44:23 Failed to invoke command [docker volume inspect  --format '{{index .Status.status}}' swarm_test_volume_1496839264]: exit status 1
2017/06/07 12:44:23 Timed out to poll status

----------------------------------------------------------------------
FAIL: swarm_test.go:91: SwarmTestSuite.TestDockerSwarm

swarm_test.go:141:
    c.Assert(status, Equals, true, Commentf("Volume %s is still attached", s.volumeName))
... obtained bool = false
... expected bool = true
... Volume swarm_test_volume_1496839264 is still attached

2017/06/07 12:44:23 Destroying volume [swarm_test_volume_1496839264]

**Comment by shuklanirdesh82** [comment]
I guess @shaominchen is taking care of this one as part of #1368. 

@shaominchen Please confirm.

**Comment by shaominchen** [comment]
Yes, in PR #1368 we are increasing the timeout value from 1 min to 2 mins.
