### ISSUE TITLE
Automate tenancy test

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1376]
Please refer to #957 : Scenario 2.

**Comment by govint** [comment]
@shuklanirdesh82 as this test is using common DB should these tests be written now but verifiable after shared DB issues are addressed?

**Comment by shuklanirdesh82** [comment]
> as this test is using common DB should these tests be written now but verifiable after shared DB issues are addressed? Same for all shared DS tests that use a common DB.

Yeah @govint that's correct this test falls into cross-esx multi tenancy.

> Also, in this particular test why are two ESX hosts able to create the same tenant names "tenant1"? Is that possible in the current level of the code - two ESX hosts able to create tenants with the same name and use those independently.

#957 : Scenario 2 was planned way before cross-esx multi-tenancy introduced. Thanks for pointing this out! By taking account of present code, it is not possible to perform the exact steps mentioned in the "scenario 2" and test should be marked as `invalid`.
