### ISSUE TITLE
Automate VSAN policy test - basic

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1377]
Please refer to #957 Scenario 3.

**Comment by shaominchen** [comment]
@shuklanirdesh82 Could you please confirm if this is duplicate to any existing VSAN policy test?

**Comment by shuklanirdesh82** [comment]
simplified steps:
1. create a valid vsan policy from E1
2. create one volume from vm1 (on E1) with policy created on E1
3. perform attach/detach for the created volume with data manipulation (write and read to confirm volume is writable)
4. remove the volume

we may enhance https://github.com/vmware/docker-volume-vsphere/blob/master/tests/e2e/vsan_test.go (existing test by adding following steps) .. by looking existing automated step only step #3 need to be added in any of the applicable automated test.

/CC @lipingxue
