### ISSUE TITLE
Automate fail-over test for docker host created on vsan

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1378]
please refer to #957 Scenario 4.

**Comment by shuklanirdesh82** [comment]
isn't it duplicate to #1377? If agree close this one by adding label `duplicate`, please explain otherwise.

**Comment by shaominchen** [comment]
@shuklanirdesh82 This is for #957 Scenario 4, while #1377 is for #957 Scenario 3. They are different, right?

**Comment by ashahi1** [comment]
Yes, scenario 3 and scenario 4 mentioned in #957 are different. Nirdesh can correct me If I am wrong.

**Comment by shuklanirdesh82** [comment]
> This is for #957 Scenario 4, while #1377 is for #957 Scenario 3. They are different, right?

after modifying the description of this issue no more confusion. Earlier issue description was pointing to scenario 3.
