### ISSUE TITLE
Automate fail-over test for docker host created on shared vmfs

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1379]
please refer to #957 Scenario 5.

**Comment by shuklanirdesh82** [comment]
@shaominchen There should be some confusion about this issue's title .. please revisit and correct it. It says "Automate VSAN policy test - fail-over for docker host created on shared vmfs" I guess VSAN policy for shared vmfs either one should be correct .. do you mean `docker host created on VSAN`?
