### ISSUE TITLE
Remove failure logs thats cluttering the e2e test logs.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1389]
The below logs make it look like the e2e tests have errors, these need to be removed till we have log levels for the tests:

2017/06/11 18:33:34 Failed to invoke command [docker volume  create --driver=vsphere  --name= 8F2qNfHK5a84jjJkwzDkh9h2fhfUVuS9jZ8uVbhV3vC5AWX39IVUWSP2NcHciWvqZTa2N95RxRTZHWUsaD6HEdz0ThbXfQ6pYSQ3n]: exit status 1

2017/06/11 18:33:35 Failed to invoke command [docker volume  create --driver=vsphere  --name= Volume_volume_4swm71tvdge@invalidDatastore]: exit status 1

2017/06/11 18:33:35 Failed to invoke command [docker volume  create --driver=vsphere  --name= Volume-000000]: exit status 1

**Comment by pshahzeb** [comment]
Agree.
This print is from the ssh util in case where the command fails
```
	out, err := exec.Command("/usr/bin/ssh", append(sshIdentity, "root@"+ip, cmd)...).CombinedOutput()
	if err != nil {
		log.Printf("Failed to invoke command [%s]: %v", cmd, err)
	}
```

But the command actually fails in the the negative test cases :-)).
I think we can silence this print here. As far as I recall, all our tests have Commentf in case when assertion fails which prints the output of the failed command.
What do you think?

**Comment by govint** [comment]
Agree, especially when debugging a CI failure it keeps showing up as failures and misleading.
