### ISSUE TITLE
[E2E] automated e2e tests should fail gracefully when test bed setup is not ideal or some environment vars are not set

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1398]
With the swarm test automation and govc integration, there are bunch of env variables need to be set inorder to execute tests locally. In an absence of ideal testbed or env. vars, tests are failing with out giving proper error message. It creates lot of confusion to the user and ends up spending more time. 

This issue is to streamline the failure and provides meaningful information to user when run into test setup issues.

- remove unnecessary environment variables from contributing.md too. 

/CC @msterin

**Comment by shaominchen** [comment]
Here's my suggestion (copied from #1517 )

1. Verify the required environment variables are properly initialized before running e2e test
2. Clean up the Config DB if it already exists before running each test group
3. Maybe more...

**Comment by shuklanirdesh82** [comment]
@ashahi1  is already having partial fix so bringing back to his plate

**Comment by ashahi1** [comment]
Fixed as part of PR #1530
