### ISSUE TITLE
test target should be in form of test-XXXX

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1403]
rename e2e-test target to keep in sync with other test targets

https://github.com/vmware/docker-volume-vsphere/blob/master/vmdk_plugin/Makefile#L351

need to rename following targets and make them consistent with others.

```
e2e-test
e2e-test-runalways
e2e-test-runonce
```

/CC @msterin

**Comment by shaominchen** [comment]
That's easy- just revert the order as below :)

test-e2e
test-e2e-runalways
test-e2e-runonce

**Comment by shuklanirdesh82** [comment]
> That's easy- just revert the order as below

That's a plan hence kept this as `0.5` point task.

**Comment by ashahi1** [comment]
Closing this since it is fixed now.
