### ISSUE TITLE
Admin CLI should return proper exit code when requested operation fails

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1411]
While running test locally basic_test fails with following error message.

```
2017/06/14 03:16:25 Finding VM name from IP Address [10.20.104.40]
2017/06/14 03:16:26 Finding VM name from IP Address [10.20.104.40]
2017/06/14 03:16:27 Finding Datastores available on ESX
2017/06/14 03:16:28 START: BasicTestSuite.TestBasicVolumeIsolation
2017/06/14 03:16:28 Creating volume [BasicTestSuite.TestBasicVolumeIsolation_volume_16ddfwutxgjte] on VM [10.20.104.40]
2017/06/14 03:16:35 Checking volume [BasicTestSuite.TestBasicVolumeIsolation_volume_16ddfwutxgjte] availability from VM [10.20.104.40]
2017/06/14 03:16:36 Checking volume [BasicTestSuite.TestBasicVolumeIsolation_volume_16ddfwutxgjte] availability from VM [10.20.104.40]
2017/06/14 03:16:37 Destroying volume [BasicTestSuite.TestBasicVolumeIsolation_volume_16ddfwutxgjte]
2017/06/14 03:16:39 END: BasicTestSuite.TestBasicVolumeIsolation
2017/06/14 03:16:39 START: BasicTestSuite.TestVmGroupVolumeIsolation
2017/06/14 03:16:39 Initializing the SingleNode Config DB on esx [10.20.105.97] 
2017/06/14 03:16:41 Creating volume [BasicTestSuite.TestVmGroupVolumeIsolation_volume_uo7w8oxnzncz] on VM [10.20.104.40]
2017/06/14 03:16:42 Checking volume [BasicTestSuite.TestVmGroupVolumeIsolation_volume_uo7w8oxnzncz] availability from VM [10.20.104.40]
2017/06/14 03:16:43 Checking volume [BasicTestSuite.TestVmGroupVolumeIsolation_volume_uo7w8oxnzncz] availability from VM [10.20.104.40]
2017/06/14 03:16:44 Creating a vmgroup [T1] on esx [10.20.105.97]
2017/06/14 03:16:46 Checking volume [BasicTestSuite.TestVmGroupVolumeIsolation_volume_uo7w8oxnzncz] availability from VM [10.20.104.40]

----------------------------------------------------------------------
FAIL: basic_test.go:155: BasicTestSuite.TestVmGroupVolumeIsolation

basic_test.go:175:
    c.Assert(accessible, Equals, false, Commentf("Volume %s is still available on [%s]", s.volName1, s.vm1))
... obtained bool = true
... expected bool = false
... Volume BasicTestSuite.TestVmGroupVolumeIsolation_volume_uo7w8oxnzncz is still available on [10.20.104.40]
```

Test fails to provide correct failure cause.

**Comment by shuklanirdesh82** [comment]
Test failure cause should be improved further to find out root cause easily. I tweaked a code locally and found out that `vmgroup creation failed` but our test is not failing at correct step and failed at the later step.

**Comment by shaominchen** [comment]
@shuklanirdesh82 I'm a little bit confused here: if vmgroup creation failed, why did the assertion (basic_test.go: L172) pass? That means admincli.CreateVMgroup didn't return any error, which seems weird. Can you please provide esx logs?

**Comment by govint** [comment]
Thats the point, admin CLI doesn't return error, checking for error doesn't help. Instead adminCLI should do a $? and get that value, like this:

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create
usage: vmdkops_admin.py vmgroup create [-h] --default-datastore
                                       DEFAULT_DATASTORE
                                       [--vm-list vm1, vm2, ...]
                                       [--description DESCRIPTION] --name NAME

$?
-sh: 2: not found <--------- !0

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create >/dev/null 2>&1;echo $?
2  <-----------

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/issues/1411#issuecomment-308332275

Agree with @govint .... could use `$?` too.

**Comment by shaominchen** [comment]
I don't think this issue is with basic_test itself - the test logic here is right and straightforward. The go sample code also demonstrates exactly the same usage (checking if err is nil): https://golang.org/pkg/os/exec/#Cmd.CombinedOutput

The real issue here is - why does the util ssh.InvokeCommand() not return an error when the command actually fails? This will make it very confusing to write the test cases. Not only this basic test, but all other test cases that rely on admincli command will run into the same issue.

I checked the ssh.go logic - we are using exec.Command.CombinedOutput() to return the command output. This API will runs the command and returns its combined standard output and standard error. I guess one possible fix is to use exec.Command.Output(). But we definitely need more investigation on this part.

@shuklanirdesh82 Can you please take a look since you originally wrote these code?

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/issues/1411#issuecomment-308527967

As discussed during the standup and @govint pointed out too, admin CLI doesn't return the error. InvokeCommand is implemented correctly and no issue while using dockerCLI command. 

IMO, we should improve admin CLI to return `exit status` or we may improve test steps to validate the step performed on admin CLI is actually correct or  not. The reported issue is not critical but good to improve the failure message that helps in triaging.

**Comment by ashahi1** [comment]
Yes, Govindan already provided similar comment - https://github.com/vmware/docker-volume-vsphere/pull/1381#discussion_r121059849

**Comment by msterin** [comment]
Looking in the code the vast majority of functions already return None for success and something else for error. So making admicli to return proper code to shell would be trivial. 
Here is the modified main() code to do that: 
```python
def main():
    log_config.configure()
    kv.init()
    if not vmdk_ops.is_service_available():
       sys.exit('Unable to connect to the host-agent on this host, ensure the ESXi host agent is running before retrying.')
    args = parse_args()
    if not args:
        sys.exit(3)
    if args.func(args) != None:
        sys.exit(2)
```

**Comment by govint** [comment]
#1464 is resolving the issue posted here. Closing.

**Comment by shuklanirdesh82** [comment]
reopening this issue as the PR hasn't merged yet

**Comment by shuklanirdesh82** [comment]
closing this now .. as the PR #1464 is merged. thanks to @msterin!

#1464 is fixing partially and remaining changes are being tracked at #1522.
