### ISSUE TITLE
Misleading CI pass impression

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1416]
For a given PR, the CI pass is indicated is indicated as success even though the CI hasn't been run successfully. 
For e.g.: https://ci.vmware.run/vmware/docker-volume-vsphere/519
If asked for what specifically is the CI log in such cases; its nothing but just something as below
```
$ git reset --hard -q f0d7a3fc0ab47b577fb7035bcd19c2b3c4014e45
```

This an be misleading and the PR indicates that CI run is successful (unless the actual CI run fails).
We should get rid of such entries .

**Comment by shaominchen** [comment]
I'm also confused by this, but this looks like related to git branch setting. @shuklanirdesh82 can comment on this.

**Comment by shuklanirdesh82** [comment]
@pshahzeb Why is this issue on `docker-volume-vsphere`? There is nothing we can do here. 

This happens as some of you are working directly on vmware/docker-volume-vsphere repository. Whenever new commit is pushed CI triggers to add commit information for your branch for the vmware master. 

Working on master is not an ideal way; instead we all should fork the repository. 

I have looked up some top vmware open source project and team is forking and work on one's own fork.

Harbor: https://github.com/vmware/harbor
VIC: https://github.com/vmware/vic
photon: https://github.com/vmware/photon
pyvmomi: https://github.com/vmware/pyvmomi
govmomi: https://github.com/vmware/govmomi

By taking reference of above projects, we should stop working on vmware repo directly and forked the repo that avoids such confusion.

/CC @pdhamdhere @tusharnt

**Comment by pshahzeb** [comment]
We can close if there isn't much we can do.

> Working on master is not an ideal way; instead we all should fork the repository.

Sure. Will try to follow this approach.

**Comment by msterin** [comment]
We can live with it but.... this is really confusing, I agree with @pshahzeb and @shaominchen  here. 
We submit a PR and the CI goes green really soon (which means nothing). It then goes yellow and in some time goes the right color. So for a period of time CI shows green when it did not really pass. 
At minimum we need to add this caveat to Contributing.md (ideally it should not go green until it really passed, but if this is the Drone issue, we should just put a line in Contributing.md and move on). 
My 2 cents

**Comment by shuklanirdesh82** [comment]
> This happens as some of you are working directly on vmware/docker-volume-vsphere repository. Whenever new commit is pushed CI triggers to add commit information for your branch for the vmware master.

> Working on master is not an ideal way; instead we all should fork the repository.

I had a quick chat with @msterin and it would be OK to move to a model where all contributor forked the repo and work on their own repository instead of working on vmware repo directly.
