### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1429]
1. Docker Volume gif under [Demos](https://github.com/vmware/docker-volume-vsphere/wiki/Demos) displays `--driver=vmdk` while it needs to be `--driver=vsphere`.

2. ESXi Admin Monitoring gif under [Demos](https://github.com/vmware/docker-volume-vsphere/wiki/Demos) displays `vmdkops_admin.py ls` while it needs to be `vmdkops_admin.py volume ls`.

3. Contribution Prereq: Docker Hub account creation, login steps aren't elaborated in `README.md`, `CONRTIBUTING.md`, or related links.

**Comment by shaominchen** [comment]
I think this is a P0 for GA - the demo needs to be updated. Temporarily parking with Nirdesh.

**Comment by lipingxue** [comment]
I discussed with Nirdesh @shuklanirdesh82, item 1 and 2 in this issue need to update https://github.com/vmware/docker-volume-vsphere/wiki/Demos.
We think we should not do that and the reasons are:
1. We already have instruction on how to install (http://vmware.github.io/docker-volume-vsphere/documentation/install.html)
2. user guide (admin-cli.md) includes the information on how to manage the whole volume life-cycle using docker volume vsphere 

If we re-record those demos, they may be outdated later if we make any changes. 
So I think we should remove the demo from the wiki page and put a link to the installation instruction and user guide. 

@pdhamdhere @msterin comments?

**Comment by pdhamdhere** [comment]
Agree on demos. Delete them.

We should address 

> 3. Contribution Prereq: Docker Hub account creation, login steps aren't elaborated in README.md, CONRTIBUTING.md, or related links.

**Comment by msterin** [comment]
+1 either delete. or if we love the demos, we can add a small note saying "syntax changes since the demo recording" :-) . P3

**Comment by lipingxue** [comment]
OK. I have delete the demo from the wiki (https://github.com/vmware/docker-volume-vsphere/wiki).
PR #1603 is out to fix the item 3.
