### ISSUE TITLE
Improve test output to have a brief summary report in the end

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1430]
It's a good practice to put Testing Done in the description when sending a PR out for review. However, right now we have to copy/paste excerpts from different areas in the output of a local test run. It will be ideal if we can improve the test output to have a brief summary report in the end.

**Comment by shuklanirdesh82** [comment]
it is being tracked (https://github.com/vmware/docker-volume-vsphere/issues/1255#issuecomment-305564582)
