### ISSUE TITLE
vmgroup create changes names of vmgroup and datastore

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1437]
This is on the ToT code.

1. Create a vmgroup vmg_nfs with a default DS ds_nfs - succeeds

[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --default-datastore ds_nfs --vm-list master-VM0.0 --name vmg_nfs
vmgroup 'vmg_nfs' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.

2. List the vmgroup
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list
------------------------------------  --------  -------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS
a3e06d1b-18ef-4d99-b823-1e8424cec4b8  vmg_nfs                              ds_nfs             master-VM0.0

3. Check the linkage created for the vmgroup
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] pwd
/vmfs/volumes/ds_nfs/dockvols

[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] ls
11111111-1111-1111-1111-111111111111  _DEFAULT                              f8cabf4a-1981-4ac9-b2e0-9885b8756cdc  vmg-nfs   <------------ name changed to "vmg-nfs"

4. The "_" in the vmgroup and datastore names have been changed to "-", as a result volumes don't get created in the default DS and volume were getting created in _DEFAULT (_VM_DS).

[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] ls -l
total 32
drwxr-xr-x    2 root     root          4096 Jun 17 20:20 11111111-1111-1111-1111-111111111111
lrwxrwxrwx    1 root     root            66 Jun 17 20:20 _DEFAULT -> /vmfs/volumes/ds-nfs/dockvols/11111111-1111-1111-1111-111111111111
drwxr-xr-x    2 root     root         20480 Jun 17 20:24 f8cabf4a-1981-4ac9-b2e0-9885b8756cdc
lrwxrwxrwx    1 root     root            66 Jun 17 19:19 vmg-nfs -> /vmfs/volumes/ds-nfs/dockvols/f8cabf4a-1981-4ac9-b2e0-9885b8756cdc

**Comment by govint** [comment]
Another manifestation,

1.  Create a new name for the DS
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes] esxcfg-nas -a -o 10.192.72.248 -s /store ds-nfs
Connecting to NAS volume: ds-nfs
ds-nfs created and connected.

2.  vmgroup create fails
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --default-datastore ds-nfs --vm-list master-VM0.0 --name vmg-nfs
Datastore ds-nfs does not exist

3. DS exists
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes] ls /vmfs/volumes/
58eb13bd-de673bfb-2897-005056a7ffe5     59474fd7-a517261a-8a1b-02001e5a2f6d     c737197a-d00f6680-2b51-8746d0c82ac7     local.0-1                               vsan:52279317df2369d3-c3ab4c72bf899c95
58eb13c4-1b84c5a8-dc5b-005056a7ffe5     59474fd9-cb1b6323-ef30-02001e5a2f6d     c957d392-06803f9c                       local.0-2                               vsanDatastore
59474fd1-55672410-d21e-02001e5a2f6d     59474fdf-78aeb1db-4d95-02001e5a2f6d     ds-nfs                                  sharedVmfs-0
59474fd4-d6871ae4-c86b-02001e5a2f6d     6b05d474-2d6e71a9-b3ee-2fdc1b9ffc6d     local.0-0                               sharedVmfs-1

**Comment by govint** [comment]
Issue 3

1. Create the vmgroup

[root@sc-rdops-vm16-dhcp-232-194:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --default-datastore ds_nfs --vm-list master-VM0.0 --name vmg-nfs
vmgroup 'vmg-nfs' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.
[root@sc-rdops-vm16-dhcp-232-194:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list
------------------------------------  --------  -------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS
ce4d5881-c660-4ec5-b5c9-bf5803911bbb  vmg-nfs                              ds_nfs             master-VM0.0

2. dockvols folder is empty in the datastore
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes] cd ds_nfs/
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c] ls
dockvols
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c] cd dockvols/
[root@sc-rdops-vm16-dhcp-232-194:/vmfs/volumes/c957d392-06803f9c/dockvols] ls -l
total 0

**Comment by lipingxue** [comment]
@govint Do you hit this issue only for NFS datastore?

**Comment by govint** [comment]
I was trying this only with NFS to setup my testbed. I'd suggest doing a repro first (I did try with a a fresh cloned codebase).

**Comment by lipingxue** [comment]
Hi Govindan,
I have tried to reproduce it with NFS, but I cannot reproduce it. The following are my steps:

1. create a NFS datastore
```
[root@sc-rdops-vm17-dhcp-3-236:~] esxcfg-nas -a -o 10.160.161.232 -s /store ds-nfs 
Connecting to NAS volume: ds-nfs
ds-nfs created and connected.

```

2. create a vmgroup, set the "default_datastore" to the NFS datastore
```
root@sc-rdops-vm17-dhcp-3-236:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name=vmg_nfs --default-datastore ds-nfs --vm-list ubuntu-VM0.0
vmgroup 'vmg_nfs' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.
[root@sc-rdops-vm17-dhcp-3-236:~] 
[root@sc-rdops-vm17-dhcp-3-236:~] 
[root@sc-rdops-vm17-dhcp-3-236:~] 
[root@sc-rdops-vm17-dhcp-3-236:~] 
[root@sc-rdops-vm17-dhcp-3-236:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list       
------------------------------------  --------  -------------------------  -----------------  ------------  
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS                           
d4f431c9-1e44-499a-bec1-94f6cef75639  vmg_nfs                              ds-nfs             ubuntu-VM0.0  
```

3. create a volume on this NFS datastore
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create --driver=vsphere --name=vol1@ds-nfs
vol1@ds-nfs
root@sc-rdops-vm02-dhcp-52-237:~# 
root@sc-rdops-vm02-dhcp-52-237:~# 
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      vol1@ds-nfs
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create --driver=vsphere --name=vol2
vol2
root@sc-rdops-vm02-dhcp-52-237:~# 
root@sc-rdops-vm02-dhcp-52-237:~# 
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      vol1@ds-nfs
vsphere:latest      vol2@ds-nfs

```

4. checked symlink,  the symlink is  correct.

```
[root@sc-rdops-vm17-dhcp-3-236:~] cd /vmfs/volumes/ds-nfs/
[root@sc-rdops-vm17-dhcp-3-236:/vmfs/volumes/7536a4cc-7159d437] ls
dockvols
[root@sc-rdops-vm17-dhcp-3-236:/vmfs/volumes/7536a4cc-7159d437] cd dockvols/

[root@sc-rdops-vm17-dhcp-3-236:/vmfs/volumes/7536a4cc-7159d437/dockvols] ls -al
total 16
drwxr-xr-x    3 root     root          4096 Jul  5 17:34 .
drwxr-xr-x    3 root     root          4096 Jul  5 17:03 ..
drwxr-xr-x    2 root     root          4096 Jul  5 17:34 d4f431c9-1e44-499a-bec1-94f6cef75639
lrwxrwxrwx    1 root     root            66 Jul  5 17:34 vmg_nfs -> /vmfs/volumes/ds-nfs/dockvols/d4f431c9-1e44-499a-bec1-94f6cef75639   ---> here the name is "vmg_nfs".

```

Let me know if you think any step is missing in my repro, and let me know if you still can repro. @govint

**Comment by govint** [comment]
Closing this as not reproduced.
