### ISSUE TITLE
With default vmgroup removed detach requests are skipped, volumes remain attached [default vmgroup removal]

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1441]
1. Create volume
```
root@photon-machine [ /usr/local/bin ]# docker volume create -d vsphere n5
n5
```
KV:
```
 cat n5-4b88db79778570b6.vmfd
{"status": "detached", "volOpts": {"diskformat": "thin", "fstype": "ext4"}, "created-by": "worker1-VM1.0", "created": "Tue Jun 20 08:32:19 2017"}                                                    
```
2. Run container
`root@photon-machine [ /usr/local/bin ]# docker run --rm -it -v n5:/vol ubuntu sh`

3. On ESX delete the _DEFAULT vmgroup (to which the VM is default assigned)
```
/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup rm --name _DEFAULT

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid  Name  Description  Default_datastore  VM_list
_----  ----  -----------  -----------------  -------_
```
4. Exit container
```
root@photon-machine [ /usr/local/bin ]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@photon-machine [ /usr/local/bin ]#
```
5. Volume in ESX is still attached. KV and VM config:
```
cat n5-4b88db79778570b6.vmfd
{"attachedVMName": "worker1-VM1.0", "status": "attached", "volOpts": {"diskformat": "thin", "fstype": "ext4"}, "attachedVMDevice": {"ControllerPciSlotNumber": "160", "Unit": "2"}, "created-by": "worker1-VM1.0", "attachedVMUuid": "564d3551-fcc6-60ae-4142-2a988fe9e1e0", "created": "Tue Jun 20 08:32:19 2017"} 
```
List vmdks attached to VM:
```
grep vmdk /vmfs/volumes/sharedVmfs-0/worker1-VM1.0/*vmx

scsi0:0.fileName = "worker1-VM1.0.vmdk"
scsi0:1.fileName = "/vmfs/volumes/59474fd4-d6871ae4-c86b-02001e5a2f6d/vmdk/c.vmdk"
scsi1:0.fileName = "/vmfs/volumes/59474fd1-55672410-d21e-02001e5a2f6d/dockvols/11111111-1111-1111-1111-111111111111/n1.vmdk"
scsi1:1.fileName = "/vmfs/volumes/59474fd1-55672410-d21e-02001e5a2f6d/dockvols/11111111-1111-1111-1111-111111111111/n3.vmdk"
scsi1:2.fileName = "/vmfs/volumes/59474fd1-55672410-d21e-02001e5a2f6d/dockvols/11111111-1111-1111-1111-111111111111/n5.vmdk"
```
It may be that default vmgroup removal is rare, but given that it can be removed  the removal can cause the service to leave volumes attached and unusable.

Question is also why allow the default vmgroup to be removed at all.

Plugin logs:
```
2017-06-20 08:32:20.78414963 +0000 UTC [INFO] Attaching volume and creating filesystem name=n5 fstype=ext4
2017-06-20 08:32:21.606910617 +0000 UTC [INFO] Scan complete event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0": 0x100 == IN_CREATE device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0"
2017-06-20 08:32:21.607103587 +0000 UTC [WARNING] Done dev attachname=n5
2017-06-20 08:32:22.369700399 +0000 UTC [INFO] Volume and filesystem created fstype=ext4 name=n5
2017-06-20 08:32:53.582996816 +0000 UTC [INFO] Mounting volume name=n5
2017-06-20 08:32:54.278721107 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0": 0x100 == IN_CREATE
2017-06-20 08:33:44.312758831 +0000 UTC [INFO] Unmounting Volume name=n5
2017-06-20 08:33:44.388951216 +0000 UTC [ERROR] Failed to unmount name="n5@sharedVmfs-0" error="VM worker1-VM1.0 does not belong to any vmgroup" <------------
```
The ESX service must allow a volume to be detached irrespective of whether the VM is in a vmgroup or not.

**Comment by govint** [comment]
While on another VM:

root@photon-machine [ ~ ]# docker run --rm -it -v n5:/vol ubuntu sh
docker: Error response from daemon: error while mounting volume '/mnt/vmdk/n5': VolumeDriver.Mount: Disk /vmfs/volumes/sharedVmfs-0/dockvols/_DEFAULT/n5.vmdk already attached to VM=worker1-VM1.0.

**Comment by pdhamdhere** [comment]
@pshahzeb Do we maintain list of VMs in DB for _DEFAULT?

**Comment by pshahzeb** [comment]
@pdhamdhere Nope.

**Comment by shaominchen** [comment]
This is related to issue #1397, so let's discuss and address both in 0.17 release.

**Comment by govint** [comment]
@shaominchen, @tusharnt - can we finalize on this issue, I don't believe its needed for GA. Its a design issue and we may just document the behavior.

**Comment by govint** [comment]
Sorry for the flip-flop on the release was clicking and each one added a release. Anyway, pulled this back into Timon. This is one thats a corner case but worth fixing.

**Comment by msterin** [comment]
Actually the `detach will fail for any vm which is removed from a group, or a group is deleted, when the VM had a volume attached`. This is because the detach code heavily relies on finding he *correct* vmgroup, and if vmgroup is not found it just fails in "can't locate the vmgroup" and returns error, but if a wrong group if found then it will proceed all the way to findDeviceByPath and most likely fail there since the path will include a wrong vmgrpoup.

So the fix I am building will address "no such VMGROUP" but will not address "wrong vmgroup is found so the vmdk_path is wrong so the findDeviceByPath fails. There is no  workaround for this one, as we do  not know if vmgroups is right (or wrong). We *can* block vm relocation to a different group if it has volumes attached. @govint - comments ?

**Comment by pshahzeb** [comment]
>We can block vm relocation to a different group if it has volumes attached. 

As of today, if VM has volumes attached, it cannot be added to a vmgroup or removed from a vmgroup. We have a check for it.
