### ISSUE TITLE
Invalid characters in name error during volume creation.

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1448]
Hit intermittently 
https://ci.vmware.run/vmware/docker-volume-vsphere/648

```
2017/06/20 18:47:56 START: VolumeAccessTestSuite.TestAccessUpdate
2017/06/20 18:47:56 Creating volume [vol_access_volume_l33x03nwf9uh@datastore1] on VM [192.168.31.81]
2017/06/20 18:48:04 Writing message_by_host1 to file test.txt on volume [vol_access_volume_l33x03nwf9uh@datastore1] from VM[192.168.31.81]
2017/06/20 18:48:09 Reading from file test.txt on volume [vol_access_volume_l33x03nwf9uh@datastore1] from VM[192.168.31.85]
2017/06/20 18:48:10 Destroying volume [vol_access_volume_l33x03nwf9uh@datastore1]

----------------------------------------------------------------------
FAIL: volume_access_test.go:76: VolumeAccessTestSuite.TestAccessUpdate

volume_access_test.go:91:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4201263e0), Stderr:[]uint8(nil)} ("exit status 125")
... docker: Error response from daemon: create vol_access_volume_l33x03nwf9uh@datastore1: "vol_access_volume_l33x03nwf9uh@datastore1" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

2017/06/20 18:48:11 START: VolumeAccessTestSuite.TestAccessUpdate_R_RW
```

Initial impression : Looks like volume creation was redirected to local driver instead of vsphere.

**Comment by shuklanirdesh82** [comment]
This is related to #1401 .... it has introduced the regression. E2E test (basic_test) doesn't check whether `config rm --local --confirm` removes the DB or not and left out vmgroup created by testcase in the system hence the volume_access_test is running into the issue.

I will raise a separate PR to add more verification steps for basic_test to help us finding root cause easily.

/CC @msterin @shaominchen

**Comment by msterin** [comment]
So why I am getting it on every CI run on https://github.com/vmware/docker-volume-vsphere/pull/1401 ?

**Comment by shuklanirdesh82** [comment]
can you please refer https://github.com/vmware/docker-volume-vsphere/pull/1401#issuecomment-310015744? I tried my best to provide detailed analysis.

**Comment by msterin** [comment]
ah, crossed in the mail :-). Thanks !
