### ISSUE TITLE
uneeded 'VM has already been deleted or has not been completely '  traceback in the log

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#1457]
Each test run generates an error below in the log. This is totally normal situation (VM was powered down and then deleted right away) and we should not log it as an error. 
In fact, it feel like a debug message, or at worst Info with explanation ("Most likely a VM was powered down and then deleted right away"

//CC @pshahzeb 

```
06/21/17 22:10:54 216439 [VMChangeListener] [ERROR  ] VMChangeListener: error (vmodl.fault.ManagedObjectNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "The object 'vim.VirtualMachine:118' has already been deleted or has not been completely created",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   obj = 'vim.VirtualMachine:118'
}
06/21/17 2
```

**Comment by msterin** [comment]
Can you please get it fixed ? It block any reasonable analysis of error logs for test-esx makefile target, as the whole log is polluted with these meaningless messages.

**Comment by pshahzeb** [comment]
Sure. Sending out a PR.

**Comment by msterin** [comment]
Thanks !
