### ISSUE TITLE
Deployment of plugin (deploy-vm failed) error on CI

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1476]
The error is about Failed to stop docker-volume-vsphere.service: Unit docker-volume-vsphere.service not loaded.

From build https://ci.vmware.run/vmware/docker-volume-vsphere/708 on CI
```
Error response from daemon: plugin "vsphere:latest" not found


=> cleanvm: Cleaning up on root@192.168.31.83 : deb Fri Jun 23 20:58:11 UTC 2017


dpkg-query: no packages found matching docker-volume-vsphere
Error response from daemon: plugin "vsphere:latest" not found


=> cleanvm: Cleaning up on root@192.168.31.85 : deb Fri Jun 23 20:58:13 UTC 2017


Failed to stop docker-volume-vsphere.service: Unit docker-volume-vsphere.service not loaded.
3390
(Reading database ... 285933 files and directories currently installed.)
Removing docker-volume-vsphere (0.10.e7acd33) ...
Purging configuration files for docker-volume-vsphere (0.10.e7acd33) ...
  File: '/proc/1/exe' -> '/lib/systemd/systemd'
dpkg: warning: while removing docker-volume-vsphere, directory '/usr/local' not empty so not removed
Error response from daemon: plugin "vsphere:latest" not found
3390


=> cleanupVMPost: Service still running on root@192.168.31.85 Fri Jun 23 20:58:32 UTC 2017


make[1]: *** [clean-vm] Error 4
make: *** [deploy-vm] Error 2
```

**Comment by tusharnt** [comment]
@venilnoronha is currently blocked on this. Any CI blocker should be fixed ASAP. 
@govint Can you please prioritize this?

**Comment by govint** [comment]
@pshahzeb can you post the CI which shows the messages. The CI posted has passed and no error. Those cleanup messages are harmless. Whats the issue here?

Unless the daemon is started manually the "cleanupVMPost: Service still running on" is never returned or the daemon is hung.

In any case why is this a blocker for the windows plugin, this is on Linux. @tusharnt, @venilnoronha

**Comment by venilnoronha** [comment]
@govint we lost the CI logs as I had restarted the job. This is a blocker for windows as we'll be refactoring some linux modules, and we want to make sure that it does not introduce regression.

**Comment by govint** [comment]
The cleanup is attempting to remove the docker plugin binary and package which is not needed with the docker plugin based deployment. But thats harmless.

**Comment by govint** [comment]
Still what's the issue caused by these messages and why is that a blocker for Windows. These messages can always come in CI run

**Comment by pshahzeb** [comment]
@govint 

Filed the issue since this error caused the CI itself to fail. We don't have logs now due to CI restart.
I don't think venil is blocked anymore. We can close this issue for now and reopen if this error is seen again. 
> The cleanup is attempting to remove the docker plugin binary and package which is not needed with the docker plugin based deployment. But thats harmless.

Not sure how do we handle this if it occurs again. Though I haven't seen it before.

**Comment by govint** [comment]
But the CI shows these messages and still continues to install the plugin and the CI progressed as expected. Did the failed CI stop after these messages? May be a different issue than these messages.

**Comment by pshahzeb** [comment]
Yes it failed. Closing it for now. Let's reopen when we see this error again and preserve the log to rootcause.
