### ISSUE TITLE
Unit test - test_vmdkops_on_default_tenant_vm test fails 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1477]
I am running into an issue where test_vmdkops_on_default_tenant_vm test fails as total volumes listed by ```admincli volume ls``` is not as expected. Test expects the output from admin cli volume ls to be two but assert fails as there are total of three volumes.  Volume named ```stale_volume``` is the third one.

https://github.com/vmware/docker-volume-vsphere/blob/master/esx_service/vmdk_ops_test.py#L813

- If I try to run test-e2e individually, then all e2e tests pass and there are no left-over volumes. But when I run test-e2e and then start test-esx, ```test_vmdkops_on_default_tenant_vm test``` fails and at the end of run, there is one left-over volume.

- One of my test deletes default vmgroup and then recreates it. 

- I am able to hit this issue locally as well. Logs are attached at the end.

- I spent lot of time debugging with Shahzeb and Nirdesh but we couldn't figure out why stale_volume is not getting cleaned-up. We are seeing this issue only with my code changes but the impact we are seeing is in some different unit test.

Logs have been attached at the end
CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/717

Error:
```
======================================================================
FAIL: test_vmdkops_on_default_tenant_vm (__main__.VmdkTenantTestCase)
Test vmdk life cycle on a VM which belongs to DEFAULT tenant
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest23218/vmdk_ops_test.py", line 814, in test_vmdkops_on_default_tenant_vm
    self.assertEqual(len(result), 2)
AssertionError: 3 != 2

----------------------------------------------------------------------
```

Admin cli volume ls:

```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume        Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By     Created Date
------------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  -------------  ------------------------
stale_volume  sharedVmfs-0  _DEFAULT  100MB     0     N/A         N/A     thin         detached     read-write  independent_persistent  test-vm_33467  Sat Jun 24 03:50:54 2017

[root@sc-rdops-vm10-dhcp-39-239:~]
```

Logs:
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/1099429/docker-volume-vsphere.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1099428/vmdk_ops.txt)

**Comment by shuklanirdesh82** [comment]
fixed via #1381
