### ISSUE TITLE
User cannot delete a vmgroup if vm from that vmgroup gets deleted

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1484]
Issue: User cannot delete a vmgroup if vm from that vmgroup gets deleted

Test steps:
1. Create a vmgroup and associate vm to it.
2. Delete the vm that was added to the vmgroup.
3. Try to remove vm from vmgroup - message ```Cannot find vm```
4. Try to delete vmgroup - message ```Cannot delete non-empty vmgroup vmgroup1. Remove VMs from the vmgroup before deleting it.```

There should be some way for user to delete a vmgroup if it's vm no longer exists. In current product behavior, there is no way for user to delete it's vmgroup if VMs from that vm group get deleted.

---------------

Steps and their output are as follows:

1. Create a vmgroup and associate VM to it.
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name=vmgroup1 --default-datastore=_VM_DS --vm-list=testVM-33
vmgroup 'vmgroup1' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.

[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                  Default_datastore  VM_list
------------------------------------  --------  ---------------------------  -----------------  ---------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is the default vmgroup  _VM_DS
baf91569-a092-44b3-b6de-18677e4091b4  vmgroup1                               _VM_DS             testVM-33

```
2. Deleted the vm that was added to the vmgroup.
3. Tried removing vm from vmgroup. As expected, operation fail as vm no longer exists.
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup vm rm --name=vmgroup1 --vm-list=testVM-33
Cannot find vm testVM-33
```
4. Tried removing vmgroup - could not remove vmgroup as it has vm in it even though that vm is deleted.
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup rm --name=vmgroup1
Cannot delete non-empty vmgroup vmgroup1. Remove VMs from the vmgroup before deleting it.
[root@sc-rdops-vm10-dhcp-39-239:~]
```

**Comment by govint** [comment]
As a fix I'm proposing that if a VM can't be found locally then the VM will still be removed from the vmgroup. If the vm was deleted then this is the way to handle it. If the VM was moved then as far as a local config is concerned its still the way to handle the scenario. Cross ESX config isn't supported today and hence won't be considered.

**Comment by govint** [comment]
Fixing via #1887
