### ISSUE TITLE
Symlink is not created after recreating default vmgroup

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1485]
- Symlink is not created after recreating default vmgroup

Steps:
1. Verify only default vmgroup is present
2. Delete default vmgroup
3. Recreate default vmgroup
4. dockvols folder only have DEFAULT_TENANT_UUID folder - ```11111111-1111-1111-1111-111111111111 ```

----------------

Steps and their output are as follows:

1. Verified setup only had default vmgroup
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name      Description                Default_datastore  VM_list
------------------------------------  --------  -------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vmgroup  _VM_DS

```

2. Deleted default vmgroup
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup rm --name=_DEFAULT
vmgroup rm succeeded
```

3. Recreated default vmgroup
```
[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup create --name=_DEFAULT --default-datastore=_VM_DS
vmgroup '_DEFAULT' is created. Do not forget to run 'vmgroup vm add' to add vm to vmgroup.

[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access set --name=_DEFAULT --datastore=_ALL_DS --allow-create True
vmgroup access set succeeded

[root@sc-rdops-vm10-dhcp-39-239:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup access ls --name=_DEFAULT
Datastore  Allow_create  Max_volume_size  Total_size
---------  ------------  ---------------  ----------
_ALL_DS    True          Unset            Unset
_VM_DS     True          Unset            Unset

```
5. No Symlink is created for default vmgroup in the dockvols folder even though we have recreated default vmgroup.
```
[root@sc-rdops-vm10-dhcp-39-239:/vmfs/volumes/594da13e-db47ffc7-ca19-0200141ee875/dockvols] ls
11111111-1111-1111-1111-111111111111    <<<<<<<< no _DEFAULT folder 
[root@sc-rdops-vm10-dhcp-39-239:/vmfs/volumes/594da13e-db47ffc7-ca19-0200141ee875/dockvols]
```

**Comment by shaominchen** [comment]
Correctness issue, since we allow user to delete default vmgroup.

**Comment by govint** [comment]
The symlink isn't needed and nor does the user see the symlink at all, in the code, the tenant name is obtained or deciphered as the default and then the ID is got from the DB and that ID is whats used to get the path to the disks. I've seen this earlier and the code is safe in that volumes can be created and both new and old volumes can be accessed. 

I'd suggest close as won't fix, its not a mustfix issue and not seen by user.

@ashahi1 can you confirm that the user sees no issues in using the volumes after recreating the default vmgroup. I've don't it earlier and it works ok, but you can confirm as well.

**Comment by govint** [comment]
P1 as no functionality is broken.

**Comment by govint** [comment]
Turning off mustfix as no functionality is broken and while its a correctness issue, its also a question why the symlinks are needed at all. Admin access to the tenant dirs. on a datastore does happen all the time and admin can get the ID (folder name) of the tenant via admin CLI and use that.

**Comment by govint** [comment]
Closing per earlier comment.
