### ISSUE TITLE
After docker restart, restarted containers show plugin volume as in-use but volume is detached

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1499]
Found this when trying the restart tests where,
1. A container is started in a docker host with the same volume.
1. Docker is restarted and so is the volume plugin
1. Container are also restarted and showing as using the volume (via docker inspect <container ID>
1. Volume itself is detached.
---
docker run --restart always --volume-driver vsphere -v restart_test_volume_1086450@sharedVmfs-0:/vol ubuntu tail -f /dev/null

docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS          PORTS   NAMES
ceb40a651252        ubuntu              "tail -f /dev/null"   16 seconds ago      Up 5 seconds      sleepy_sammet

docker volume inspect restart_test_volume_1086450\@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/restart_test_volume_1086450@sharedVmfs-0",
        "Name": "restart_test_volume_1086450@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "worker1-VM1.0",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "2"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Wed Jun 28 09:41:19 2017",
            "created by VM": "worker1-VM1.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
                              "status": "attached" <---------------   volume in use
        }
    }
]

systemctl restart docker

root@photon-machine [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED              STATUS              PORTS               NAMES
ceb40a651252        ubuntu              "tail -f /dev/null"   About a minute ago   Up 8 seconds  

docker volume inspect restart_test_volume_1086450\@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/restart_test_volume_1086450@sharedVmfs-0",
        "Name": "restart_test_volume_1086450@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Wed Jun 28 09:41:19 2017",
            "created by VM": "worker1-VM1.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
                          "status": "detached" <--------------- volume is detached 
        }
    }
]

docker inspect ceb40a651252
[
    {
        "Id": "ceb40a651252524459d86f4eb9f80961cde4a93868af297cb201010781c44a5f",
        "Created": "2017-06-28T09:44:02.998003405Z",
        "Path": "tail",
        "Args": [
            "-f",
            "/dev/null"
        ],

        "Mounts": [
            {
                "Type": "volume",
                "Name": "restart_test_volume_1086450@sharedVmfs-0",
                "Source": "/vol/docker/plugins/64eb6a41c3edcaa29d9eda4f7bcb11e9e76ae43aaa5a92900cad9ad0e6db984f/rootfs/mnt/vmdk/restart_test_volume_1086450@sharedVmfs-0", <------------ volume is in use AFADIC
                "Destination": "/vol",
                "Driver": "vsphere:latest",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

**Comment by pshahzeb** [comment]
@govint  By any chance do you have logs? I tried manually to mimic the exact steps you have pointed out in description.

But at the end I see the volume inspect saying it is attached.

```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create -d vsphere --name restart_vol
restart_vol
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      restart_vol@sharedVmfs-0
```

```
root@sc-rdops-vm02-dhcp-52-237:~# docker run --restart always --volume-driver vsphere -v restart_vol@sharedVmfs-0:/vol busybox tail -f /dev/null
```

From another terminal
```
root@sc-rdops-vm02-dhcp-52-237:~# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
661dee276b8f        busybox             "tail -f /dev/null"   55 seconds ago      Up 54 seconds                           admiring_cori
```

```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      restart_vol@sharedVmfs-0
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect restart_vol@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/restart_vol@sharedVmfs-0",
        "Name": "restart_vol@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "ubuntu-VM0.0",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Wed Jun 28 16:38:21 2017",
            "created by VM": "ubuntu-VM0.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        }
    }
]
```

```
root@sc-rdops-vm02-dhcp-52-237:~# service docker restart
docker stop/waiting
docker start/running, process 10471
```

```
root@sc-rdops-vm02-dhcp-52-237:~# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
661dee276b8f        busybox             "tail -f /dev/null"   2 minutes ago       Up 14 seconds                           admiring_cori
```

```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect restart_vol@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/restart_vol@sharedVmfs-0",
        "Name": "restart_vol@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "ubuntu-VM0.0",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Wed Jun 28 16:38:21 2017",
            "created by VM": "ubuntu-VM0.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        }
    }
]
```

**Comment by pshahzeb** [comment]
To add to this, for every docker volume inspect we do a volume get, which fetches volume meta from vmdkops service on ESX. Hence will also need to take a look at vmdkops log from ESX side.

**Comment by govint** [comment]
I did this on the same docker host. I can try a repro and post logs.

**Comment by pshahzeb** [comment]
@govint For test TestRecoverMountsAfterRestart in PR #1500, I have a comment on the failed assert.
I wasn't able to reproduce.
But I enabled just test TestRecoverMountsAfterRestart and corrected the assert as per the comment and looks like this test passed.

**Comment by govint** [comment]
Repro again,
root@photon-machine [ ~ ]# docker inspect rvol0
[
    {
        "Driver": "vsphere:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/rvol0",
        "Name": "rvol0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "master-VM0.0",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Fri Jun 30 04:40:50 2017",
            "created by VM": "master-VM0.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        }
    }
]
root@photon-machine [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
7b269b63a86e        ubuntu              "tail -f /dev/null"   13 seconds ago      Up 11 seconds                           kind_roentgen
root@photon-machine [ ~ ]# systemctl restart docker
root@photon-machine [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
7b269b63a86e        ubuntu              "tail -f /dev/null"   53 seconds ago      Up 13 seconds                           kind_roentgen
root@photon-machine [ ~ ]# docker inspect rvol0
[
    {
        "Driver": "vsphere:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/rvol0",
        "Name": "rvol0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Fri Jun 30 04:40:50 2017",
            "created by VM": "master-VM0.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]

        "Mounts": [
            {
                "Type": "volume",
                "Name": "rvol0",
                "Source": "/vol/docker/plugins/c028788ff0a9e8e6b9ef55c5533ed14a1d98b22be80ee6ab2199cfd82bd3cbe8/rootfs/mnt/vmdk/rvol0@sharedVmfs-0",
                "Destination": "/vol",
                "Driver": "vsphere:latest",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

2017-06-30 05:12:49.571178871 +0000 UTC [INFO] Mounting volume name=rvol0
2017-06-30 05:12:50.211706152 +0000 UTC [INFO] Scan complete event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0"
2017-06-30 05:13:17.650387974 +0000 UTC [INFO] Unmounting Volume name=rvol0

_Restarted by docker restart_
2017-06-30 05:13:18.41902903 +0000 UTC [WARNING] Received signal signal=terminated
2017-06-30 05:13:21.681999577 +0000 UTC [INFO] No config file found. Using defaults.
2017-06-30 05:13:21.685313868 +0000 UTC [WARNING] Failed to load config file /etc/docker-volume-vsphere.conf: open /etc/docker-volume-vsphere.conf: no such file or directory
2017-06-30 05:13:21.685331881 +0000 UTC [INFO] Starting plugin driver=vsphere log_level=info config="/etc/docker-volume-vsphere.conf"
2017-06-30 05:13:21.685350761 +0000 UTC [INFO] Plugin options - port=1019
2017-06-30 05:13:21.686168009 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2017-06-30 05:13:23.686530963 +0000 UTC [INFO] Can't connect to unix:///var/run/docker.sock due to (An error occurred trying to connect: context deadline exceeded), skipping discovery
2017-06-30 05:13:23.686578624 +0000 UTC [INFO] Refcounting failed: (An error occurred trying to connect: context deadline exceeded).
2017-06-30 05:13:23.68659359 +0000 UTC [INFO] Docker VMDK plugin started version="vSphere Volume Driver v0.4" port=1019 mock_esx=false
2017-06-30 05:13:23.688472749 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock"
2017-06-30 05:13:23.690969817 +0000 UTC [INFO] Scheduling again after 2 seconds
2017-06-30 05:13:25.691247484 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock

_Container is restarted by docker and re-mounting the volume_
2017-06-30 05:13:26.990279566 +0000 UTC [INFO] Mounting volume name=rvol0
2017-06-30 05:13:27.670195681 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE
2017-06-30 05:13:27.691465519 +0000 UTC [INFO] Can't connect to unix:///var/run/docker.sock due to (An error occurred trying to connect: context deadline exceeded), skipping discovery
2017-06-30 05:13:27.691522168 +0000 UTC [INFO] Refcounting failed: (An error occurred trying to connect: context deadline exceeded). Attempts left: 20
2017-06-30 05:13:27.691530759 +0000 UTC [INFO] Scheduling again after 4 seconds
2017-06-30 05:13:31.692163945 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock

_Refcounter found the one container_
2017-06-30 05:13:31.718334778 +0000 UTC [INFO] Found 1 running or paused containers

_Refcounter doesn't get a refcount for the volume - its not a VMDK volume? Unmounts the volume_
2017-06-30 05:13:31.724049229 +0000 UTC [INFO] Initiating recovery unmount. name="rvol0@sharedVmfs-0" refcnt=0 mounted=true dev="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0"

2017-06-30 05:13:32.474790482 +0000 UTC [INFO] Discovered 1 volumes in use.

_Ref count is zero_
2017-06-30 05:13:32.474835895 +0000 UTC [INFO] Volume name=rvol0@sharedVmfs-0 count=0 mounted=true device='/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0'
2017-06-30 05:13:32.474843722 +0000 UTC [INFO] Refcounting successfully completed

**Comment by govint** [comment]
root@photon-machine [ ~ ]# docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
c028788ff0a9        vsphere:latest      VMWare vSphere Docker Volume plugin   true

**Comment by govint** [comment]
OK, found the issue, docker by default uses the run time root (where all meta-data and images are placed) at /var/lib/docker.

On my VM i have no space on the root FS and hence made a new disk to place the docker meta-data. Docker allows specifying the runtime as _-g, --graph string                          Root of the Docker runtime (default "/var/lib/docker")_

In my case dockerd is run with -g /vol/docker as below,
dockerd -H unix:///var/run/docker.sock -g /vol/docker --containerd /run/containerd.sock

The bug is in refcnt.go:isVMDKMount() where its expecting that any path with _/var/lib/docker_ should he a VMDK mount. Which is wrong, the code should just check if the driver is _vsphere_ and accept that as a VMDK volume.

        "Mounts": [
            {
                "Type": "volume",
                "Name": "rvol0",
                "Source": "/vol/docker/plugins/c028788ff0a9e8e6b9ef55c5533ed14a1d98b22be80ee6ab2199cfd82bd3cbe8/rootfs/
^^^^^^^^^^^^^^
mnt/vmdk/rvol0@sharedVmfs-0",
                "Destination": "/vol",
                "Driver": "vsphere:latest", <--------- should check this instead.
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

**Comment by govint** [comment]
Making it a P1 as users may not frequently be using a different location for the docker runtime, but its something to be fixed.

**Comment by govint** [comment]
Actually, this is a good use case for vSphere where the images can be located on a single disk thats attached to multiple docker hosts. It may be used as a multi-writer VMDK and allow docker hosts to share the images that docker is pulling on those VMs. Allowing much less storage to be used across a set of docker hosts as well.

**Comment by govint** [comment]
Closing this as presently Docker doesn't allow a plugin to uniquely identify a volume as belonging to it. Using the driver name to identify a volume is going to pick the alias used to install the plugin which can be anything that the user set. And surely not uniquely identifying the volume as a vsphere managed volume.
