### ISSUE TITLE
[E2E] Volume data is missing after failover across swarm nodes

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1505]
One verification step in existing TestFailoverAcrosssSwarmNods has been commented out because it always fails during auto run. However, the same verification passes during manual run. Need to investigate the issue, figure out the root cause, and re-enable this verification in the test.

**Comment by shaominchen** [comment]
I've figured out the root cause. It has been very confusing that the same test steps always pass manually, but fail in automatic run. The truth is: the govc poweroff command is doing a real abrupt power off on the given VM, but the power off button triggered from NGC UI is actually doing a guest shutdown (by default). So, when we run the test steps manually (by clicking power off from UI), the VM is always shut down gracefully without data corruption. But when we run the test steps automatically, the VM is powered off abruptly, and causing data corruption. Please refer to this document for more information about VM shut down and power off: https://www.vmware.com/support/ws5/doc/ws_running_poweroff_vs_shutdown.html.

When the volume is mounted to a container and some data are written into the volume, the data may not be flushed into disk immediately. During automatic test run, the VM is powered off right after the data being written to the volume. That's why the data corruption happens.

The fix is straightforward: we should shut down (instead of powering off) the VM in this test. Abrupt power-off should not be used in most cases unless there's no data to be protected.

**Comment by shaominchen** [comment]
This is confirmed not a product issue, so moving back to P1. The fix is ready, but being blocked on the failure on one of CI testbeds.

**Comment by ashahi1** [comment]
While trying to debug this issues as to why this test only fails on CI, we managed to found bug #1621.
After Govindan fixed that bug in PR #1626, last two runs on CI are green and one more is going on.
If current also finishes successfully, we can merge this change.

**Comment by ashahi1** [comment]
Last three runs are green on CI. Closing this issue.
