### ISSUE TITLE
Improve the robustness of e2e test infrastructure

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1517]
Filing this issue to track some efforts for improving the robustness of e2e test infrastructure:

1. Verify the required environment variables are properly initialized before running e2e test
2. Clean up the Config DB if it already exists before running each test group
3. Maybe more...

The goal is to make sure each test should fail gracefully to make troubleshooting easier.

Please share your comments/suggestions/concerns here.

**Comment by shuklanirdesh82** [comment]
this seems duplicate to #1398 ... Let's track improvement there.
