### ISSUE TITLE
Test should not wait unnecessary  while verifying DetachedStatus

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1528]
current util is waiting for 2 seconds then invokes `adminCli volume ls` to check for "attached/detached" status. It is scary and might be hiding some race condition if there is any. we should get rid of blind wait time for each and every tests. Only special test step should use the poller when required. 

This issue to adjust the util by calling *VerifyDetachedStatus* with out wait time i.e. immediately after performing an operation.

https://github.com/vmware/docker-volume-vsphere/blob/0caae1cd2a0f5b53b3b5a1c5c3a972a53757e4a5/tests/utils/verification/volumeproperties.go#L146

interesting code snip
```
// VerifyDetachedStatus - check if the status gets detached within the timeout
func VerifyDetachedStatus(name, hostName, esxName string) bool {
	log.Printf("Confirming detached status for volume [%s]\n", name)

	//TODO: Need to implement generic polling logic for better reuse
	const maxAttempt = 60
	for attempt := 0; attempt < maxAttempt; attempt++ {
		misc.SleepForSec(2)
		status := getVolumeStatusHost(name, hostName)
		if status != properties.DetachedStatus {
			continue
		}
```

We should add such poller with wait time whenever is required with selective test. 

/CC @msterin

**Comment by govint** [comment]
Get the status from doing a Get() call to the ESX service rather than using admin CLI for this. A function has been added in #1500 to return a map of volume properties which includes the status and attached-to fields also. That can be used for checking status unless we need to only use admin cli (like testing admin cli)
