### ISSUE TITLE
vDVS documentation main landing page is not showing images

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1531]
<img width="970" alt="screen shot 2017-06-30 at 8 18 32 pm" src="https://user-images.githubusercontent.com/22988730/27758819-36f7fa3a-5dd3-11e7-84fa-af53fdfd67f8.png">

Images are missing from the index page.

/CC @tusharnt @girishshilamkar

**Comment by girishshilamkar** [comment]
@shuklanirdesh82 I quick fix is to copy https://github.com/infracloudio/docker-volume-vsphere/tree/gh-pages/documentation/images to https://github.com/infracloudio/docker-volume-vsphere/tree/gh-pages/images

And then we can figure out the long term solution.

**Comment by girishshilamkar** [comment]
It looks like since we build the docs and move to /documentation the relative path to images does not work. I am trying out absolute path, will send PR once i verify it.

**Comment by shuklanirdesh82** [comment]
fixed by #1541.
