### ISSUE TITLE
vDVS documentation related issues

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1545]
Some leftover items needs to be taken care.

- [x] image is missing from http://vmware.github.io/docker-volume-vsphere/documentation/docker-compatibility.html

<img width="910" alt="screen shot 2017-07-05 at 9 47 38 pm" src="https://user-images.githubusercontent.com/22988730/27895972-b34c09a4-61cb-11e7-9cf1-e685338e88b5.png">

- [x] ~propagates doc changes to gh-pages from vmware master and serves latest document (html pages) automatically~ [being tracked at #1721]

- [x] Publishing document steps needs be improved (at https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md#documentation); while publishing document using the steps mentioned in `CONTRIBUTING.md` overwrites the html changes.

- [x] `Edit me` link is not working for the home page i.e. index.html (https://github.com/vmware/docker-volume-vsphere/edit/gh-pages/jekyll-docs//.md)

- [x] Needs cleanup at https://github.com/vmware/docker-volume-vsphere/tree/gh-pages 
There are so many folders and might be redundant; it is better to clean them ASAP.

so far supplying above action items from top of my head, some more will be added soon...

/CC @tusharnt @girishshilamkar @vishal-biyani

**Comment by tusharnt** [comment]
@girishshilamkar Will you please take care of this?

**Comment by tusharnt** [comment]
@girishshilamkar plans to address this by 7/21/17.

**Comment by girishshilamkar** [comment]
@shuklanirdesh82 For the "Documentation Version" it is the old content which I picked up from existing documentation. I am not sure where the old releases are. Please send details. Thanks!

**Comment by shuklanirdesh82** [comment]
@girishshilamkar with the new layout and directory structure document html (serving files) should be preserved in the respective folder.

**Comment by girishshilamkar** [comment]
@shuklanirdesh82 Sorry I don't understand. We have added jekyll-docs folder and it probably needs to preserved. I am not sure what the old process was but only change would be to preserve jekyll-docs. Hope this answers your question.

**Comment by shuklanirdesh82** [comment]
Following action item will be taken care as part of separate task.

- [ ] Following paragraph is misleading. (http://vmware.github.io/docker-volume-vsphere/documentation/index.html#documentation-version) .. document is pointing to the latest version and no way to navigate per older release...Allowing user to navigate through older release notes

```
Documentation Version
The documentation here is for the latest release. 
The current master documentation can be found in markdown format in the documentation folder. 
For older releases, browse to releases select the release, click on the tag for the release 
and browse the docs folder.
```

In short, document release process is broken and needs to be corrected (link should point to release version's document along with latest document)
