### ISSUE TITLE
VerifyAttachedStatus() encounters govc error : No such Vm

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1560]
From CI run https://ci.vmware.run/vmware/docker-volume-vsphere/965,

govc vm.info -vm.ip=<ip address> fails for a VM that was suspended and resumed.

Causes test errors but can't confirm that its only for suspended and resumed VMs. The error didn't happen for the same VM for the other tests that kill and restart the VM.

2017/07/07 14:15:07 Creating volume [vmlistener_test_volume_774882] on VM [192.168.31.81]
2017/07/07 14:15:12 Attaching volume [vmlistener_test_volume_774882] on VM [192.168.31.81]
2017/07/07 14:15:28 Confirming attached status for volume [vmlistener_test_volume_774882]
2017/07/07 14:15:28 Fetching full name for volume [vmlistener_test_volume_774882] from VM [192.168.31.81]
2017/07/07 14:15:29 Full volume name: [vmlistener_test_volume_774882@datastore1]

2017/07/07 14:15:31 Expected Attached VM name is [govc: no such VM] <----------------
2017/07/07 14:15:31 Attached VM name from Docker CLI is [photon.vmfs]
2017/07/07 14:15:31 Attached VM name from Admin CLI is [photon.vmfs]

2017/07/07 14:15:32 Checking container [vmlistener_test_container_467428] presence on VM [192.168.31.81]
2017/07/07 14:15:32 container [vmlistener_test_container_467428] is present
2017/07/07 14:15:32 Removing container [vmlistener_test_container_467428] on VM [192.168.31.81]

**Comment by shuklanirdesh82** [comment]
@govint Is it working fine while running against your local testbed?

> [govc: no such VM]

Such kind of error comes when VM is not available on network in short it is not reachable.

**Comment by govint** [comment]
Not really, of the three newly added tests the one before passed with the same check on the same VM, while one  test failed.

this issue is a blocker if its going to delay getting tests submitted.

**Comment by govint** [comment]
Debugged this further and looks like govc is getting an error when getting VM name from the IP address. Added a delay after the suspend resume and able to get the test pass. Closing with changes in #1513.
