### ISSUE TITLE
CI package install fails with Failed to create ramdisk vibtransaction

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1562]
Happened in multiple CI runs, newest one is https://ci.vmware.run/vmware/docker-volume-vsphere/958

mkdir: can't create directory '/tmp/docker-volume-vsphere': File exists
Errors: 
 [VibDownloadError]
 ('/tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib', '/tmp/vibtransaction/tmp.vib', '[Errno 2] Local file does not exist: /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib')
        url = /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib
 Please refer to the log file for more details.
Errors: 
 [InstallationError]
 Failed to create ramdisk vibtransaction
 Please refer to the log file for more details.
Errors: 
 [VibDownloadError]
 ('/tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib', '/tmp/vibtransaction/tmp.vib', '[Errno 2] Local file does not exist: /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib')
        url = /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib
 Please refer to the log file for more details.
Errors: 
 [InstallationError]
 Failed to create ramdisk vibtransaction
 Please refer to the log file for more details.
Errors: 
 [VibDownloadError]
 ('/tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib', '/tmp/vibtransaction/tmp.vib', '[Errno 2] Local file does not exist: /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib')
        url = /tmp/docker-volume-vsphere/vmware-esx-vmdkops-0.15.d800c6a.vib
 Please refer to the log file for more details.

**Comment by shuklanirdesh82** [comment]
duplicate to #1548

It was happening due to CI race issues.
