### ISSUE TITLE
CI run failed as e2e tests could not finish within 30 mins

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1577]
https://ci.vmware.run/vmware/docker-volume-vsphere/1152

```
panic: test timed out after 30m0s

goroutine 827 [running]:
panic(0x5b7be0, 0xc4203a6010)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:918 +0x10b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:154 +0x44


FAIL	github.com/vmware/docker-volume-vsphere/tests/e2e	1800.041s
make[1]: *** [test-e2e-runonce] Error 1
make: *** [test-e2e-runonce] Error 2
```

**Comment by shaominchen** [comment]
Right now we have bumped up the timeout limit from 30 mins to 40 mins. The intention of this PR is to track the improvement of e2e tests to try to reach the goal of 30 mins of total running time.

**Comment by tusharnt** [comment]
If tests consistently fail even after bumping up the timeout limit to 40 min then we will target this with the priority.

**Comment by shaominchen** [comment]
We have increased the timeout limit to 50/60 mins for e2e test. It's been running for a while and it doesn't seem to be too bad. It's probably unpractical to achieve 30 mins goal. We should definitely fix this if the timeout exceeds 60 mins.

**Comment by shuklanirdesh82** [comment]
closing this for now .. we shall reopen with more detail.
