### ISSUE TITLE
Adding Windows VM to CI testbed

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1578]
Similar to photon and ubuntu VMs, we need to have a windows VM so that e2e tests can be run against windows implementation in automated fashion.
Important from the point of view project skylight (support for windows)

**Comment by pshahzeb** [comment]
As of now we need a make target something like test-windows that will run the tests against Windows VM.
As per whatever implementation we do, we can add relevant test under this target to be run.
To start with there can be only one windows VM (lets say to test volume creation).
With more implementation we can add more tests and probably add second windows VM if need be.
At the end of the code completion for skylight, all plugin tests should run against windows. If not we need to handle/fix those.

This target can be run through drone.yml file and during this run we can export windows VM ips.
Marking it P0 since we already have PRs coming in for windows support.

// CC @tusharnt @shuklanirdesh82 @shaominchen @venilnoronha

**Comment by tusharnt** [comment]
This needs to be fixed ASAP in order to enable feature testing for Project Skylight.

**Comment by shuklanirdesh82** [comment]
> https://github.com/vmware/docker-volume-vsphere/issues/1578#issuecomment-314900981

tracking at #1595 and #1597

**Comment by shuklanirdesh82** [comment]
Windows VM is added to CI.
