### ISSUE TITLE
vSphere + Docker-Machine + Swarm + docker-volume-vsphere

### ISSUE THREAD

**Issue by blop** [vmware/docker-volume-vsphere#1583]
Hello,

I'm using docker-machine to provision VM as swarm nodes.

I saw there is a VMware Photon OS which should be "optimized" for the vSphere environment.
I will try to see if I can provision VM with Photon using docker-machine (not tried yet).

Also, I was wondering if there is any preconfigured image (Photon OS or other), which comes preconfigured with docker-volume-vsphere ?

The idea is to build a docker swarm cluster on vSphere using docker-machine, and have the docker-volume-vsphere plugin available immediately.

Thanks!

**Comment by pdhamdhere** [comment]
@blop You can have docker volume plugin installed in OVF/OVA image that you use with docker-machine driver. Alternatively, you can install docker-volume-plugin during startup with following simple command;

`docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest`

**Comment by tusharnt** [comment]
This is already tracked by issue #634

**Comment by shaominchen** [comment]
We have decided not to fix issue #634.
