### ISSUE TITLE
Why using govc CLI instead of govmomi?

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1586]
This question was raised in a PR review discussion: https://github.com/vmware/docker-volume-vsphere/pull/1585#discussion_r127342230

Why are we not using govmomi directly? Is it because govc CLI is easier to integrate with?
@shuklanirdesh82 @msterin

**Comment by govint** [comment]
One advantage of using the CLI vs. govmomi is the test code is simpler from not having to traverse the object hierarchy and hence more code to fetch data. At least that part of the test code is really small now with only command invocation and output parsing in use.

**Comment by msterin** [comment]
yeah, but it does screen scraping, , doesn't it ? Or does govc spit out xml or json ?

**Comment by govint** [comment]
Json format is what we do today for the few commands used.

**Comment by shuklanirdesh82** [comment]
In addition to https://github.com/vmware/docker-volume-vsphere/issues/1586#issuecomment-315724606 (Thanks @govint ) .. the reason behind leveraging govc to keep in sync with other CLI approaches; we are using docker CLI, admin CLI so thought it would be better and lighter to use govc CLI. `govc` has argument support for `-json=false|true (by default)` and json parser that we use to grab the require output.

**Comment by shuklanirdesh82** [comment]
As per my understanding importing `govmomi` libraries requires to add entry to `vendor` folder, better to avoid for testing effort. If there is a strong opinion on using govmomi then we leave this issue open and enhance out test libraries in the future.

Please feel free to correct me about adding entry to `vendor` for dependency is not correct.

**Comment by msterin** [comment]
1. I don't see a problem in adding govmomi to ./vendor. We already have  plenty there. 
2. we are using 'docker' CLI because allegedly it gives us a better test coverage and "user" experience. I am not sure I agree, but docker CLI does wrap up sequences of API calls so it makes sense to check them.
same args to not apply to `govc`. We do not have "other CLI approaches"
3.with intermediate json, govc is OK, so I am fine if you close

**Comment by shaominchen** [comment]
Closing this as per above discussion - we don't have strong motivation to switch to govmomi as of now.
