### ISSUE TITLE
Current license or ESXi version prohibits execution of the requested operation.

### ISSUE THREAD

**Issue by JoeriVeder** [vmware/docker-volume-vsphere#1599]
After following the install guide i can't create any volumes.

When i run:

```
docker volume create --driver=vsphere --name=new-vol1 -o size=100MB
```

It returns an error response:

```
Error response from daemon: create new-vol1: VolumeDriver.Create: Server returned an error: (vim.fault.RestrictedVersion) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Current license or ESXi version prohibits execution of the requested operation.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

If have been looking around to see if i actually need a special license, but as far as i could see i don't . Right now i'm using a free license. Could you confirm that with this license i should be able to run this plugin?

On the Esxi host when i follow the "/var/log/vmware/vmdk_ops.log" log file i see the following:

```
07/18/17 13:10:06 2036640 [MainThread] [INFO   ] Started new thread : 112802672 with target <function execRequestThread at 0x346086f4> and args (13, 1840616, '{"cmd":"get","details":{"Name":"new-vol1"},"version":"2"}')
07/18/17 13:10:06 2036640 [Thread-17640] [INFO   ] db_mode='MultiNode (local symlink pointing to shared DB)' cmd=get opts={} vmgroup=_DEFAULT datastore_url=_VM_DS:// is allowed to execute
07/18/17 13:10:06 2036640 [sm1.webservice.comave.com-datastore1._DEFAULT.new-vol1] [INFO   ] executeRequest 'get' completed with ret={u'Error': 'Volume new-vol1 not found (file: /vmfs/volumes/datastore1/dockvols/_DEFAULT/new-vol1.vmdk)'}
07/18/17 13:10:06 2036640 [MainThread] [INFO   ] Started new thread : 112802672 with target <function execRequestThread at 0x346086f4> and args (14, 1840616, '{"cmd":"create","details":{"Name":"new-vol1","Opts":{"fstype":"ext4","size":"100MB"}},"version":"2"}')
07/18/17 13:10:06 2036640 [Thread-17641] [INFO   ] db_mode='MultiNode (local symlink pointing to shared DB)' cmd=create opts={u'size': u'100MB', u'fstype': u'ext4'} vmgroup=_DEFAULT datastore_url=_VM_DS:// is allowed to execute
07/18/17 13:10:06 2036640 [sm1.webservice.comave.com-datastore1._DEFAULT.new-vol1] [INFO   ] *** createVMDK: /vmfs/volumes/datastore1/dockvols/_DEFAULT/new-vol1.vmdk opts={u'size': u'100MB', u'fstype': u'ext4'} vm_name=sm1.webservice.comave.com vm_uuid=564d0cb7-399b-bc42-0227-71d7315b9b3e tenant_uuid=11111111-1111-1111-1111-111111111111 datastore_url=/vmfs/volumes/57fe37c7-ea6f8774-2231-1866da6cc0be
07/18/17 13:10:06 2036640 [sm1.webservice.comave.com-datastore1._DEFAULT.new-vol1] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1597, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 963, in executeRequest
    datastore_url=datastore_url)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 207, in createVMDK
    name=volume_datastore_path, spec=vdisk_spec)
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 543, in <lambda>
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
  File "/build/mts/release/bora-3620759/bora/build/esx/release/vmvisor/sys/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1273, in InvokeMethod
vim.fault.RestrictedVersion: (vim.fault.RestrictedVersion) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Current license or ESXi version prohibits execution of the requested operation.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
``` 

Wich also results in the "Current license or ESXi version prohibits execution of the requested operation." message. 

Please let me know how to approach this issue.

**Comment by Gyvastis** [comment]
Having the same issue here with a similar approach. Any ideas on what could be wrong?

**Comment by govint** [comment]
@JoeriVeder, thanks for reporting the issue you are observing, can you describe the set up you have for the ESX and the datastores in use. Are these local disks that you are using for the datastores?  Or USB/NFS? May be unrelated, is there a reason why the configuration DB is configured as multi-node mode vs. local?

**Comment by govint** [comment]
Basically, the free license disallows operations that need write access to the host (in this case creating a virtual disk) via, for example, the vSphere API, which is what is used here. Is it possible to use an evaluation license at least in order to be able to use the plugin.

**Comment by JoeriVeder** [comment]
@govint, Thank you for your quick reply!

I have three physical Esxi machines. On each machine i have one vm running as a member of my docker swarm. What I'm trying to achieve it that when one node in the swarm fails the others can still access the volume. So it should be a shared volume among the servers.

On these swarm nodes i'm running Docker version 17.06.0-ce, build 02c1d87.

I'm don't know why the db_mode is set to 'MultiNode'. This I assume happened by default.

**Comment by govint** [comment]
@JoeriVeder @Gyvastis, can you'll confirm that the plugin works ok with an evaluation license of ESX?

**Comment by JoeriVeder** [comment]
@govint I would like to try this, but I'm not sure how to get an evaluation license. I tried to get one via the vmware website an registered for one, but instead of a different license key I only got the option to download esxi (I guess pre evaluated). This would mean I would have to reinstall everything.

Do you know how/where I can get a evaluation license key, so I can test this?

**Comment by pdhamdhere** [comment]
@JoeriVeder You can go [here](https://my.vmware.com/en/web/vmware/evalcenter?p=vsphere-6&src=WWW_us_VMW_XfK4FDRuqSPE01Y7isJw) for 60 days free eval.

**Comment by JoeriVeder** [comment]
@pdhamdhere as mentioned before, you do not get a new license key on that page. Only a complete new build. Which for me is completely out of the case. I have a current setup with running production servers. I need a license key not a new licensed build.

**Comment by pdhamdhere** [comment]
This is being resolved over email.

**Comment by anthonyloukinas** [comment]
Not to poke the bear and re-open this issue, but I'm also experiencing the same issue on the Free version of ESXi. I followed @pdhamdhere link to obtain an evaluation key, but instead it forces me to download an entirely new ISO (bundled with key I imagine). Is there any easy way to get a key vs. an ISO? I'd like to test this Docker Volume Plugin before I start working in Production.

**Comment by kymbob** [comment]
"resolved over email" is an interesting resolution. I have the same issue on my lab, is there a way around this?

**Comment by JoeriVeder** [comment]
This was never resolved over e-mail.. not resolved at all.

**Comment by wwwlookformetop** [comment]
I  use the  vSphere API to backup  virtual disks,but it throws a exception  like :  current license or esxi version prohibits execution of the requested operation
