### ISSUE TITLE
Prepare github pages

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#16]
- Co-ordinate with VMware Open Source to bless repo, internal ticket with OSSTP was filed when repo was created.
- Co-ordinate with CNA Org for look and feel
- Investigate options for running surveys and analytics.

**Comment by msterin** [comment]
@kerneltime - can we close this one ?

**Comment by pdhamdhere** [comment]
Yes, page is live. However, logo on https://vmware.github.io/ needs an update. Assigning to Aparna

**Comment by asomaiah** [comment]
The logo cant be updated there for now. Approval process is taking longer than expected. Closing this for now and will update once the approval process is complete.
