### ISSUE TITLE
How to use the docker-volume-vsphere plugin with coreos (docker 1.2)

### ISSUE THREAD

**Issue by Jamlee** [vmware/docker-volume-vsphere#1607]
Hi:
   My docker use coreos as the host.  the version is the docker 1.12.6, so there is no `docker plugin` command. 

Can i install the plugin use `docker run -v /run/docker/libcontainerd/docker-containerd.sock:/xxxxxx.sock  vmware/docker-volume-vsphere` ?

**Comment by govint** [comment]
@Jamlee, the preferred way would be to upgrade Docker to the current stable version on CoreOS and use the managed plugin with that.

**Comment by Jamlee** [comment]
@govint the laster version (1465) of coreos also the docker version 1.12.6. it is not possbile for to change the docker version.

**Comment by govint** [comment]
@Jamlee, ok but the supported way to get to using the plugin is to use Docker version 1.13 (17.03) or later with the managed plugin. Suggest trying using another Linux distro other than CoreOS if that works.

**Comment by pdhamdhere** [comment]
@Jamlee Check out [issue](https://github.com/vmware/docker-volume-vsphere/issues/730) for workaround
