### ISSUE TITLE
Allow multiple Docker Hosts accessing same volume

### ISSUE THREAD

**Issue by Nagoo** [vmware/docker-volume-vsphere#1608]
Currently vSphere Volume (VMDK) formatted with local FS can only be used by one Docker Host (VM) at any point in time.

It will be quite useful to make it able to have several Docker Hosts connected to the same volume.

By having this, you could have several services running in a Docker Swarm cluster moving around the different nodes using the same volume. You will not have to add constraints to deploy a specific set of services in the same host, and instead you could let them be redeployed within any node.

It will also help when you scale your services, as you will not have to worry about where they get deployed.

**Comment by pdhamdhere** [comment]
@Nagoo +1 

We are actively looking into this. Stay tuned. Feel free to reach out to containers@vmware.com for more details.

**Comment by shuklanirdesh82** [comment]
We should revisit the description before calling vFile beta.

**Comment by luomiao** [comment]
@Nagoo 
The vFile plugin which supports the multiple VMs to access the same VMDK volume simultaneously is there as an experimental feature:
http://vmware.github.io/docker-volume-vsphere/documentation/vfile-plugin.html
You are welcome to give it a try.

We are planning to release the beta version in December. Stay tuned :)

**Comment by tusharnt** [comment]
@Nagoo Please let us know if you have feedback about vFile at hatchway@vmware.com
