### ISSUE TITLE
Extra testbed for test matrix (ESX versions, Docker versions) 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#161]
We need a testbed to test with different ESX version and different DOcker version.
Not urgent yet, but will be for GA. 

This could be done with Nimbus and will be used as manually started validaton at first. 
Or with Drone to make it a part of check in

This issue is to make decisions, review and implement

Assigning to Ritesh as he keeps the key to CI and testbeds.

**Comment by kerneltime** [comment]
Do we still want to do a nimbus testbed?

**Comment by msterin** [comment]
we don't - looks like Drone is doing fine :-)

**Comment by kerneltime** [comment]
Adding need for 6.5 testing https://github.com/vmware/docker-volume-vsphere/issues/666

**Comment by msterin** [comment]
changing milestone to 0.9 so we can officially support ESX 6.5

**Comment by kerneltime** [comment]
This is a much broader test matrix problem.. not sure milestone 0.9 makes sense. We can have a targeted issues for 6.5 only as a sub issue for this one.

**Comment by kerneltime** [comment]
https://github.com/vmware/docker-volume-vsphere/issues/763

**Comment by tusharnt** [comment]
@ashahi1 Isn't this already addressed? Apart from docker 1.13 on Photon OS, is there anything else remaining?

**Comment by ashahi1** [comment]
We support ubuntu with docker-0.11, 0.12 and 0.13 and Photon with docker-0.11 and 0.12

**Comment by ashahi1** [comment]
Now we can deploy testbed on Nimbus with Photon version 1.13. So closing this issue.
