### ISSUE TITLE
Add sshpass to the vibauthor container

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1612]
Presently the vibauthor container used to run the builds has all the tools that are needed for the build. As part of #1515 a new make target is being added to allow a developer to deploy a testbed (1master + 2 workers) and then deploy the plugin on those. Thus allowing the developer run all their tests on the testbed without having to set those up manually.

Its convenient to use the vibauthor container to run the script to deploy the VMs as it already has govc installed in it and usable to import the OVAs and create the VMs.

The issue faced in #1515 is to be able to run commands via SSH on the VMs, as those need the password to be entered. Even to do a password-less SSH command we need to first copy the public key to the VM which again needs the password.

sshpass allows passing the password to an ssh command. Allowing the deploy script to get the password via an env. var. and then using sshpass to run ssh commands.

The container already contains ssh utils like - ssh  ssh-add  ssh-agent  ssh-copy-id  ssh-keygen  ssh-keyscan.

So, ..... this issue is to add sshpass to the container so the deploy script can work.

**Comment by govint** [comment]
#1515 to create a test bed for a developer doesn't seem like its a much needed capability and users should be able to set up their workspaces of VMs by themselves. Moreover, developers (outside of the core dev. team) who want to run e2e tests (do they) would typically use a set up for a longer time vs. creating and discarding those setups often. I'm pushing this out to a future release unless this is really worth implementing.

Creating a script to make a test bed has nothing to do with the plugins we have and really shouldn't be in this code base either.

**Comment by shuklanirdesh82** [comment]
we can revisit after kubecon release not mustfix

**Comment by govint** [comment]
This is not a must fix and the original reason was to be able to create a test set up via a make target. Which, IMO, is not needed at all. Given users already have the means to set up a cluster of hosts the plugin doesn't need to provide any such capability. Closing this.
