### ISSUE TITLE
How to support multiple Docker versions and not mess up vendoring 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#162]
it is not clear how we would handle supporting misc. Docker versions - engine API is in ./vendor... so will we keep multiple versions there ? How would we test ?

**Comment by kerneltime** [comment]
We will always support the latest release in master and that has to be backward compatible. So far we have not encountered a problem. Is this still an issue?

**Comment by tusharnt** [comment]
@msterin What needs to be done here?

**Comment by msterin** [comment]
nothing. We rely on docker keeping reasonable (current and one prior) API compatibility
