### ISSUE TITLE
Unable to start test in CI with stale plugin lock

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#164]
OVer the weekend was trying some fixes and after a few runs CI tests ran for ever waiting for a stale lock to be released. The lock not being released no further builds could be done or tested.

/tmp/docker-vmdk-plugin.lock was the culprit.

CI must clean up if tests fail or killed and there should be a way for a user to clobber the test and be able to restart.

**Comment by pdhamdhere** [comment]
Existing issues leaving behind stale lock are fixed. "Cancel Build" is difficult to implement and have dependency on external team. Closing this as won'tfix. If we run into this again frequently, we can revisit and re-open.
