### ISSUE TITLE
Remove references to Photon Controller from vDVS docs

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1647]

**Comment by shuklanirdesh82** [comment]
As discussed offline following files and their references should be removed.

- [ ] https://github.com/vmware/docker-volume-vsphere/blob/gh-pages/jekyll-docs/photon.md
- [ ] https://github.com/vmware/docker-volume-vsphere/blob/gh-pages/jekyll-docs/photon-overview.md
- [ ] http://vmware.github.io/docker-volume-vsphere/documentation/photon.html

Reference: 
![photon_ref](https://user-images.githubusercontent.com/22988730/29799876-a2437230-8c1b-11e7-835b-f755b455990d.jpg)

**Comment by shaominchen** [comment]
Issue fixed with 2 PRs:
1. https://github.com/vmware/docker-volume-vsphere/pull/1840
2. https://github.com/vmware/docker-volume-vsphere/pull/1846
