### ISSUE TITLE
Document Windows plugin

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1664]
- [x] Installation:
A Windows plugin installation script has been added via PRs #1642, #1650 and #1654. We should also elaborate plugin installation instructions in the `README.md`, along with a few examples.
- [x] Known differences with vDVS on Linux:
a. Names
- [x] FAQs

/cc @shaominchen

**Comment by tusharnt** [comment]
This needs to be pulled back into master.
