### ISSUE TITLE
golint error for one of the method in etcdops.go

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1676]
#1661 introduces following, `make build` is also complaining about the same.

```
$ make -s build
drivers/shared/etcdops.go:89:39: exported func NewKvStore returns unexported type *shared.etcdKVS, which can be annoying to use
```

/CC @tusharnt

**Comment by luomiao** [comment]
oops. thanks for catching this.
It's strange that I didn't see this error in either local or CI testing...
Is it a warning or error?

**Comment by luomiao** [comment]
I found the CI testing of this PR:
https://ci.vmware.run/vmware/docker-volume-vsphere/1384

CI returns success while in the beginning it gave this warning:
```
$ make -s build
drivers/shared/etcdops.go:89:39: exported func NewKvStore returns unexported type *shared.etcdKVS, which can be annoying to use
warning: no packages being tested depend on github.com/vmware/docker-volume-vsphere/client_plugin/drivers/shared
warning: no packages being tested depend on github.com/vmware/docker-volume-vsphere/client_plugin/shared_plugin
```

Is it possible to fail CI if there is a warning?

And regarding to this warning, it will be gone when we finish the refactoring of the shared plugin.

**Comment by shuklanirdesh82** [comment]
Hey @luomiao, our build script is not strict for golint or pylint warnings/errors due to time constraints and we have an issue open to make python code to compliant with pylint warning. Post vmworld it is possible to restrict the build incase of such warning till then we have to look manually while proposing the new code change. 

It will be great if you can supply a quick fix or include any of your ongoing PR to turn off such warning. Since #1661 merged all our builds are having such warning.

**Comment by luomiao** [comment]
Resolved in https://github.com/vmware/docker-volume-vsphere/pull/1687
