### ISSUE TITLE
FAQs : Document why multi writer mode does not solve shared volume use case for all applications.

### ISSUE THREAD

**Issue by shivanshu21** [vmware/docker-volume-vsphere#1681]
This should be clearly documented in FAQ section for vFile - https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/vfile-plugin.md

**Comment by shuklanirdesh82** [comment]
mustfix for vFile beta release

**Comment by luomiao** [comment]
Closed by #1971
