### ISSUE TITLE
Investigate it is possible to provide param to set client timeout

### ISSUE THREAD

**Issue by shivanshu21** [vmware/docker-volume-vsphere#1683]
File server client timeout should be a param in kahuna

**Comment by luomiao** [comment]
SMB client could timeout if cannot find the remote server.
Need to explore if there is a parameter to control the timeout.
Or else, need to handle.

**Comment by shuklanirdesh82** [comment]
adding mustfix kw to finish investigation.

**Comment by lipingxue** [comment]
I did some research and there is no param for timeout can be set for cifs mount.

**Comment by luomiao** [comment]
Since it's not possible to use parameters to control the timeout, we will just close this issue.
And we have added retry for failed SMB client in order to reduce the possible error from slow server:
https://github.com/vmware/docker-volume-vsphere/pull/1886

**Comment by shuklanirdesh82** [comment]
Adding `wontfix` kw.
