### ISSUE TITLE
Test should accept "Driver type" as an input to reuse existing E2E automated tests

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1685]
existing test target should be enhanced to accept "driver type" as an user input.

The benefit of doing this to leverage existing test to extend test coverage for "shared" plugin.

e.g. `docker volume create -d <driver_name> -name=abc`

Currently driver name is controlled through test constants, it should be configurable through command line. 

current code: https://github.com/vmware/docker-volume-vsphere/blob/master/tests/constants/dockercli/cmd.go#L46

```
	// VDVSPluginName name of vDVS plugin
	VDVSPluginName = "vsphere "
```

/CC @luomiao @tusharnt @shivanshu21

**Comment by luomiao** [comment]
Need to explore if this is needed.

**Comment by shuklanirdesh82** [comment]
adding mustfix kw to finish investigation.

**Comment by luomiao** [comment]
Closed by https://github.com/vmware/docker-volume-vsphere/pull/1886
