### ISSUE TITLE
[CI] Swarm fail-over test failed as vm could not be powered-off using govc

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1688]
Swarm test failed on CI as vm could not be powered-off. This is an intermittent issue.
https://ci.vmware.run/vmware/docker-volume-vsphere/1404

Test name: SwarmTestSuite.TestFailoverAcrossSwarmNodes
ESX: 192.168.31.19 (6.0)
VM: Ubuntu.1404.vsan

Snippet from test logs:
```
2017/08/03 16:29:02 Shutting down VM [Ubuntu.1404.vsan]
2017/08/03 16:29:02 Failed to invoke command [govc vm.power -s=true Ubuntu.1404.vsan]: exit status 1                    <<<<<<<<<<<<<<<<<<<<<

----------------------------------------------------------------------
FAIL: swarm_test.go:73: SwarmTestSuite.TearDownTest

Test logs:
swarm_test.go:76:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4201fece0), Stderr:[]uint8(nil)} ("exit status 1")
...

----------------------------------------------------------------------
PANIC: swarm_test.go:96: SwarmTestSuite.TestFailoverAcrossSwarmNodes

swarm_test.go:136:
    c.Assert(isStatusChanged, Equals, true, Commentf("VM [%s] should be powered off state", hostName))
... obtained bool = false
... expected bool = true
... VM [Ubuntu.1404.vsan] should be powered off state

... Panic: Fixture has panicked (see related PANIC)
```

**Comment by tusharnt** [comment]
@ashahi1 every issue filed for the current sprint needs to have a owner.

**Comment by ashahi1** [comment]
Another instance on CI: https://ci.vmware.run/vmware/docker-volume-vsphere/1509

**Comment by shuklanirdesh82** [comment]
It is a govc error with reference `2017/08/03 16:29:02 Failed to invoke command [govc vm.power -s=true Ubuntu.1404.vsan]: exit status 1`.

I'm moving to post vmworld sprint. If we don't have repro in future it is safer to close as `could-not-reproduce`.

**Comment by shuklanirdesh82** [comment]
Haven't seen such issue in last one week. Please reopen if the issue will be reproduced.
