### ISSUE TITLE
Contact Us page is pointing to old slack channel

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1695]
README.md and http://vmware.github.io/docker-volume-vsphere/documentation/contactus.html are pointing to old slack channel which is old (https://vmwarecode.slack.com/archives/docker-volume-vsphere)

We have moved to #docker slack channel, `README.md` & `Contact Us` page needs to be updated.

- [ ] http://vmware.github.io/docker-volume-vsphere/documentation/contactus.html
- [ ] https://github.com/vmware/docker-volume-vsphere#public

/CC @tusharnt

**Comment by shuklanirdesh82** [comment]
We have to make correction at both places using `https://vmwarecode.slack.com/messages/docker/`

**Comment by ashahi1** [comment]
Fixed as part of PR #1790 and verified. Closing it.
