### ISSUE TITLE
[Debuggability] Show VM name in error message and logs

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1702]
Currently VM uuid is shown in case of errors.
For example: error during volume attach is as follows:
```
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/07edacf1891edd3b20bd2a3cc91439b73cc449822d4df431b7c14bc5212c3cef/rootfs/mnt/vmdk/mark': VolumeDriver.Mount: Failed to add disk 'scsi1:0'. disk /vmfs/volumes/sp-sys-docker/dockvols/_DEFAULT/mark.vmdk already attached to VM=5010dd5f-26b8-3719-2032-f8a8432a106c.
```

Since these errors are also logged (if not we need to do them), the name can be used in logs as well.

**Comment by shuklanirdesh82** [comment]
While talking with @pshahzeb figured out that we need to improve error message for attach/delete volume workflow (as of now - will be updated missing workflow). We need a common util which converts to vmName from vmUUID. 

Refreshing the estimate.
