### ISSUE TITLE
Print vDVS version in plugin and esx logs

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1708]
We need to log the vDVS version on esx log. We have it (shown during vmdkops_admin status command). Let's also log it.

On the plugin side, we need to log the managed plugin version. Also we need to log the version of VIB installed on ESX host on which the VM resides (where plugin is installed). Probably this can be exchanged during first handshake between plugin and esx service.

**Comment by govint** [comment]
Similar to #1662

**Comment by pshahzeb** [comment]
Debugging the CI failure for PR #1893

**Comment by shuklanirdesh82** [comment]
helps while triaging issues from customer side.

**Comment by tusharnt** [comment]
Fixed. @pshahzeb  to add PR info.
