### ISSUE TITLE
shared plugin: cannot remove volume from worker node

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1715]
I am able to create volume from worker node, but when I try to remove the volume from worker node, I get the following error:

```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume rm BasicSharedTestSuite.TestVolumeLifecycle_volume_316078
Error response from daemon: unable to remove volume: remove BasicSharedTestSuite.TestVolumeLifecycle_volume_316078: Post http://%2Frun%2Fdocker%2Fplugins%2F008e1fcc9a74075a72233fd7bd15004ddc666dd66049ae31aa63ba9e30924965%2Fshared.sock/VolumeDriver.Remove: http: ContentLength=66 with Body length 0
```

**Comment by shivanshu21** [comment]
CompareAndPutOrFetch() did not create an etcd client properly, hence this was not working on worker nodes. Will fix in the next PR for mount().

**Comment by luomiao** [comment]
@shivanshu21 
CompareAndPut doesn't create an ETCD client neither.
It's ok for now since CompareAndPut is only called by event handler (only on master)
But considering the timeout problem, can you add the client create in CompareAndPut too?

**Comment by shivanshu21** [comment]
I have added it everywhere. ReadMetaData() was creating client but not checking if returned client is nil.
