### ISSUE TITLE
VMDKOps Service communication failure on Windows VM

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1720]
It's observed that all operations via vDVS on Windows fail to communicate with the VMDKOps Service intermittently, and we observe the following error message in the logs.

```
Internal issue: ret != 0 but errno is not set. Cancelling operation -
```

It's also observed that redeploying the VM sometimes solves the issue.

/cc @pshahzeb @ashahi1

**Comment by pshahzeb** [comment]
Tried to reproduce it.

I am consistently seeing the test pass and not seeing the error above. I tried it 4 times. 
I have an ESX in nimbus tested bed with windows VM created from OVA indicated in the Win Dev Setup.

However, I am consistently seeing this failure given that ESX service is not installed or it is down.
When we saw this error, was it confirmed that ESX side vmdkops service is up and running healthy?

Closing this for now. If seen again, please update the issue with status of vmdkopsd on esx host and both vmdkopsd.log and plugin log.

**Comment by venilnoronha** [comment]
@pshahzeb the status of VMDKOps Service wasn't confirmed. I'll post the logs if I see it occur again.
