### ISSUE TITLE
gh-pages (document release branch) should be automatically populated 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1721]
Currently, any changes to [vmware]/docs has to be manually copied to gh-pages. The process should be automated - any changes to [vmware]/docs should be promoted to gh-pages automatically

https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md#documentation-pr

**Comment by pdhamdhere** [comment]
Changes should be promoted from master to gh-pages every time we cut release. And this is P0 and must be fixed before next release.

**Comment by shuklanirdesh82** [comment]
PR #1798 is bringing doc changes from vmware:master to vmware:gh-pages automatically. 

Next step:

- [ ] 1. configure a vm to invoke cron job to run this script daily.

**Comment by ashahi1** [comment]
Filed a separate issue for creating a cron job - #1854
