### ISSUE TITLE
Support for Resilient File System (ReFS) type for Windows Plugin

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1731]
Currently, plugin for windows support volume create with filesystem NTFS.
Need a support to provide ReFS file system type during volume creation.

**Comment by pshahzeb** [comment]
```
Resilient File System (ReFS)

Creation ability will be available in the following editions only: Windows 10 Enterprise and Windows 10 Pro for Workstations.

Creation ability will be removed from all other editions.  All other editions will have Read and Write ability.

(added: August 17, 2017)
```

From https://support.microsoft.com/en-us/help/4034825/features-that-are-removed-or-deprecated-in-windows-10-fall-creators-up

**Comment by shuklanirdesh82** [comment]
@pshahzeb Shouldn't we close this issue and mark is as `wontfix`? As per (https://support.microsoft.com/en-us/help/4034825/features-that-are-removed-or-deprecated-in-windows-10-fall-creators-up) I guess the support is removed for ReFS.

**Comment by pshahzeb** [comment]
Yes. We can.
