### ISSUE TITLE
Handle swarm node role change in vFile plugin

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1732]
Currently the vFile plugin proceeds with the role of the node when the plugin is installed.

However the role of a node can change.
A helper thread is needed in each plugin to handle the change of the role.
For example, when a node is promoted from worker to manager, it should join the etcd cluster and start watcher. On the other hand, when a node is demoted to worker, it should leave the etcd cluster and stop watcher.
The helper thread should regularly check the status of the node.

Question: can the plugin get notified when a node is promoted/demoted?

**Comment by shuklanirdesh82** [comment]
good to have for vFile beta release
