### ISSUE TITLE
Windows plugin should use UniqueId in place of DiskNumber

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1738]
The current `fs` module [implementation](https://github.com/vmware/docker-volume-vsphere/blob/5a7d3a6f3106801f4c953a87e0efefbf88399d66/client_plugin/utils/fs/fs_windows.go#L60) for Windows relies entirely on `DiskNumber` (aka `Index`, `Number`). The implementation should instead use `UniqueId`s to avoid collisions.

See below for examples on how to obtain a disk's `UniqueId`.

<img src="https://user-images.githubusercontent.com/1722758/29188125-f676ab64-7dc6-11e7-9c64-efddbc462c39.png">

**Comment by pshahzeb** [comment]
The id (device signature) captured (as shown in description) cannot be 

```
PS C:\Users\root> diskpart

Microsoft DiskPart version 10.0.14393.0

Copyright (C) 1999-2013 Microsoft Corporation.
On computer: WIN-QBI6V8BMPGM

DISKPART> select disk 2

Disk 2 is now the selected disk.

DISKPART> detail disk

VMware Virtual disk SCSI Disk Device
Disk ID: C6CE28EB
Type   : SAS
Status : Online
Path   : 0
Target : 0
LUN ID : 0
Location Path : PCIROOT(0)#PCI(1700)#PCI(0000)#SAS(P00T00L00)
Current Read-only State : No
Read-only  : No
Boot Disk  : No
Pagefile Disk  : No
Hibernation File Disk  : No
Crashdump Disk  : No
Clustered Disk  : No

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 4         test1        NTFS   Partition     98 MB  Healthy
    C:\Windows\System32\config\systemprofile\AppData\Local\docker-volume-vsphere\mounts\test1@sharedVmfs-0\
```

```
PS C:\Users\root> Get-Disk -Number 2 | Select UniqueId

UniqueId
--------
SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\000000:WIN-QBI6V8BMPGM
```

This is the id that needs to be further used with Set-Disk, Initialize-Disk command with flag -UniqueId.
ex:
```
PS C:\Users\root> Set-Disk -UniqueId "SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\000000:WIN-QBI6V8BMPGM" -IsReadOnly $True
PS C:\Users\root> Set-Disk -UniqueId "SCSI\DISK&VEN_VMWARE&PROD_VIRTUAL_DISK\000000:WIN-QBI6V8BMPGM" -IsReadOnly $False
```

Using device signature won't find the device (disk)
```
PS C:\Users\root> Set-Disk -UniqueId "C6CE28EB" -IsReadOnly $False
Set-Disk : The requested object could not be found.
At line:1 char:1
+ Set-Disk -UniqueId "C6CE28EB" -IsReadOnly $False
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_StorageCmdlets:ROOT/Microsoft/..._StorageCmdlets) [Set-Disk], CimException
    + FullyQualifiedErrorId : MI RESULT 6,Set-Disk
```

But the first question is can disk Index cause collision?
Disk number is the default and easy way to identify disks
Windows numbers them as part of enumeration during Plug and Play process.
For newer disks, incremental index numbers are provided.
See the cause section [here](https://support.microsoft.com/en-us/help/937251/disk-drive-numbers-may-not-correspond-to-the-sata-channel-numbers-when) 

So as such disk number (index collision) doesn't seem to be real-world reasonable possibility.

**Comment by shaominchen** [comment]
I agree. Using UniqueId looks not straightforward. We can stick with DiskNumber for now unless there's a right reason to change.
