### ISSUE TITLE
Populate client list on mount and depopulate on unmount

### ISSUE THREAD

**Issue by shivanshu21** [vmware/docker-volume-vsphere#1761]
A shared volume could be running anywhere on the swarm cluster. If a user tries to delete this volume and repeatedly gets the message "The volume is in use", it will be frustrating to keep looking for containers on every host.

Volume metadata already has a place to store the name of host VMs where the volume is mounted. This list should be populated during mount and unpopulated during unmount.

**Comment by shuklanirdesh82** [comment]
correctness issue for vFile
