### ISSUE TITLE
[CI] Volume creation failed

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1765]
CI run failed as test could not create a volume.
**Error:** ```Error response from daemon: create VmGroupTest.TestVmGroupVolumeClone_volume_525171: Post http://%!F(MISSING)run%!F(MISSING)docker%!F(MISSING)plugins%!F(MISSING)458f3e98b5bda0e5210f6b999d183fd301623d7967adefa85e775d40718b7fb0%!F(MISSING)vsphere.sock/VolumeDriver.Create: http: ContentLength=70 with Body length 0```

Test: VmGroupTest.TestVmGroupVolumeClone (https://github.com/vmware/vsphere-storage-for-docker/blob/master/tests/e2e/vmgroups_test.go#L542)

CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1504

```
2017/08/16 03:22:44 START: VmGroupTest.TestVmGroupVolumeClone
2017/08/16 03:22:44 Creating volume [VmGroupTest.TestVmGroupVolumeClone_volume_525171] on VM [192.168.31.241]

----------------------------------------------------------------------
FAIL: vmgroups_test.go:542: VmGroupTest.TestVmGroupVolumeClone

vmgroups_test.go:546:
    // 1. Create a volume in the VM's vmgroup
    vg.createVolumes(c, vg.volName1)
vmgroups_test.go:135:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4202d9240), Stderr:[]uint8(nil)} ("exit status 1")
... Error response from daemon: create VmGroupTest.TestVmGroupVolumeClone_volume_525171: Post http://%!F(MISSING)run%!F(MISSING)docker%!F(MISSING)plugins%!F(MISSING)458f3e98b5bda0e5210f6b999d183fd301623d7967adefa85e775d40718b7fb0%!F(MISSING)vsphere.sock/VolumeDriver.Create: http: ContentLength=70 with Body length 0
```

**Comment by tusharnt** [comment]
@shaominchen please move it to sprints post Mufusa if this is not critical.

**Comment by shaominchen** [comment]
We don't see this issue in the latest CI runs. If this happens again, we will disable this test and figure out the cause.

**Comment by shuklanirdesh82** [comment]
Let's reopen if the issue will be reproduced.
