### ISSUE TITLE
Rename docker-volume-vsphere/vdvs in Windows installer/documentation

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1772]
The Windows installation/documentation calls the plugin as `docker-volume-vsphere` / `vdvs` at some places and we should rename that to `vSphere Storage for Docker`.

**Comment by shuklanirdesh82** [comment]
We have reverted the rename change and back to `docker-volume-vsphere` so closing this as invalid. 

Windows doc/code will be taken care in a shot while doing renaming to `vsphere-storage-for-docker` again.
