### ISSUE TITLE
vFile plugin: automatically upload plugin to cnastorage docker hub in CI

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1776]
Plugin needs to be uploaded to cnastorage docker hub so user can install it through:
docker plugin install --grant-all-permissions --alias vshared cnastorage/vfile:latest-dev

**Comment by luomiao** [comment]
Manually uploaded to cnastorage/vfile:latest-dev.
CI change TBD.

**Comment by shuklanirdesh82** [comment]
vFile CI integration so mustfix

**Comment by luomiao** [comment]
Closed by https://github.com/vmware/docker-volume-vsphere/pull/1886
