### ISSUE TITLE
Skylight performance improvement - Investigate to reduce disk-attach wait time in the Windows plugin

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1780]
The `fs.maxDiskAttachWaitSec` is set to 60 seconds to prevent failures during parallel volume requests, as access to the `powershell` utility is synchronized. This should be reduced once parallel disk identification is implemented. Currently, `fs.getDiskNum(..)` blocks during parallel execution due to synchronized access to `ps.Exec(..)`. Therefore, parallel volume creation in `e2e` tests block in `fs.DevAttachWait(..)` for a while and so we allow a long delay here.

See #1775 and [these lines](https://github.com/venilnoronha/docker-volume-vsphere/blob/0653f749f67c9e561e71964ff7cc7e133816ccbc/client_plugin/utils/fs/fs_windows.go#L34-L40) for more information.

/cc @shaominchen

**Comment by tusharnt** [comment]
@shaominchen , @pshahzeb Can you please add the perf numbers after @venilnoronha's change went in.

**Comment by shaominchen** [comment]
We are putting 2 days for investigation of this issue. Will file separate issues if parallel execution can be achieved.

**Comment by shuklanirdesh82** [comment]
> We are putting 2 days for investigation of this issue. Will file separate issues if parallel execution can be achieved.

mustfix for atleast investigation task (adding mustfix and investigate keywords)
