### ISSUE TITLE
Offline install 

### ISSUE THREAD

**Issue by frjaraur** [vmware/docker-volume-vsphere#1794]
Is there anyway of having an offline install of this docker plugin?. Not everyone can execute 
docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest on their docker nodes.

I tried to pull vmware/docker-volume-vsphere:latest from docker hub/store with no luck.

Can someone guide me to do install this plugin offline?.

Many Thanks in Advance,
Javier R.

**Comment by govint** [comment]
@frjaraur, thanks for contacting on this issue, the plugin is to be used as a managed volume plugin for docker and as such needs to be installed via _docker plugin install_. Did you plan to run the plugin not as a managed plugin?

**Comment by govint** [comment]
@frjaraur I'm closing this issue unless there is a problem with installing the plugin via _docker plugin install_. Please let us know if plugin install works fine with that.
