### ISSUE TITLE
Add documentation(user guide) for shared volume support.

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1796]

**Comment by tusharnt** [comment]
@luomiao please reference this issue in your documentation change that is already for review.

**Comment by luomiao** [comment]
Added userguide to master branch.
Need to sync up with gh-pages.

**Comment by tusharnt** [comment]
Closing this since the the remaining work of syncing up master and gh-pages branches is tracked by #1721
