### ISSUE TITLE
Finalize the nomenclature for stable and edge releases

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1797]
Finalize and document the nomenclature for stable and edge releases

**Comment by lipingxue** [comment]
**Type of Release:**
We plan to have two type of releases: edge release and stable release.

- edge release: will be released every month for users who want a drop of latest 
- stable release:  will be release every 3 month for users who want to a stable version

**Nomenclature for release:**

 The Nomenclature for release will follow the format  ```major-version. minor-version.build-version.release-type```.

 “Major-Version” will be the major version number, “minor-version” will be the minor version number which will be bumped on each monthly release. “build-version” by default is 0.  If we decide to cut one more release on that month (maybe some patch releases), we can increase the “build-version” by 1 for that release. “release-type” has two possible values: “stable” to mark a stable release and “edge” to mark a edge release.
 
For Example,  assume  we plan to cut the first release for GA on August , the release number will be “1.0.0.stable”. Then the monthly edge release  on September will be “1.1.0.edge”,  the monthly release on October will be “1.2.0.edge” and the stable release on November will be “1.3.0.stable”, etc.

**Comment by shuklanirdesh82** [comment]
Some action items:

- [ ] CONTRIBUTING.md needs to be updated (https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md#cutting-a-new-release-guidelines)

- [ ] our customer facing document home page (http://vmware.github.io/docker-volume-vsphere/documentation/index.html) or FAQ page (http://vmware.github.io/docker-volume-vsphere/documentation/faq.html) about release should be updated.
