### ISSUE TITLE
vFile: tests to verify performance, functionality and robustness

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1806]
This ticket is used to track tests for verifying behavior and robustness of vFile volume plugin, before auto-testing is fully accomplished.

- [ ] **Test 1 (TBD post VMworld)
Purpose: achieve basic performance number of vFile plugin**
Setup: 3 nodes, 1 manager, 2 workers
Steps:
IOPS: latency/bandwidth for a single container read/write performance
IOPS: latency/bandwidth for two containers on the same node read/write performance
IOPS: latency/bandwidth for two containers on two different hosts read/write performance
How long does it take to: Create/Remove/Mount/inspect a volume
 

- [ ] **Test 2:  (TBD post VMworld)
Purpose: Stress tests to find out the maximum number of shared volumes can be mounted on each container host**
Setup: 1 node, 1 manager
Steps: Repeat creating and mounting vFile volumes until hit the maximum number of SMB servers can be started on each node.
 

- [x] **Test 3: (Liping)
Purpose: Verify the correctness and robust of vFIle plugin with a larger cluster and a larger number of containers in parallel**
Setup: 10 nodes, 3 managers, 7 workers
Steps:
Create one volume per host VM (total 10).
Repeat to start/stop up to 10 containers in each host VM (total 100) with random sleep interval and access all 10 vFile volumes from each node.
 

- [x] **Test 4: (Miao)
Purpose: Verify the behavior during file transfer when file sharing server fails over**
Setup: 5 nodes, 3 managers, 2 workers
Steps:
Start copying a huge file from local path to a vFile volume.
Power-off the node where the samba container is running.
Wait for the copy to finish.
Compare the checksum of the files on local path and on vFile volume

**Comment by luomiao** [comment]
Test 4:
Purpose: Verify the behavior during single file transfer when file sharing server failover

Test command: `cp`
Test file: ubuntu16-docker17-06.ova 
size: 2.02GB
Action: power off the node where file sharing server is running during cp operation in progress

The behavior is different according to the container's base image.

- Base image - centos:

`cp: failed to close '/dst/ubuntu16-docker17-06.ova': Input/output error`

- Base image - busybox:

1. `ls: ./dst: Resource temporarily unavailable`
2. Input/Output Error
```
/ # cp /src/ubuntu16-docker17-06.ova /dst
cp: error writing to '/dst/ubuntu16-docker17-06.ova': Input/output error
```
3. Hang

- Base image - ubuntu:

Data transfer will continue and complete. However checksum reveals the destination file is different from the original file.

If `cp` returns error, users need to re-do the copy operation again. Since the file sharing server has been failover to a new node, the second try will succeed.
However for the case where copy can continue but result in a corrupted data file, users must make sure to verify the files afterwards.

**Comment by lipingxue** [comment]
**Test3:**
Actually, I tested with smaller configuration with 6 VMs.
Configuration:
6 VMs in one swarm cluster, 3 VMs are assigned as manager and 3VMs are assigned as worker

**Steps:**
1. create 6 volumes using vFile driver, named testvol0... testvol5.
2. split 6 VMs into three groups, and each group includes 2 VMs, one VM will be served as a writer and the other will be served as a reader 
3. For each group, run the following testing:
3.1 sleep a random number of seconds (between 0 ~5 seconds)
3.2.  For each volume, start a container from writer VM to attach the volume and write some content in a file (For example, I used the naming convention like this: for group 0 and vol 0, the file name is "grp0vol0" etc).
3.3 sleep a random number of seconds (between 0 ~5 seconds)
3.4 For each volume, start a container from read VM to attach the volume and read the data back to make sure it matches the content written in 3.2.
4. Run the same test mentioned above on three groups in parallel

**Result:**
  No error is found, work as expected

**Comment by lipingxue** [comment]
Test1 Result:
I use "fio" to test it, please see the following result.

- A single container

|Access Pattern | IOPS |Bandwidth|
| ------------- | ------------- |------------- |
| RandWrite4K| 370|1482.2KB/s  |
| RandWrite8K | 358| 2865.8KB/s |
| RandWrite16K | 304 | 4867.2KB/s |
| RandWrite32K | 292  | 9359.5KB/s |
| RandRead4K| 1003  |4014.5KB/s  |
| RandRead8K | 898  | 7190.1KB/s |
| RandRead16K | 730  | 11681KB/s |
| RandRead32K | 669  | 21424KB/s |
| SeqWrite4K| 335  |1343.2KB/s  |
| SeqWrite8K | 316  | 2535.5KB/s |
| SwqWrite16K | 306  | 4910.8KB/s |
| SeqWrite32K | 292 | 9371.4KB/s |
| SeqRead4K| 2350 |9401.1KB/s  |
| SeqRead8K | 2042  | 16342KB/s |
| SwqRead16K | 1415  | 22645KB/s |
| SeqRead32K | 541 | 17335KB/s |
-

**Comment by lipingxue** [comment]
I tested vFile volume create/inspect/mount/remove, the following is the result.
Test Configuration: 3VM, each VM has 1GB memory and 16GB disk, 3VM are in a swarm cluster, 1 VM is the master and the other two are workers.

I tested with 60 volumes with 100MB size

|Operation| Avg |Min|Max|
| ------------- | ------------- |------------- |------------- |
| Create| 3.87s|3.40s  | 4.58s|
| Inspect | 0.015s| 0.011s |0.046s|
| Mount | 9.84s | 8.72s |12.01s|
| Remove | 3.47s| 3.35 |3.64s

**Comment by luomiao** [comment]
Stress test: repeat creating and mounting vFile volumes.

**1 node situation (1 manager)**:
Creating of vFile volumes failed at around **40** volumes with error:
`VolumeDriver.Create: Failed to place new disk - The maximum number of supported volumes has been reached.`

**3 node situation (1 manager, 2 workers)**:
The vFile file server services are placed on the three nodes in a round robin way.
Creating of vFile volumes failed at around **110** volumes with error:
`VolumeDriver.Create: Failed to place new disk - The maximum number of supported volumes has been reached.`

The errors came from the vDVS plugin, since each VM has limited number of PVSCSI slots. When all the PVSCSI slots are used up, new vDVS volumes cannot be created.
With current version of vFile plugin, when the underlying vDVS plugin failed to create new volumes, it will create local volume as internal volume.
This should be addressed to return errors only without creating an internal volume: issue TBD.

Conclusion: vFile plugin can handle the creating/mounting requests until the limit of underlying vDVS plugin is reached. The maximum number of supported volumes of vDVS plugin is **60** volumes/VM.
