### ISSUE TITLE
Fix swarm certificate expiry issue in CI

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1810]
We recently ran into this failure in CI:

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
FAIL: swarm_test.go:46: SwarmTestSuite.SetUpSuite

swarm_test.go:58:
c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc42042fa60), Stderr:[]uint8(nil)} ("exit status 1")
... Error response from daemon: Swarm certificates have expired. To replace them, leave the swarm and join again.
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

The failure was caused by swarm certificate expiry. We should fix this to avoid same issue happening again in the future. Possible solutions:
1. Investigate if it's possible to set the certificate expiry date to a very long time, such as 10 years
2. Renew automatically if the certificate expires

**Comment by shuklanirdesh82** [comment]
ci improvement issue adding mustfix

**Comment by tusharnt** [comment]
Tracked as part of #1269
