### ISSUE TITLE
Upgrading docker version in CI testbeds

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1814]
Currently we have two setups with 17.04 and 17.03 docker

17.04 should be upgraded to 17.06

17.03 should be upgraded to 17.03.02

With fix from #1811, all tests pass with docker 17.06. I verified on local testbed.

CC @tusharnt @shuklanirdesh82

**Comment by shuklanirdesh82** [comment]
CI testbed VMs are upgraded with the required docker version.
