### ISSUE TITLE
Document the setup required for contributing to windows plugin

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1825]
Document steps required to setup environment to contribute to the windows plugin
Explicit steps to download and install specific versions of

1. Windows VM
2. Docker 
3. Go
4. MSVC 2015 Build Tools
5. MinGW-W64

Any additional steps required as appropriate.

**Comment by shuklanirdesh82** [comment]
contributing.md should be having such useful information.
