### ISSUE TITLE
vFile : plugin installation intermittently fails

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1829]
On a setup on which vsphere plugin succeeds, vFile plugin install fails.

$ docker plugin install store/vmware/docker-volume-vsphere:latest —alias vsphere
Plugin "store/vmware/docker-volume-vsphere:latest" is requesting the following privileges:
 - network: [none]
 - mount: [/dev]
 - mount: [/var/run]
 - mount: [/etc]
 - mount: [/var/log]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from store/vmware/docker-volume-vsphere
bc8c14d82abc: Download complete
Digest: sha256:6b81577c0502f537bc8a5ccf3f1599d9f9b7276242d7043d00d04496f312b976
Status: Downloaded newer image for store/vmware/docker-volume-vsphere:latest
Installed plugin store/vmware/docker-volume-vsphere:latest
tthole-m01:Documents tthole$ docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
5abad0739fd2        vsphere:latest      VMWare vSphere Docker Volume plugin   true

$ docker plugin install —grant-all-permissions —alias vfile cnastorage/vfile:latest
latest: Pulling from cnastorage/vfile
a4861ee109f5: Download complete
Digest: sha256:aa22f7d5ba8459079b69c64c326f5f8c77945355cdf8e09eadcaea5911b99cff
Status: Downloaded newer image for cnastorage/vfile:latest
Error response from daemon: dial unix /run/docker/plugins/219663b1f16a17bb12b81bd368ced10b243673118aeb74034102350022f28479/vfile.sock: connect: no such file or directory

**Comment by luomiao** [comment]
This should already be addressed by:
https://github.com/vmware/docker-volume-vsphere/pull/1823

Please use latest vfile plugin at: vmware/vfile:latest.
