### ISSUE TITLE
Improve error message when config db is not initialized

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1834]
An error message should be improved when config db is not initialized, it is still suggesting to use `vmdkops_admin.py` even though we have esxcli integration now.

After esxcli integration with our vDVS driver(admin CLI) following message is not appropriate.

```
[root@promc-2n-dhcp105-97:~] esxcli storage guestvol vmgroup access ls --name=_DEFAULT
Configuration not found. Please init configuration with 'vmdkops_admin.py config init'.
```

user will be confused easily by `Please init configuration with 'vmdkops_admin.py config init` even though it is possible to initialize config through esxcli.

We should provide a **generic message** or a message like `Configuration not found. Please init configuration with 'vmdkops_admin.py config init' or 'esxcli storage guestvol config init' (if using esxcli)` or just "esxcli" command.

cosmetic fix required at https://github.com/vmware/docker-volume-vsphere/blob/8de97721d2f1ff1e62d0f918c502450782134072/esx_service/utils/error_code.py#L134

```
 ErrorCode.INIT_NEEDED: "Configuration not found. Please init configuration with 'vmdkops_admin.py config init'.",
```

/CC @pdhamdhere @tusharnt

**Comment by pshahzeb** [comment]
Closed through #1836
