### ISSUE TITLE
"Edit Me" link should point to vmware:master markdown files

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1847]
Currently "Edit me" links are pointing to gh-pages branch. We need to point this link to master document so that PR is generated against vmware:master and our automated script takes care such update automatically while generating github.io pages. 

- [ ] make sure Edit me points to vmware:master/docs folder.

**Comment by ashahi1** [comment]
Fixed as part of PR #1885
