### ISSUE TITLE
gh-pages branch cleanup

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1848]
Let's remove unwanted files from gh-pages.

- [x] invalid MD files should be removed from jeckyll-docs and keep those files insync with vmware:master

- [x] remove unwanted images

- [x] remove unwanted yaml files from jeckyll-docs/_data

in short, go through jeckyll-docs and remove unnecessary stuff.

**Comment by ashahi1** [comment]
Addressed as part of issue #1861 and #1862
