### ISSUE TITLE
 ImportError: No module named esxcli.Session

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1869]
CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1579
```
2017/09/07 01:21:17 Deleting a vmgroup [T1] on esx [192.168.31.19] with delete_vol[%!d(bool=false)]
2017/09/07 01:21:19 Checking if vmgroup [T1] exists from esx [192.168.31.19] 
2017/09/07 01:21:20 Removing the SingleNode Config DB on esx [192.168.31.19] 

----------------------------------------------------------------------
FAIL: basicdefault_test.go:75: BasicTestSuite.TestVmGroupVolumeIsolation

basicdefault_test.go:126:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420124580), Stderr:[]uint8(nil)} ("exit status 1")
... CRITICAL:root:Exception:No module named esxcli.Session
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session
```

/CC @ashahi1

**Comment by shuklanirdesh82** [comment]
The failure is observed on our master so keeping P0 to triage, if necessary please adjust the priority after triaging .

**Comment by pshahzeb** [comment]
This is a failure while executing esxcli binary itself; which is a python script. Occurred on esx box with ESX 6.0. Trying to reproduce.

**Comment by shuklanirdesh82** [comment]
```
Installation Result:
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: VMWare_bootbank_esx-vmdkops-service_0.17.fbb8518-0.0.1
   VIBs Removed: 
   VIBs Skipped: 
watchdog-hostd: Terminating watchdog process with PID 34650
hostd stopped.
Ramdisk 'hostd' with estimated size of 114MB already exists
hostd started.
vmdkops-opsd is running pid=94990
95018
```

As discussed offline, we should introduce some wait time between vib installation and hostd restart to register esxcli namespace (`guestvol`).

**Comment by pshahzeb** [comment]
At times saw this warning after hostd restart.
```
ResourceGroup: failed to instantiate group with id 164618: Unable to complete Sysinfo operation.  Please see the VMkernel log file for more details.: Sysinfo error: Not initializedSee VMkernel log for details.
ResourceGroup: failed to instantiate group with id 164794: Unable to complete Sysinfo operation.  Please see the VMkernel log file for more details.: Sysinfo error: Not initializedSee VMkernel log for details.
ResourceGroup: failed to instantiate group with id 164850: Unable to complete Sysinfo operation.  Please see the VMkernel log file for more details.: Sysinfo error: Not initializedSee VMkernel log for details.
ResourceGroup: failed to instantiate group with id 164861: Unable to complete Sysinfo operation.  Please see the VMkernel log file for more details.: Sysinfo error: Not initializedSee VMkernel log for details.
ResourceGroup: failed to instantiate group with id 164862: Unable to complete Sysinfo operation.  Please see the VMkernel log file for more details.: Sysinfo error: Not initializedSee VMkernel log for details.
```

I think the reason is hostd isn't complete stable and we do 
```localcli --plugin-dir=/usr/lib/vmware/esxcli/int sched group list```
to check if vmdkops service is properly configured.


The warning 
```
Ramdisk 'hostd' with estimated size of 114MB already exists
``` 
is always visible when you restart hostd on ESX 6.0

Are these warnings safe to ignore?

**Comment by shuklanirdesh82** [comment]
mustfix for atleast investigation task

**Comment by shaominchen** [comment]
Closing this as we don't see this issue anymore.

**Comment by ashahi1** [comment]
Saw this issue again on CI: https://ci.vmware.run/vmware/docker-volume-vsphere/1647

```
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session

----------------------------------------------------------------------
FAIL: vmlistener_test.go:272: VMListenerTestParams.TestFailoverAcrossVmOnVsan

vmlistener_test.go:340:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420440900), Stderr:[]uint8(nil)} ("exit status 1")
... CRITICAL:root:Exception:No module named esxcli.Session
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session
```

**Comment by ashahi1** [comment]
@govint do you think you can take a look at this issue?

**Comment by ashahi1** [comment]
Another failure on CI: https://ci.vmware.run/vmware/docker-volume-vsphere/1652
```
2017/10/10 09:46:58 Creating policy [some-policy] with content ['(("proportionalCapacity" i50)''("hostFailuresToTolerate" i0))'] on ESX [192.168.31.19]

----------------------------------------------------------------------
FAIL: vmlistener_test.go:272: VMListenerTestParams.TestFailoverAcrossVmOnVsan

vmlistener_test.go:277:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420366000), Stderr:[]uint8(nil)} ("exit status 1")
... CRITICAL:root:Exception:No module named esxcli.Session
CRITICAL:root:Traceback (most recent call last):
   File "/bin/esxcli", line 53, in <module>
    from vmware.esxcli.Session import Session, SessionOptions, IsInVisor, \
 ImportError: No module named esxcli.Session
```

**Comment by govint** [comment]
https://ci.vmware.run/vmware/docker-volume-vsphere/1652 seems to have failed for a different reason, admin CLI didn't return the name of the VM thats attaching the independent disk. That happened because the tests are using the _shortls_ option thats available only via esxcli and not the admin CLI. Will open a separate issue to fix that.

**Comment by govint** [comment]
Pls. ignore last statement in my earlier update, on any ESX host the esxcli python packages are located at /lib64/python3.5/site-packages/vmware/esxcli. The session package is located here. Unless the ESX install is broken this error "No module named esxcli.Session" shouldn't arise.

@shuklanirdesh82, @ashahi1 if this issue recurs then can you'll check the CI host if the above folder is present and has the files as listed below,
/lib64/python3.5/site-packages/vmware/esxcli] ls
Formatters.pyc  Session.pyc     __init__.pyc

Unless the install is corrupt likely this error shouldn't happen. Please collect vmkernel.log if the issue recurs

**Comment by govint** [comment]
Missed to mention, this issue needs live debugging of the ESX host used for CI if the issue repros. Let me know host access details if the issue happens.

**Comment by govint** [comment]
Running a config init and config remove in a loop from the guest to the ESX to run the esxcli command, don;t see the issue reported here. Restarted hostd during the loop, no repro still.

**Comment by govint** [comment]
This is confirmed to be an external error and will be resolved later. For now lets revert back to using the vmdkops_admin CLI for the E2E tests. 

I'll post a PR to fix this.

Users can still use esxcli on the ESX host to run _guestvol_ commands.

**Comment by govint** [comment]
This is an external issue, but I'm going to hold off reverting to using the admin CLI unless the issue becomes a frequent observation in CI. Right now it happens one off.

**Comment by govint** [comment]
@ashahi1, @shuklanirdesh82 pls. let me know if @pshahzeb earlier change needs to be reverted. The current code is the way forward and reverting and re-adding the changes later looks unnecessary If the internal issue doesn't have any fix in the near term then I'll revert some of the changes and leave it that way for the e2e tests. How frequent is this issue observed.

**Comment by shuklanirdesh82** [comment]
@govint The reported issue was observed 1 failed occurrence out of 10 runs. As you mentioned at https://github.com/vmware/docker-volume-vsphere/issues/1869#issuecomment-340439803 being an external issue, we will bring it back if occurs more frequest to revert **Test** changes to use *ADMIN_CLI* instead of *esxcli*. I am dropping from *Ironman* sprint by marking *P1*

**Comment by shuklanirdesh82** [comment]
this was not reproduced so closing this now .. we shall reopen when it occurs again.
