### ISSUE TITLE
Volume date incorrect for a vfile volume

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1870]
Created a volume via the vfile driver and it created the volume, inspect shows in correct date though.

docker plugin ls
ID                  NAME                DESCRIPTION                           ENABLED
49d7cc1ded23        vsphere:latest      VMWare vSphere Docker Volume plugin   true
84b927e50e98        pivot:latest        VMWare vFile Docker Volume plugin     true

docker volume create -d pivot fvol2
fvol2

docker volume inspect fvol2
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z", <-------------
        "Driver": "pivot:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vfile/fvol2/",
        "Name": "fvol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Clients": null,
            "File server Port": 0,
            "Global Refcount": 0,
            "Service name": "",
            "Volume Status": "Ready"
        }
    }
]

root@sc-rdops-vm02-dhcp-52-237:/vol/docker# date
Thu Sep  7 03:13:33 PDT 2017

**Comment by lipingxue** [comment]
Hi Govindan,
  Have you seen this with the top of the tree? I cannot reproduce it with the top of the tree.
1.  create a volume using vfile plugin
```
vmware@ubuntu16:~$ docker volume create --driver=vfile --name=vol2
vol2
vmware@ubuntu16:~$ docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      InternalVolspace vol5@vsanDatastore
vsphere:latest      InternalVolspace vol6@vsanDatastore
vsphere:latest      InternalVolspace vol7@vsanDatastore
vsphere:latest      InternalVolspace vol8@vsanDatastore
vsphere:latest      _vF_vol1@vsanDatastore
vsphere:latest      _vF_vol2@vsanDatastore
vsphere:latest      abc def@vsanDatastore
vsphere:latest      testvol1@vsanDatastore
vfile:latest        vol1
vfile:latest        vol2

```
2. inspect the volume, no field ""CreatedAt" is displayed
```
vmware@ubuntu16:~$ docker volume inspect vol2
[
    {
        "Driver": "vfile:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vfile/vol2/",
        "Name": "vol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Clients": null,
            "File server Port": 0,
            "Global Refcount": 0,
            "Service name": "",
            "Volume Status": "Ready"
        }
    }
]

```

3. inspect the internal volume
```
vmware@ubuntu16:~$ docker volume inspect _vF_vol2
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/_vF_vol2/",
        "Name": "_vF_vol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "80MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Thu Sep  7 20:21:31 2017",
            "created by VM": "node01",
            "datastore": "vsanDatastore",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]

```
Please let me know if you still can reproduce it with top of the tree.

**Comment by lipingxue** [comment]
@govint

**Comment by govint** [comment]
I installed the vFile:latest via docker plugin install, not the ToT.  If its solved in the current code then this should be closed.
