### ISSUE TITLE
Investigate possibility to use systemd to manage ETCD services

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1873]
Currently vFile plugin manage ETCD services by os/exec and Process.Kill():
```
        cmd := exec.Command("/bin/etcd", lines...)
        err := cmd.Start()
```
```
        // stop ETCD process
        if err := e.etcdCMD.Process.Kill(); err != nil {
                log.Errorf("Failed to stop ETCD process. Error: %v", err)
                return
        }
```
This requires the plugin to handle the ETCD data directory clean up and so on.
Using systemd to manage ETCD services should be able to achieve better resource allocation automatically.

**Comment by shuklanirdesh82** [comment]
mustfix for atleast investigation task

**Comment by luomiao** [comment]
docker plugins are using alpine as the base image. Alpine uses openRC to start init services. OpenRC uses shell scripts to start ETCD. In this case, there is no difference to start ETCD as a process. Furthermore we will have the ETCD data-dir be persistent after node is rebooted. Thus there is no need to start ETCD as an init service.
