### ISSUE TITLE
Add warning during installation when users are using a wrong docker version 

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1874]
vFile plugin requires docker version higher or equal to 17.06.
With docker 17.03, removing vFile plugin (or other plugins) will result failure with the rest of the plugins.
Since we won't be able to do anything when the plugin is deleted, at least we should print out some warning message during the installation, if the docker version does not meet the requirement.

**Comment by shuklanirdesh82** [comment]
nice to have for vFile beta release (improves usability)

**Comment by luomiao** [comment]
Closed by #2014
