### ISSUE TITLE
Resize volume

### ISSUE THREAD

**Issue by urkl** [vmware/docker-volume-vsphere#1876]
Hi.

Is there any procedure about resizing vsphere volume mounted to container?

**Comment by govint** [comment]
@urkl, no there is no way resize a volume mounted to a container. Nor is it feasible, presently, to resize a volume as Docker volume plugin API doesn't allow modifying properties for an existing volume.  Can you elaborate the use case you have in mind for this ask.

**Comment by urkl** [comment]
@govint, thanks for replay. We have containerized process for storing some small images to persistent volume. And of course, we run out of space.

**Comment by govint** [comment]
Closing this issue as there is no way presently to support volume resize. Will open a separate issue to investigate options to resize a volume via the admin-cli.

**Comment by govint** [comment]
@urkl, just curious, does it help to create a thin volume of a _large_ capacity (say a 1TB volume) and use that for your usecase? The storage is anyway allocated as needed and  most likely the volume won't need to be resized over time. Resizing a volume entails extending the partition or creating a new partition and formatting it, which can be avoided with a large thin disk.

**Comment by urkl** [comment]
@govint  yes we were considering this option, but what when storage gets over 1T...
Our solution is creating storage pool in our service.
