### ISSUE TITLE
Add Table of Contents for Contributing.md

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1884]
It's getting too big.

**Comment by shuklanirdesh82** [comment]
It is nice to have; adding mustfix (can be adjusted further .. it is trivial task though)

**Comment by tusharnt** [comment]
Can we please take care of this?

**Comment by shuklanirdesh82** [comment]
Sure, @ashahi1 Please send out the PR.

**Comment by ashahi1** [comment]
Review is out #2015

**Comment by ashahi1** [comment]
Fixed as part of #2015
