### ISSUE TITLE
Support resizing a vDVS volume

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1891]
We have had the request from users to be able to resize a vDVS volume, the most recent of which indicated a use case where vDVS volume was itself used to store images. This and more use cases seem to make it useful to support the option to resize via the admin CLI (for now) till docker/CSI enables this feature (if they do). The resize itself is done with vmkfstools -X.

Setting as a P2 for now, can be prioritized later.

**Comment by shuklanirdesh82** [comment]
> We have had the request from users to be able to resize a vDVS volume

Adding mustfix keyword to discuss further with @shaominchen @tusharnt @govint

**Comment by govint** [comment]
One more option is to do a _docker volume create -d vsphere <volname> -o size=<new size>, recreate=true_. Here, the plugin will expect the volume to exist, per the flag _recreate=true_ and will extend the existing disk and update the filesystem on it as well to account for the new volume size.

Only volume extend will be supported, volume size reduction will not be allowed.

Let me post a PR with this change. I don't believe admin CLI needs changes for this.

**Comment by tusharnt** [comment]
@govint to find out whether there is an existing feature request against docker.

**Comment by govint** [comment]
When docker supports it or really when CSI includes it.
