### ISSUE TITLE
vFile:  GC should not remove orphan internal volume

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#1897]
Currently, GC removed orphan service and orphan internal volume. It will cause some issue.
For example:  two ESX shared 1 datastore, one each ESX, we have a swarm cluster running.  When the first swarm cluster create a volume "aaa", an internal volume "_vf_aaa" will be created on the shared datastore. Then for the second swarm cluster, only internal volume "_vf_aaa" is visible, and it think "_vf_aaa" is an orphan volume and try to delete volume "aaa", which is wrong.

So we should remove the code to cleanup orphan internal volume.

**Comment by shuklanirdesh82** [comment]
mustfix for vFile beta release
