### ISSUE TITLE
vFile: when failed to create the internal vDVS volume, should not create a local volume instead

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1903]
In current version of vFile plugin, when there is an error creating the internal vDVS volume, such as, the maximum supported number of vDVS volumes is reached, vFile plugin will go ahead create a local volume instead.
This is not an expected action since users are expecting the volumes from required internal plugin only. A local volume instead of vDVS volume can result in unexpected errors or results with user application.
vFile plugin should be updated to return error only without creating the local volume.

**Comment by shuklanirdesh82** [comment]
correctness issue so adding `mustfix` kw.

**Comment by luomiao** [comment]
This is not valid. The local volumes are created when "docker run" with an non-existing volume. This is an expected action.
