### ISSUE TITLE
vfile: update documentation with supported limits (derived from performance and stress testing)

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1910]
We have done several performance and stress tests for vFile plugin at: https://github.com/vmware/docker-volume-vsphere/issues/1806

We need to update those results in userguide accordingly.

**Comment by shuklanirdesh82** [comment]
Adding `mustfix` kw: we are planning vFile beta and this is nice to have document requirement.

**Comment by luomiao** [comment]
Close since not necessary. Will refer #1806 for previous testing result.
