### ISSUE TITLE
Enable CI Test for vFile plugin: resolving current bugs

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1911]
https://ci.vmware.run/vmware/docker-volume-vsphere/1625

Basic tests for vFile CI testing failed with error:
FAIL: basic_vfile_test.go:80: BasicVFileTestSuite.TestVolumeLifecycle

basic_vfile_test.go:91:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc42013afa0), Stderr:[]uint8(nil)} ("exit status 125")
... e09e2b3c49ece11dbd558668bf82806eb6dc41e53cbf8e4dc66425020e41c87c
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/732e5ae63625543d6ea2580ce94280030eb54d452d777bf394e35fc8aa235f0b/rootfs/mnt/vfile/vfilevolume253398': VolumeDriver.Mount: Failed to blocking wait for Mounted state. Error: Timeout reached; BlockingWait is not complete.

Need triage reason.

**Comment by shuklanirdesh82** [comment]
Adding `mustfix` kw: must need for kubecon release

**Comment by luomiao** [comment]
Multiple issues resulted in the error.

1. Testbed is comparably slow. As a result, the tasks started by a file server service may be failed due to slow node.
2. For some unknown reason, tasks also can be rejected by one of the ubuntu node. 
3. When some of the tasks are rejected/failed, the current function to check if file server is already running has a problem. It will return false as long as one of the tasks **is not running**. But in this case, since we only have a single container for this file service, it should return true as long as one of the tasks **is running**.
