### ISSUE TITLE
Issue to add a test for validating RPM/DEB based install

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1915]
https://github.com/vmware/docker-volume-vsphere/issues/1166#issuecomment-333604678

**Comment by govint** [comment]
The docs were updated earlier that package based installs are not supported any more and neither does docker support running plugins installed as packages as they need to be managed plugins. Do we still need to test that package installs work?

**Comment by shuklanirdesh82** [comment]
closing as per previous comment.
