### ISSUE TITLE
Sharing volumes between Docker Hosts on different datastore (DEFAULT tenant)

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#193]
Support a create time option to allow a volume to be attached by more than one VM. Multi-writer vmdks can be shared across VMs and needed if we expect to support that workload.

**Comment by dack** [comment]
At the very least, the readme/wiki should make it clear that a volume can only be mounted on a single VM at a time.

**Comment by bk1te** [comment]
Hi. What if I would like to create volume, accessible on all nodes across swarm cluster? So that only one container would be attached. Swarm manager would decide on what node to run container.

**Comment by govint** [comment]
That would be possible, a volume created on shared storage accessible on all nodes. One container can attach that volume from any host in the cluster.

**Comment by bk1te** [comment]
I created volume on shared storage, but it is visible only for node on which i created volume.

**Comment by govint** [comment]
Can you list the steps to create the volume and the results of "docker volume ls" on both the creating and non-creating nodes.

Can you also give the output of "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls" on both the nodes.

**Comment by bk1te** [comment]
node-1: docker volume create --driver=vmdk --name=Test@store-1 -o size=10Gb -o diskformat=thin
node-1: vmdk Test@store-1
host-1:  
Volume   Datastore    Created By VM    Created   Attached   Policy    Capacity   Used    Disk Format   
Test         store-1        node-1                <date>    detached  N/A      10GB         145Mb  thin               ext4 read-write independent_persist
node-2:  empty
host-2: empty
Sorry can`t copy paste directly

**Comment by govint** [comment]
@bk1te can you also show the disk config from the two hosts and show the
details of store-1 on both hosts.

**Comment by bk1te** [comment]
@govint can you link me what commands to execute

**Comment by pdhamdhere** [comment]
@bk1te I assume`store-1` accessible to ESX Hosts where VMs are running. Have you installed on VIB on all ESX Hosts where Docker VMs are running?

Is node-1 & node-2 VM on same datastore? 

Can you paste output of following command from node-1 and node-2 vm;
`docker volume create --driver=vmdk --name=Test@badDS`

We are also available on Slack;
`https://vmwarecode.slack.com/messages/docker-volume-vsphere/`

**Comment by govint** [comment]
@bk1te, please use "esxcfg-scsidevs -m" and "esxcfg-scsidevs -l" on both the ESX hosts to which the volume has been shared. Pls. post the output from both commands on both hosts.

**Comment by bk1te** [comment]
Running command "docker volume create --driver=vmdk --name=Test@badDS" on both VM returned:
Error response from daemon: create Test@badDS: VolumeDriver.Create: Server returned an error: TypeError('can only join an iterable',)

**Comment by govint** [comment]
@bk1te, is this a different problem, in which case suggest making a new issue. In fact two issues perhaps , one for the earlier issue where volumes aren't visible on two nodes and this one.

**Comment by bk1te** [comment]
it is not an issue badDS doesnot exist

**Comment by bk1te** [comment]
esxcfg-scsidevs -m on both esx hosts returned:
naa.<id> /vmfs/devices/disks/naa.<id> <same uuid> 0 store-1

esxcfg-scsidevs -l on both esx hosts returned:
naa.<id>
 Device Type: Direct-Access
 Size: 2TB
 Display Name: HP iSCSI Disk(na.<id>)
 Multipath Plugin: NMP
 Console Device: /vmfs/devices/disks/naa.<id>
 Vendor: HP Model: MSA Revis: M111
SCSI Level: 5 Is Pseudo: false Status: on
Is RDM Capable: true Is Removable: false
Is Local: false is SSD: false
VAAI Status: unknown

**Comment by msterin** [comment]
@bk1te write
> it is not an issue badDS does not exist

It is a bug somewhere in our vmdk_ops service - this command is supposed to print something like "badDS datastore is not found; available datastores are : <list>".

There seems to be something special about about your datastores list that exposes the bug. Would it be possible to list the datastores ? `ls -l /vmfs/volumes`  ?

**Comment by bk1te** [comment]
@msterin on "docker volume create --driver=vmdk --name=Test@badDS"
Unhandled Exception: Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1373, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 746, in executeRequest
    %(datastore, ", ".join(get_datastore_names_list), vm_datastore))
  TypeError: can only join an iterable

**Comment by shuklanirdesh82** [comment]
@bk1te 

>Unhandled Exception: Traceback (most recent call last):
File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1373, in execRequestThread
opts=opts)
File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 746, in executeRequest
%(datastore, ", ".join(get_datastore_names_list), vm_datastore))
TypeError: can only join an iterable

It is being tracked at #817.

**Comment by shuklanirdesh82** [comment]
@bk1te : can you please try following what @msterin is asking?

> Would it be possible to list the datastores ? ls -l /vmfs/volumes ?

**Comment by bk1te** [comment]
I`ll try.
There 15 directories like <uuid> and 11 symlinks to directories
When I try to list <uuid> directories which does not have symlinks I got 
ls: <uuid>: No such file or directory

**Comment by govint** [comment]
@bk1te, can you also confirm that both VMs are on the same datastore. And can you upload /var/log/vmware/vmdk_ops.log from both hosts.

1. Do "docker volume ls" on both nodes.
2. Upload /var/log/vmware/vmdk_ops.log from both nodes.

**Comment by bk1te** [comment]
esx1 esx2 both have access to shared datastore-0 on which I would like to create shareble disk
vm1 is on esx1 datastore-2
vm2 is on esx2 datastore-1

**Comment by bk1te** [comment]
@govint I can upload /var/log/vmware/vmdk_ops.log from both hosts but later

**Comment by bk1te** [comment]
Just posted here requested info
[esx-1-ls-vmfs-volumes.txt](https://github.com/vmware/docker-volume-vsphere/files/781222/esx-1-ls-vmfs-volumes.txt)
[esx-1-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/781221/esx-1-vmdk_ops.txt)
[esx-2-docker-volume-ls.txt](https://github.com/vmware/docker-volume-vsphere/files/781223/esx-2-docker-volume-ls.txt)
[esx-2-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/781220/esx-2-vmdk_ops.txt)
[esx-1-ls-vmfs-volumes-msa-2312i-docker-store-0.txt](https://github.com/vmware/docker-volume-vsphere/files/781219/esx-1-ls-vmfs-volumes-msa-2312i-docker-store-0.txt)
[esx-2-ls-vmfs-volumes.txt](https://github.com/vmware/docker-volume-vsphere/files/781224/esx-2-ls-vmfs-volumes.txt)
[esx-1-docker-volume-ls.txt](https://github.com/vmware/docker-volume-vsphere/files/781225/esx-1-docker-volume-ls.txt)
[esx-2-ls-vmfs-volumes-msa-2312i-docker-store-0.txt](https://github.com/vmware/docker-volume-vsphere/files/781226/esx-2-ls-vmfs-volumes-msa-2312i-docker-store-0.txt)

**Comment by bk1te** [comment]
Here is requested info
[esx-1-ls-vmfs-volumes.txt](https://github.com/vmware/docker-volume-vsphere/files/781241/esx-1-ls-vmfs-volumes.txt)
[Uploading esx-1-vmdk_ops.txt…]()
[esx-2-docker-volume-ls.txt](https://github.com/vmware/docker-volume-vsphere/files/781243/esx-2-docker-volume-ls.txt)
[esx-2-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/781242/esx-2-vmdk_ops.txt)
[esx-1-ls-vmfs-volumes-msa-2312i-docker-store-0.txt](https://github.com/vmware/docker-volume-vsphere/files/781244/esx-1-ls-vmfs-volumes-msa-2312i-docker-store-0.txt)
[esx-2-ls-vmfs-volumes.txt](https://github.com/vmware/docker-volume-vsphere/files/781245/esx-2-ls-vmfs-volumes.txt)
[esx-1-docker-volume-ls.txt](https://github.com/vmware/docker-volume-vsphere/files/781246/esx-1-docker-volume-ls.txt)
[esx-2-ls-vmfs-volumes-msa-2312i-docker-store-0.txt](https://github.com/vmware/docker-volume-vsphere/files/781247/esx-2-ls-vmfs-volumes-msa-2312i-docker-store-0.txt)

**Comment by bk1te** [comment]
[esx-1-vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/781281/esx-1-vmdk_ops.txt)

**Comment by pdhamdhere** [comment]
@bk1te Thanks for sharing logs. This is a regression. We are working on emergency patch. Stay tuned.

**Comment by shuklanirdesh82** [comment]
@bk1te Please give a shot with an emergency path for the reported issue. You may find at https://github.com/vmware/docker-volume-vsphere/releases/tag/0.11.1

Please feel free to reach us out, if you have any concern.

Thanks!
