### ISSUE TITLE
Swarm test fail intermittently against ESX 6.0 setup

### ISSUE THREAD

**Issue by luomiao** [vmware/docker-volume-vsphere#1946]
During the CI, there is a race condition which results in the failure of swarm test:
```
2017/10/21 01:59:23 Checking running containers for docker service [swarm_test_service_1048760] on docker hosts: [192.168.31.241 192.168.31.163 192.168.31.195]
2017/10/21 01:59:23 Sleep for 5 seconds
2017/10/21 01:59:29 Sleep for 5 seconds
2017/10/21 01:59:35 Sleep for 5 seconds
2017/10/21 01:59:41 Sleep for 5 seconds
2017/10/21 01:59:47 Sleep for 5 seconds
2017/10/21 01:59:52 Sleep for 5 seconds
2017/10/21 01:59:58 Sleep for 5 seconds
2017/10/21 02:00:04 Sleep for 5 seconds
2017/10/21 02:00:10 Sleep for 5 seconds
2017/10/21 02:00:16 Sleep for 5 seconds
2017/10/21 02:00:21 Sleep for 5 seconds
2017/10/21 02:00:27 Sleep for 5 seconds
2017/10/21 02:00:33 Sleep for 5 seconds
2017/10/21 02:00:39 Sleep for 5 seconds
2017/10/21 02:00:45 Sleep for 5 seconds
2017/10/21 02:00:50 Sleep for 5 seconds
2017/10/21 02:00:56 Sleep for 5 seconds
2017/10/21 02:01:02 Sleep for 5 seconds
2017/10/21 02:01:08 Sleep for 5 seconds
2017/10/21 02:01:13 Sleep for 5 seconds
2017/10/21 02:01:19 Sleep for 5 seconds
2017/10/21 02:01:25 Sleep for 5 seconds
2017/10/21 02:01:31 Sleep for 5 seconds
2017/10/21 02:01:37 Sleep for 5 seconds
2017/10/21 02:01:42 Sleep for 5 seconds
2017/10/21 02:01:48 Sleep for 5 seconds
2017/10/21 02:01:54 Sleep for 5 seconds
2017/10/21 02:02:00 Sleep for 5 seconds
2017/10/21 02:02:06 Sleep for 5 seconds
2017/10/21 02:02:11 Sleep for 5 seconds
2017/10/21 02:02:16 Destroying volume [swarm_test_volume_974966]

----------------------------------------------------------------------
FAIL: swarm_test.go:96: SwarmTestSuite.TestFailoverAcrossSwarmNodes

swarm_test.go:115:
    c.Assert(status, Equals, true, Commentf("Container %s is not running", s.serviceName))
... obtained bool = false
... expected bool = true
... Container swarm_test_service_1048760 is not running
```

This error happens even before the failover tests are started.
Need to root the reason and found a solution.

A sample log:
https://ci.vmware.run/vmware/docker-volume-vsphere/1679

**Comment by ashahi1** [comment]
We are seeing this intermittent failure on CI when the swarm master is not able to communicate to the worker nodes.  Worker nodes are listed as "down" and hence, swarm master is not able to execute services on that particular node and as a result test fails. 
VMs are up and running but for some reason, those nodes are listed as down for swarm cluster.

After one of the failed runs, following is the status of the swarm cluster. We can clearly see that both the nodes are down.

```
root@photon-msiZGdRAu [ ~ ]# docker node ls
ID                           HOSTNAME          STATUS  AVAILABILITY  MANAGER STATUS
2t6t0s5wbukdw5q8oix9zetmg *  photon-msiZGdRAu  Ready   Active        Leader
fczni2rxl4x9o4w8sj3ao0cyh    ubuntu            Down    Active
vvkmvc9brmo6wwgbkxafwj159    ubuntu            Down    Active
root@photon-msiZGdRAu [ ~ ]#
```

**Comment by tusharnt** [comment]
@ashahi1 to trigger multiple iterations of vDVD swarm tests to get a repro so that @govint can triage it further.

**Comment by ashahi1** [comment]
@govint Can you please take a look at this issue. I have uploaded all the logs.

Failed CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1679

Swarm on 6.0 ESX has one master node and two worker nodes.
All the nodes with swarm were up before the e2e tests started on 6.0 ESX. 

But sometime during execution of e2e-tests, both the worker nodes went down - Nodes are still up and running but it's just that nodes show-up as down on swarm master node. 
And a result swarm test failed.

Logs:
[Master-241-vDVS.txt](https://github.com/vmware/docker-volume-vsphere/files/1412883/Master-241-vDVS.txt)
[Master-241-docker.txt](https://github.com/vmware/docker-volume-vsphere/files/1412882/Master-241-docker.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1412884/vmdk_ops.txt)
[Worker1-195-docker.txt](https://github.com/vmware/docker-volume-vsphere/files/1412885/Worker1-195-docker.txt)
[Worker1-195-vDVS.txt](https://github.com/vmware/docker-volume-vsphere/files/1412886/Worker1-195-vDVS.txt)
[Worker2-163-docker.txt](https://github.com/vmware/docker-volume-vsphere/files/1412887/Worker2-163-docker.txt)
[Worker2-163-vDVS.txt](https://github.com/vmware/docker-volume-vsphere/files/1412888/Worker2-163-vDVS.txt)

**Comment by shuklanirdesh82** [comment]
We need some more information:
- test suite and test name (failed scenario information)
- how frequently this is occurring? (fail times/ #of attempts)
- what is the reason behind worker going down? (known docker issue ??, docker version adds any mix?? etc.)
- need to identify where is this interop causing issue.

/CC @tusharnt @ashahi1

**Comment by shuklanirdesh82** [comment]
@govint  Please adjust the label after your analysis, currently it has `test` and `test-infrastructure` ( kind of confusing)

**Comment by ashahi1** [comment]
@govint 

In reply to this comment: https://github.com/vmware/docker-volume-vsphere/issues/1946#issuecomment-339740226

**Note:** When the tests started on 6.0, all the docker nodes were showing as - ```Ready and Active``` 
1. Test suite 
    SwarmTestSuite
2. Test name 
    TestFailoverAcrossSwarmNodes

**Note:** Swarm worker nodes were showing as - ```Down and Active``` even before swarm test had started. So some test even before the above mentioned test might be causing the issue.

3. How frequently this is occurring? 
    Failed twice in last three runs
4. What is the reason behind worker going down? (known docker issue ??, docker version adds any mix?? etc.)
  Not sure if it a docker issue since we only see this issue on 6.0 ESX. We never hit this issue on 6.5 ESX.


Please take a look at the following information and let me know if you need anything more. Logs have already been uploaded.

**Comment by govint** [comment]
Looking at the logs, question also is whether before the swarm test were there any tests that restart docker, which may cause the master to mark those as down. Let me check.

**Comment by shuklanirdesh82** [comment]
it turned out CI testbed issue .. @ashahi1 has fixed the testbed and reran the failure builds. 

re-ran of https://ci.vmware.run/vmware/docker-volume-vsphere/1694 passed so closing this now.
