### ISSUE TITLE
Upgrading docker version in CI testbeds

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#1951]
Currently we have two setups with 17.06 and 17.03.02 docker. 

Docker stable release 17.09.0-ce (2017-09-26) is out and 17.03.02 should be upgraded to 17.09 (TOT - https://docs.docker.com/release-notes/docker-ce/)

/CC @tusharnt

**Comment by ashahi1** [comment]
Upgraded docker version on Photon VMs to  17.09.0-ce. Closing this issue.
