### ISSUE TITLE
Support Storage vMotion while vDVS volumes are attached

### ISSUE THREAD

**Issue by madjam002** [vmware/docker-volume-vsphere#1977]
I'm aware that currently Storage vMotion isn't supported by this plugin and results in strange behaviour, but it would be nice if this could be supported somehow?

I'm not sure how it would work with volumes created on specific datastores (e.g `MyVolume@datastore1` - `datastore1` would be available on one host but not another) but for those with no datastore constraint (e.g just `MyVolume`) this currently resolves to the same datastore where the current VM resides, so it could theoretically be migrated to the same target datastore for the VM during Storage vMotion?

At the moment my workflow for executing a Storage vMotion is to stop all running containers on the host so that the vDVS disks are detached from the VM, run Storage vMotion on the VM, manually move the VMDKs for the vDVS disks from within the vSphere Client and then start the containers again, but it would be nice if the containers could stay running somehow.

Thanks for the great work on this project :smile:

**Comment by govint** [comment]
@madjam002, thanks for letting us know of your requirement, I'm curious why the VDVS volumes would need to be migrated. Storage vmotion applies to VMs where the VM's VMDKs (dependent disks) are migrated to a target datastore. The VDVS volumes are completely separate from VM disks and are managed wholly by the plugin and via the admin CLI on the ESX host. The datastores where the VDVS volumes get placed is also related but not limited to the datastore where the VM is located (although that's the default location).

I'd like to know the use case that requires migrating the VDVS volumes to a different location. The VDVS volumes are all tracked in a config database (if initialized) and that data would go stale if the volumes are migrated using the vSphere client.

**Comment by madjam002** [comment]
@govint When I attempted a Storage vMotion earlier I noticed that the vDVS VMDKs were migrated but to the VM folder on the target datastore, not the `dockvols` directory.

My use case is being able to vMotion VMs off a host when it needs to be taken down for maintenance and currently it doesn't seem to be possible to migrate VMs with running Docker Containers with 100% uptime to another host.

Maybe there's another way to do this that I'm missing?

**Comment by govint** [comment]
@madjam002, at this point in time VM migration scenarios aren't supported with VDVS disks attached. One option is to stop the workload and then migrate the VM. Assuming a docker swarm, another option is to drain services (containers) deployed to the VM first (via _docker node_ command) and then migrate the VM. Post migrate, the VM would be made active to redeploy services.

**Comment by govint** [comment]
Closing this as presently we don't support  migration scenarios for container volumes, plus, should also rethink if migration really makes sense with container workloads. The VM is very much part of the infrastructure and the workload (container) migrates across VMs. Balancing of volumes across (not supported yet) is something that can be addressed as also being able to migrate container volumes over datastores. Migration of VMs really doesn't apply, if anything

1. Simply drain the node (VM) of container workloads.
1. Perform maintenance of the VM (migrate).
1. Resume scheduling workloads to the node (VM).

**Comment by madjam002** [comment]
@govint Can this not stay open? One of the benefits of vMotion is that you can reschedule a VM without downtime, and currently there isn't a way to migrate a VM with associated containers without downtime? The solution you proposed involves stopping the container on the VM.

**Comment by govint** [comment]
@madjam002, this is an enhancement to how migration of VMs handle virtual disks and I already had an internal issue to address that on the ESX platform. But that will be addressed in subsequent releases of the ESX software. This issue need not be kept open as such. That said, draining containers off a VM only implies that those will now be scheduled on other VMs on the ESX hosts.or the same ESX host as the case may be. The containers shouldn't have to be stopped.

**Comment by madjam002** [comment]
@govint Ah that's great so a future version of ESX will migrate attached virtual disks to the right location when doing vMotion?

And by draining containers off a VM still means that the container will be stopped and started on a different VM. With some container workloads which require persistent storage will result in downtime when doing this.

**Comment by govint** [comment]
@madjam002, yes, thats the current idea to be able to address the needs of container workloads during migration.

**Comment by govint** [comment]
FWIW, opened https://github.com/moby/moby/issues/35715 to allow an app to shutdown gracefully on container stop/pause so the app gets a chance to bring its data to a sane state before exiting or pausing. Can even allow the app to implement a hand-off to another instance if needed. Helps when instances are drained off a docker host for example.
