### ISSUE TITLE
Test compatibility with Photon OS 2.0

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1979]
Based on the results of the investigation, we need to update our customer facing documentation.

Useful links -
- https://blogs.vmware.com/cloudnative/2017/11/01/version-2-0-project-photon-os/
- https://www.virtuallyghetto.com/2017/11/workarounds-for-deploying-photonos-2-0-on-vsphere-fusion-workstation.html

**Comment by ashahi1** [comment]
Ran all the end-to-end for vDVS against Photon 2.0 and all tests finished successfully. No issues were found while running theses tests with Photon 2.0.

Got the Photon 2.0 from the link - https://github.com/vmware/photon/wiki/Downloading-Photon-OS
