### ISSUE TITLE
WIndows E2E tests throws exception stack in CI

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1980]
The below issue is seen in CI run https://ci.vmware.run/vmware/docker-volume-vsphere/1717.

@ashahi1 can you confirm that the windows e2e tests were verified to run ok prior to enabling on master (it may have been but the below issue is there). Also, can you say what version of Go is on the Windows VM where the tests are running.

Preferrably, the Windows e2e tests should have been verified prior to merge in the master.

2017/11/07 12:25:21 VM name is: windows
2017/11/07 12:25:21 START: BasicTestSuite.TestVolumeLifecycle
2017/11/07 12:25:21 Creating volume [basictestsuite.testvolumelifecycle_volume_294584] on VM [192.168.31.210]
panic: test timed out after 50m0s <---------

syscall.Syscall6(0xf7, 0x1, 0xdce, 0xc42001e880, 0x1000004, 0x0, 0x0, 0x5a69a0, 0xc420057568, 0x4320ce)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420090690, 0x5ee050, 0xc4200269a0, 0xc4200ac160)
	/usr/local/go/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc420090690, 0x0, 0x40ef3e, 0xc4200aa100)
	/usr/local/go/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc420090690, 0xc420057670, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:49 +0x2b
os/exec.(*Cmd).Wait(0xc4200269a0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:434 +0x6d
os/exec.(*Cmd).Run(0xc4200269a0, 0xc42001a8c0, 0x20)
	/usr/local/go/src/os/exec/exec.go:279 +0x48
os/exec.(*Cmd).CombinedOutput(0xc4200269a0, 0xc4200ac060, 0xc4200577d8, 0x3, 0x3, 0xc42008a3c0)
	/usr/local/go/src/os/exec/exec.go:494 +0x140
github.com/vmware/docker-volume-vsphere/tests/utils/ssh.InvokeCommand(0xc420012268, 0xe, 0xc42001cc00, 0x60, 0x30, 0xc42001cc00, 0x60, 0x5d6d8e)
	/drone/src/github.com/vmware/docker-volume-vsphere/tests/utils/ssh/ssh_win.go:48 +0x2a7
github.com/vmware/docker-volume-vsphere/tests/utils/dockercli.CreateVolume(0xc420012268, 0xe, 0xc4200900c0, 0x30, 0x1, 0x7f7c8c1fac80, 0x450360, 0x7f7c8c1f64b0)
	/drone/src/github.com/vmware/docker-volume-vsphere/tests/utils/dockercli/volumelifecycle.go:41 +0x198
github.com/vmware/docker-volume-vsphere/tests/e2e.(*BasicTestSuite).TestVolumeLifecycle(0xc420020120, 0xc42008a1e0)
	/drone/src/github.com/vmware/docker-volume-vsphere/tests/e2e/basic_test.go:84 +0xd2
reflect.Value.call(0x5a8540, 0xc420020120, 0xa13, 0x5d5c08, 0x4, 0xc420057f30, 0x1, 0x1, 0x6dc960, 0x5d0680, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x5a8540, 0xc420020120, 0xa13, 0xc420057f30, 0x1, 0x1, 0xc42008a2d0, 0xc4200316cf, 0x0)

**Comment by ashahi1** [comment]
@govint We haven't seen any issues with Windows plugin tests on CI. Most recent run on CI against master has all tests passed including windows tests:

https://ci.vmware.run/vmware/docker-volume-vsphere/1710

**Comment by shuklanirdesh82** [comment]
https://ci.vmware.run/vmware/docker-volume-vsphere/1722 and https://ci.vmware.run/vmware/docker-volume-vsphere/1723 are not showing any issue so closing this issue now.
