### ISSUE TITLE
Validate that vDVS works against VVol datastores

### ISSUE THREAD

**Issue by tusharnt** [vmware/docker-volume-vsphere#1995]
As per @cormachogan, this is an important use case.
@ashahi1,
We need to document the outcome of our investigation.

**Comment by tusharnt** [comment]
@ashahi1 can you please elaborate which basic scenarios you will validate against VVol datastores?

**Comment by ashahi1** [comment]
@tusharnt I plan to execute all end-2-end tests using VVOL datastores.

**Comment by shuklanirdesh82** [comment]
documentation PR is merged and one issue (https://github.com/vmware/docker-volume-vsphere/issues/1998) is raised so closing this one now as the testing task is done.
