### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by divyenpatel** [vmware/docker-volume-vsphere#2003]
- [x] Commands are not properly formatted on this page - http://vmware.github.io/docker-volume-vsphere/documentation/admin-cli.html#create
- [x] ~The VDVS documentation doesn't say explicitly that it cannot manage heterogeneous docker hosts. For example, I might have windows docker hosts and Linux docker hosts managed by a single ESX host. so any volumes created on windows host will fail to mount on Linux hosts.~

[ @ashahi1 ] It is already documented at http://vmware.github.io/docker-volume-vsphere/documentation/faq.html#can-i-migrate-data-between-linux-and-windows-containers

- [x] https://github.com/vmware/docker-volume-vsphere/blob/master/docs/external/Interop.md is not linked anywere on the external documentation site. HTML file is located at https://github.com/vmware/docker-volume-vsphere/blob/gh-pages/documentation/Interop.html. We should link this on the sidebar.

[ @shuklanirdesh82 ] It was fixed through https://github.com/vmware/docker-volume-vsphere/pull/2011

- [x] Fix instructions on How to install and use the driver? - http://vmware.github.io/docker-volume-vsphere/documentation/vfile-plugin.html#how-to-install-and-use-the-driver Lets not refer to any md file in the documentation. Direct link to generated html file would be good.

**Comment by divyenpatel** [comment]
- [ ] apply formatting for commands at the end of the page - http://vmware.github.io/docker-volume-vsphere/documentation/docker-stacks.html

**Comment by prashima** [comment]
**Correctness**

- [ ] http://vmware.github.io/docker-volume-vsphere/documentation/docker-volume-cli.html mentions ’The docker volume commands are completely supported by vDVS plugin.’ and in the same page it is mentioned that prune volume command is not supported.

- [ ] http://vmware.github.io/docker-volume-vsphere/documentation/docker-volume-cli.html has link Storage policy based management that takes user to this page http://vmware.github.io/policy-based-management.html, which doesn’t really show any details about policy based management. 

- [ ] http://vmware.github.io/docker-volume-vsphere/documentation/tenancy.html#admin-cli has link for ‘Design Spec for tenancy’ that leads to 404 https://github.com/vmware/docker-volume-vsphere/blob/master/docs/misc/docker-volume-auth-proposal.v1_2.md. The link doesn’t seem useful for documentation.

**Typos & formatting**

- [ ] The docker plugin will look for existing filesystesm -> filesystems http://vmware.github.io/docker-volume-vsphere/documentation/docker-volume-cli.html
- [ ] Formatting needs to be fixed at the bottom of this page http://vmware.github.io/docker-volume-vsphere/documentation/docker-stacks.html 

**Usage**
- [ ] From documentation it’s not clear that once created, vmgroup’s volume-maxsize and volume-totalsize can be updated later or not. If update is allowed what will happen to the existing volumes that doesn’t match those new restrictions.

- [ ] One simple example of for creating container with volume would be useful. None of the current examples demonstrate this usage: docker run -it --volume-driver=vsphere -v MyVolume@sharedVmfs-0:/vol1 --name ub ubuntu. Existing examples make use of docker compose only.

**Comment by ashahi1** [comment]
PR is merged. vDVS documentation is updated. Thanks Prashima and Divyen.
