### ISSUE TITLE
Prepare documentation for how to use offline depot for software deployment on ESX

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#202]
VC, image builder have options for how to include offline depots for software deployment for ESX. Include quick steps and references to documentation to github after testing.

**Comment by tusharnt** [comment]
@kerneltime can you please elaborate what you meant here? Is this issue still relevant?

**Comment by tusharnt** [comment]
Here's a blog that explains how to use ESXi image builder for deploying VIBs - https://blogs.vmware.com/vsphere/2012/04/using-the-vsphere-esxi-image-builder-cli.html

We need to provide concrete steps for installing vDVS VIB by following the above info.

**Comment by govint** [comment]
This is closed via #1596
