### ISSUE TITLE
Document the upper to lower case conversion of volume names in Windows 

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#2033]
Windows converts all names to lower case when using docker commands and this can create the types of issues as in #2006. While #2006 is fixed for the datastore name getting converted to lower case, the plugin has no way of figuring out the real volume name if the container volume name has a mix of upper and lower case letters. 

For example, creating two volumes like _Bvol_ and _bVol_ ends up creating a single volume _bvol_ on the backing storage since Windows converts both volume names to _bvol_. Hence on Windows at least the user should avoid using mixed case or upper case letters in the volume name.

PS C:\Users\root> docker volume create -d vsphere Bvol    

PS C:\Users\root> docker volume inspect bVol
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "C:\\Windows\\system32\\config\\systemprofile\\AppData\\Lo
cal\\docker-volume-vsphere\\mounts\\bvol\\",
        "Name": "bvol", <-----------------------
        "Options": {},
        "Scope": "global",                                                              "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "48MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Mon Dec 11 04:10:23 2017",
            "created by VM": "Windows-VM-1",
            "datastore": "vsanDatastore",
            "diskformat": "thin",
            "fstype": "ntfs",
            "status": "detached"
        }
    }
]

**Comment by shuklanirdesh82** [comment]
Yeah it is already documented for the windows plugin (FAQ page and known difference between linux plugin vs windows plugin)
