### ISSUE TITLE
Linux distro we need to support (TP, GA)

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#213]
(1) We need to sync the list below with  ViC "official tested" linux distro list , and finalize the list. 
Then the issue can be split in "support multipe Linux clients in test" and "test and make it work for xxx:

(2) Tentatively, at release TP and GA we need to support at least the following : 

TP (making code public) 
- [x] Ubuntu 14 , kernel 3.13 or up
- [x] Photon 

GA 
- [ ] RedHat Atomic
- [ ] Ubuntu 15 
- [ ] Ubuntu 16
- [ ] ? Snappy Ubuntu Core
- [ ] ? CoreOS
- [ ] ? Debian
- [ ]  ? OpenSuse

**Comment by justinclayton** [comment]
FYI, `ls /sys/bus/pci/devices/*/label` definitely doesn't work for RHEL/CentOS 7.x.

**Comment by msterin** [comment]
//CC @govint @kerneltime

**Comment by kerneltime** [comment]
Thanks @justinclayton we are expanding the support matrix and we will look into RHEL and CentOS.
Can you email us @ cna-storage@vmware.com with what you need supported for your environment to make sure we can get that out in our next release?
