### ISSUE TITLE
Review K8S needs and update design / protocol  / code to support it

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#27]
In preliminary discussions, we decide that we need a few simple fixes to the guest-host protocol to support K8S:
- allow "no volume formatting" option
- allow to choose a folder on datastore

We should review it again, get a list of changes and implement. 
We should do it earlier to allow the reuse of protocol and code.

**Comment by pdhamdhere** [comment]
K8S doesn't use vmdkops.
