### ISSUE TITLE
Document interop with vSphere features

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#270]
Investigate interop with vSphere features. Identify additional work required or document best practices. 
- [x] vSphere HA
- [x] vMotion, SvMotion, XvMotion
- [x] DRS
- [x] Storage DRS
- [x] Snapshots
- [x] Site Recovery Manager
- [x] Host Maintenance mode
- [x] DS Maintenance mode
- [x] VM Lifecycle (Poweroff | Reset | Suspend | Resume)
- [ ] Anything else? Please append here.

**Comment by shaominchen** [comment]
Per offline discussion, we will look at this post GA.

**Comment by ashahi1** [comment]
Bugs Filed:
#1651
#1618
#1638
#1649

**Comment by tusharnt** [comment]
The only thing remaining here is to document that SRM support is currently broken. @ashahi1  to file an issue. Team is actively looking into the failure.

**Comment by ashahi1** [comment]
All the listed Interop VC features have been tested with vDVS and issues discovered during testing have been updated to interop.md file. Closing this PR as information has also been copied over to gh-pages branch as well.
