### ISSUE TITLE
VIB signing

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#273]
ESX VIB is not signed. Need to setup process to sign VIB automatically for each tagged release. 

~~RPM and Deb files also need signing.~~ Please see https://github.com/vmware/docker-volume-vsphere/issues/273#issuecomment-289175029

**Comment by kerneltime** [comment]
We have a solution for signing the artifacts for the upcoming beta. A more formal workflow is being worked on for GA. Once the binaries are built, I will upload the signed binaries to github releases.

**Comment by pdhamdhere** [comment]
Let's keep it open until we figure out a process to sign binaries.

**Comment by shuklanirdesh82** [comment]
starting vDVS 0.13 we are recommending to use managed docker volume plugin by pulling from docker store so updating the title to have signing only for VIB.

**Comment by shuklanirdesh82** [comment]
when the artifacts is ready for VIB, it will be signed by vmware EE team. Following each releases, signed VIB should be uploaded to bintray for download.
