### ISSUE TITLE
Support Read only volumes?

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#274]
This came up during meeting with TM. Does Docker support read only volumes? RD Only volume will enable sharing. What are concrete use cases this would enable?

**Comment by msterin** [comment]
Note: -o readonly would mean a volume is ALWAYS readonly , on any use. It would be OK If we had a way to reclassify it as "writeable" at some point - but we don't

**Comment by msterin** [comment]
Let's look at that in GA context - we have a few use cases popping up already, e.g. read-only docs distribution and immutable code libraries. Not sure if we can/should squeeze it it, but it's worth taking a look  sketching  / costing

**Comment by govint** [comment]
Closed via #583
