### ISSUE TITLE
On create, reject file names > 255 chars on ‘create’

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#284]
This is from a TODO in refcnt.go

**Comment by msterin** [comment]
//CC @pdhamdhere @andrewjstone 

An update. 
* The current code rejects long names (> 255 chars)  with `VolumeDriver.Create: Failed to create <name>. Failed to create virtual disk: The filename is too long (45).`
* names with spaces rejected with `Error response from daemon: create Some Volume With Spaces: VolumeDriver.Create: Failed to create /vmfs/volumes/56be7b43-11018e33-fe41-000c293742b9/dockvols/Some Volume With Spaces.vmdk. Extra arguments at the end of the command line.`
* names under 105 characters length work fine
* names over 105 (but less that 256) are failed with `Error response from daemon: create <name>: VolumeDriver.Create: Failed to create metadata kv store for <full name>`
* docker local volumes names are analyzed by docker , here in attempt to create name with spaces '`Error response from daemon: create   d   d: "  d   d" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed`

A suggestion: block on client using regexp [a-zA-Z0-9][a-zA-Z0-9_.-]{0,104}
