### ISSUE TITLE
Use docker volume name in reconfig request deviceInfo.label in vmdk_ops.py

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#292]
we hardcode the label for volume now 
``` 
       label = "dockerDataVolume",
        summary = "dockerDataVolume",
```
We should use Docker volume name instead (truncated to maxsize of volume).
this would make it easier to locate in UI/code , thus assisting management, and also may help in looking for volume by label

**Comment by pdhamdhere** [comment]
Both label and summary are overwritten :(
