### ISSUE TITLE
Docker does not send umount after mount failure.

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#320]
We need to check with docker for the behavior of the engine on mount failures. 
There seems to be relevant discussion here: https://github.com/docker/docker/pull/21015/files
This issue is to follow up with Docker and figure out the right recovery of refcount status after mount failure.
1. Should we decrement on mount failure (which makes umount handling complicated)
2.  We depend on docker always sending umounts.

**Comment by pdhamdhere** [comment]
CC @govint

**Comment by govint** [comment]
Behavior is the same with Docker 1.12,

First time, docker reaches to the plugin to mount the disk, it fails.

Thereafter docker runs the container creating a folder on the local host FS and starts the container with the given working dir.

I'll try submitting a change to docker issue #22564

**Comment by govint** [comment]
Creating a new issue for the plugin, Docker is fixing this with a change to never send an unmount for a failed mount (docker PR 27116). Closing this issue.

**Comment by kerneltime** [comment]
Using this issue to track the work we need to do once Docker releases https://github.com/docker/docker/pull/27116
If you have filed an issue for that work then reference it here and close the issue with the label wontfix or invalid as no code change was part of closing this issue.

**Comment by govint** [comment]
Closing as #608 will address changes to the plugin to handle new docker behavior on mount failure.
