### ISSUE TITLE
Support python lint for the automated builds.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#351]
Install pylint in the docker image, Invoke lint on esx_service/Makefile.

**Comment by msterin** [comment]
As #721 indicates, we drift from good state pretty fast. Elevating priority and assigning to myself, will do ASAP

**Comment by govint** [comment]
There are a lot of errors reported by pylint on syntax. Possibly, this needs to be a make target and a checklist in a PR to have pylint verified for at least new code.

**Comment by msterin** [comment]
I plan to make build fail if pylint returns errors. We will start adding more checks and warning after that

**Comment by msterin** [comment]
Fixed by #739
