### ISSUE TITLE
Auto-cleanup after VM power off (detach volumes)

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#369]
In some use cases (e.g. force power off/power on) we can get into a situation when a vmdk is still attached to a VM but not used by Docker. This VMDK will be blocked from used in other VMs/ Docker engines . The suggestion is to handle it automatically, and on "power off" event from hostd (if possivle to get one) to check if any of the volumes in voldir are still attached , if they are - detach them 

When docker is not running, detach volumes (if any):
When plugin starts and sees that Docker is not running, we know that no volumes should be attached to the VM. Let's tell that to ESX service so it can detach all docker volumes.
This will do auto-cleanup of stale volumes after VM power on/ off

**Comment by pdhamdhere** [comment]
First part when VM is powered off with volume attached is already being worked on in #515 

Let's use this issue to track 2nd part where plugin tells ESX Service to detach.

/CC @msterin @govint

**Comment by msterin** [comment]
This is an urgent issue as we already have info from customers that it makes the service too unpredictable to use in production 

The solution is very clear - we need to register for PowerOff events from hostd, and on power Off make sure we detach all VDS volumes (i.e. the ones from .../dockvols/... folders)
