### ISSUE TITLE
Frequent warnings (Failed to open <vmdk> for descriptor check) in vmdk_ops.log

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#371]
Steps to reproduce:

1. Created a VMDK volume
2. Run docker run --rm -it -v v6:/data busybox ls -l /data in VM1
3. Run docker run --rm -it -v v6:/data busybox ls -l /data in VM2
4. Repeat step 2 & 3 several times

I see following warnings in ESX Service log. AFAICT they haven't resulted in any user visible failures.

```
05/18/16 23:51:26 2764794 [WARNING] Failed to open /vmfs/volumes/4bad174b-b67f5cfc-2fc6-0026b966a303/dockvols/v6.vmdk for descriptor check
```

**Comment by govint** [comment]
Tried the steps mentioned. Didn't get the error messages. But at one point, the same disk was configured to both VMs. VM 1 was reset (via vim-cmd)during the test on VM1, I'm not sure if that contributed to this weird scenario. May be it did. 

The volume kv was marked as "attached".  But still VM 2 was able to attach the same volume, there are no logs indicating a detach from VM1. Or may be a detach did happen (no logs) and the KV was marked as "detached".

So, VM2 was able to configure the disk later (when VM1 was still down). But once VM1 came up the disk was stuck in VM1 and can't be removed nor can VM2 attach the volume.

From the server side logs:
06/01/16 08:19:22 1011327083 [DEBUG  ] Found /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols, returning
06/01/16 08:19:22 1011327083 [INFO   ] *** attachVMDK: /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk to 1 VM uuid = 4225d240-b7f5-3825-e1c4-e69a08844980
06/01/16 08:19:22 1011327083 [DEBUG  ] controller_key = 1003 slot = 0

06/01/16 08:19:22 1011327083 [DEBUG  ] Set status=attached disk=/vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk VM name=1 uuid=4225d240-b7f5-3825-e1c4-e69a08844980

KV was marked as "attached".

06/01/16 08:19:23 1011327083 [INFO   ] Disk /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk successfully attached. disk_slot = 0, bus_number = 3

06/01/16 08:19:23 1011327083 [DEBUG  ] executeRequest ret = {'Bus': '3', 'Unit': '0'}
06/01/16 08:19:23 1011327083 [DEBUG  ] lib.vmci_reply: VMCI replied with errcode 0

At this point VM1 has attached clone-vol-9. But reset happened and VM1 went down.

06/01/16 08:19:23 1011327083 [DEBUG  ] lib.vmci_get_one_op returns 7, buffer '{"cmd":"attach","details":{"Name":"clonevol-9"}}'
06/01/16 08:19:23 1011327083 [DEBUG  ] Found /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols, returning
06/01/16 08:19:23 1011327083 [INFO   ] *** attachVMDK: /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk to 2 VM uuid = 564d392b-3cb8-5a4a-862a-3df7a590d97e
06/01/16 08:19:23 1011327083 [DEBUG  ] controller_key = 1003 slot = 1
06/01/16 08:19:24 1011327083 [DEBUG  ] Set status=attached disk=/vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk VM name=2 uuid=564d392b-3cb8-5a4a-862a-3df7a590d97e

VM2 is also configured with the same volume clonevol-9!!! Disk kv is still marked as "detached" but configured to VM1 (down at this time).

06/01/16 08:19:24 1011327083 [INFO   ] Disk /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk successfully attached. disk_slot = 1, bus_number = 3
06/01/16 08:19:24 1011327083 [DEBUG  ] executeRequest ret = {'Bus': '3', 'Unit': '1'}
06/01/16 08:19:24 1011327083 [DEBUG  ] lib.vmci_reply: VMCI replied with errcode 0


06/01/16 08:19:24 1011327083 [DEBUG  ] lib.vmci_get_one_op returns -1, buffer '{"cmd":"attach","details":{"Name":"clonevol-9"}}'
06/01/16 08:19:24 1011327083 [WARNING] VMCI Get Ops failed - ignoring and moving on.

Then detach happens on VM 2.

06/01/16 08:19:24 1011327083 [DEBUG  ] lib.vmci_get_one_op returns 7, buffer '{"cmd":"detach","details":{"Name":"clonevol-9"}}'
06/01/16 08:19:24 1011327083 [DEBUG  ] Found /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols, returning
06/01/16 08:19:24 1011327083 [INFO   ] *** detachVMDK: /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk from 2 VM uuid = 564d392b-3cb8-5a4a-862a-3df7a590d97e
06/01/16 08:19:24 1011327083 [DEBUG  ] findDeviceByPath: MATCH: dockvols/clonevol-9.vmdk
06/01/16 08:19:25 1011327083 [DEBUG  ] Set status=detached disk=/vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk
06/01/16 08:19:25 1011327083 [INFO   ] Disk detached /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-9.vmdk

Now, KV is correctly marked as "detached", but the volume is configured in VM1 still.

**Comment by msterin** [comment]
The bug is as follows: 
* 2 docker VMs in the same ESX host
* one Docker VM is doing attach (or detach) operation and locking the .vmdk
* another docker VM is doing `volume ls` operation and tried to enumerate **all** vmdks - and the ones locked by the first VM are reporting the above error. and silently skipped in 'ls' command

**Comment by pdhamdhere** [comment]
```
def vmdk_is_a_descriptor(filepath):
...
    if filepath.endswith('.vmdk') and os.stat(filepath).st_size < MAX_DESCR_SIZE:
        try:
            with open(filepath) as f:
                line = f.readline()
                return line.startswith('# Disk DescriptorFile')
...
```
Peeking into VMDK file and checking for '# Disk DescriptorFile' is additional safety check. Return TRUE `if filepath.endswith('.vmdk') and os.stat(filepath).st_size < MAX_DESCR_SIZE`.

**Comment by govint** [comment]
We can't ignore the check on the descriptor file as otherwise we will report the flat disks as well to docker. A read-only open is sufficient to open the file (even if there is a lock on the file) and check the descriptor file.

For example:

Disk is in use by VM.

[root@localhost:/vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols] diskTool -i4q clonevol-39.vmdk
Failed to open disk 'clonevol-39.vmdk' : Failed to lock the file (16392).


Use read-only open option.
[root@localhost:/vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols] diskTool -irq clonevol-39.vmdk
Info:
     capacity       : 104857600 bytes (100 MB) 204800 blocks
     backing length : 104857600 bytes (100 MB)
     spaceUsed      : 14680064 bytes (14 MB)
     bottomLinkSpaceUsed : 14680064 bytes (14 MB)
     unsharedSpace  : 14680064 bytes (14 MB)
     unsharedSpace valid: yes
     parentFileName : (null)
     digestDisk     : (null)
     digestType     : (null)
     numLinks       : 1
     CID            : 0xfffffffe
     parentCID      : 0xffffffff
     keyID          : 00000000
     bottomEmpty    : TRUE
     compressed     : no
     nativeParentHint : (null)
     immutableLength : 0 bytes
     reclaimSpace   : 0 bytes (0 bytes)
     logicalSectorSize  : 512 bytes
     physicalSectorSize : 512 bytes
     allocationType : thin
     createType     : vmfs
     device         : (null)
     objType        : file

Files in chain from current link upwards:
     /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-39.vmdk

**Comment by govint** [comment]
Don't intend to use diskTool, its only for reference.

**Comment by msterin** [comment]
There is a size check there, so flat files or digests won't be reported. And the vmdk is already open as readonky. So it should either be open as noio which may or may not help , or, as Prashant has suggested, open failure ignored with a log warning

**Comment by govint** [comment]
The read-only open vis python open() is not the same as read-only via diskLib. DiskTool is using disklib to open the file.

**Comment by msterin** [comment]
are you agreeing that the failure should be simply ignored , or are you suggesting some other (not suggested in this thread) way of dealing with the failure ?
