### ISSUE TITLE
KV files need to be aligned on 4K

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#388]
and probably using ObjLib_Pread/Pwrite instead of read/write.
See discussion in #373 for more details. 
Impact: most likely svmotion and clone are broken; maybe encryption and who knows what else- basically, anything reading from sidecars

Per disklib folks
* the sidecar is open with O_DIRECT and this NEEDS (and checks for) sector alignment, 4K is to guarantess no issues with 4k disks going forward
* objlib_pread/pwrite is needed to support VVOL and encrypted disks (with encrypted sidecars). With regular read/write these features will be broken

**Comment by govint** [comment]
PR #433

**Comment by govint** [comment]
Closed via #433
