### ISSUE TITLE
Support dependent and independent disks as volume create options.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#390]
Presently the plugin supports only independent persistent disks. But its possible that a container will want independent persistent/non-persistent and dependent persistent-non-persistent disks for different data uses. Being able to return to a point in time for data is a useful usecase to support for containerd applications. Similarly, being able to start always at a known state on container restart (non-persistent disk) could be useful.

Dependent disks may be treated as "private disks" for the VM that created then in that those disks can't be attached to another VM during its entire life-time.

**Comment by msterin** [comment]
related to #60 and #374. It all boils down to how we support Vm snapshots, disk snapshots and how do we deal with deltadisks

**Comment by msterin** [comment]
removing my pushback... we do need it for backup - since backup vendors rely on **VMsnapshot->backup PIT->snapshot remove** sequence, we need to support dependent disks, and disk snapshots. See #547 got the first step in this support.

**Comment by pdhamdhere** [comment]
Fixed with #547
