### ISSUE TITLE
ESX services throws on detach task failure

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#399]
A disk was a part of snapshot (before we changed disks to independent) , and now `docker volume rm ` fails.  ESX log shows \ 
 `Cannot remove virtual disk from the virtual machine because it or one of its parent disks is part of a snapshot of the virtual machine.'` The failure leads to ESX service throwing exception and dying, (and then restarted by watchdog) and vmdk plugin showing "cannot connect to ESX" 

this exposes a general issue - task (vim.fault.InvalidDeviceSpec) exceptions are not handled, so there may be more glitches

**Comment by pdhamdhere** [comment]
PR #460 should fix this rt? @msterin

**Comment by msterin** [comment]
yes

**Comment by msterin** [comment]
Fixed by #460
