### ISSUE TITLE
Integrate with Bintray

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#403]
Integrate with bintray to make latest release available for Download from landing page. See VIC for reference below.

[![Download](https://api.bintray.com/packages/vmware/vic/Download/images/download.svg)](https://bintray.com/vmware/vic/Download/_latestVersion)

**Comment by kerneltime** [comment]
This is not in our court, we are depending on the CNA team to bless us with a repo.

**Comment by pdhamdhere** [comment]
No luck for Beta. We will try again for GA. CC / @frapposelli

**Comment by shuklanirdesh82** [comment]
Manual effort is required to upload VIB on the bintray account. 

README.md has been updated with bintray badge hence closing this issue.
