### ISSUE TITLE
Add code coverage for python tests (test-esx)

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#404]
Integration with tools to measure code coverage from CI tests.

**Comment by kerneltime** [comment]
In addition to adding coverage tracking we should integrate with coverage.vmware.run tracked in https://github.com/vmware/docker-volume-vsphere/issues/670

**Comment by shuklanirdesh82** [comment]
Sharing some notes from my analysis:

our test-esx tests are written using python unittest framework, a preliminary analysis was done through [coverage-py](http://coverage.readthedocs.io/en/latest/#coverage-py) and easier to capture the coverage data for some tests by running locally the rest of tests required to have access pyVmomi library. Our test-esx tests run on the ESX by copying them on the ESX. 

I hit the blocker while integrating `coverage-py` onto ESX 6.0 U2 (GA) version.

Pasting output for the reference:

```
I tried on my local and it does generate the good html report 

nshukla-mbp:utils nshukla$ coverage run cli_table_test.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
nshukla-mbp:utils nshukla$ coverage report -m
Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
cli_table.py           82     37    55%   33-39, 48-53, 76, 110, 129-133, 138-141, 146-149, 170-181
cli_table_test.py      39      0   100%
-------------------------------------------------
TOTAL                 121     37    69%
nshukla-mbp:utils nshukla$ coverage html
```
