### ISSUE TITLE
Handle documentation of docker VM  snapshots, clone with independent disks

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#406]
When we have independent disks the below ops aren't allowed - needs to be added to documentation:

1. VM snap with memory snapshot enabled:
"Cannot take a memory snapshot, since the virtual machine is configured with independent disks."

2. Clone VM - not supported with VMs with independent disks:
"Virtual machine is configured to use a device that prevents the operation: (vmodl.fault.SystemError) {
   faultCause = null,
   faultMessage = null,
   reason = The operation is unsupported with virtual disks in independent mode or raw disk mappings in physical compatibility mode
}"

**Comment by pdhamdhere** [comment]
Already documented in Known Issues. Also we have separate issue tracking vSphere Interop.
