### ISSUE TITLE
Does the plugins support multi-ESX host?

### ISSUE THREAD

**Issue by yadzhang** [vmware/docker-volume-vsphere#409]
For example, there are two ESX host, a VM (docker host) on one ESX host, create a volume on the other ESX host and VM can use the volume on the other ESX host. I think it is very useful and convenient for docker immigration. I do not know whether the plugin support and whether it can be implement?

Another small question: what is the configuration file (/etc/docker-volume-vsphere.conf) format?
Can you give an example with some description?

**Comment by pdhamdhere** [comment]
Yadong, Short answer is Yes. Plugin supports multi-esx hosts.

Containers running in same Docker Host /VM can share VMDK volume. Also volume created by one Docker Host can be used by another Docker Host as long as VMs are residing on same Datastore. We have an issue open to support multiple datastores #288. 

Good catch on configuration file format. Will add it to [wiki](https://github.com/vmware/docker-volume-vsphere/wiki)

**Comment by yadzhang** [comment]
Thank you for answer. You mean is that the plugin will support multi-esx host in near future, but don not support now, temporarily ?

**Comment by msterin** [comment]
it works for multi-ESX scenario with 2 constraints: 
- Vms have to be placed on the same datastore to share volumes 
- onluy one VM at a time (but multiple containers withing this VM) will be able to use it
