### ISSUE TITLE
Docker PRs - still missing functionality 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#42]
- [x] ~~'docker volume inspect' is missing metadata passed with -o. So if we pass size or policy via -o, there is nothing about this in inspect. **every** early adopter looking at TP asked for this. They also asked for actual size, consumed storage, storage policy, etc...~~ Fixed "details" in 1.12 and related volume plugin support
- [x] ~~We need some way to know which container creates and requests a volume. This way we can map volume->vm->container, which is what customers are asking about all the time~~ not needed - we can interrogate docker for containers 
- [ ] docker 'ls' is missing a way to do driver-specific filter, or driver-specifci information (e.g. size , consumed storage, datastore, policy...)
- [ ] docker does not prove use any ID nor repeats any ID from plugin, so a swarm cluster may talk to plugin running on different storage clusters, and we will not know

update: 
- [ ] missing a way to config a volume post-create (e.g. change a policy
- [ ] missing a way to tell per-volume "global" or "local" scope. During the scope discussion the Docker folks decided there was no use case, thus creating a problem for vsphere driver

Andrew - this one compliments https://github.com/vmware/docker-vmdk-plugin/issues/17

**Comment by govint** [comment]
'docker volume inspect' is missing metadata passed with -o. So if we pass size or policy via -o, there is nothing about this in inspect. every early adopter looking at TP asked for this. They also asked for actual size, consumed storage, storage policy, etc... note it is partially supported via "details" in 1.12.

Get() in the plugin is now returning actual size vs. configured size plus create time options (as provided).

**Comment by msterin** [comment]
Out of 2 issue
*  one can be punted (docker 'ls' is missing a way to do driver-specific filter,) 
* another one -  `docker does not prove use any ID nor repeats any ID from plugin, so a swarm cluster may talk to plugin running on different storage clusters, and we will not know` should be tested  on a swarm (i.e. have swarm workers on  2 different ESXs, make sure both docker VMs run on local storage which has the same name on the both ESXs, have bring one node down and check what happens with apps using a volume on failover)

**Comment by tusharnt** [comment]
@govint to investigate whether to file issues against Docker for these items.

**Comment by govint** [comment]
The CSI https://github.com/container-storage-interface/spec/blob/master/spec.md is the place for definition of container orchestrator <-> storage plugin interactiosn in a cluster env. Closing this issue as the cluster use case is being addressed via CSI.
