### ISSUE TITLE
Ability to query policies when creating Docker Volume

### ISSUE THREAD

**Issue by lamw** [vmware/docker-volume-vsphere#421]
VI Admins can create VSAN policies which then are consumed by end users (Developers) when creating the Docker Volumes. However, it doesn't look like Docker can query the plugin capabilities today which would mean the VI Admin must then communicate this info to all the Developers which isn't really a scalable solution.

**Comment by msterin** [comment]
As a poor man solution, I suggest to report list of avail policies on command line 
`docker volume create --driver=vmdk --name=doesnotmatter -o policy=some-bad-name`
and we'll reply with 'Error: no such policy: some-bad-name. Available policies are : <list...>`
