### ISSUE TITLE
Plugin specific cli

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#425]
While docker is still adding features, we need to provide a Cli
* query options capabilities (man page for plugin)
* query available options on an install 
* query state for the back end 
* ...

**Comment by msterin** [comment]
Can you elaborate ? I am not sure what "query state for backend" or "query avail options on install" would mean ? Generally, I'd prefer to avoid another CLI and would rather push a PR to docker `inspect` or other commands...

**Comment by pdhamdhere** [comment]
Discussed and agreed to contribute to Docker rather than inventing our own CLI.
