### ISSUE TITLE
Volume to VM to Container Mapping

### ISSUE THREAD

**Issue by ryandotclair** [vmware/docker-volume-vsphere#434]
Taking the below output:

```
vmdkops_admin.py ls -c volume,datastore,created-by,policy,attached-to,capacity,used

Volume  Datastore   Created By  Attached To                           Policy  Capacity  Used
------  ----------  ----------  ------------------------------------  ------  --------  --------
Ryan    datastore1  PhotonOS_1    564dae2e-cc4c-36a4-1371-a2422132add3  N/A     5.00GB    130.00MB
```

It's my understanding that if a vmdk created by one VM (read: the "Created By" field) can't be leveraged in another VM through the docker volume commands (a limitation of Docker Volume command's scope). Assuming that's indeed the case, I'd prefer to see "VM Owner" instead of "Created By" and "Attached to Container" as oppose to the "Attached To" field... which from what I've gathered is the unique BIOS ID?

**Comment by pdhamdhere** [comment]
VMDK volume can be shared by containers running on same host. As long as VMDK volume is not in use by any container, any docker host (VM) can claim the volume. For e.g. VM1 can create a volume and container in VM2 can use it.

yes, both "Created By"  & "Attached To" are VM names. We have replaced UUID of VM with VM name on master. Here is how it looks on top of tree;

```
 vmdkops_admin ls
Volume  Datastore  Created By  Created                   Attached To  Policy  Capacity  Used
------  ---------  ----------  ------------------------  -----------  ------  --------  -------
v1      Storage1   ubuntu-1    Wed Jun  1 22:41:20 2016  ubuntu-2     N/A     100.00MB  14.00MB
```

**Comment by msterin** [comment]
I think we should change the labels to "Create By VM" and "Attached to VM". 
As for container names - I would **love** to provide "used by containers" list for volume, but Docker does not give us any clue about it. See #42 
//CC @Andrewstone

**Comment by ryandotclair** [comment]
@pdhamdhere I understand that it could be used by another DOCKER_HOST, technically speaking, but when I point the docker client to another VM on the same physical host, and run `docker volume ls` against it, it doesn't show the available vmdk that was created by another VM (same host). Ergo, I don't see this created by information being of value...  Or am I missing something/lost in translation?

**Comment by msterin** [comment]
@ryandotclair - does this other VM have the volume-vsphere plugin installed ?

**Comment by ryandotclair** [comment]
![image](https://cloud.githubusercontent.com/assets/13955610/15797303/78dc034a-29d8-11e6-9f5c-ea7717fac58a.png)

I can't believe I forgot to install that on the second one.

Thanks @msterin!

OK, ignore that. Cool. Yes, "Created by VM" and "Attached to VM" would be most helpful. Although I'm not sure how the value of "Created by VM" would be operationally unless a developer only has access to a given VM(s)?

**Comment by govint** [comment]
Ryan,
     To add (I had wanted to ask this), the two VMs need to be on the same
datastore and path in order to for both VMs to see volumes created by the
other. If you have VM1 on /vmfs/volumes/ds1/a/b/c/vm1 and VM2 on
/vmfs/volumes/ds1/a/vm2 then again the two docker hosts won't be able to
see the volumes created by the other.

Today the plugin keeps the volumes in a folder thats located on the same
parent folder as where the VM lives. So, for volumes created from VM1,
 those will live in /vmfs/volumes/ds1/a/b/c/<volumes folder> and for VM2
they will be at /vmfs/volumes/ds1/a/<volumes-folder>.

Obviously the same applies if the VMs are on different datastores.

Soon it should be possible to locate volumes in a folder of the users
choice independent of where the VMs on a host live.

**Comment by msterin** [comment]
@ruansotclair  -yes, we were thinking about devs (or teams) having access to subsets of VMs , and then our ESX CLI controlling which VM can do what with storage , and reporting which VM has created or has the volume attached

**Comment by msterin** [comment]
@ryandotclair - sorry about my fat fingers , the last message was for you :-)

**Comment by ryandotclair** [comment]
@msterin 👍 That I'm down for. Just... still not sure the value of "created by VM" mainly due to the assumption of knowing who has access to which VM's. Create by username/group, though, that would be nice. Then again, that might be difficult to implement considering "root" might be in use. Hmmm.

**Comment by andrewjstone** [comment]
@ryandotclair Indeed, auth has to be tied to the VM and can't be based on user group because of the root issue. We are still discussing solutions, as our initial one got some funny looks at RADIO. It's what's described in the admin cli spec using the name of the VM for permissionss.

**Comment by ryandotclair** [comment]
Yeah, that's a tough one. Another approach could be to leverage a specific tag, to at least get the dev group name, but then that assuming you've got an orchestration layer spawning the VM (or forces the VI admin to manually create one, using a specific syntax). Hmm. Thinking Created by VM is the best option here--at least better than nothing.
