### ISSUE TITLE
VMCI Go module hierarchy and configuration cleanup

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#439]
One way to layer the code is as follows
- ESX code publishes a GO wrapper for VMCI communication. This can be an API without exposing JSON serialization.
- The Plugin takes a dependency on the VMCI Go module and uses it to invoke the API. 

Also, when instantiating the VMCI Go module the configuration is read in and passed.

**Comment by govint** [comment]
Closing. Plugin works fine with current vmci integration
