### ISSUE TITLE
Admin CLI ls could include last attached fields.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#441]
The volume list for 'ls' command could include a "Last attached" fields which could list the last attached by VM (name) and the last attached and detached time of the volume.

The last attached VM allows an admin to track which VM (and hence containers in that VM) accessed data on a volume. This and the last detached time give a limited audit capability to the admin to track usage of each volume. 

For an admin, there is no way to figure what all volumes are lying unused and occupying storage when they can't figure when a volume was last used. "docker volume ls" doesn't doesn't provide such information. The last attached time will help the admin who wants to reclaim storage to filter volumes that can be removed.

**Comment by msterin** [comment]
I suspect this (information on volume age) was already speced on the wiki - can you check and update the issue ? 

> The last attached VM allows an admin to track which VM (and hence containers in that VM) accessed data on a volume.

No it does not allow to track much. It simply shows who accessed it last. If we want to track, we need to use LogInsight or something like that. 

>  The last attached time will help the admin who wants to reclaim storage to filter volumes that can be removed.

if t's the goal, it makes sense to provide "sort by ;ast attached" in admin_cli 'ls'

**Comment by govint** [comment]
No takers and not a critical feature to support.
