### ISSUE TITLE
Support importing a disk into a volume repository on an ESX host

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#442]
To allow existing users migrate their data (vmdks) to be managed by the docker-volume-vsphere plugin we need a way by which users can specify a single or multiple volumes to be "imported" into the volume repository managed by the plugin and hence docker.

This is assuming that docker will not accept volumes that are simply placed into the volume repo on the ESX host side unless the volume is explicitly created via docker.

So,
1. Support a "docker volume create -o "importvol=<path to vol>...." " option specifying the location (on the host) from where an existing volume must be imported into the docker volume repo on the host.
1. Create fails if the volume doesn't exist.
2. If the volume exists at the specified path at the host, then move the volume to the repo and init meta-data for it.
3. Done.

Point to consider is whether the volume must be migrated to the volume-repo of the plugin or it remains where it is (say 1TB volume) but we create a vmdk descriptor in the volume-repo and the meta-data for it while the actual volume stays elsewhere (for vsan and vvol thats the case anyway).

**Comment by msterin** [comment]
what's wrong with simply moving vmdk to the right folder ESX ?

**Comment by govint** [comment]
That won't be the way a user who's using VSphere VMs today to migrate to docker. The volumes need to be created thru docker so that docker knows of the volumes and the plugin can create the meta-data for the imported volumes. How will meta-data be created by moving the volumes or how will docker know of the volumes either?

ANother workflow is to be able to migrate volumes from another plugin-type into the vsphere plugin. For example, how will a volume managed by flocker-vsphere-plugin be migrated/imported by the vsphere-plugin?

**Comment by msterin** [comment]
First of all that's not true - dicker uses Listvrequest to know about volumes and copy to folder works. We should simply recreate metadata if it's missing

Second, unless a customer asks for that, we should not spend time on this IMO

**Comment by govint** [comment]
It looks more a hack to have users copy files into a volume repository
managed by the plugin on a specific esx host than importing via docker
which looks correct given these are docker volumes. And then expect to run
their container on a VM on that specific host. Going via docker and
ensuring metadata gets created correctly is better user experience as well.

**Comment by msterin** [comment]
yes , it is better, if anyone ever will be using it. But it's not free and it's distracting from what we already *know* customers are asking for - e.g. backup story. Besides, it's an extension to existing #62 which is already slated for v.next.
So let's hear at least *some* customers asking for it before starting to worry about it and spend time on this. Parking to v.next for now

**Comment by govint** [comment]
Closing, adding a datastore to a vmgroup allows the feature that this issue was originally asking for.
