### ISSUE TITLE
Allow a volume create option to add a fixed length volume description.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#444]
While users are able to create volumes in VSphere storage it will be cool to allow users to add a short description (say 256 chars) of the volume like a volume label/description that they want associated with the volume. VMDK labels are 16 bytes and may be restrictive. The description that the user provides can be persisted as volume meta-data and listed via admin CLI 'ls' command.

While users may create disks with names the description allows them to in a way label intended content in the volume as well.

Something like "docker volume create -o "description="......"......"

**Comment by msterin** [comment]
if we do it. description would alsa have to show in admin CLI 'ls' command. However, what do you suggest for a  **docker** user to see descriptions on existing volumes ?

**Comment by govint** [comment]
Yes, the admin CLI ls command must show this. For docker, this won't be
possible till docker supports listing the options with which a volume was
created. For example, today docker volume inspect doesn't allow seeing a
volume's size, we can create a volume with a policy but can't see it later
via "volume ls" or "volume inspect". Need a docker issue to add this.

**Comment by govint** [comment]
This is very similar to the 1.12 capability to add a "label" for a volume. But Docker seems to not have enabled passing the label to a plugin. Which seems odd. On the one hand they have added support for scope (local or global volumes in 1.12) but the label is still local to the docker engine that created the volume.

Surely, for "global" scoped volumes we need every docker host in the cluster to be able to provide the same label as was specified at volume creation. For now the "volume meta-data or description string" needs to be provided within the -o"...." string.

**Comment by pdhamdhere** [comment]
If I understand correctly, these labels will be used by higher level abstractions like Docker Swarm for placement decision. In theory, Admin using esx-cli don't care about labels added by Developer. So, why would we duplicate docker label feature in backend?

**Comment by govint** [comment]
Yes, but right now those labels are local to the docker host thats creating
the volumes. Docker isn't addressing the case where the volume scope (1.12)
is global and in which case the label too should be global. The label
allows the user to associate meta-data with a volume. For volumes created
by a plugin the label can't be specific to the host. Its got to be
associated with the volume on the backend/

**Comment by govint** [comment]
The label option on volume create is designed to be docker internal and the plugins never see it. Closing.
