### ISSUE TITLE
make deploy doesn't remove the VIB thats present and install fails

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#445]
make deploy doesn't first remove the existing vib and hence the deploy of the VIB itself fails. "make all" seems to do this as part of a cleanup that happens before the build starts and hence installs the vib on the ESX host.

But if we run "make;make deploy ...." then VIB install fails. Whichever way its run the make must install components as expected - either as "make all" or as "make deploy". "make deploy" must deploy.

Most of the time user wants to build and deploy and run tests and hence "make;make deploy ..." is the command used.

Right now this is what happens, vib is skipped.

make --directory=vmdk_plugin deploy
make[1]: Entering directory `/home/administrator/vpl-kv/docker-volume-vsphere/vmdk_plugin'
../misc/scripts/deploy-tools.sh deployesx "10.110.48.29" "../build/vmware-esx-vmdkops-0.1.0.tp.2.172872e.vib"

=> Deploying to ESX root@10.110.48.29

Installation Result:
   Message: Host is not changed.
   Reboot Required: false
   VIBs Installed:
   VIBs Removed:
   VIBs Skipped: VMWare_bootbank_esx-vmdkops-service_1.0.0-0.0.1 <-------
vmdkops-opsd is running pid=1013003366
../misc/scripts/deploy-tools.sh deployvm "10.110.48.56 10.110.48.38" ../build

**Comment by msterin** [comment]
How is it a P0 ? It's been there for ages and I just run `make clean-all deploy-all`. There is no impact on end product, just extra 9 characters to type (or add an alias).
It's an easy fix ( make deploy-* targets should depend on clean-* target and drone should not call clean-*  targets before deploy-*) but it's quite low priority - I think it's won't fix but if someone want to volunteer and fix it, I think it's goodness

**Comment by govint** [comment]
I've always used make;make deploy... and haven't seen this before. It has
worked and do remember we had an issue (fixed) where the VIB wasn't getting
removed properly before install happens. In any case a make deploy must
work.

**Comment by msterin** [comment]
Dude - **how it is a P0** was my question ? Just add 'clean-all' to your command line or go ahead and fix it if you think it's urgent and blocks your work flow
