### ISSUE TITLE
Use a master directory to map volume names to their current snap level.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#446]
When docker user creates a volume the volume plugin will track the volume by name and there is a one to one correspondence between the volume name and the VMDK.

When the docker host VM is snapped then the volumes attached as dependent disks to the docker host will also be snap'ed creating  new VMDK descriptor files that are named appropriately - this should happen for any backing for a VMDK.

When a container wants to attach a volume the plugin (server) needs to pick the current usable snap of the volume vs. any older snap or even the base disk that was originally created.

If the plugin (server) uses the volume name as is to identify the VMDK to attach its going to pick the base disk which is incorrect. The plugin (server) mustn't be picking VMDKs based on volume name provided and instead must maintain a persistent directory of volume names to "current usable disk".

And snapshots too must go thru the plugin(server) (first via admin CLI perhaps and later thru docker, when docker implements volume snapshots).

As and when a snap is taken of a volume, the plugin updates its master directory indicating what disk is the current-usable-disk for the volume. The parent child relationship between snaps are all well managed via ESX already, so that data doesn't need to be maintained by the plugin.

Alternatively, the plugin(server) can be retained as a simple python module while the master directory can be maintained from inside ESX itself.

The volume repository is created and managed via an ESX side entity (new object backend) which will handle creating disks on actual physical backends (like vvol/vmfs/vsan/nfs) and manage the directory of volumes for that repository. Then all snap/clone/migrate workflows can be addressed as appropriately. The plugin server would be able to CRUD volumes in the repository via the new obj backend, without implementing a lot of logic thats really not to be in the plugin.

This is significant amount of work and may be considered for a future release.

**Comment by msterin** [comment]
this seems to be an implementation suggestion for #374 
@govint - please do not create Issues which are implementation suggestions to existing issues; instead feel free to update the original one with your implementation suggestion
