### ISSUE TITLE
Make vSocket port an option, make default under 1024, check for privileges in GO

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#45]
Currently port number is hardcoded. Needs to be a config option , and also default needs to require root.
Alsom, would be good to review vSocket security and add check that the guest communicates is from ROOT

**Comment by kerneltime** [comment]
Relevant doc: https://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.vmci.pg.doc/vsockSecurity.7.4.html?path=7_6_0_4_2_2#1006237

**Comment by kerneltime** [comment]
I will be splitting this issue into 2
1. Make socker port selection configurable (This bug for TP #45)
2. Check the client socker port bind capabilities.https://github.com/vmware/docker-volume-vsphere/issues/436 (beta)

**Comment by kerneltime** [comment]
closed in https://github.com/vmware/docker-volume-vsphere/pull/438
