### ISSUE TITLE
Check disk format options (spelling and case) on vol create.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#461]
The code in vmdk_ops.py:validate_disk_allocation_format() is comparing with a lower case format name of the requested disk format. This isn't necessary as any incorrect format name must be caught and errored with the same message. Below we see two separate messages

a) unsupported format and

administrator@hte-1s-eng-dhcp98:~/vpl-kv/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol-82 -o diskformat=thinn
Error response from daemon: create clonevol-82: VolumeDriver.Create: Disk Allocation Format thinn does not exist. Valid options are: ['zeroedthick', 'thin', 'eagerzeroedthick']

b) owing to matching with a lower case format name we validate that the option is ok (while its not) and run the vmkfstools command which fails.

administrator@hte-1s-eng-dhcp98:~/vpl-kv/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol-82 -o diskformat=thiN
Error response from daemon: create clonevol-82: VolumeDriver.Create: Failed to create /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-82.vmdk. Incorrect disk option "thiN"

administrator@hte-1s-eng-dhcp98:~/vpl-kv/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol-82 -o diskformat=ZeroedThick
Error response from daemon: create clonevol-82: VolumeDriver.Create: Failed to create /vmfs/volumes/523c14b7-e5561042-5e2f-002481aaea6c/dockvols/clonevol-82.vmdk. Incorrect disk option "ZeroedThick"

Prefer to support exactly those options names (spelling and case) that are actually supported by the backend (vmkfstools).

**Comment by pdhamdhere** [comment]
Good catch. Missed it in code review. @abrarshivani can you do a quick fix?

**Comment by abrarshivani** [comment]
@pdhamdhere I have fixed the issue. Now, option names are supported in lower case only.
