### ISSUE TITLE
Handle std out and std err for the python daemon

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#470]
Currently the std out and std err generated from the c code is not captured.
A simple redirect part of setsid and watchdog command does not seem to work (needs to experimenting).
One option is to redirect the std out and err from python itself. 

There is useful debugging information that we currently miss out on.

**Comment by tusharnt** [comment]
Not critical. Aimed at GA opportunistically.

**Comment by shuklanirdesh82** [comment]
Error reporting has been improved and relying on the return code from python daemon, closing this as `invalid`.
