### ISSUE TITLE
Support 64-bit python 3.5.1 and libs

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#480]
Following syntax errors are getting reported with Python 3.5.1. Check all files for these type of errors.

1. All print statements must use '(' and ')' to enclose the print args. Example,

[root@localhost:~] python /usr/lib/vmware/vmdkops/bin/vmdk_ops.py -p 1019
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 744
    print "Usage: %s -p <vSocket Port to listen on>" % sys.argv[0]
                                                   ^
SyntaxError: Missing parentheses in call to 'print'

2. Use "except <exception> as ex:" format, (two places in vmdk_ops.py) example:

[root@localhost:~] python /usr/lib/vmware/vmdkops/bin/vmdk_ops.py -p 1019
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 754
    except getopt.error, msg:
                       ^
SyntaxError: invalid syntax

**Comment by pdhamdhere** [comment]
Why is this Beta blocker? ESX hasn't moved to Python 3.

**Comment by govint** [comment]
This can move to GA also. I kept in beta since with Python 3.5.1 the code
is broken.

**Comment by msterin** [comment]
Related to #33

**Comment by govint** [comment]
Both this issue and #481 . This issue and #481  can't be fixed separately, once the syntax errors are fixed, the server still fails to start as its using a 32-bit library.

**Comment by govint** [comment]
PR #479

**Comment by govint** [comment]
Merged #479
