### ISSUE TITLE
refcnt test failure

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#489]
*many* failures  of the same nature: https://ci.vmware.run/vmware/docker-volume-vsphere

//cc @pdhamdhere @kerneltime

**Comment by pdhamdhere** [comment]
@kerneltime Can you please look into this with priority?

**Comment by andrewjstone** [comment]
Here's an instance of this occurring: https://ci.vmware.run/vmware/docker-volume-vsphere/690

**Comment by govint** [comment]
Seeing two types of errors today on CI

1. Out of resources - VSAN isn't able to create VMDKs as there is no space on the datastore:

DISKLIB-LIB_CREATE : CREATE: Creating disk backed by 'vsan' OBJLIB-VSANOBJ: VsanObjCreate: failed to create object: No space left on device (1835010). DISKLIB-LIB_CREATE : Cannot create the requested object : Out of resources (1835026)

2. Once disk is created, KV creation fails as the disk can't be opened - too many open files (https://ci.vmware.run/vmware/docker-volume-vsphere/719). Error 28 below indicates too many open files on the host.

06/29/16 10:56:48 2878003 [MainThread] [WARNING] Open /vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c/dockvols/vol_UnitTest_Create.vmdk failed - 28
06/29/16 10:56:48 2878003 [MainThread] [WARNING] Side car create for /vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c/dockvols/vol_UnitTest_Create.vmdk failed - 1
06/29/16 10:56:48 2878003 [MainThread] [WARNING] Failed to create metadata kv store for /vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c/dockvols/vol_UnitTest_Create.vmdk

Pls. see https://ci.vmware.run/vmware/docker-volume-vsphere/713 for a CI trace that has the lsof output.

**Comment by pdhamdhere** [comment]
#496 is tracking "out of resource" failure. This issue will track failures in refCntTest.

**Comment by pdhamdhere** [comment]
Hypothesis is refCntTest was failing due to Docker daemon's stale volume cache. PR #499 restarts docker daemon invalidating cache should address this issue.
