### ISSUE TITLE
Test error message "No VIB matching VIB search specification 'esx-vmdkops-service'."

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#494]
The issue here is that this is a noise in the log and in 'make' runs which distracts and confuses   (no real issues with test or feature code)

'make clean-esx' now produces "No VIB matching VIB search specification 'esx-vmdkops-service'."  message is the VIB is not installed. **It is  a regression**, it used to check for installation and then silently succeed if the VIB was not installed. 

The same issues is with 'make clean-vm', and it should also be fixed:

```
Failed to stop docker-volume-vsphere.service: Unit docker-volume-vsphere.service not loaded.
error: package docker-volume-vsphere is not installed
```

Example:  https://ci.vmware.run/vmware/docker-volume-vsphere/730

umbrella issue: #489

**Comment by govint** [comment]
Closing as this message isn't observed now.
