### ISSUE TITLE
Error message during cleanupVolumes:

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#495]
The message does not necessarily indicated error (or does it?) but is confusing and distracting as it is a false positive from log errors point of view. 
If plugin is not running, we should say so and skip the 'docker volume rm'

```
=> cleanupVolumes: Asking docker root@192.168.31.121 to remove volumes (vol-build730)

list vmdk: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.List: dial unix /run/docker/plugins/vmdk.sock: connect: no such file or directory
``

example: https://ci.vmware.run/vmware/docker-volume-vsphere/730

Umbrella issue #489

```

**Comment by kerneltime** [comment]
I do not see this log message any more. https://ci.vmware.run/vmware/docker-volume-vsphere/370
