### ISSUE TITLE
ESX API need idempotency or a well defined retry framework

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#501]
vSocket is not perfect and we can see errors on vSocker based on kernel version. Thus, requests need retrying, which in turn needs idempotent APIs or well defined behavior for plugins to behave as per their API.

**Comment by pdhamdhere** [comment]
@kerneltime is this still an issue? Close?

**Comment by pdhamdhere** [comment]
#1076 has more context and is tracking same issue. Closing as dupe.
