### ISSUE TITLE
Leverage role based access of VC to manage volume creation.

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#502]
This is based on feedback received @http://cormachogan.com/2016/06/01/docker-volume-driver-vsphere/#comment-4465 
This is a request to leverage role based access part of VC to control volume creation and workflow when VC is part of the environment.

**Comment by andrewjstone** [comment]
I think we should very strongly consider tying the plugin to vcenter, and how we do it. If we feed vcenter info that's one thing, but relying on it for centralized management state seems wrong in a container centric world. Especially with regards to photon controller use in the future.

**Comment by govint** [comment]
+1 not having to rely on VC is the way forwards. But the way VSphere is made, we need a parallel implementation thats non-VC role-based access. And that should be implemented for VSphere, not for/by the plugin.

**Comment by andrewjstone** [comment]
I agree govint.

**Comment by pdhamdhere** [comment]
Addressed with #603 and tech-preview available in Oct 2016 release.
