### ISSUE TITLE
overall analytics (usage, volume visibility, etc...) planning

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#51]
Need to look at existing docker/ community stuff for overall analytics (usage, volume visibility), need to choose interesting one and see if we need to do work to integrate. 

Ritesh - can you elaborate ? Then we can reassign if needed.

**Comment by kerneltime** [comment]
This needs to be split into 2 parts. This is a wish list and needs to be mapped to implementation issues.

# ESX Admin
* Which docker volumes are currently in use
* Current performance numbers 
    * IOPS used
    * Capacity used
* Snapshot relations between docker volumes
* Usage history
* Performance history
* Backup configuration

# Add Admin
* Which volumes are on which datastores
* Policy history for volumes
* Which volumes are unused
* Which volumes are backed up and where

**Comment by govint** [comment]
Docker volume info. is available via admin CLI and docker CLI. Backup config isn't supported for vDVS volumes. Stats is via docker stats. History data per volume doesn't have a use case.
