### ISSUE TITLE
Error message when invalid volume name is specified

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#510]
Below command should possibly give the error message about invalid syntax vs. volume is not there.

a. administrator@hte-1s-eng-dhcp98:~/vpl-stats/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol_5
clonevol_5

b. administrator@hte-1s-eng-dhcp98:~/vpl-stats/docker-volume-vsphere$ docker volume inspect clonevol-5
[]
Error: No such volume: clonevol-5

Server:
07/05/16 12:40:52 1001423551 [2] [INFO   ] executeRequest 'get' completed with ret={'Error': '"Invalid syntax: \'clonevol-5\'.\\nValid syntax is volume@datastore, where \'volume\' or \'datastore\' contain up to 100 of allowed characters ([a-zA-Z0-9_.]) each"'}

**Comment by pdhamdhere** [comment]
`docker volume inspect` correctly reported that volume doesn't exist. (Looks like you have typo)

For invalid volume name, command fails with correct error;

```
root@ubuntu:~# docker volume create -d vmdk --name=clonevol_5
clonevol_5
root@ubuntu:~# docker volume inspect clonevol_5
[
    {
        "Name": "clonevol_5",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/clonevol_5",
        "Labels": {}
    }
]
root@ubuntu:~# docker volume create -d vmdk --name=clonevol-5
Error response from daemon: create clonevol-5: VolumeDriver.Create: "Invalid syntax: 'clonevol-5'.\nValid syntax is volume@datastore, where 'volume' or 'datastore' contain up to 100 of allowed characters ([a-zA-Z0-9_.]) each"
root@ubuntu:~#
```
