### ISSUE TITLE
vmdk-opsd doesn't start on boot

### ISSUE THREAD

**Issue by justinclayton** [vmware/docker-volume-vsphere#516]
After a reboot of the ESX host the vmdk-opsd service did not start. Typing `/etc/init.d/vmdk-opsd status` returns `vmdkops-opsd is not running`, and one must run `/etc/init.d/vmdk-opsd start` to allow VMCI communications with dvv to continue.

This is even though the init script contains `# chkconfig on 20 20`, and `chkconfig --list vmdk-opsd` returns `on`.

**Comment by msterin** [comment]
Good catch ! @kerneltime   - pls take a look , we are missing jumpstart config

**Comment by pdhamdhere** [comment]
ESX indeed attempts to start vmdk-opsd. However it fails to start with 503 Service unavailable error. 

/etc/init.d/hostd:# chkconfig: on 18 82
/etc/init.d/vpxa:# chkconfig: on 31 69
/etc/init.d/vmdk-opsd:# chkconfig: on 20 20

vmdk-opsd starts and fails to connect since vpxa is still not up.

**Comment by pdhamdhere** [comment]
Testing with /etc/init.d/vmdk-opsd:# chkconfig: on 99 99
