### ISSUE TITLE
Support returning status for a volume as allowed by Docker 1.12.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#524]
As discussed in #341, this issue is to track returning volume status when inspecting a volume.

**Comment by govint** [comment]
the current  version of the plugin helpers doesnt accommodate thw status for a volume (low level meta data) have got in touch with the author regarding this.

**Comment by govint** [comment]
Plan to submit a change to go-plugin-helpers to add status for a volume and then pick this up,

**Comment by govint** [comment]
This is what we get to see now, let me know if this data is good or we want to display anything more:

docker volume inspect clonevol_1
[
    {
        "Name": "clonevol_1",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/clonevol_1",
        "Status": {
            "allocated": "14680064",
            "attachedVMName": null,
            "created-by": "2",
            "diskformat": null,
            "size": "104857600",
            "status": "detached",
            "vsan-policy-name": null
        },
        "Labels": {},
        "Scope": "global"
    }
]

**Comment by pdhamdhere** [comment]
a. Represent capacity/size related information as MB/GB 
b. Group "size" and "allocated" 
c. "Created-by" is 2. What is 2? Should this be VM name?
d. vsan-policy-name": Should we drop this if volume is not on vSAN datastore
e. With muti-DS support, can we also include datastore information?
f. Can we change field name to descriptive names like "vmdkops_admin.py ls"

**Comment by govint** [comment]
Modified as below ('2' is the VM name):

$ docker volume inspect clonevol_1
[
    {
        "Name": "clonevol_1",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/clonevol_1",
        "Status": {
            "capacity": {
                "allocated": "14.0MB",
                "size": "100.0MB"
            },
            "created": "Wed Jul 20 12:29:08 2016",
            "created-by": "2",
            "datastore": "bigone",
            "status": "detached"
        },
        "Labels": {},
        "Scope": "global"
    }
]

**Comment by pdhamdhere** [comment]
Looks good to me. For attached disk, I assume caption would be "Attached to VM". Change "created-by" to "Created by VM"?

**Comment by govint** [comment]
Yes the attached to details are included as also the vsan meta data for
vsan data stores

**Comment by govint** [comment]
Raised issue on go-plugin-helpers to have status supported - https://github.com/docker/go-plugins-helpers/issues/53. I've got the changes and tested with me and have asked to be added to contributors list (getting permission error when pushing changes).

**Comment by govint** [comment]
Closed via #548
