### ISSUE TITLE
Underlying VSAN setup is facing high latency

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#537]
The root folder of VSAN is facing high latency. This leads to VSAN info tests to fail.
ref: https://ci.vmware.run/vmware/docker-volume-vsphere/997
latency
```
[root@sabu-esx-01:/vmfs/volumes/vsan:5220b6f4208d15c5-22eacf2d7f134e1c] time ls
107b6057-9c9e-2bee-9d91-000c29e3609e  d3826057-683d-6e52-69c1-000c29e3609e  photon.rc.vsan.2
5c806057-77fa-85df-a219-000c29e3609e  dockvols                              vsan_info_test
b3028457-0019-39f4-9901-000c29e3609e  photon.rc.vsan
real	2m 14.41s
user	0m 0.00s
sys	0m 0.00s
```

**Comment by kerneltime** [comment]
For now will disable VSAN tests to allow for other tests to run and for PRs to make progress.

**Comment by kerneltime** [comment]
List of things undone which then needs to be redone after we RCA the problem
https://github.com/vmware/docker-volume-vsphere/pull/538

**Comment by kerneltime** [comment]
The current status
1. New vsan cluster single node is up and running 
2. Docker on the vms do not connect via tcp:// even though they are started up correctly

**Comment by kerneltime** [comment]
Refer #538 for changes made

**Comment by kerneltime** [comment]
Reassigning to Andy to look into the VSAN test commented out in #538

**Comment by andrewjstone** [comment]
That test is not supposed to run if there is no vsan. I don't understand the failure at all. The path in that test is relevant to the vsan datastore only, and if there isn't a vsan datastore the test won't run. Are we sure this isn't crosstalk between tests as was seen before where one test run interferes with anothers? I can't explain it otherwise.

**Comment by kerneltime** [comment]
There is a VSAN store but the path used is that of VMFS, from what I saw it lists the datastores and uses the first one when trying to create which is not guaranteed to be VSAN.

**Comment by andrewjstone** [comment]
I think that is very old code. The code on master calls `vsan_info.get_vsan_dockvols_path()` which explicitly checks that the store is vsan. Also, in master line 130 of vmdk_ops_test is not an assert. It appears an old version of the code was being run.

**Comment by andrewjstone** [comment]
Ugh. I was looking at the wrong test. It appears this one is using a vmdk path by mistake. Changing that to a vsan path will fix it. Doing now...
