### ISSUE TITLE
Distribute config file to ESXs via VC file browser

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#54]
We should be able to upload config file (JSON one in each datastore plugin folder) in VC file browser . Also it needs to be added to tests automation.

**Comment by pdhamdhere** [comment]
@msterin Do you remember which config file you are referring here? We already implemented policy support in admin CLI. Should this be closed as "won'tfix"?

**Comment by msterin** [comment]
It is obsolete by now, we should close this

**Comment by pdhamdhere** [comment]
Sure. One more down!
