### ISSUE TITLE
Admin CLI does not show columns requested

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#549]
When trying to get the demos going I ran into the following issue
```
devbox:~ ssh -qt root@$ESX /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls -c volume,created-by
Volume    
--------  
MyVolume
```
The over all command works fine without requesting columns.
```
devbox:~ ssh -qt root@$ESX /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls 
Volume    Datastore      Created By VM  Created                   Attached To VM  Policy          Capacity  Used      
--------  -------------  -------------  ------------------------  --------------  --------------  --------  --------  
MyVolume  vsanDatastore  photon.vsan.1  Thu Jun  2 08:31:55 2016  detached        [VSAN default]  10.00GB   364.00MB  

devbox:~ 
```

**Comment by lipingxue** [comment]
I did some test, the behavior is as expected.
From the help command , the usage of the ls command is

vmdkops_admin ls -h
usage: vmdkops_admin ls [-h] [-c Col1,Col2,...]

optional arguments:
  -h, --help        show this help message and exit
  -c Col1,Col2,...  Display selected columns: Choices = ['volume',
                    'datastore', 'created-by', 'created', 'attached-to',
                    'policy', 'capacity', 'used']

When '-c' argument is given, a column list (separated by comma) should be given, the valid column name in the column list should come from the the Choices field.

See the following 

vmdkops_admin ls -c 'volume','datastore'
Volume    Datastore   
--------  ----------  
MyVolume  datastore1 

If we have some spaces between the comma separated column name, then the command failed 

vmdkops_admin ls -c 'volume',  'datastore'
usage: vmdkops_admin ls [-h] [-c Col1,Col2,...]
vmdkops_admin ls: error: argument -c: invalid choice:  (choose from ['volume', 'datastore', 'created-by', 'created', 'attached-to', 'policy', 'capacity', 'used'])

The error message seems somehow misleading. We should discuss and make decision on how we  should improve this command.

**Comment by lipingxue** [comment]
I did more test, the command with "-c" option failed if the column name includes "-", see the following example

```
[root@localhost:~] vmdkops_admin ls -c 'volume','datastore','created-by','attached-to','policy'

Volume    Datastore   Policy  
--------  ----------  ------  
MyVolume  datastore1  N/A     
```

Two columns "created-by" and "attached-to" are missing from the result.

**Comment by andrewjstone** [comment]
The issue with the dashes is that the parser is expecting underscores. It's a mismatch between the help/usage text and what is actually accepted. Changing the parser to accept dashes should fix it.

As for the spaces, that's limited by what argparse in python can handle. The error message can be changed, but spaces still shouldn't be allowed.
