### ISSUE TITLE
Support datastore clusters

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#556]
Currently the plugin does not support datastore clusters, we need to add support for datastore clusters.

**Comment by shaominchen** [comment]
@pdhamdhere Do we really need this feature for GA? This feature is useful, but may not be critical for GA release.

**Comment by pdhamdhere** [comment]
This was a ask from customer. We should at least investigate if we have to do any additional work to support DSC and document in Interop matrix.

**Comment by ashahi1** [comment]
vDVS  populates datastoreCache from the actual datastores list ( si.content.rootFolder.childEntity[0].datastoreFolder.childEntity) so DS clusters would be declined before even trying. We also create VMDK using a vmdkpath on a local datastore.

DS Clusters (as a part of Storage DRS) are not available on individual ESX and are a VC feature, so it's not that easy to implement in the current architecture 

Steps performed and its output is as followed:

--------------------

1. Created a datastore cluster of shared Vmfs datatores
2. Tried creating volume by specifying the datastore cluster name - creation failed
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create -d vsphere:latest --name=testVol33@DatastoreCluster
Error response from daemon: create testVol33@DatastoreCluster: VolumeDriver.Create: Invalid datastore 'DatastoreCluster'.
Known datastores: sharedVmfs-0, sharedVmfs-1, local.2-0, local.2-1, local.2-2, vsanDatastore.
Default datastore: _VM_DS
```

**Comment by ashahi1** [comment]
Fixed as part of PR #1582

**Comment by tusharnt** [comment]
[Known issues section ](http://vmware.github.io/docker-volume-vsphere/documentation/known-issues.html)  also needs to be updated.

**Comment by ashahi1** [comment]
http://vmware.github.io/docker-volume-vsphere/documentation/known-issues.html is updated.
Closing this issue.
