### ISSUE TITLE
Support for multiple namespaces (Tenants)

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#559]
Multiple namespaces for volumes on the same datastore allows for multiple Docker clusters to be run . Each VM would be part of one and only one namespace.

**Comment by lipingxue** [comment]
AdminCLI change to support multi-tenancy is addressed in #645

**Comment by pdhamdhere** [comment]
Addressed with #603  & #645 and tech-preview available in Oct 2016 release.
