### ISSUE TITLE
Integration of plugin and VIC

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#56]
Vsphere integrated Containers (VIC) have a different (from regulatr Docker-in-a-vm case) model of Engine/VM/Containers deployment. In VIC, one VM runs a docker engine and that handles creating containers (VM == container) on request. The container VMs can run on any node in a vSphere cluster. Also, the volume attach is done by the VIC engine creating the correct VM reconfigure spec, and running this when the container VM is forked. 

So in order to use named VMDK volumes in VIC there need to be an integration with this mechanism.
This is a lower priority item, as VIC already auto-creates VMDK volumes for -v /path:/container_path option, so basic support of  external VMDK volumes is already there

Also, this may be better done by VIC team. Still, we need to decide when / who does the integration, and execute. Adding  tracking item

**Comment by pdhamdhere** [comment]
Based on discussion with VIC experts, there is no immediate integration required. Closing for now.
