### ISSUE TITLE
Update documentation for VSAN policy

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#562]
This is a follow up from https://github.com/vmware/docker-volume-vsphere/pull/561
The VSAN policy strings and how they are used and demo needs to be updated.

**Comment by kerneltime** [comment]
https://github.com/vmware/docker-volume-vsphere/blob/master/CONTRIBUTING.md 
has the steps to preview the changes via mkdocs serve

**Comment by msterin** [comment]
Depends on #576. Will update the policy info when #576 is in

**Comment by msterin** [comment]
The final version of #576 actually includes examples and a link to official doc for VSAN policy strings, so closing the isue.
