### ISSUE TITLE
Need Admin CLI coverage and unit test coverage for delta disk handling code

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#569]
#547 introduces proper handling of deltadisks and allows to define a volume  as participating in VM snapshot. However, to complete #390 we still neeed to do the following: 
* Add Admin CLI option to change `attach_as` ("snapshottable") status of the disk (format  TBD)
* Add Admin CLI information about existing deltadisk in the chain (format TBD)
* Add automated test: 
  * attach as default. Check the VM.config to make sure it is attached correctly
  * Change ths status. Make sure VM.config changed. 
  * generate fake .vmdk and -0000x.vmdk files and add unit tests for vmdk_utils handling this 

//CC @pdhamdhere

**Comment by lipingxue** [comment]
I read the description of this issue and looked at the related code. This is my understanding for the requirement for the first item:
we need to support command like the following to change the attach_as status of the disk
  set --volume=vol_name --options="attach_as=independent"

Is that correct?

For the second task "Add Admin CLI information about existing deltadisk in the chain (format TBD)". I am not quite sure what need to be done here. Mark/Prashant, could you elaborate more? @msterin @pdhamdhere

**Comment by govint** [comment]
Presently only access is allowed to be set with the set command. You will
need to add support for the attach_as option if that needs to be modified
via set.

**Comment by lipingxue** [comment]
Hi Govindan,
  Yes. I think add support for the attach_as option for add command is only the first task which Mark mentioned. 
What does the second task"Add Admin CLI information about existing deltadisk in the chain (format TBD)" mean? Do you have some idea? @govint

**Comment by govint** [comment]
@lipingxue the second item about adding data for existing snaps is for what snaps of the volumes may already exist. Like user has taken a snap of the VM and snap'able disks are already having delta-disks attached to the VM. Question is how to depict them to the user via admin CLI (yes?). Intent is to be able to show the current snap in use to the user (admin cli ls). 

We haven't yet tested docker volume inspect with  snaps of volumes, that would be something to verify.

PR #595 fixes the issue with set calling a missing method and also makes it easy for the user to specify the volume and its location for the user.
