### ISSUE TITLE
VMs used in CI must not have a PVSCSI controller.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#579]
The plugin server logic includes code to add a PVSCSI controller and as such that must be tested during CI. Which is easily done by having VMs in CI that don't have a pvscsi controller. This will ensure more of the plugin server logic getting exercised and any regressions caught there.

**Comment by kerneltime** [comment]
Can we add a test which removes a PVSCSI controller and then adds it? It is cheaper than keeping dedicated VMs for it.

**Comment by govint** [comment]
Yes, may be test set up should add the controller and remove at end of the
test.

**Comment by shuklanirdesh82** [comment]
As per the ask, PVSCSI controller is removed from all the vms exist in the current CI system.

ESX 6.5 having 4 vms
```
echo "=> Running tests on VMFS ESX_6.5" `date`
VMFS datastore: photon.vmfs & Ubuntu.16.10

echo "=> Running tests on VSAN ESX_6.5" `date`
VSAN datastore: photon.vsan & Ubuntu.14.04
```

ESX 6.0 having 4 vms
```
echo "=> Running tests on VMFS ESX_6.0" `date`
VMFS datastore: photon.ga.vmfs & Ubuntu.1404.vmfs

echo "=> Running tests on VSAN ESX_6.0" `date`
VSAN datastore: photon.ga.vsan & Ubuntu.1404.vsan
```

After removing controller from above vms and #989 exposes the volume creation failure for the test ```TestVolumeCreationFirstTime```; which was added as part of #794 (to cover #656 failure case)

https://ci.vmware.run/vmware/docker-volume-vsphere/1477

=== RUN   TestVolumeCreationFirstTime
```
creating volume [abc_1488520428] on VM[192.168.31.176]--- FAIL: TestVolumeCreationFirstTime (21.66s)
	createVolume_test.go:58: 
		Error has occurred [Error response from daemon: create abc_1488520428: Post http://%2Frun%2Fdocker%2Fplugins%2Fvsphere.sock/VolumeDriver.Create: http: ContentLength=36 with Body length 0
		] 
			while creating volume [abc_1488520428] very first time: err -> exit status 1
```

**Comment by shuklanirdesh82** [comment]
Expected work is done and supplied a change to reorder test sequence as part of this activity. 

currently CI is failing as expected and @govint is looking at similar failure cause.
