### ISSUE TITLE
Docker PR (potential) - need support for existing volume reconfigure

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#59]
Use case: volume exists , but we need to change policy to tolerate more failure. 
Desired support: 
Docker volume config <vol_name> -o option1=value1...

And related API /Volume.Config 
And support on our driver side

This is an extension of https://github.com/vmware/docker-vmdk-plugin/issues/42 which already requests PRs to /Volume.Get /Volume.Create /Volume.List

**Comment by govint** [comment]
Closing this, CSI may address this ask, docker closed the issue raised on it to support volume updates in favor of CSI.
