### ISSUE TITLE
Fixes to "vmdkops_admin.py ls"

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#592]
a) Include the location of the volume in ls output:
This comes up as a comment from #583 which added support in admin cli to modify volume attrs post volume creation. For the user to identify the volume we need the path of the vmdk to modify its attrs. User needs to know the exact location (full path) for a vmdk,

b) Support providing a volume name on ls command line and return just the data for the vmdk:
Allow a user to specify a volume@datastore and fetch data for that volume alone.

c) Provide a help message for the ls command.

**Comment by andrewjstone** [comment]
I don't really understand the issue in `a`. The datastore is already given.

For `b` I don't think it should be part of the `ls` command. it's easy enough to just grep.

For `c`: `ls -h` already shows help.

**Comment by govint** [comment]
Ok, after discussion the ls command works as expected today. Closing.
