### ISSUE TITLE
Verify docker service commands with the volume plugin 

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#601]
Docker 1.12 and 1.12.1 added up docker service command to create, scale and manage services via docker. We need to verify the volume plugin works seamlessly (especially the --mount option with type=volume) in any of the use cases that docker service is used.

**Comment by govint** [comment]
From last week, ran docker engine in swarm mode on two VMs and created a service that uses a persistent volume with single replica, two replicas and in global mode. The single replica works fine with the volume getting created as part of defining the service via "docker service create".

The two replicas scenario also works fine with the two running on the same node.

Global mode is a bit mixed up where one docker host (VM) gets to mount the volume and the second seems to be using a local docker volume. Ideally it would be correct to have the volume plugin create a snap of the persistent volume and each replica uses a snap of the single volume. The plugin needs to be supporting such an interface (Docker needs to define that). The attach_as attribute should allow a non-persistent mode which should allow creating a snap when a service instance runs.

Will update more on the global mode as I investigate this.

**Comment by govint** [comment]
Besides not being able to share volumes on container instances across VMs we can showcase using the VMDK driver for cases where a service can migrate across hosts and VMs and still be able to access its data, like this one - https://github.com/codedellemc/labs/tree/master/demo-persistence-with-minecraft-docker.
cc @asomaiah

**Comment by ashahi1** [comment]
Created a two seperate swarm setup of three nodes - one master and two worker nodes. 
Docker version: 1.12.1

Setup:
1. All three VMs are on the same host and shared-vmfs datastore.
2. All three VMs are on the same host and vsan datastore.

Performed following steps across both the setups so that we cover  both vsan and vmfs datastores :
--------
Steps for testing docker service commands:
1. Created a thin provisioned volume from master vm
2. Created a service with replica 1
command: docker service create --replicas 1 --name SrvcOnThinVolm --mount type=volume,source=volXXX,target=/vol,volume-driver=vmdk busybox tail -f /dev/null
3. Verified from VC and ESX - volume was successfully attached to the worker-1
4. Scaled the replica to 2
5. Stopped the service on worker-1. Checked in VC and ESX, volume got attached to worker-2 and worker-1 no longer had volume attached.
6. Tried deleting the volume, but failed as volume was still being used.
7. Deleted the service running in swarm. Volume was no longer attached to any node.
8. Removed the volume successfully.
----------

Did the same steps for volumes of different disk-format types: zeroedthick and eagerzeroedthick

**Comment by ashahi1** [comment]
For vmfs/vsan datastores, if we deploy a service to the swarm with multiple replicas (--replicas) and --mount flag with type=volume, there will be only one instance of container with state as 'Running' and other instances will be in 'Ready' state. 
If the currently running container instance stops or is stopped, another container instance will move from 'Ready' state to 'Running' state since a volume can be attached to only one container at any particular time.

**Comment by pdhamdhere** [comment]
Can you please add output of these commands for e.g. showing nodes, state etc. Please refer to [github markdown](https://guides.github.com/features/mastering-markdown/) for formatting console output in comments.

**Comment by ashahi1** [comment]
1. Created a swarm of three nodes - one master and two worker nodes. All three VMs are on the same host and shared-vmfs datastore
```
root@photon-TX4FfW2ET [ ~ ]# docker node ls
ID                           HOSTNAME          STATUS  AVAILABILITY  MANAGER STATUS
0nu5ndv8jfmby8896nm8v39j4    photon-TX4FfW2ET  Ready   Active
5s7maij1jjybdetc1xed9w2ke    photon-TX4FfW2ET  Ready   Active
azjys9qqaln1nmb9l2et7zoau *  photon-TX4FfW2ET  Ready   Active        Leader
```
2. Created a thin provisioned volume from master vm. Volume is detached currently.
```
[root@sc2-rdops-vm02-dhcp-90-19:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
Volume  Datastore     Created By VM  Created                   Attached To VM (name/uuid)  Policy  Capacity  Used  Disk Format  Filesystem Type  Access      Attach As
------  ------------  -------------  ------------------------  --------------------------  ------  --------  ----  -----------  ---------------  ----------  ----------------------
volXXX  sharedVmfs-0  Master-VM-19   Fri Feb 24 19:00:22 2017  detached                    N/A     100MB     13MB  thin         ext4             read-write  independent_persistent
```
3. Created a service with replica 1.
```
root@photon-TX4FfW2ET [ ~ ]# docker service create --replicas 1 --name bb --mount type=volume,source=volXXX,target=/vol,volume-driver=vmdk busybox tail -f /dev/e98bixgk3y3r1pf5a7wevl8u7
root@photon-TX4FfW2ET [ ~ ]# docker service ps bb
ID                         NAME  IMAGE    NODE              DESIRED STATE  CURRENT STATE          ERROR
ccafihmdu3lltohufum0oztms  bb.1  busybox  photon-TX4FfW2ET  Running        Running 2 minutes ago
root@photon-TX4FfW2ET [ ~ ]# docker service inspect --pretty bb
ID:             e98bixgk3y3r1pf5a7wevl8u7
Name:           bb
Mode:           Replicated
 Replicas:      1
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
ContainerSpec:
 Image:         busybox
 Args:          tail -f /dev/null
 Mounts:
  Target = /vol
  Source = volXXX
  ReadOnly = false
  Type = volume
Resources:
```
4. Worker-2 showed a container running. Checked in the VC and ESX, volume was successfully attached to the worker-2.
```
root@photon-TX4FfW2ET [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
bba78126b92c        busybox:latest      "tail -f /dev/null"   5 minutes ago       Up 5 minutes                            bb.1.ccafihmdu3lltohufum0oztms
```
From ESX:
```
[root@sc2-rdops-vm02-dhcp-90-19:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
Volume  Datastore     Created By VM  Created                   Attached To VM (name/uuid)  Policy  Capacity  Used  Disk Format  Filesystem Type  Access      Attach As
------  ------------  -------------  ------------------------  --------------------------  ------  --------  ----  -----------  ---------------  ----------  ----------------------
volXXX  sharedVmfs-0  Master-VM-19   Fri Feb 24 19:00:22 2017  Worker-2                    N/A     100MB     15MB  thin         ext4             read-write  independent_persistent
```
5. Scaled the replica to 2
```
root@photon-TX4FfW2ET [ ~ ]# docker service scale bb=2
bb scaled to 2
root@photon-TX4FfW2ET [ ~ ]# docker service inspect --pretty bb
ID:             e98bixgk3y3r1pf5a7wevl8u7
Name:           bb
Mode:           Replicated
 Replicas:      2
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
ContainerSpec:
 Image:         busybox
 Args:          tail -f /dev/null
 Mounts:
  Target = /vol
  Source = volXXX
  ReadOnly = false
  Type = volume
Resources:
```
To see the nodes running the service:
```
root@photon-TX4FfW2ET [ ~ ]# docker service ps bb
ID                         NAME      IMAGE    NODE              DESIRED STATE  CURRENT STATE            ERROR
ccafihmdu3lltohufum0oztms  bb.1      busybox  photon-TX4FfW2ET  Running        Running 7 minutes ago
7xah6o6k80zx7w3opjbubi6um  bb.2      busybox  photon-TX4FfW2ET  Ready          Preparing 1 seconds ago
4p0opkgk3wap01zopnojuc2kz   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 1 seconds ago     "starting container failed: Vo…"
5n0nifwxi8w7b56lf6dsjreir   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 6 seconds ago     "starting container failed: Vo…"
carvjus2thbvekveeob8gxaxb   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 12 seconds ago    "starting container failed: Vo…"
c18z9fbphjlu29ko1247k7qjl   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 18 seconds ago    "starting container failed: Vo…"
root@photon-TX4FfW2ET [ ~ ]#
```
6. Stopped the service on worker-2.
```
root@photon-TX4FfW2ET [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
bba78126b92c        busybox:latest      "tail -f /dev/null"   10 minutes ago      Up 10 minutes                           bb.1.ccafihmdu3lltohufum0oztms
root@photon-TX4FfW2ET [ ~ ]# docker stop bb.1.ccafihmdu3lltohufum0oztms
bb.1.ccafihmdu3lltohufum0oztms
```
7. Checked in VC and ESX, volume got attached to worker-1. Worker-2 no longer had volume attached.
```
[root@sc2-rdops-vm02-dhcp-90-19:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
Volume  Datastore     Created By VM  Created                   Attached To VM (name/uuid)  Policy  Capacity  Used  Disk Format  Filesystem Type  Access      Attach As
------  ------------  -------------  ------------------------  --------------------------  ------  --------  ----  -----------  ---------------  ----------  ----------------------
volXXX  sharedVmfs-0  Master-VM-19   Fri Feb 24 19:00:22 2017  Worker-1                    N/A     100MB     15MB  thin         ext4             read-write  independent_persistent
```
From Master-vm:
```
root@photon-TX4FfW2ET [ ~ ]# docker service ps bb
ID                         NAME      IMAGE    NODE              DESIRED STATE  CURRENT STATE          ERROR
00abzwlg63vxya0xc9wf5tfyl  bb.1      busybox  photon-TX4FfW2ET  Ready          Ready 2 seconds ago
a1mmdla9etnb89mhxnv4lmqwj   \_ bb.1  busybox  photon-TX4FfW2ET  Shutdown       Failed 4 seconds ago   "starting container failed: Vo…"
750qom1gqcbfhgsi6tqrv8hn8   \_ bb.1  busybox  photon-TX4FfW2ET  Shutdown       Failed 9 seconds ago   "starting container failed: Vo…"
9kzggmo8qgvgjzfkhw8h03w8w   \_ bb.1  busybox  photon-TX4FfW2ET  Shutdown       Failed 15 seconds ago  "starting container failed: Vo…"
eisdpt61yvkz64j50twxablz1   \_ bb.1  busybox  photon-TX4FfW2ET  Shutdown       Failed 20 seconds ago  "starting container failed: Vo…"
4g7y1zb8dl9g3cq74idszsy5d  bb.2      busybox  photon-TX4FfW2ET  Running        Running 2 minutes ago
b98pp7n8xlm3ol1fbpwsg81nf   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 2 minutes ago   "starting container failed: Vo…"
2ea65s9jpqze6ay2dtg7i32tt   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 2 minutes ago   "starting container failed: Vo…"
1x69defsmcy1w9lqky92cpjq4   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 2 minutes ago   "starting container failed: Vo…"
90bl4e2vid78cs7ki1xukrboq   \_ bb.2  busybox  photon-TX4FfW2ET  Shutdown       Failed 3 minutes ago   "starting container failed: Vo…"
```
8. Tried deleting the volume, failed as volume was still being used.
```
root@photon-TX4FfW2ET [ ~ ]# docker volume rm volXXX
Error response from daemon: Unable to remove volume, volume still in use: remove volXXX: volume is in use - [95ade549b9f10c0cdd075488d94a5b4d7e1140504e1e947c1f9e76e6dcd65669, 6bd806eaaa79e12c75928261ed05046bd48c850345a499322ec4200b01e27c01, 7e8d1c5ac5a5a31abc50be1fa06d7242c10e7dabbcfc231880dee78e96b4696d, 0223476e4446da0f7b58be7381d9956aec79c09d3d862f1fca413a6032c4aa36]
root@photon-TX4FfW2ET [ ~ ]#
```
9. Deleted the service running in swarm. 
```
root@photon-TX4FfW2ET [ ~ ]# docker service rm bb
bb
root@photon-TX4FfW2ET [ ~ ]# docker service ps bb
Error: No such service: bb
```
10. Volume was no longer attached to any node. Verified from VC and ESX.
```
[root@sc2-rdops-vm02-dhcp-90-19:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
Volume  Datastore     Created By VM  Created                   Attached To VM (name/uuid)  Policy  Capacity  Used  Disk Format  Filesystem Type  Access      Attach As
------  ------------  -------------  ------------------------  --------------------------  ------  --------  ----  -----------  ---------------  ----------  ----------------------
volXXX  sharedVmfs-0  Master-VM-19   Fri Feb 24 19:00:22 2017  detached                    N/A     100MB     15MB  thin         ext4             read-write  independent_persistent
```
11. Removed the volume
```
root@photon-TX4FfW2ET [ ~ ]# docker volume rm volXXX
volXXX
```

**Comment by tusharnt** [comment]
@pdhamdhere, Do you have any more comments on this or can this be closed?

**Comment by pdhamdhere** [comment]
Thanks @ashahi1 

Added test-needed label to add test.

**Comment by lipingxue** [comment]
@ashahi1 
The --replica option in swarm is not used to scale a stateful application. Instead, it should used to scale a stateless application. So why do we try to add the test with --replica 2 here? Any specific reason? @ashahi1

**Comment by ashahi1** [comment]
@lipingxue I added --replica as I wanted to test fail-over condition. Basically checking if service starts running the second instance if the first one goes down.

**Comment by shaominchen** [comment]
As @lipingxue pointed out, the scaled-replicas feature should not be used for stateful applications. Please refer to https://github.com/moby/moby/issues/24089

However, we discussed and agreed that it still makes sense to keep this test scenario. Basically, #927 will focus on failover across different swarm nodes, while this test will focus on failover across different swarm service replicas, even though the volume cannot be attached to two service replicas at same time.
