### ISSUE TITLE
Errno=104

### ISSUE THREAD

**Issue by FarhadF** [vmware/docker-volume-vsphere#602]
Hi guys,

I'm getting this error.
`Error response from daemon: create MyVolume: VolumeDriver.Create: 'create' failed: connection reset by peer (errno=104). Cannot communicate with ESX, please refer to the FAQ https://github.com/vmware/docker-volume-vsphere/wiki#faq`

Already read  the FAQ, The only problem is my docker VMs aren't on the same host with VIB installed. Is this the problem?  I assume so because there is no esxi IP/NAME in the configs...

Any clarification on this matter would be appretiated.

**Comment by pdhamdhere** [comment]
Correct. VIB must be installed on ESX hosting Docker VMs.

**Comment by FarhadF** [comment]
Thanks for the fast response, Let me throw another question here:
Does the plugin support swarm mode at the moment? When Containers restart on different node with persistent volume attached.

**Comment by pdhamdhere** [comment]
Yes, I successfully tested swarm "on-node-failure" policy with vSphere Docker volumes. All VMs in Swarm cluster must have vSphere Docker Volume service and ESX should have VIB installed.

**Comment by FarhadF** [comment]
Thanks for the feedback, I'll Open the issue again if my tests fail.
