### ISSUE TITLE
Update documentation and demos for file system format option

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#604]
Documentation and demos need updating post https://github.com/vmware/docker-volume-vsphere/pull/597 merge

**Comment by brunotm** [comment]
@kerneltime 
There is more documents needing an update other than the README.md?

**Comment by kerneltime** [comment]
Yup. https://vmware.github.io/docker-volume-vsphere/ content needs updating which gets generated from https://github.com/vmware/docker-volume-vsphere/tree/master/docs. We will be cutting a release on the 28th, if it is not done by then I will do it as part of the release.

**Comment by brunotm** [comment]
I will look into it.
Should #35 also be closed after #597 merge? Found it in the README.md and remember @msterin commenting something about a similar issue.

**Comment by msterin** [comment]
@brunotm - unfortunately  #35 is still valid. #597 makes it low(er) priority - before your fix `create of a large volume` blocked ALL plugins on the given ESX host for the time it took to format the volume. Now, it only blocks an individual Docker engine plugin, but other Docker VMs are fine. 
Still, everything is serialized per Docker engine, and other ops are serialized globally.

**Comment by kerneltime** [comment]
Fixed in #605
