### ISSUE TITLE
Update of "docker create" -o parsing, and -datastore options support in the plugin

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#61]
This is a tracking item for the following work: 
- Set a list of known -o options and warn if the option is unknown (we do not want to fail as it will make it harder to add new things, like -o action=<action> 
  - note: whoever works on this, please have a quick discussion on "fail vs warn" here
  - add validation parser to size=<size>. Currently it will fail on ESX side if the syntax is wrong.  It's OK to fail on ESX side but we need to check the error handling. Or we can parse and fail on Docker side
- add -datastore=<> option (this one can be pushed out to v1.next - but please create a PR if doing so)

**Comment by yadzhang** [comment]
-o datastore= : Optional. Default the datastore where the Docker VM resides. 
"docker volume create" does not support this option now. And just support 
_Valid options and defaults: [('size', '100mb'), ('vsan-policy-name', '[VSAN default')]_

**Comment by msterin** [comment]
@yadzhang - the `-o datastore` is not in TP and the work is tracked in #288
