### ISSUE TITLE
need implement code get_auth_db_path

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#618]
For multi-tenancy support, we need to store some informations in the database. We choose to 
use sqlite3 DB.
Currently, the following 4 tables are created.
- tenants
- vms
- privileges
- volumes
  For detail of this authorization database, please refer to this wiki.
  https://wiki.eng.vmware.com/Authorization_Spec#Authorization_Databases

This function need to return the path of the authorization  database.  Currently, the function returns a hardcoded string. But later we need change this function based on the following algorithm.
- If VSAN datastore is available, store the DB at VSAN datastore/dockvol/DB_name
- If VSAN datastore is not available, check if other shared datastore is available, if yes, store the DB at shared_datastore/dockvol/DB_name
- Otherwise, return error

**Comment by pdhamdhere** [comment]
@lipingxue Is this still relevant?

**Comment by pdhamdhere** [comment]
Not relevant with design changes.
