### ISSUE TITLE
Extra work in Tenant authorization - fallbacks and defaults

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#621]
1.handling "fallback" tenant (When VM does not belong to any tenant)
2. handing "fallback" privileges (no matching privileges is found in privileges table)
3. handling default datstore (for volume_name without@datastore)

**Comment by msterin** [comment]
Here is  a quick design sketch for the items above, from our discussion yesterday:
# handling "fallback" tenant 
* When a VM which does not belong to any tenant issues a request to vmdk_ops, we will check in auth_db for the presense of "__FALLBACK" tenant. 
* if this tenant is present, this VM will be assumed to be in __FALLBACK tenant, and will get privileges associated with this tenant
** note that auth_db record will not be added for this VM
* __FALLBACK tenant will be automatically added on DB creation, so by default vmdk_ops will support request from any VM , thus maintaining backward compatibility and simplicity of installation 
* an admin can remove this teanant or modify privileges, thus locking down vmdk_ops to serve only explicitly configured VMs
* __FALLBACK tenant is handle just like all other tenants - all volumes are in dockvols/__FALLBACK and visible only to VMs not in other tenantsa
* if a VM is assigned to another tenant, it loses access to __FALLBACK volumes, just like in any other  VM reassignment to a different tenant

# handing "fallback" privileges 
* When a VM tries to manipulate volumes on a datastore which is not configured in auth_db  (privileges table) , the system will use privileges from "fallback" record in the `privileges` table. This record will have DB name "__FALLBACK" and Vm name '*'. 
* we will create this record on auth_db creation , thus allowing access to ANY datastore by default
* an admin can edit or remove this record, thus locking down the functionality to allow access only to explicitly configured datastores

# handling default datastore (for volume_name without@datastore)
* When a VM addresses the volume using short notation (`volume_name`, without `@datastore`), we currently use the datastore this VM config file is located on (aka "VM datastore"). We also strip `@datastore` from `docker volume ls` output for the volumes located on the VM datastore.  
** With introduction of tenants, this schema will force admin to open access to ALL VM datastores to any VM in the tenant, and will force to keep privileges table contant record for each VM's datastore. 
** as an alternative, user can alsways refer to volumes with a full name `volume@datastore` which makes docker volume user know and remember lots of irrelevant datastore names
* to address this, we will introduce "default datastore" for a tenant.
** ALL VMs in this tenant will use default datastore as the one in short volume reference (`volume_name` will actually mean`volume_name@default_datastore`. 
** Default datastore name will be also stripped from 'docker volume ls' output. 

This design is open for comments.

//CC @pdhamdhere @marksoper @andrewjstone @kerneltime @govint

**Comment by andrewjstone** [comment]
I was prepared to have some comments, but I only have one. It looks great! 👍

**Comment by andrewjstone** [comment]
Very creative idea with the fallback tenant, so you can give permissions :)

**Comment by msterin** [comment]
A small update: if there are volumes in dockvols already when we upgrade the binaries. we need to warn and try to move them to __FALLBACK tenant

**Comment by kerneltime** [comment]
It would be nice to move the volumes to a tenant post upgrade. But what is the expectation post install default for fallback? Do we want out of the box experience to be permissive or limited?
