### ISSUE TITLE
vmdkops-admin-cli-spec.md needs update to reflect new Tenants design

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#622]
it currently says

```
# tenant
Create, delete, configure and show access control settings for a Tenant.
A tenant is defined as a collection of VMs, so access control settings are assigned via a
VM naming convention.
*** The rest of section below needs rework as it represents obsolete "role" design ***
```

We need to update the doc to match the design/implementation

**Comment by kerneltime** [comment]
The public facing admin cli spec is https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/admin-cli.md posted here https://vmware.github.io/docker-volume-vsphere/user-guide/admin-cli/

**Comment by pdhamdhere** [comment]
@kerneltime Close?
