### ISSUE TITLE
Support admin CLI option (-f) to accept a script of commands and client CLI.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#625]
Admin CLI should allow users to script their container infra on VSphere, let admin CLI support a -f option.

Consider a guest side admin CLI that can download a script to a host and have it executed there.

The vmdk-ops server could handle the requests  to invoke the API that CLI commands use today (or later) - either individual commands or a script sent by the guest-side CLI client.

Users may not always use the GUI and allowing container users to script their infra would be great to have.

CC @vmware/cna_storage-maintainers

**Comment by msterin** [comment]
What exactly do you expect -f to do, and why it is needed in addition to uaing the CLI or API ?

**Comment by govint** [comment]
Today the user runs each command as a separate invocation of the admin CLI, this issue is to support users to be able to script their configuration and be able to run that to create what configuration they need.

**Comment by govint** [comment]
Good to have but not a feature that we absolutely need.
