### ISSUE TITLE
error code is not reported to 'docker volume get' 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#628]
When server returns error on `get()` operation, this error is not reported to Docker command line. 
To repro, add an error to server vmdk_ops.getVMDK() - it shows in the error log on ESX but not reported on Docker: 

ESX: 

```
10/15/16 08:04:40 52044 [photon-1] [INFO   ] executeRequest 'get' completed with ret=Failed to get disk details for /vmfs/volumes/vsanDatastore/dockvols/v11.vmdk
```

Guest:

```
 docker volume inspect v11@vsanDatastore
[]
Error: No such volume: v11@vsanDatastore
root@photon-1 [ ~ ]# 
```

(found when investigating #627 )

**Comment by govint** [comment]
The code returns the error to the client (from the guest) and the client plugin code also returns the error to docker. Seems like docker is displaying the error when it gets an error response.

**Comment by msterin** [comment]
@govint - can you open a related issue for engine-api then?  They need to print original error msg too...

**Comment by govint** [comment]
This is the code:
  ---
// VolumeInspectWithRaw returns the information about a specific volume in the docker host and it's raw representation
func (cli *Client) VolumeInspectWithRaw(ctx context.Context, volumeID string) (types.Volume, []byte, error) {
        var volume types.Volume
        resp, err := cli.get(ctx, "/volumes/"+volumeID, nil, nil)
        if err != nil {
                if resp.statusCode == http.StatusNotFound { <-------- code seems to be setting this status, otherwise, the error returned by the plugin is returned below.
                        return volume, nil, volumeNotFoundError{volumeID}
                }
                return volume, nil, err
        }
   .....
  ---

**Comment by shaominchen** [comment]
Hi Govindan, can you take care of this since you already have some analysis?

**Comment by govint** [comment]
This is an issue with how docker is handling errors returned from Get(). I'll raise an issue on Docker and closing this one as there are no changes for the plugin.
