### ISSUE TITLE
Bundle docker-volume-vsphere with Photon OS

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#634]
- Add docker-volume-vsphere to Photon OS tdnf repository so that `tdnf update` can fetch latest plugin binaries.
- Package & install docker-volume-vsphere plugin with minimal Photon installation. VMDK Plugin service should be installed but deactivated. User will have to manually activate VMDK plugin: `systemctl enable docker-volume-vsphere`

New packages can be added in Photon OS by adding a SPEC file in [Photon SPECS folder](https://github.com/vmware/photon/tree/master/SPECS)

CC/ @kerneltime @govint @sharathjg @gregmmurray

**Comment by kerneltime** [comment]
- [ ] need to add versioning for RPC between ESX and Plugin, if their install and upgrade lifecycle needs to be split.

**Comment by tusharnt** [comment]
Now that managed plugin is supported customers can easily automate vDVS installation in their Photon OS based deployment. So there is no reason to fix this issue.
