### ISSUE TITLE
Unable to start vmdk-ops service - python sqlite3 package not found.

### ISSUE THREAD

**Issue by BaluDontu** [vmware/docker-volume-vsphere#646]
Hey guys,

I am unable to install the vib on my ESX 6.0 host (basic version). It fails with the following error 
"ImportError: No module named sqlite3".

I think sqlite3 python binary is not by default present in ESX 6.0 basic and U1 versions. So the vmdk-ops service fails running. Can you please address this issue.

Thanks,
Balu

**Comment by msterin** [comment]
this is a regression from auth PR #603 - it adds dependency on sqlite3 py module, but does not check it. 
And it is present in ESX 6.0 U2+ only - which is what we use in CI and dev env. 
 
We should simply include our own copy and update the sys.path.

//CC @lipingxue @pdhamdhere
