### ISSUE TITLE
vmdkops_admin.py - ImportError: No module named argparse

### ISSUE THREAD

**Issue by hreidar** [vmware/docker-volume-vsphere#647]
Any idea on how to fix this?

/tmp # esxcli --version
Script 'esxcli' version: 5.5.0
/tmp # 
/tmp # esxcli software vib install --no-sig-check -v /tmp/vmware-esx-vmd
kops-1.0.beta.vib 

Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: VMWare_bootbank_esx-vmdkops-service_1.0.0-0.0.1
   VIBs Removed: 
   VIBs Skipped: 
/tmp # 
/tmp # 
/tmp # /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 18, in <module>
    import argparse
ImportError: No module named argparse
/tmp #

**Comment by msterin** [comment]
Thanks for reporting this one. 
Per Readme.md we tested on ESX 6.0 and newer. 
It looks like you are running 5.5. It does not have some Python modules (argsparse is one of them). 
But I agree the behavior is wrong, we should either block VIB install or provide a clear failure message. 

//CC @pdhamdhere

**Comment by msterin** [comment]
An update - there is more in the code dependent on ESX 6.0, so we currently do not plan to support ESX 5.5

@kerneltime  - we need to block install on pre-6.0 ESX using <depends> in VIB XML.

**Comment by pdhamdhere** [comment]
Fixed with #674
