### ISSUE TITLE
Implement tenant describe command

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#651]
Implement "tenant describe" which lists everything related to tenant including list of VMs.

Background:
Prashant mentioned in the PR https://github.com/vmware/docker-volume-vsphere/pull/645

Number of VMs in a tenant could be really large and obfuscate the tenant ls output on screen. May be introduce tenant describe which lists everything related to tenant including list of VMs.

**Comment by govint** [comment]
Closing and instead review vmgroup set of admin cli commands and raise a new issue if something is needed there similar to this.  Admin cli vmgroup set allows these:

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup -h
usage: vmdkops_admin.py vmgroup [-h] {vm,create,update,ls,access,rm} ...

optional arguments:
  -h, --help            show this help message and exit

Administer and monitor volume access control:

  {vm,create,update,ls,access,rm}
                        action
    vm                  Add, removes and lists VMs in a vmgroup
    create              Create a new vmgroup
    update              Update an existing vmgroup
    ls                  List vmgroups and the VMs they are applied to
    access              Add or remove Datastore access and quotas for a
                        vmgroup
    rm                  Delete a vmgroup
