### ISSUE TITLE
Cleanup work for "AdminCLI change to support multitenancy"

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#653]
The following work are needed as cleanup work for "AdminCLI change to support multitenancy"
- The message printed out when cmd succeeds should be changed to make sure they are consistent with existing AdminCLI command
-  The code in this PR https://github.com/vmware/docker-volume-vsphere/pull/645
  assume the "tenant_name" is unique, we should decide how to handle if the "tenant_name" 
  is not unique. See @govint comments in #645 on the subject as well
- Tests need to be added for error condition , i.e. something that causes auth.py code to throw exceptions
- Also, from #645 review: 
  - max_size should be validated to be under the datastore size
  - functions dealing with internal DB data structures should be in auth.py
  - tenant delete should not exit on individual vmdk delete failure. It should print & save the info and continue to try to finish the cleanup

**Comment by pdhamdhere** [comment]
All done with #645 and #729
