### ISSUE TITLE
Get configured size of disk chain when getting disk size.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#665]
getVMDK() uses the disklib API to fetch current disk size stats for a docker volume. Currently its fetching the stats for the newest element in the disk chain which works fine for single disks with a disk chain (snaps for example) need to get the size of the actual disk vs. for the element in the chain.

**Comment by brunotm** [comment]
@govint
I couldn't find any available documentation on libvmsnapshot or DiskLib_GetSize(), there's anything that can be shared?

**Comment by govint** [comment]
@brunotm these are ESX libraries and don't have any documentation as such.
