### ISSUE TITLE
vSphere 6.5 readiness

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#666]
[vSphere 6.5](https://blogs.vmware.com/vsphere/2016/10/introducing-vsphere-6-5.html) is on it's way. This issue is to track and verify vSphere docker volume service works out of box on ESX 6.5

- ESX 6.5 ships with Python 3 only. Make sure ESX components (vmdkops and admin CLI) are Python 3 compatible
- Install VIB and run CI tests with ESX 6.5
- Add ESX 6.5 to CI test matrix.

CC/ @msterin @shuklanirdesh82

**Comment by govint** [comment]
Do we want to collect issues here and solve as one change? In which case here is one (we can keep adding perhaps to the list):
  ---
1/ Use "as" vs. ",' in except block:
 python /usr/lib/vmware/vmdkops/bin/vmdk_ops.py -p 1019
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 81, in <module>
    import vmdk_utils
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 25, in <module>
    import vmdk_ops
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 84, in <module>
    import auth
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 58
    except sqlite3.Error, e:
                        ^
SyntaxError: invalid syntax

**Comment by pdhamdhere** [comment]
[vSphere 6.5 is GA](https://www.vmware.com/support/pubs/vsphere-esxi-vcenter-server-6-pubs.html)! Build# 4564106
