### ISSUE TITLE
Improve the format of "tenant access ls" output

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#682]
Currently the "tenant access ls" output shows like this:

[root@localhost:/usr/lib/vmware/vmdkops/bin] vmdkops_admin tenant access ls --name MyTenant
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              0             128.00MB         1.00GB      

The create/delete/mount privileges should be shown as boolean values ("True" and "False") instead of 1 and 0. Even though the backend db schema type is INTEGER (SQLite doesn't support Boolean), we should be able to convert the output format very easily.

This is not a correctness issue, but I think it's not user friendly and affects the usability a little bit.

**Comment by kerneltime** [comment]
I was about to file the same issue :-)
```
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access ls --name tenant1
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  1              1              1             0B               0B   
```
