### ISSUE TITLE
Tenancy: Creating volume fails in absence of "mount" privilage

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#709]
Creating volume fails with "No mount privilege" though VM has "create" privilage.
```
# docker volume create -d vmdk --name=vol101 
Error response from daemon: create vol101: VolumeDriver.Create: No mount privilege
```
This VM is member of Tenant- T6
```
[root@localhost:~] vmdkops_admin tenant create --name=T6 --vm-list=test1
tenant create succeeded
[root@localhost:~] vmdkops_admin tenant access add --datastore=datastore1 --rights=create,delete --name=T6
{'mount_volume': 0, 'global_visibility': 0, 'max_volume_size': 0, 'create_volume': 1, 'delete_volume': 1, 'datastore': 'datastore1', 'usage_quota': 0}
tenant access add succeeded
[root@localhost:~] vmdkops_admin tenant access ls --name=T6
Datastore   Create_volume  Delete_volume  Mount_volume  Max_volume_size  Total_size  
----------  -------------  -------------  ------------  ---------------  ----------  
datastore1  True           True           False         Unset            Unset       
```

Creating a volume requires volume to be attached/detached to VM for formatting. Attaching volume to VM requires mount privilege and thus create volume fails with "No mount privilege".

CC/ @lipingxue @msterin

**Comment by lipingxue** [comment]
If the user has the create privilege, does it imply he/she should have mount privileges? @pdhamdhere  @msterin ?

**Comment by pdhamdhere** [comment]
It would be absurd to not have mount privilege when you are allowed to create volume. So, Create implies remove, mount, unmount privilege and `--rights` is obsolete? If datastore access is granted then VMs within that tenant has full access (create, remove, mount, unmount, list, get). Makes sense to me.

**Comment by msterin** [comment]
Let's say I want to provision volumes for a tenant manually and I do not want tenant VMs to use only pre-created volumes. 

So I would say if the access is granted, still can have 2 levels
* _All_ privileges: create/delete/set/mount/unmount
* _Use_ privilege: mount/unmount (attach)

this brings a question "how this volume would be created". Ideally, 'docker volume create -o tenant=<other_tenant>. That brings another concept (not for this PR)
* _root_ (or su): a right to manipulate volumes in other tenants.

**Comment by lipingxue** [comment]
Already fixed, close it.
