### ISSUE TITLE
Tenancy: tenant name need to be unique

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#711]
Tenant name in "tenant table" need to be unique.

**Comment by pdhamdhere** [comment]
If we make tenant name unique then we won't need tenant-uuid right?

**Comment by lipingxue** [comment]
Yes.  the "tenant_uuid" will not need if we make the "tenant_name" unique. Is there any use cases that require "tenant_name" not unique? I cannot think of any. @msterin

**Comment by lipingxue** [comment]
Currently, the quick fix I made is to mark both "tenant_uuid" and "name" as primary key in "tenants" table. I also add some code in "create_tenant" function to check whether a tenant with the given name already exists or not. If the tenant already exists, return with error.

The complete fix should be remove "tenant_uuid" from "tenants" table and also change corresponding SQL statements.

**Comment by lipingxue** [comment]
Manually unit test:
1. create a tenant "tenant1"
```
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list    
------------------------------------  -------  -----------  -----------------  ---------  
b00870a1-e652-4b9e-93f3-7434476a43b2  tenant1               default_ds         photon-v1  
```
2. try to create another tenant with the same name "tenant1", which should fail
```
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant create --name tenant1 --vm-list photon-v1
WARNING:root:Tenant tenant1 already exists
Tenant tenant1 already exists
```

**Comment by msterin** [comment]
As long as tenant _rename_ is supported, we can stick with the name as a unique key

**Comment by lipingxue** [comment]
In auth_data.py, we do have API "set_name" to change the name of a tenant. In AdminCLI, we do not have code to rename a tenant.

**Comment by lipingxue** [comment]
#715 is filed to track the AdminCLI work to rename a tenant.
