### ISSUE TITLE
Tenancy: Add AdminCLI command to rename a tenant.

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#715]

**Comment by lipingxue** [comment]
Manually unit test:

1. 

 rename existing "tenant1" to a new name "new_tenant1"
```
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name     Description  Default_datastore  VM_list    
------------------------------------  -------  -----------  -----------------  ---------  
d1cd4387-8ecb-4433-8175-44cdd45fa34c  tenant1               default_ds         photon-v1  

[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant rename --help
usage: vmdkops_admin.py tenant rename [-h] --new_name NEW_NAME --name NAME

optional arguments:
  -h, --help           show this help message and exit
  --new_name NEW_NAME  The new name of the tenant
  --name NAME          The current name of the tenant
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant rename --name=tenant1 --new_name=new_tenant1
tenant rename succeeded
[root@localhost:~]  /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name         Description  Default_datastore  VM_list    
------------------------------------  -----------  -----------  -----------------  ---------  
d1cd4387-8ecb-4433-8175-44cdd45fa34c  new_tenant1               default_ds         photon-v1  

```

**Comment by pdhamdhere** [comment]
@lipingxue TenantName is used as directory name for storing volumes. Renaming a tenant either has to rename directories on assigned datastores or we will have to maintain mapping somewhere or create sym links?

**Comment by lipingxue** [comment]
I discussed this with Mark. This is the redesign we need to do for this:
- currently, we create a directory "datastore/dockvol/tenant_name" to store all volumes created by this tenant. 
- the proposed change is
  1) we don't create directory by using tenant_name, instead we use tenant_uuid. So we will create a directory like "datastore/dockvols/tenant_uuid" to store all volumes create by this tenant. The good thing about this is "tenant_uuid" will not change after tenant is created, and we don't need to rename the directory after user rename the tenant.
2) After directory "datastore/dockvols/tenant_uuid" is created, we create a symlink "datastore/dockvols/tenant_name" to point to this path. Then when user rename the tenant, we just need to remove the old symlink and then create the symlink like this "datastore/dockvols/new_tenant_name"
