### ISSUE TITLE
vmdk_ops.py:removeVMDK() must check that a volume isn't in use before even attempting to remove it.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#719]
Add check for usage before disk is removed.

**Comment by msterin** [comment]
Before we introduced KV files there was no need to check, as the VMX and VMFS locks were checking it for us. With sidecar KVs, we planned to rely on sidecar / vmdk transactionality (that, in fact, was top reason to pick up sidecars).  Unfortunately it is not working as promised, but my suggestion would be to just recover KV file if removeVMDK fails - it will have to happen very unfrequently, while check for usage will have to happen every time.

**Comment by govint** [comment]
This is a bug in the way a disk unlink is working presently. Looks like the fix is part of #716 so, I'll close this one.

**Comment by pdhamdhere** [comment]
Opened accidentally.
