### ISSUE TITLE
Versioning tolerance (Plugin, Server, CLI, UI)

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#724]
- Support backward compatibility. Volumes created with earlier version should be usable after upgrade.
- Make sure Plugin, Server and CLI with different versions can interoperate. 
- We can brainstorm and limit the matrix but at very least each component need to be 1 release backward compatible.
- Add unit tests to avoid regressions.

This is a pre-requisite to bundle vSphere Docker Volume Service with Photon OS (See #634). Upgrades for In-guest components (Plugin) and Server components (Server, CLI, UI) are managed by different identities and they are likely to be out of sync.

Adding 0.9 milestone. We may not finish all the work for 0.9 but we need to get started on this asap.

**Comment by msterin** [comment]
This one seems to be a superset of #318

**Comment by kerneltime** [comment]
Not sure why this was tagged for 0.9 it has not been scoped or assigned.

**Comment by shuklanirdesh82** [comment]
This issue depends on the protocol version introducing as part of #318. 

As we haven't reach GA yet, following has been planned to achieve till GA.

- [ ] #318 should be done as part of 0.13
- [ ] prepare some testcases during 0.13 -> v1 GA with versioning changes
- [ ] Any future releases should be backward compatible with GA

**Comment by tusharnt** [comment]
#318 and #1059 track the work mentioned in this issue.
