### ISSUE TITLE
Tenancy: need add code to validate input parameters for all AdminCLI for tenant management

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#734]
Comments from PR #729  suggested that input parameters for all AdminCLI for tenant management need to be validated .
For detail, see this PR https://github.com/vmware/docker-volume-vsphere/pull/729

**Comment by tusharnt** [comment]
@ashahi1 can you please check whether we have any gaps in this area? Please add details about the tests you're running and their outcome.

**Comment by lipingxue** [comment]
I think we already have those checks in the current code, close this issue.
