### ISSUE TITLE
unit test for multi-tenancy need to be data-driven

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#740]
The following is from review comment for this PR  https://github.com/vmware/docker-volume-vsphere/pull/729
A general comment on tests: it is better to have them data drivel . I.e. instead of using tenantx_volx ad opts and other stuff in the code, ALL that should be in data structures and the test should just taverse the structures. See example (testInfo traversing) in vmdk_ops_test.py.

It's OK to leave it as is for this PR but please do open an issue for test rearrangement and making them data driven - that allows to understand tests better and to add to the test set easily

**Comment by govint** [comment]
Closing and please check the e2e vmgroup tests and figure if any thing is missing there.
