### ISSUE TITLE
installing ESXi VIB (release 0.8.1) does not work on Photon Platform ESXi host

### ISSUE THREAD

**Issue by guillierf** [vmware/docker-volume-vsphere#764]
hi

I tried to installed vmware-esx-vmdkops-0.8.1.vib on an ESXi host prepared with Photon Platform and I got the following message:

root@localhost:/tmp] esxcli software vib install --no-sig-check -v /tmp/vmware-esx-vmdkops-0.8.1.vib 
 [DependencyError]
 VIB VMware_bootbank_photon-controller-agent_v1.0.0-c8a0db0's acceptance level is community, which is not compliant with the ImageProfile acceptance level partner
 To change the host acceptance level, use the 'esxcli software acceptance set' command.
 Please refer to the log file for more details.
[root@localhost:/tmp] 

is there a way to force the vmware-esx-vmdkops-0.8.1.vib VIB software acceptance level to CommunitySupported ?

thanks in advance

**Comment by guillierf** [comment]
note: using the --force option works

[root@localhost:/tmp] esxcli software vib install --no-sig-check -v /tmp/vmware-esx-vmdkops-0.8.1.vib --force
Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: VMWare_bootbank_esx-vmdkops-service_0.8.1-0.0.1
   VIBs Removed: 
   VIBs Skipped: 
[root@localhost:/tmp]

**Comment by pdhamdhere** [comment]
@guillierf vSphere Docker Volume Service is NOT supported on Photon Platform. We are actively exploring options to integrate with Photon Platform. Is there specific use case you have in mind?

CC/ @govint @AlainRoy  @asomaiah

**Comment by pdhamdhere** [comment]
Photon Platform support is tracked in different forum.
