### ISSUE TITLE
Automated testbed deployment 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#773]
This involves automating the testbed deployment
# Internal
- [x] Single command to   deploy a testbed with one ESX 6.0U2, VMFS & VSAN datastores and two Photon VMs on each datastore (default configuration docker 1.11).

- [x] need to have support for docker update version too i.e. 1.12

- [x] Automating configuration of IPTables and upgrading the docker version on the photon VMs

# External
- [ ] List the steps needed to deploy a testbed manually from outside the VMware's network and update Contributing.md

**Comment by kerneltime** [comment]
# Internal

- [ ] Add support for selection version of ESX
- [ ] Add support for selection of OS distro

**Comment by lipingxue** [comment]
Can we add support to set the default logging level to DEBUG? That would be very helpful for debugging the test failure.

**Comment by shuklanirdesh82** [comment]
closing this as `wontfix` for an external testbed deployment on the other end we do have separate issue taking care for such work. 

The required work for an internal testbed deployment is done.
