### ISSUE TITLE
Tenant Admin CLI may return obsolete VM name

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#783]
Currently we are persisting both VM ID and VM name in the backend database. However, VM name can be changed after the VM was created. If this happens, when user executes Tenant Admin CLI such as "vmdkops_admin tenant ls" or "vmdkops_admin tenant vm ls", the command will return obsolete VM names.

Some possible options to resolve this issue:
1. Don't persist VM name. Always query VM name at runtime
2. Still persist VM name. When user executes Tenant CLI queries (i.s. "tenant ls" or "tenant vm ls"), query and return the latest VM name, also update the db if necessary.

**Comment by pdhamdhere** [comment]
Good catch. We only need to store UUID and convert UUID to VM Name when needed at runtime. See related PR #722

**Comment by shaominchen** [comment]
This issue has already been fixed as part of https://github.com/vmware/docker-volume-vsphere/pull/828

I have verified the scenario and it works now.
