### ISSUE TITLE
Revisit how tests are run for CI to reduce over all time taken.

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#806]
CI runs currently take around 1.5 hours. Out of which 2 test take around 40 minutes (10 min each run * (2 ESX * 2 Backends per ESX)  (tests: vmdk_ops_test.py + vmdkops_admin_test.py). Not all of the tests need to be run per back end and some of the tests can be skipped as the risk of breakage is low and those can be run as part of master builds only.
Some ideas for improving CI run times.
- [ ] Which tests should be run only once per ESX

- [ ] Which tests can be skipped for PRs

- [ ] Run each ESX version run in parallel

- [ ] Adding more Virtual machines to get more parallel runs.

**Comment by brunotm** [comment]
@kerneltime 
I have an old change laying around, that wires the CI run type (VSAN/VMFS) to the tests that should run but it can help to save some, eg:

- On VSAN, run everything on VSAN datastores (all the unit tests and vms creation)
- On VMFS don't run VSAN tests even if a VSAN datastore is available.

It is unfinished and I just rebased it against master at [hint-vsan-unity-tests](https://github.com/brunotm/docker-volume-vsphere/tree/brunotm.hint-vsan-unity-tests) if this looks interesting for this issue i can try to continue the work on it.

**Comment by kerneltime** [comment]
Did a quick scan, looks good, let me know when you think it is ready, I can update the .drone.sec file in that branch to allow you to do a PR

**Comment by govint** [comment]
Closing this as newer e2e tests and issues are in use and efforts on to check how those can be optimized.
