### ISSUE TITLE
Change name of vmdk plugin driver to "vsphere"

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#812]
With the addition of  a "photon" volume type to the volume plugin, for consistency, change "vmdk" volume type to "vsphere".

**Comment by pdhamdhere** [comment]
Should we support both vSphere as well as VMDK?

**Comment by govint** [comment]
Possibly only have "Vsphere" as the other plugin is for "photon" both of
which are platform specific. vmdk is common to both.

**Comment by govint** [comment]
One catch with changing the driver name to "vsphere" is existing volumes created with the "vmdk" driver won't be usable. Because Docker won't find  driver of that name anymore. Can be worked around by having two listeners to handle requests with two different names (vmdk and vsphere) and deprecate the vmdk listener in a subsequent release. Or if this issue isn't adding much value suggest deferring or rejecting it all together.

CC @pdhamdhere

**Comment by govint** [comment]
Closed via #919
