### ISSUE TITLE
Investigate execution times of concurrent tests on VSAN

### ISSUE THREAD

**Issue by brunotm** [vmware/docker-volume-vsphere#813]
The actual (before #802) concurrent tests on CI usually takes around 80 seconds to complete in vmfs datastores. On vsan it can take anywhere between 80 to 3000 seconds to complete.

Investigation is needed to understand if some kind of adjustment is needed in the vmdk_ops service when running on VSAN, which may not be tuned for the rate of create/delete operations of the tests or if we are triggering background processess that slow's it down.

**Comment by govint** [comment]
Pulling in this one to figure if there is an issue to address or not.

**Comment by shuklanirdesh82** [comment]
duplicate to #1057
