### ISSUE TITLE
Add Test: create volume with access:read-write and later change it to read-only

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#820]
Requirement: at-least 2 docker VMs (VM1 & VM2) on the same ESX host

Test objective: update access option for the volume

1. covert read-only volume to read-write and back to read-only
2. covert read-write volume to read-only and back to read-write

Automation steps:

Steps for #1:

1. create a volume Vol1 as ('access', 'read-write')
2. attach a container from VM1 and write to volume and exit
3. access the volume from VM2 and read the data written by VM1 and modify the data to make sure VM2 is able to write to the volume and exit
4. From ESX: set access permission as 'read-only'
5. try to write using any of the docker VM and make sure further write is not possible as admin-cli has set the access as read-only
6. From ESX: set access permission back to 'read-only'
7. make sure from both nodes (VM1 & VM2); we are able to read and writes are not possible

Steps for #2:

1. create a volume Vol1 as ('access', 'read-write')
2. attach a container from VM1 and write to volume and exit
3. access the volume from VM2 and read the data written by VM1 and modify the data to make sure VM2 is able to write to the volume and exit
4. From ESX: set access permission as 'read-only'
5. try to write using any of the docker VM and make sure further write is not possible as admin-cli has set the access as read-only
6. From ESX: set access permission back to 'read-write'
7. make sure further writes are available from both nodes i.e. VM1 & VM2

/CC @ashahi1 @kerneltime

**Comment by kerneltime** [comment]
LGTM. We should also add a test to make sure we can convert a read-only drive to read-writable drive.

**Comment by tusharnt** [comment]
Manual execution of this test found #998.

Test automation is TBD.
