### ISSUE TITLE
Incorporate generating plugin driver version number during build.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#821]
Presently, the vmdk driver version is fixed in the code and instead needs to be generated during the build process. There is no API to get the driver version, but it can well be included in the volume status (via Get() on a volume) in case we want to expose this anyway.

**Comment by govint** [comment]
CC @kerneltime

**Comment by kerneltime** [comment]
Can you answer the question here https://github.com/vmware/docker-volume-vsphere/pull/811#discussion_r92241774
Why do we need the const version? The only place it is used is to log it.

**Comment by govint** [comment]
Closing, not a requirement anymore.
