### ISSUE TITLE
Testbed need to have at least two datastores to run unit test for tenancy

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#834]
In this PR, https://github.com/vmware/docker-volume-vsphere/pull/828,  we introduce the support
for default_datastore. 
User can specify "default_dastore" when setting datastore access privileges using
the command like the following
```
/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant access add --name=tenant1 --datastore=datastore2 --allow-create --switch-default-datastore --volume-maxsize=500MB --volume-tot
alsize=1GB
tenant access add succeeded
[root@localhost:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant ls
Uuid                                  Name      Description               Default_datastore  VM_list 
------------------------------------  --------  ------------------------  -----------------  ------- 
93377b1e-af74-47ca-888e-75fd0a2a4aba  _DEFAULT  This is a default tenant                             
948f0edc-3a06-4d95-8b8c-8cf278154fc3  tenant1                             datastore2         photon4 
```

After setting the default_datastore, user can specify the volume without specify the datastore name(i.e., user can only specify vol_name, instead of vol_name@datastore_name)

The unit test for support this feature require at least two datastores to run.

1. Testbed used in CI test need to make sure to have at least two datastores in order to run this test
2. CONTRIBUTING.md need to be updated to let user know they need at least two datastores to run this test when they need to run CI test locally

**Comment by kerneltime** [comment]
CI currently has 2 datastores (VMFS and VSAN).

**Comment by lipingxue** [comment]
Close this issue based on Ritesh's comment above.
