### ISSUE TITLE
Test to check the capacity of volume using AdminCLI

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#835]
Test steps:
1) Create VMDKs of different unit GB, TB and MB using vmdk_ops.createVMDK()
2) Check the capacity of volume using AdminCLI 
     command used: /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls -c volume capacity
3) Compare that both sizes are same.

**Comment by shuklanirdesh82** [comment]
will be taken care by #831
