### ISSUE TITLE
vm creation is failing on vsanDatastore

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#836]
I have a VSAN setup where there's only one single vsanDatastore. I tried to run test-esx in this environment and some test cases failed:

Running unit tests in /tmp/vmdk_ops_unittest15141/vmdk_ops_test.py...
..E.........EEE.
======================================================================
ERROR: testAttachDetach (__main__.VmdkAttachDetachTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 482, in setUp
    datastore=self.datastore_name)
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 420, in create_vm
    vmdk_ops.wait_for_tasks(si, [task])
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops.py", line 1497, in wait_for_tasks
    raise task.info.error
vim.fault.FileNotFound: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File  was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [
      (vmodl.LocalizableMessage) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'com.vmware.esx.hostctl.default',
         arg = (vmodl.KeyAnyValue) [
            (vmodl.KeyAnyValue) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 'reason',
               value = 'Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test-vm/test-vm (File Not Found)'
            }
         ],
         message = 'Operation failed, diagnostics report: Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test-vm/test-vm (File Not Found)'
      }
   ],
   file = ''
}

======================================================================
ERROR: test_vmdkops_on_default_tenant_vm (__main__.VmdkTenantTestCase)
Test vmdk life cycle on a VM which belongs to DEFAULT tenant
This operation may take a while. Please be patient.
This operation may take a while. Please be patient.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 746, in setUp
    datastore=self.datastore_name)
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 420, in create_vm
    vmdk_ops.wait_for_tasks(si, [task])
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops.py", line 1497, in wait_for_tasks
    raise task.info.error
vim.fault.FileNotFound: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File  was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [
      (vmodl.LocalizableMessage) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'com.vmware.esx.hostctl.default',
         arg = (vmodl.KeyAnyValue) [
            (vmodl.KeyAnyValue) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 'reason',
               value = 'Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
            }
         ],
         message = 'Operation failed, diagnostics report: Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
      }
   ],
   file = ''
}

======================================================================
ERROR: test_vmdkops_on_different_tenants (__main__.VmdkTenantTestCase)
Test vmdkops on VMs which belong to different tenant
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 746, in setUp
    datastore=self.datastore_name)
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 420, in create_vm
    vmdk_ops.wait_for_tasks(si, [task])
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops.py", line 1497, in wait_for_tasks
    raise task.info.error
vim.fault.FileNotFound: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File  was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [
      (vmodl.LocalizableMessage) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'com.vmware.esx.hostctl.default',
         arg = (vmodl.KeyAnyValue) [
            (vmodl.KeyAnyValue) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 'reason',
               value = 'Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
            }
         ],
         message = 'Operation failed, diagnostics report: Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
      }
   ],
   file = ''
}

======================================================================
ERROR: test_vmdkops_on_tenant_vm (__main__.VmdkTenantTestCase)
Test vmdk life cycle on a VM which belongs to a tenant
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 746, in setUp
    datastore=self.datastore_name)
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops_test.py", line 420, in create_vm
    vmdk_ops.wait_for_tasks(si, [task])
  File "/tmp/vmdk_ops_unittest15141/vmdk_ops.py", line 1497, in wait_for_tasks
    raise task.info.error
vim.fault.FileNotFound: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File  was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [
      (vmodl.LocalizableMessage) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'com.vmware.esx.hostctl.default',
         arg = (vmodl.KeyAnyValue) [
            (vmodl.KeyAnyValue) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 'reason',
               value = 'Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
            }
         ],
         message = 'Operation failed, diagnostics report: Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
      }
   ],
   file = ''
}

----------------------------------------------------------------------
Ran 16 tests in 30.362s

FAILED (errors=4)

......

Running unit tests in /tmp/vmdk_ops_unittest15141/vsan_policy_test.py...

...INFO:Delete_nonexistent_policy:
This is a negative test to delete a non-existent vsan policy.
Test is expected to raise exception log - Failed to remove the policy file error. 

ERROR:root:Failed to remove test_policy policy file
Traceback (most recent call last):
  File "/tmp/vmdk_ops_unittest15141/vsan_policy.py", line 209, in delete
    os.remove(policy_path(name))
OSError: [Errno 2] No such file or directory: '/vmfs/volumes/vsanDatastore/dockvols/policies/test_policy'
..
----------------------------------------------------------------------
Ran 5 tests in 1.109s

Ritesh also helped to take a look. For the first 4 failures, it looks like our create_vm() test code is calling some API which is not applicable to vsanDatastore. Last test_policy seems a different issue.

Anyway, our test suite should support VSAN datastore.

**Comment by shuklanirdesh82** [comment]
@shaominchen can you please share vc/esx IP to take a look? I have run tests recently and the same 4 tests are failing with other reason and raised the issue #832

**Comment by shaominchen** [comment]
@shuklanirdesh82 Here is my VC (10.160.179.66) and here is one of my ESX hosts: 10.160.188.18

**Comment by msterin** [comment]
Thej log says
> value = 'Could not get ObjectStoreFileSystem for /vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 (File Not Found)'
}

And `/vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm1/test_vm1 ` is NOT SUPPOSED to be OSFS file system. It is a regular directory under `/vmfs/volumes/vsan:52b2067d4d8fa677-de50f4c784493a59/test_vm` OSFS file system. 

Something is broken in test directory names generation

**Comment by shuklanirdesh82** [comment]
changes are merged (see #839) so closing this one.
