### ISSUE TITLE
Tenancy: User guide need to be updated

### ISSUE THREAD

**Issue by lipingxue** [vmware/docker-volume-vsphere#837]
User guide (admin-cli.md) need to be updated accordingly after the DEFAULT_TENANT, DEFAULT_PRIVILEGE, and DEFAULT_DATASTORE change are introduced.

**Comment by kerneltime** [comment]
The user guide gets updated each time a release is cut.

**Comment by lipingxue** [comment]
Close this issue based on Ritesh's comment above.
