### ISSUE TITLE
Python admin cli error messages are not bubbled up to the docker volume driver

### ISSUE THREAD

**Issue by curator** [vmware/docker-volume-vsphere#852]
The error messages represented in the admin cli python code are not generally being bubbled up to the docker volume driver, which instead returns a relatively unhelpful generic error.

See code here:

https://github.com/vmware/docker-volume-vsphere/blob/75072a9fc1f57ca452c7d27eca833d9ba6e5ead9/esx_service/vmdk_ops.py#L481-L484

Instead of this error text we see in the ESXi host log file, we see:

`Error response from daemon: Error while removing volume myvol: remove myvol: VolumeDriver.Remove: Server returned an error: AttributeError("'NoneType' object has no attribute 'config'",)`

There are other instances with such errors where this is true, but ideally, for ease of troubleshooting and quicker resolution, the more explicit errors should be available from the return text from docker volume driver.

**Comment by govint** [comment]
@curator can you upload the ESXi host log file, because, the error seems to indicate that the VM object wasn't found and hence the error message. L481 - L484 did'nt happen and hence that error wasn't posted to Docker.

**Comment by msterin** [comment]
@govint - it  seems we do not handle some exception, somewhere. You are right - a repro or an ESX log would be lovely indeed. 

**@curator - can you share the text from ESXi log which you mention above ?** The code you refer would have printed "`Failed to remove volume ...` so it may be something else

**Comment by tusharnt** [comment]
@ashahi1 to verify whether this is already fixed.

**Comment by ashahi1** [comment]
1. Created a volume
2. Mounted the volume to a container.
3. Tried removing the volume but operation is expected to fail as volume is already attached to vm.
And then I do see the following error message:
```
Error response from daemon: Error while removing volume vol852@vsanDatastore: remove vol852@vsanDatastore: VolumeDriver.Remove: Failed to remove volume: Error caused by file /vmfs/volumes/vsan:525bc223ae963c21-153129789d124635/7a91b758-02d3-ee96-2642-0200351cdccb/11111111-1111-1111-1111-111111111111/vol852.vmdk
```

**Comment by msterin** [comment]
Looks good to me - the original issue is fixed.
