### ISSUE TITLE
'policy ls' command does not show the name of the volume using that policy

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#853]
'policy ls' command does not show the name of the volume using that policy

========================================

Steps are as follows:
1) Created a vsan storage policy using the following command: 
/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py policy create --name some-policy --content '(("proportionalCapacity" i0)("hostFailuresToTolerate" i0)'

[root@sc2-rdops-vm03-dhcp-97-99:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py policy ls

Policy Name  Policy Content                                            Active
-----------  --------------------------------------------------------  ------
some-policy  (("hostFailuresToTolerate" i0) ("forceProvisioning" i0))  Unused

Active column shows unused since no volume is using this policy.

2) Created a volume named some-vol using the above created policy:
docker volume create --driver=vmdk --name=some-vol -o vsan-policy-name=some-policy

Docker inspect for the created volume shows name of the policy used by the volume

root@photon-TX4FfW2ET [ ~/docker-volume-vsphere ]# docker volume inspect some-vol | grep "Name\|vsan-policy-name"
        "Name": "some-vol",
            "vsan-policy-name": "some-policy"

			
3) 'policy ls' command still shows policy as unused:

[root@sc2-rdops-vm03-dhcp-97-99:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py policy ls
Policy Name  Policy Content                                            Active
-----------  --------------------------------------------------------  ------
some-policy  (("hostFailuresToTolerate" i0) ("forceProvisioning" i0))  Unused

==================================		

Ideally we should see the name of the virtual disks using the policy should show up in the Active column.

**Comment by shaominchen** [comment]
I have narrowed down the root cause to be in vmdk_utils.list_vmdks() method. Please focus on this method to fix the issue.
