### ISSUE TITLE
Release docker-volume-vsphere to the Project Atomic ostree repositories

### ISSUE THREAD

**Issue by kbrowder** [vmware/docker-volume-vsphere#854]
Seems like it'd be nice to be able to `rpm-ostree pkg-add docker-volume-vsphere`  on both the CentOS and Fedora Project Atomics.  Otherwise I believe changes aren't carried over upgrades.

**Comment by kerneltime** [comment]
Thanks @kbrowder will look into this.

**Comment by kerneltime** [comment]
There are ways to build custom own os-trees to use.. so far we have not looked into upstreaming the plugin into the official repos. How important is this for you? We might not do this at least until we release 1.0

**Comment by kbrowder** [comment]
For me it's mostly a matter of convenience and me trying to avoid creating
and managing an ostree repo.

However I certainly could understand if you didn't go through the process
of getting this in ostree repos until 1.0.

**Comment by kerneltime** [comment]
Keeping this open. Will revisit once we hit 1.0

**Comment by tusharnt** [comment]
Not critical for GA.

**Comment by pdhamdhere** [comment]
We wont need this once we switch to managed plugin #886

**Comment by tusharnt** [comment]
Now vDVS is now already available as a managed plugin and it can be installed as follows -
docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest

For details, please check it out installation instructions here - 
http://vmware.github.io/docker-volume-vsphere/documentation/install.html
