### ISSUE TITLE
Capture plugin code coverage

### ISSUE THREAD

**Issue by kerneltime** [vmware/docker-volume-vsphere#869]
When test coverage is run for go plugin the test code does not measure the code coverage of the plugin but only the test and the functions it depends on. The actual execution is done via a RPC call over docket.

- [x] To measure the test coverage correctly the go plugin needs to run in an instrumented manner.
- [ ] Generate an instrumented vDVS plugin binary
- [ ] Generate a managed plugin that uses instrumented vDVS plugin binary

**Comment by shuklanirdesh82** [comment]
> When test coverage is run for go plugin the test code does not measure the code coverage of the plugin but only the test and the functions it depends on. The actual execution is done via a RPC call over docket.

the original issue was filed to keep track off above issue. I have verified that code coverage is captured correctly whenever the execution is done via RPC over socket/remote docker end point.

> Generate an instrumented vDVS plugin binary

#1589 is raised to track this issue.

> Generate a managed plugin that uses instrumented vDVS plugin binary
#1590 is raised to achieve this.
