### ISSUE TITLE
Admin CLI is not allowing to move VM from one tenant to another tenant

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#870]
Steps to repro:

1. create two tenants T1 & T2
2. Add VM1 to T1 and VM2 to T2
3. move VM2 from T2
4. add VM2 to T1

Current outcome: Admin CLI is not allowing to add VM2 to T1; and runs into following error
```column vm_id is not unique``` It seems VM2 goes to ```_DEFAULT``` tenant group and inaccessible for further addition to any tenants

on ESX:
```
[root@promc-2n-dhcp105-97:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name T9
Uuid  Name  
----  ----  

[root@promc-2n-dhcp105-97:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name T10
Uuid                                  Name     
------------------------------------  -------  
564ded53-984d-642b-3a24-ed8f86f23214  photon1  

[root@promc-2n-dhcp105-97:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls --name _DEFAULT
Uuid  Name  
----  ----  

[root@promc-2n-dhcp105-97:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm add --vm-list=photon1 --name T10
column vm_id is not unique
```

/CC @kerneltime @tusharnt

**Comment by lipingxue** [comment]
@shuklanirdesh82 What do you mean "move VM2 from T2"? Could you provide the complete esx command you ran for this test? It seems to me that the esx command you provided above is incomplete.

**Comment by shuklanirdesh82** [comment]
After refreshing the testbed, I'm not able to reproduce so closing as of now. 

We shall reproduce if it is reproducible.
