### ISSUE TITLE
Plugin throwing error on volume create in Docker 1.13

### ISSUE THREAD

**Issue by mlschuh** [vmware/docker-volume-vsphere#876]
Hi there,

I was testing compatibility with 1.13 release and came across the following:

```
isaac@ubuntu:~$ sudo docker volume create --driver=vmdk --name=db-vol-1 -o size=10gb
Error response from daemon: create db-vol-1: VolumeDriver.Create: Server returned an error: IndexError('list index out of range',)
```

This was on a fresh install of the following:
Docker 1.13
Volume plugin 0.10
Ubuntu 16.04.1

VM logs:

```
2017-01-24 14:53:24.001751062 -0500 EST [DEBUG] vmdkOps.Get name=db-vol-1
2017-01-24 14:53:24.087598782 -0500 EST [DEBUG] vmdkOp.Create name=db-vol-1
2017-01-24 14:53:24.138577283 -0500 EST [ERROR] Create volume failed error="Server returned an error: IndexError('list index out of range',)" name=db-vol-1 
```

Host logs:

```
01/24/17 19:34:22 2343525 [Thread-788] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1359, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 745, in executeRequest
    error_info, tenant_uuid, tenant_name = auth.authorize(vm_uuid, datastore, cmd, opts)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 419, in authorize
    error_info, privileges = get_privileges(tenant_uuid, datastore)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 179, in get_privileges
    datastore_url = vmdk_utils.get_datastore_url(datastore)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 316, in get_datastore_url
    return res[0]
IndexError: list index out of range
01/24/17 19:34:22 2343525 [Thread-789] [ERROR  ] Unhandled Exception:
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 1359, in execRequestThread
    opts=opts)
  File "/usr/lib/vmware/vmdkops/bin/vmdk_ops.py", line 745, in executeRequest
    error_info, tenant_uuid, tenant_name = auth.authorize(vm_uuid, datastore, cmd, opts)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 419, in authorize
    error_info, privileges = get_privileges(tenant_uuid, datastore)
  File "/usr/lib/vmware/vmdkops/Python/auth.py", line 179, in get_privileges
    datastore_url = vmdk_utils.get_datastore_url(datastore)
  File "/usr/lib/vmware/vmdkops/Python/vmdk_utils.py", line 316, in get_datastore_url
    return res[0]
IndexError: list index out of range
```

Docker Engine Logs:

```
Jan 24 14:52:47 ubuntu systemd[1]: Started Docker Application Container Engine.
Jan 24 14:53:24 ubuntu dockerd[22017]: time="2017-01-24T14:53:24.139312459-05:00" level=error msg="Handler for POST /v1.25/volumes/create returned error: create db-vol-1: VolumeDriver.Create: Server returned an error: IndexError('list index out of range',)"
```

**Comment by lipingxue** [comment]
Hi @mlschuh,
   I checked hostlog, the exception you hit is because the datastore does not exist. I have serveral questions for you to understand your steps:
1. Have you created any tenant and assign the VM to that tenant?
2. Have your assigned the default_datastore for that tenant? If you do assign, what is the name of that datastore?  If not, what is the datastore where your VM lives?

If possible, could you try to reproduce this issue with turning on  DEBUG log for ESX Plugin logs and send us ESX Plugin logs? 
This is the link about how to turn on DEBUG log for ESX Plugin logs.  https://github.com/vmware/docker-volume-vsphere/blob/34f91627a75eda1bebe0972bc4980014b5935a51/README.md#L122

Thanks.

**Comment by mlschuh** [comment]
I have not knowingly made anything related to a tenant as I'm unaware of what a tenant is. The VM is living on DS_ISAAC_Staging.

I'll grab logs the logs you request shortly.

**Comment by mlschuh** [comment]
@lipingxue I've tried finding how to launch the volume plugin manually but cannot seem to find the location on my VM. Can you let me know/update the README on where to find it?

**Comment by lipingxue** [comment]
Hi @mlschuh, are you using gitter or other chat tools? We can chat online to better understand your problem.

**Comment by mlschuh** [comment]
@lipingxue I can be available on gitter tomorrow anytime during EST business hours. Feel free to add me to an appropriate room.

**Comment by lipingxue** [comment]
@mlschuh OK. I just created a gitter room named https://gitter.im/docker-volume-vsphere, and send you a request to join this room. Let us chat tomorrow.

Btw, are you able to get the ESX plug in log with turning on the DEBUG log? If you can, please share with me, I can take a look before we chat tomorrow.

**Comment by mlschuh** [comment]
While attempting to retrieve the logs, I was able to get it working. Here's what I ended up doing (mostly for future reference):

1. Adjusted the config file on the esxi host and restarted the service. Upon attempting to reproduce, this error was thrown:

```
isaac@ISAACTemplateDeploy1:~$ sudo docker volume create --driver=vmdk --name=db-vol-1 -o size=10gb
Error response from daemon: create db-vol-1: create db-vol-1: Error looking up volume plugin vmdk: legacy plugin: plugin not found
```

2. To attempt to revive it, I confirmed that the plugin was installed:

```
[root@localhost:~] esxcli software vib install --no-sig-check -v /vmware-esx-vmdkops-0.10.04f085b.vib 
Installation Result
   Message: Host is not changed.
   Reboot Required: false
   VIBs Installed: 
   VIBs Removed: 
   VIBs Skipped: VMWare_bootbank_esx-vmdkops-service_0.10.04f085b-0.0.1
[root@localhost:~]
```

3. I then decided to attempt to start fresh by removing the .vib and the ubuntu package:

```
[root@localhost:~] esxcli software vib remove -n esx-vmdkops-service
Removal Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: 
   VIBs Removed: VMWare_bootbank_esx-vmdkops-service_0.10.04f085b-0.0.1
   VIBs Skipped: 
[root@localhost:~]
```

```
isaac@ISAACTemplateDeploy1:~$ sudo apt-get remove docker-volume-vsphere 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  docker-volume-vsphere
0 upgraded, 0 newly installed, 1 to remove and 47 not upgraded.
After this operation, 12.5 MB disk space will be freed.
Do you want to continue? [Y/n] Y
```

4. After that, I reinstalled following the methods in the project readme which then the service worked as designed. Because of this, I wasn't able to ever get debug logs exhibiting the error.

I am not certain if it was the VM plugin that needed a reinstall after updating to docker 1.13 or if the esxi host .vib was upset but clearing out both resolved whatever wonky was happening. I'm not sure it would be worth the time and effort to attempt to reproduce it again other than me being aware that this might be a problem during future Docker updates.
