### ISSUE TITLE
Docker 1.13 support/interop

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#882]
- Plugin support (#886)
- docker new commands

- [x] docker introduce "docker stack deploy" from a compose file, need to test this new command with docker-volume-vsphere plugin (PR27998) 

- docker changes to existing commands
- [x] Remove --name from docker volume create (PR23830), need test to verify plugin works for both old and new format 
- [ ] Add support for filtering volumes by label (PR25628),  docker-volume-vsphere plugin need to support "docker volume ls --filter label".
- [x] Add a --force flag in docker volume rm to forcefully purge the data
 of the volume that has already been deleted (PR23436). With suppport multiple-ESX host which shared same storage, we may see similar issue as flocker, need to verify "volume rm -f" can solve this issue

**Comment by govint** [comment]
Can the volume can be re-formatted to destroy the data in the volume.

**Comment by pdhamdhere** [comment]
> - [x] docker introduce "docker stack deploy" from a compose file, need to test this new command with docker-volume-vsphere plugin (PR27998) 

```
cat nginx-stack-vmdk.yaml 
version: "3"

services:

  nginx:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - log:/var/log/nginx

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
   log:
      driver: vmdk

root@master:~# docker stack deploy -c nginx-stack-vmdk.yaml ng
Creating network ng_default
Creating service ng_nginx

root@master:~# docker stack ps ng
ID            NAME        IMAGE         NODE    DESIRED STATE  CURRENT STATE          ERROR  PORTS
jsp8zcxa2e9g  ng_nginx.1  nginx:latest  master  Running        Running 3 seconds ago         

root@master:~# docker volume ls
DRIVER              VOLUME NAME
vmdk                ng_log@vsanDatastore

root@master:~# curl 10.162.7.145:5000
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

Summary: Single replica works fine. Since VMDK volume can only be used by one docker host at any time, replicas > 1 will fail to start.

> - [x]  Remove --name from docker volume create (PR23830), need test to verify plugin works for both old and new format

CLI is backward compatible and no additional work required.

```
root@master:~# docker volume create -d vmdk --name v1
v1
root@master:~# docker volume create -d vmdk v2
docker volv2
root@master:~# docker volume ls
DRIVER              VOLUME NAME
vmdk                v1@vsanDatastore
vmdk                v2@vsanDatastore
```

**Comment by pdhamdhere** [comment]
Follow-up actions:

- Add test for "docker stack deploy" from a compose file
