### ISSUE TITLE
CI test is failing due to error: dpkg status database is locked by another process

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#887]
CI test is failing due to error: dpkg status database is locked by another process. Both Mark and I have run into this issue:

https://ci.vmware.run/vmware/docker-volume-vsphere/1063
https://ci.vmware.run/vmware/docker-volume-vsphere/1065

@msterin @shuklanirdesh82 @kerneltime

**Comment by ashahi1** [comment]
Hit this issue durin CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1095

===================================
Snippet from error log:

=> Deploying root@192.168.31.83 : deb Wed Feb 8 23:11:59 UTC 2017


dpkg: error: dpkg status database is locked by another process
make[1]: *** [deploy-vm] Error 2
make: *** [deploy-vm] Error 2


=> Build + Test not successful Wed Feb 8 23:12:00 UTC 2017

**Comment by ashahi1** [comment]
Failed CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1098

=====
=> Deploying root@192.168.31.83 : deb Thu Feb 9 00:30:49 UTC 2017


dpkg: error: dpkg status database is locked by another process
make[1]: *** [deploy-vm] Error 2
make: *** [deploy-vm] Error 2

**Comment by ashahi1** [comment]
CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1099

==========
=> Deploying root@192.168.31.85 : deb Thu Feb 9 00:46:08 UTC 2017


dpkg: error: dpkg status database is locked by another process
make[1]: *** [deploy-vm] Error 2
make: *** [deploy-vm] Error 2


=> Build + Test not successful

**Comment by shuklanirdesh82** [comment]
Looking at it, just a quick note (192.168.31.85 & 192.168.31.85 only are having the issue).

**Comment by shuklanirdesh82** [comment]
@shaominchen @ashahi1 : I've fixed both VMs and made sure by running multiple times. Please reopen if observes again.
