### ISSUE TITLE
CI test fails intermittently due to error: Unsupported VM Type

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#888]
CI test is failing due to error: Unsupported VM Type. This seems to be an intermittently issue:

https://ci.vmware.run/vmware/docker-volume-vsphere/1061

@kerneltime @shuklanirdesh82

**Comment by kerneltime** [comment]
This seems to be an issue of govc not being able to fetch IP. 

Possible solution: We need to add a sleep and retry loop.

**Comment by shuklanirdesh82** [comment]
Proposed changes are merged.

Please reopen if the issue will be observed again.

**Comment by shuklanirdesh82** [comment]
Added retry mechanism for VMs; proposing changes through #913

**Comment by shuklanirdesh82** [comment]
merged #913
