### ISSUE TITLE
CI test is failing due to VIB InstallationError

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#891]
CI test is failing due to InstallationError

Errors: 
 [InstallationError]
 There was an error checking file system on altbootbank, please see log for detail.
 Please refer to the log file for more details.

=> deployESXInstall: Installation hit an error on root@192.168.31.62 Fri Feb 3 20:10:00 UTC 2017

make[1]: *** [deploy-esx] Error 2
make: *** [deploy-esx] Error 2

https://ci.vmware.run/vmware/docker-volume-vsphere/1067
https://ci.vmware.run/vmware/docker-volume-vsphere/1068

**Comment by shuklanirdesh82** [comment]
I guess we need to apply the solution described at https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2033564

**Comment by shuklanirdesh82** [comment]
Resolved the issue observing on ESX 6.5 and invoked following two runs...

https://ci.vmware.run/vmware/docker-volume-vsphere/1112
https://ci.vmware.run/vmware/docker-volume-vsphere/1113

Not seeing VIB installation error.
