### ISSUE TITLE
Fail when trying to Create a volume twice (Docker PR)

### ISSUE THREAD

**Issue by andrewjstone** [vmware/docker-volume-vsphere#90]
Currently the semantics of docker 1.10 do not allow fail on Create. Instead Create will just return success with the name of the already existing Volume. Implementing the new semantics will require a PR to Docker and an update of the plugin.

**Comment by govint** [comment]
Docker 1.12 also doesn't fail a duplicate create. Does this PR need any changes at all. When a volume is created, docker keeps track of it and a duplicate create is returned as successful by docker itself without any call to the server.

Which seems fine by behavior. Why fail when the volume is present. Unless create has an "exclusive create" option to ensure that duplicate creates are failed.

administrator@hte-1s-eng-dhcp98:~/vpl-kv/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol_2
clonevol_2
administrator@hte-1s-eng-dhcp98:~/vpl-kv/docker-volume-vsphere$ docker volume create --driver=vmdk --name=clonevol_2
clonevol_2

And server gets the request only once.

07/04/16 12:27:52 1001163483 [2] [INFO   ] executeRequest 'get' completed with ret={'Error': 'Volume clonevol_2 not found (file: /vmfs/volumes/bigone/dockvols/clonevol_2.vmdk)'}
07/04/16 12:27:52 1001163483 [2] [INFO   ] *** createVMDK: /vmfs/volumes/bigone/dockvols/clonevol_2.vmdk opts = {}
07/04/16 12:27:54 1001163483 [2] [INFO   ] executeRequest 'create' completed with ret=None

Do we need to fix/change this?

**Comment by govint** [comment]
Tried this out with two VMs creating the same volume in sequence, the first one creates it and on the second VM, docker issues a Get() to the plugin which finds the existing volume and reports it.

The issue in docker PR 19953 seems to be with creating non-existent host directories when running a container. For the volume plugin a volume is created once and thats it. Don't see any issue to address and hence closing it.
