### ISSUE TITLE
Support getting VM ID from photon for the volume plugin

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#907]
ON plugin startup for photon driver, get the VM ID from photon.

Actually, given the photon controller IP we may as well query all tenants, projects and then figure the project and VM ID. Ideally Photon should be able to give this. but at the cost of a slower plugin start up (for a photon controller with large number of clients/projects and VMs) we can do with a single input from the user.

**Comment by tusharnt** [comment]
@govint can you please confirm whether this is a purely a performance issue?  Can you please post some analysis of how much performance improvement we will get if we do this fix?

**Comment by govint** [comment]
@tusharnt this is not a performance issue as much as its a user experience issue. I don't believe Photon deployments will be loaded with tenants and projects that fetching the tenant and project list per tenant will be hugely impactful. Plus Photon Controller is planning on exposing a meta-data service that will remove the need for the VM to identify itself in this way in the future. This change simplifies the user's work a lot.

Currently user has to provide the VM and project IDs to run the plugin - from discussions it was felt that this is cumbersome for the user and hence the change.

**Comment by govint** [comment]
PC platform issues will be picked up later as needed. Closing.
