### ISSUE TITLE
CI run failed due to error: getsockopt: no route to host 

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#908]
Error - getsockopt: no route to host 
CI run: https://ci.vmware.run/vmware/docker-volume-vsphere/1144

Log snippet:
=======
govc: Post https://192.168.31.62/sdk: dial tcp 192.168.31.62:443: getsockopt: no route to host
$ export VM2=`$GOVC_GET_IP Ubuntu.16.10`
govc: Post https://192.168.31.62/sdk: dial tcp 192.168.31.62:443: getsockopt: no route to host
$ ./misc/drone-scripts/deploy-and-test-wrapper.sh $GOVC_URL_6_5 $VM1 $VM2 1144 < /dev/null
./misc/drone-scripts/deploy-and-test-wrapper.sh <ESX IP> <VM1 IP> <VM2 IP> <Build id>
root user will be used for all operations
Advisable to setup ssh keys.
run this script from the root of the repo
[info] build failed (exit code 1)

**Comment by shuklanirdesh82** [comment]
@ashahi1 I have refreshed the n/w mgmt setting, please repush your changes and update the issue if reproducible.
