### ISSUE TITLE
Datastore names with embedded spaces in them can't be used when creating a volume.

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#916]
For example, docker volume create -driver vmdk -name vol@data\  store - won't work as the code doesn't handle datastore names with spaces in it. This can be fixed to allow such names. Or we can take the approach that the plugin only allows names without spaces in them - have a uniform naming convention for all names handled via the plugin - tenant, datastore names at least.

**Comment by lipingxue** [comment]
Run the following test manually

Configuration:
two datastores "datastore1" and "datastore2" are accessible by VM "photon6"
VM "photon6" belongs to _DEFAULT tenant, and is created on "datastore1"

Step1: run "docker volume ls" to list current volume
```
root@photon-KwqUODFXp [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             vol1@datastore1
vsphere             vol2@datastore1
```

Step2: rename "datastore2" to "datastore   2",  then create a volume with vol_name@datastore\ \ \ 2 (spaces are included in datastore name), volume creation succeeded.
```
root@photon-KwqUODFXp [ ~ ]# docker volume create --driver=vsphere --name vol3@datastore\ \ \ 2
vol3@datastore   2
root@photon-KwqUODFXp [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             vol1@datastore1
vsphere             vol2@datastore1
vsphere             vol3@datastore   2

```

**Comment by lipingxue** [comment]
Fixed by this PR https://github.com/vmware/docker-volume-vsphere/pull/988
