### ISSUE TITLE
preempt (force detach) existing volume

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#92]
Here is the use case I was trying;

Setup postgres on VM1.
1.  docker volume create --driver=vmdk --name=postgresvol-02 -o size=1gb
2. docker run --name postgres-02 -v postgresvol-02:/var/lib/data -e POSTGRES_PASSWORD=secretpass -e PGDATA=/var/lib/data/db -d postgres
3. docker rm -f postgres-02 <<<Killed the container. But forgot -v i.e. detach volume

On VM2
4. docker run --name postgres-02 -v postgresvol-02:/var/lib/data -e POSTGRES_PASSWORD=secretpass -e PGDATA=/var/lib/data/db -d postgres

Failed to attach postgres-02 since it is already attached to VM1.

It would be nice if there is a way to say preempt postgresvol-02 and attach to my node.

**Comment by msterin** [comment]
Update: refnt cannot help here.The use case is - Docker container was running with a volume, and VM crashed. Volume is still attached, but internally, in the VM, is not used (that is if VM is running)

Suggested behavior: something like  `vmdkops_admin volume detach --name <volume_name>`
* scan registered VMs for this volume (using PriopertyCollector)
* if the volumes is attached to a powered off VM, detach and report
* if the volume is attached to a powered off VM, request confirmation (or --force option) , then reconfigure / detach and report

//CC @andrewjstone

**Comment by govint** [comment]
This will be closed via PR #573

**Comment by govint** [comment]
Closed via #573
