### ISSUE TITLE
The command behavior of "tenant rm" and "policy rm" are inconsistent

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#922]
When we run "vmdkops_admin policy rm MyPolicy", we don't need to specify the parameter name "--name". However, to run "vmdkops_admin tenant rm --name MyTenant", we must specify "--name".

I think we should keep the command behavior consistent. My suggestion is to fix the "tenant rm" command, because the behavior of "policy rm" command is more natural, and it's also consistent with other CLI tools, such as "docker volume rm" command.

**Comment by tusharnt** [comment]
Even tests need to be fixed.

**Comment by msterin** [comment]
The suggested change will leave 'tenant <command>' set inconsistent. 
Please do not do it - instead, *if* it is an issue, we need to do a pass on all commands and make them consistent in using --name vs positional name

**Comment by shaominchen** [comment]
@msterin I don't think this will leave "tenant set" inconsistent. For CUD operations, only D (rm) does not need "--name". Add & set still need "--name". This is just a convention for most command lines tools.

**Comment by pshahzeb** [comment]
From https://docs.docker.com/engine/reference/commandline/docker/
I think many, if not all, docker commands use positional name instead of --name for all CUD operations. (only volume create requires --name)

I think we can go ahead with something consistent for all commands. Right now, only policy rm command takes positional name. All other commands require --name.

**Comment by msterin** [comment]
> This is just a convention for most command lines tools.
I do not think it's true for "most" CLIs - can you give us examples ? 
At any rate, It is certainly  not true for most Docker subcommands, and it is super confusing IMO as the user has to think every time what is the command format. 

A natural way is to use positionals. I am fine with using `--name` also (as Docker user to do but seems to have moved away from) as long as it's consistent across all commans.

So I agree with @pshahzeb  here.  And if we do it, we also need to change the related doc and test, and do it in 0.13 or GA , it will be more impacful later.

**Comment by shaominchen** [comment]
@msterin Some examples:
"docker create" and "docker volume create" use "--name", but "docker rm" and "docker volume rm" use positional name;
"vmdkops_admin policy create" and "vmdkops_admin policy update" use "--name", but "vmdkops_admin policy rm" use positional name

Anyway, I agree that keep consistency (especially local consistency) is very important.

**Comment by pshahzeb** [comment]
@shaominchen @msterin 
I think correcting policy rm command to make use of --name would be more safe. Since it is a small change, would make all the commands consistent, and would cause less inconvenience to existing users as well

**Comment by shaominchen** [comment]
@pshahzeb I agree.

**Comment by shuklanirdesh82** [comment]
Can you make sure admin_cli information is in sync with the proposed changes?

e.g. https://github.com/vmware/docker-volume-vsphere/blob/master/docs/user-guide/admin-cli.md#remove-3
