### ISSUE TITLE
Proper error message should be thrown when volume is not visible to docker host though it is trying to attach the container (current error message is misleading)

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#935]
Testbed scenario: 2 ESX host having local datastore + docker_host vm on each ESX

Steps to reproduce:
1. create a volume from one of the docker_host (VM1) on local datastore
2. make sure volume is created correctly 
3. attach container from VM1 and make sure operation is successful
4. detach the container from VM1
5. perform step#3 on VM2
6. observed the following error

```
root@photon-TX4FfW2ET [ ~ ]# docker run --rm -it -v vol_242_local@local.1-0:/mnt/myvol2 --name cnt_2311 busybox
docker: Error response from daemon: create vol_242_local@local.1-0: "vol_242_local@local.1-0" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
```

**Expectation**: Proper error message should be thrown like "volume is not visible/accessible". Current error message is misleading.

**Comment by govint** [comment]
The volume is assumed to be local by docker as it has no idea that such a volume even exists. Possibly include the "--volume-driver" option so docker knows to try the plugin. Again, docker will try to create the volume which should return OK from the plugin (and service) and mount should fail with the volume not being available (detached).

**Comment by tusharnt** [comment]
As per @lipingxue, this should already be addressed.

**Comment by shuklanirdesh82** [comment]
@lipingxue  The reported issue is still exist..reassigning to you (please feel free to move into v1GA if major effort is required)

```
On VM1:

root@photon-xVmYMbyTn [ ~ ]# docker volume create --driver=vsphere --name=abc@local.3-0
abc@local.3-0
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             abc@local.3-0
root@photon-xVmYMbyTn [ ~ ]# docker run --rm -it -v abc@local.3-0:/mnt/myvol2 --name cnt_2311 busybox
/ # exit

On VM2:

root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
root@photon-xVmYMbyTn [ ~ ]# docker run --rm -it -v abc@local.3-0:/mnt/myvol2 --name cnt_2311 busybox
docker: Error response from daemon: create abc@local.3-0: "abc@local.3-0" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.
root@photon-xVmYMbyTn [ ~ ]# rpm -qa | grep docker
docker-volume-vsphere-0.12.3f64805-1.x86_64
```

**Comment by shuklanirdesh82** [comment]
@govint Thanks for the comment, please find my response as inline.

> Possibly include the "--volume-driver" option so docker knows to try the plugin. Again, docker will try to create the volume which should return OK from the plugin (and service) and mount should fail with the volume not being available (detached).

```
root@photon-xVmYMbyTn [ ~ ]# docker run --rm -it --volume-driver=vsphere -v abc@local.3-0:/mnt/myvol2 --name cnt_2311 busybox
docker: Error response from daemon: create abc@local.3-0: VolumeDriver.Create: Invalid datastore 'local.3-0'.
Known datastores: sharedVmfs-0, local.1-0, local.1-1, vsanDatastore.
Default datastore: sharedVmfs-0.
See 'docker run --help'.
```

**Comment by govint** [comment]
But when vsphere driver is provided Docker is contacting the plugin and the plugin is throwing the error that the datastore is unknown. Which is correct behavior.

And without the volume driver option Docker is correctly failing the "run" request owing to the invalid '@' char.

**Comment by shuklanirdesh82** [comment]
Thanks @govint! closing this issue as ```invalid``` as per https://github.com/vmware/docker-volume-vsphere/issues/935#issuecomment-284140769
