### ISSUE TITLE
Cannot remove vmdk volume from Deamon

### ISSUE THREAD

**Issue by brockz** [vmware/docker-volume-vsphere#949]
Hello

I not able to remove a vmdk  Volume from my Docker Install:
sudo docker volume rm MyVolume@shrk-vSAN01
Error response from daemon: Error while removing volume MyVolume@shrk-vSAN01: remove MyVolume@shrk-vSAN01: VolumeDriver.Remove: Failed to remove volume /vmfs/volumes/shrk-vSAN01/dockvols/11111111-1111-1111-1111-111111111111/MyVolume.vmdk, in use by VM uuid = 42383f4e-ff1c-97d0-0536-4e73d1558910.

The vmdk is not mounted anymore on a vm !

Br Stefan

**Comment by govint** [comment]
@brockz  can you upload the same set of logs as requested for the other issue - /var/log/vmware/vmdk_ops.log on the ESX host and /var/log/docker-volume-vsphere.log on the guest OS.

**Comment by pdhamdhere** [comment]
@brockz sorry, you are running into issues with this. I went through "delete volume" code flow and unable to reason case when this could happen. VM and ESX logs would definitely help. Also, I suspect we may need to look at Docker Engine logs too.

Is it possible to jump on quick webEx/call to understand your environment & use case? You can send us your contact details, day & time that works best for you @ containers@vmware.com
We are available on [Slack](https://github.com/vmware/docker-volume-vsphere#contact-us)  too.

**Comment by govint** [comment]
@brockz is there an update on this issue, if you have any logs from a repro please upload those to this issue.

**Comment by govint** [comment]
Closing, please reopen if this issue reproduces and please upload the service logs (/var/log/vmware/vmdk_ops.log on the ESX host) and the plugin logs (/var/log/docker-volume-vsphere.log).
