### ISSUE TITLE
Use the tenant name in the logs instead of tenant IDs

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#955]
The tenant UUIDs are long sequences of digits and make for difficult reading in the logs and error messages as the user needs to lookup the tenant mapping from UUID to tenant name to figure which tenant is in use for volume ops (when debugging).

When a tennat dir. (uuid is dir name) is made then also create a symlink to that uuid-dir which is the name of the tenant. Similar to ESX datastores that use a readable name for every datastore.

**Comment by msterin** [comment]
> When a tennat dir. (uuid is dir name) is made then also create a symlink to that uuid-dir which is the name of the tenant. 

it already works that way. Maybe you meant to ask "put tenant names rather than tenant uuids into the log" ?   This would be reasonable. However it would make it really hard to debug cross-esx issues if one of the symlinks is overriden by a different ESX

**Comment by govint** [comment]
Correct, the tenant names in the log is easier to read (like datastore names in ESX logs).
