### ISSUE TITLE
Volume creation goes through fine but 'docker volume ls' does not lists that particular volume.

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#956]
Volume creation goes fine for volume named - vol1
Tried to list the volume using docker volume ls but do not see vol1.

=======
Sequence of steps:

root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=10gb
vol1
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol2 -o size=400mb
vol2
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol3 -o size=400mb
vol3
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
vmdk                vol3@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=400mb
vol1
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
vmdk                vol3@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
b86d9faf9677        busybox:latest      "tail -f /dev/null"   54 seconds ago      Up 48 seconds                           e2eThin.3.ei59xvh90lm9j1o7h7wu24b9s
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
vmdk                vol3@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume create --driver=vmdk --name=vol1 -o size=1gb
vol1
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
vmdk                vol3@sharedVmfs-0
root@photon-TX4FfW2ET [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vmdk                SrvcVol@sharedVmfs-0
vmdk                vol2@sharedVmfs-0
vmdk                vol3@sharedVmfs-0

====================
Following logs have been attached:
From Docker VM: /var/log/docker-volume-vsphere.log
From ESX: /var/log/vmware/vmdk_ops.log
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/797326/docker-volume-vsphere.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/797327/vmdk_ops.txt)

**Comment by shuklanirdesh82** [comment]
@ashahi1 : some questions

1. was the ```vol1``` created and deleted before executing above steps?
2. where does ```SrvcVol@sharedVmfs-0``` come from? have you created one. Please do mention to avoid confusion.
3. what is the docker version?

**Comment by govint** [comment]
The ESX logs show vol1 getting created multiple times and also getting removed. Possibly the exact sequence of steps used should be provided so it can be repro'ed.

**Comment by ashahi1** [comment]
@govint I didn't remove the volume vol1. I was trying to create vol1 but 'docker volume ls' was never listing it.
I will deploy a fresh setup and see if issue is reproducible.
Docker version used is 1.12.1

**Comment by shuklanirdesh82** [comment]
> Docker version used is 1.12.1

attached logs having multiple creation and deletion for the "vol1" and on the other hand docker 1.12 was having a known issue for not listing down volume if the creation with the same name which got deleted couple mins back .. it was fixed in 1.13

This doesn't look like a bug so closing this for now and reopen if it is reproducible.
