### ISSUE TITLE
[Tenant] better to use all 0's or f's for the _DEFAULT tenant UUID instead of all 1's

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#963]
```
/vmfs/volumes/vsanDatastore/dockvols/11111111-1111-1111-1111-111111111111
```
It looks little bit ugly while reading up logs and not much intuitive.
Proposing to use all 0's or f's: ```00000000-0000-0000-0000-000000000000``` or ```ffffffff-ffff-ffff-ffff-ffffffffffff```

IMO, it increases readability. 

//CC @msterin @pdhamdhere

**Comment by govint** [comment]
Related to #955

**Comment by shuklanirdesh82** [comment]
@govint Thanks for pointing at #955, if would be more meaningful to show ```_DEFAULT``` I guess that is what #955 is referring. 

I am requesting to update tenant UUID as well for ```vmdkops_admin tenant ls```.

**Comment by msterin** [comment]
The rename would also require us to add migration code form 0.11.2 forward :-(  - I am not sure it's worth the effort.

**Comment by shuklanirdesh82** [comment]
I thought there is a dependency only on ```_DEFAULT``` name and not UUID hence the usability request. 

If you think there will be too much work and not worth spending time; please feel free to close this one. It could be a more personal preference to have something like ```00000000-0000-0000-0000-000000000000``` or ```ffffffff-ffff-ffff-ffff-ffffffffffff```

**Comment by lipingxue** [comment]
I agree with Mark that the change may not worth the effort.  Nirdesh, if you have no objection, please close this issue, thanks.

**Comment by shuklanirdesh82** [comment]
Closing this issue.
