### ISSUE TITLE
[Tenant] Restrict user from creating/renaming tenant with name=_DEFAULT 

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#966]
With the multi-tenancy feature, vmdk driver is creating ```_DEFAULT``` tenant to maintain backward compatibility. As ```_DEFAULT``` tenant is treated as a special case (system created tenant), vmdkops_admin should restrict user to create/rename tenant with name=```_DEFAULT```

It is unlikely for any user to choose such name but would be a good candidate for GA to restrict user in earlier phase.

//CC @pdhamdhere @msterin @lipingxue

**Comment by tusharnt** [comment]
Won't fix.
