### ISSUE TITLE
[Tenant] Enhance vmdkops_admin tenant vm ls to show tenant<->list[VMs] information

### ISSUE THREAD

**Issue by shuklanirdesh82** [vmware/docker-volume-vsphere#967]
```
[root@sc-rdops-vm17-dhcp-0-84:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm ls
usage: vmdkops_admin.py tenant vm ls [-h] --name NAME
vmdkops_admin.py tenant vm ls: error: the following arguments are required: --name
[root@sc-rdops-vm17-dhcp-0-84:~] 
```

Raising a tracker issue as per offline discussion with @msterin, vmdk driver is expecting to have tenant name retrieved from user in order to show list of vm information here are some proposal for team to take further review.

**Proposal#1**: ```vmdkops_admin.py tenant vm ls``` should fall back on the ```_DEFAULT``` tenant if exist and shows list [VMs] part of ```_DEFAULT``` tenant otherwise empty response suffice.

**Proposal#2**: ```vmdkops_admin.py tenant vm ls``` should respond with the current tenant<->list[VMs] association.

//CC @msterin @pdhamdhere

**Comment by govint** [comment]
@shuklanirdesh82 is this still an enhancement we want? Suggest drop unless its a must have.

**Comment by shuklanirdesh82** [comment]
closing this issue as we have a way to capture `tenant (vmgroup)<->list[VMs]` association
