### ISSUE TITLE
Default tenant should not be visible to users

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#980]
[root@sc2-rdops-vm03-dhcp-106-65:~] vmdkops_admin tenant ls
Uuid                                  Name      Description               Default_datastore  VM_list  
------------------------------------  --------  ------------------------  -----------------  -------  
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default tenant                        

This seems to be a regression issue as I didn't see default tenant being listed in older builds.

**Comment by shaominchen** [comment]
Shahzeb, can you please take care of this?

**Comment by lipingxue** [comment]
We did show _DEFAULT tenant in previous builds.

**Comment by shaominchen** [comment]
OK. Anyway we should just filter it out as this is internal implementation detail which should not be exposed to users.

**Comment by shuklanirdesh82** [comment]
> This seems to be a regression issue as I didn't see default tenant being listed in older builds.

It was shown in 0.11 release.

**Comment by pdhamdhere** [comment]
Why not list DEFAULT tenant? Admin may want to put constraints on DEFAULT tenant.

**Comment by shaominchen** [comment]
@pdhamdhere Good point. I forgot about this scenario. Then I agree it makes sense to list the DEFAULT tenant.
