### ISSUE TITLE
Do not see all the volumes listed after restarting a host which has a docker vm - container was running with volumes mounted when esx was rebooted

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#987]
VM had multiple volumes and when container was running on that vm, I restarted the esx.
After the esx came back up, powered-on the vm.
After vm came back, 'docker volume ls' does not lists all the volumes that were there prior to esx reboot.

I am not sure if this issue is same as as the one reported in #976 because even if I start vmdk-opsd, do not see all the volumes that were already there when esx was rebooted.

-----------------------------------------------
Steps and their outputs are as follows:

-  1) Setup already had multiple volumes.

```
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             Vol1E2P1@vsanDatastore
vsphere             Vol2E2P2@vsanDatastore
vsphere             VolE1@vsanDatastore
vsphere             VolE2@vsanDatastore
vsphere             testvol122@vsanDatastore
vsphere             testvol255@vsanDatastore
vsphere             vol251@sharedVmfs-0
```

-  2. Started a container with volumes mounted

```
root@photon-xVmYMbyTn [ ~ ]# docker run -it --volume-driver=vsphere -v VolE1@vsanDatastore:/vol1 -v VolE2@vsanDatastore:/vol2 -v Vol1E2P1@vsanDatastore:/vol3 -v Vol2E2P2@vsanDatastore:/vol4 --name ubE2 ubuntu
root@b15daa249e8b:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vol1  vol2  vol3  vol4
root@b15daa249e8b:/# cat vol3/hellos
I'm container from vm1
root@b15daa249e8b:/# cat vol4/hellos
I'm container from vm1
root@b15daa249e8b:/#
```

- 3. Then rebooted the esx. After reboot, powered-on the vm.
- 4. vmdk-opsd was not running hence started it.

```
[root@sc2-rdops-vm05-dhcp-188-183:~] /etc/init.d/vmdk-opsd status
vmdkops-opsd is not running
[root@sc2-rdops-vm05-dhcp-188-183:~] /etc/init.d/vmdk-opsd start
Starting vmdkops-opsd
vmdkops-opsd is running pid=71835
```

- 5. Checked the volumes using admin cli and docker cli - do not see all the volumes

```
[root@sc2-rdops-vm05-dhcp-188-183:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
-c volume,datastore,capacity,attached-to
Volume  Datastore     Attached To VM (name/uuid)            Capacity
------  ------------  ------------------------------------  --------
vol251  sharedVmfs-0  564dcdc7-7c7e-1d99-7c1d-df9e013c7961  100MB
```

```
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             vol251@sharedVmfs-0

```

I was able to create a volume later on but still did not see all the volumes.

```
root@photon-xVmYMbyTn [ ~ ]# docker volume create -d vsphere --name=testvolReboot -o size=500mb
testvolReboot
root@photon-xVmYMbyTn [ ~ ]# docker volume ls
DRIVER              VOLUME NAME
vsphere             testvolReboot@vsanDatastore
vsphere             vol251@sharedVmfs-0
root@photon-xVmYMbyTn [ ~ ]#

```

Logs: 
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/814831/docker-volume-vsphere.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/814832/vmdk_ops.txt)

**Comment by govint** [comment]
Post reboot list isn't picking anything from vsanDatastore.  What about after reboot admin CLI ls, is it also showing the same volumes or all of those from before the reboot.

**Comment by ashahi1** [comment]
@govint  After post reboot, it is also not showing the volumes that were there prior to reboot.

Please see the output below
```
[root@sc2-rdops-vm05-dhcp-188-183:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py ls
-c volume,datastore,capacity,attached-to
Volume  Datastore     Attached To VM (name/uuid)            Capacity
------  ------------  ------------------------------------  --------
vol251  sharedVmfs-0  564dcdc7-7c7e-1d99-7c1d-df9e013c7961  100MB

```

**Comment by pdhamdhere** [comment]
As Govindan mentioned, volumes created in vsanDatastore are missing. Did you check `ls -l /vmfs/volumes/vsanDatastore/dockvols/_DEFAULT/`

**Comment by ashahi1** [comment]
@pdhamdhere 
ls -l output is below. All these volumes were created post-reboot. I do not see the volumes that were created prior to esx-reboot.
```
[root@sc2-rdops-vm05-dhcp-188-183:~] ls -l /vmfs/volumes/vsanDatastore/dockvols/_DEFAULT/
total 16
-rw-------    1 root     root          4096 Mar  2 04:10 testvolReboot-534cb769b4431a12.vmfd
-rw-------    1 root     root           593 Mar  2 04:10 testvolReboot.vmdk
-rw-r--r--    1 root     root          4096 Mar  2 21:27 vol852-e63dd0b32a0a3cf8.vmfd
-rw-------    1 root     root           517 Mar  2 21:39 vol8522.vmdk
[root@sc2-rdops-vm05-dhcp-188-183:~]
```

**Comment by govint** [comment]
Is it a property of the vsan datastore? May be its cleaning up on startup.

**Comment by pdhamdhere** [comment]
```
ls -l vsanDatastore/
total 6144
drwxr-xr-t    1 root     root          3500 Mar  2 03:33 507db758-7fb6-ab50-593f-020035d3ac9f
drwxr-xr-t    1 root     root          2100 Mar  2 03:01 7684b758-a677-c0b9-8220-0200351cdccb
drwxr-xr-t    1 root     root          3360 Mar  2 02:43 7786b758-b7a2-4df8-8a97-0200351cdccb
drwxr-xr-t    1 root     root          1540 Mar  2 04:10 7a91b758-02d3-ee96-2642-0200351cdccb
lrwxr-xr-x    1 root     root            36 Mar  3 18:35 TestVM-122 -> 7786b758-b7a2-4df8-8a97-0200351cdccb
lrwxr-xr-x    1 root     root            36 Mar  3 18:35 TestVM-183 -> c486b758-4691-05bc-645f-020035d3ac9f
drwxr-xr-t    1 root     root          3500 Mar  2 05:44 c486b758-4691-05bc-645f-020035d3ac9f
lrwxr-xr-x    1 root     root            36 Mar  3 18:35 dockvols -> 7a91b758-02d3-ee96-2642-0200351cdccb
drwxr-xr-t    1 root     root          3360 Mar  2 02:04 f57cb758-5589-29e1-3c7e-0200351cdccb
lrwxr-xr-x    1 root     root            36 Mar  3 18:35 vm33_vsan_E1 -> f57cb758-5589-29e1-3c7e-0200351cdccb
lrwxr-xr-x    1 root     root            36 Mar  3 18:35 vm44_vsan_E2 -> 507db758-7fb6-ab50-593f-020035d3ac9f
```

Before Reboot;
dockvols => 7684b758-a677-c0b9-8220-0200351cdccb

All old volumes are present in 7684b758-a677-c0b9-8220-0200351cdccb/_DEFAULT

After Reboot;
dockvols => 7a91b758-02d3-ee96-2642-0200351cdccb

CC / @msterin

**Comment by pdhamdhere** [comment]
```
[root@sc2-rdops-vm05-dhcp-188-183:/vmfs/volumes] /usr/lib/vmware/osfs/bin/objtool getAttr -u 7684b758-a677-c0b9-8220-0200351cdccb --format JSON
{
   "UUID": "7684b758-a677-c0b9-8220-0200351cdccb", 
   "Object type": "vsan", 
   "Object size": "273804165120", 
   "User friendly name": "dockvols",  <<<<<<<<<<<<<<
   "HA metadata": "(null)", 
   "Allocation type": "Thick", 
   "Policy": "((\"stripeWidth\" i1) (\"proportionalCapacity\" (i0 i100)) (\"hostFailuresToTolerate\" i0))", 
   "Object class": "vmnamespace", 
   "Object capabilities": "NONE", 
   "Object path": "/vmfs/volumes/vsan:525bc223ae963c21-153129789d124635/", 
   "Group uuid": "00000000-0000-0000-0000-000000000000" 
}
[root@sc2-rdops-vm05-dhcp-188-183:/vmfs/volumes] /usr/lib/vmware/osfs/bin/objtool getAttr -u 7a91b758-02d3-ee96-2642-0200351cdccb --format JSON
{
   "UUID": "7a91b758-02d3-ee96-2642-0200351cdccb", 
   "Object type": "vsan", 
   "Object size": "273804165120", 
   "User friendly name": "dockvols",  <<<<<<<<<<<<<<
   "HA metadata": "(null)", 
   "Allocation type": "Thick", 
   "Policy": "((\"stripeWidth\" i1) (\"proportionalCapacity\" (i0 i100)) (\"hostFailuresToTolerate\" i0))", 
   "Object class": "vmnamespace", 
   "Object capabilities": "NONE", 
   "Object path": "/vmfs/volumes/vsan:525bc223ae963c21-153129789d124635/", 
   "Group uuid": "00000000-0000-0000-0000-000000000000" 
}
```

Directory lookup for "dockvols" failed after reboot so we issued mkdir dockvols which succeeded.

Another VM Directory also got affected on same setup. This seems unrelated to our code. Will open a case with vSAN.

**Comment by pdhamdhere** [comment]
On a side note, it seems `osfs-mkdir -n /vmfs/volumes/vsanDatastore/dockvols` has different default policy settings than vSAN Datastore default. For e.g. VM name has following policy setting;

```
{
   "UUID": "7786b758-b7a2-4df8-8a97-0200351cdccb", 
   "Object type": "vsan", 
   "Object size": "273804165120", 
   "User friendly name": "TestVM-122", 
   "HA metadata": "(null)", 
   "Allocation type": "Thick", 
   "Policy": "((\"stripeWidth\" i1) (\"cacheReservation\" i0) (\"proportionalCapacity\" i0) (\"hostFailuresToTolerate\" i1) (\"forceProvisioning\" i0) (\"spbmProfileId\" \"aa6d5a82-1c88-45da-85d3-3d74b91a5bad\") (\"spbmProfileGenerationNumber\" l+0) (\"spbmProfileName\" \"Virtual SAN Default Storage Policy\"))", 
   "Object class": "vmnamespace", 
   "Object capabilities": "NONE", 
   "Object path": "/vmfs/volumes/vsan:525bc223ae963c21-153129789d124635/", 
   "Group uuid": "00000000-0000-0000-0000-000000000000" 
}
```

**Comment by msterin** [comment]
The VM was probably created from VC and picked up whatever (default storage) policy was there - see spbm entries. 
dockvols was created from ESX and pciked up whatever default storage policy was in VSAN

**Comment by msterin** [comment]
Also @pdhamdhere - I wonder if could  be that our service was started too early (before osfs recovered the symlink) ?

**Comment by govint** [comment]
Should the ESX service install itself with a jumpstart plugin so it starts
in sequence in the proper order after system (ESX) services come up first.

**Comment by pdhamdhere** [comment]
>dockvols was created from ESX and pciked up whatever default storage policy was in VSAN

Yes, should we be explicitly specifying policy "hostFailuresToTolerate" in particular.

>I wonder if it could be that our service was started too early (before osfs recovered the symlink) ?

Good thinking! We are almost at the end among 150+ services started on this host. vSAN services are early in startup. Also note that 
a. We do not touch/create dockvols until request comes from VM so there is considerable delay
b. it's not only dockvols but another VM Folder is affected too. 
c. mkdir dockvols suceeded which should have failed if OSFS is not up.

>Should the ESX service install itself with a jumpstart plugin so it starts
in sequence in the proper order after system (ESX) services come up first.

We already have jumpstart and start service at very end.

**Comment by govint** [comment]
Is it possible to keep the UUID of the datastore in the tenant DB (for applicable datastores) and on startup, verify that the UUID exists and set up the linkage for that.

**Comment by pdhamdhere** [comment]
This is an issue with vSAN and I don't think we should add workarounds in our code.

Unfortunately logs have rolled over. Coudn't reproduce after several reboots. @ashahi1 Next time you see this, can you immediately backup entire "/var/log" and open issue with vSAN. This was a great catch. Thank you!
