### ISSUE TITLE
[Tenant]Error message is not clear while trying to add two vms with same names to a tenant.

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#994]
Error message reported when user tries to add two VMs with same names to a tenant with single command - Internal Error(UNIQUE constraint failed: vms.vm_id)

Proper error message be thrown so that it's easier for user to understand.

```
[root@sc-rdops-vm18-dhcp-47-89:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py tenant vm add --name=tenant1 --vm-list=Ubuntu-VM1-89,Ubuntu-VM1-89
Internal Error(UNIQUE constraint failed: vms.vm_id)

```

**Comment by pshahzeb** [comment]
Is there a need for error? Should we just remove duplicates from the list of VM names?

// CC @lipingxue @msterin

**Comment by msterin** [comment]
I think the perfect way would be remove a duplicate a warn.
An acceptable way would be to fail with a clear message. 
removing a duplicate silently is not nice , it could be a user typo :-)
