### ISSUE TITLE
Unable to inspect/use volumes created in 0.12 after upgrade to 0.13

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#995]
1. With Docker 1.13, & vDVS 0.11, created some volumes.
2. Upgrade to vDVS 0.12
3. docker volume ls shows volumes but inspect fails.

```
docker volume ls
DRIVER              VOLUME NAME
vsphere             vol113@datastore-1
vsphere             vol2@datastore-1
vsphere             volume1@datastore-1
root@u-1:~# docker volume inspect volume1@datastore-1
[]
Error: No such volume: volume1@datastore-1
```

**Comment by pdhamdhere** [comment]
This issue is specific to Docker 1.13. Docker for whatever reasons decided to persist volume name and their driver names in local DB. We changed driver name in 0.12 but Docker doesn't update it's DB based on registered plugins.

**Workaround**: Delete `/var/lib/docker/volumes/metadata.db `and restart docker. Docker will rebuild database with new driver name. This doesn't affect volume contents or associated metadata.

**Comment by govint** [comment]
For volumes created in Docker 1.13 it doesn't seem to behave this way. Its possible to create a volume with one driver and on restart of docker the same volume is associated with the driver thats reporting it now.

**Comment by pdhamdhere** [comment]
Govindan, I see this with Docker 1.13.

There isn't much we can do here. Docker will rebuild DB upon restart. Docker uses DB to store volume labels which will be lost.
